source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               src/org/wcs/smart/er/query/model/types/,\
               OSGI-INF/,\
               OSGI-INF/l10n/bundle.properties
