
/* Drop Tables */

DROP TABLE SMART.SURVEY_OBSERVATION_QUERY;




/* Create Tables */

CREATE TABLE SMART.SURVEY_OBSERVATION_QUERY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,
	QUERY_FILTER VARCHAR(32672),
	CA_FILTER VARCHAR(32672),
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	FOLDER_UUID CHAR(16) FOR BIT DATA ,
	COLUMN_FILTER VARCHAR(32672),
	SURVEYDESIGN_KEY VARCHAR(128),
	SHARED BOOLEAN NOT NULL,
	ID VARCHAR(6) NOT NULL,
	PRIMARY KEY (UUID)
);

/* Create Foreign Keys */

ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) 
	REFERENCES SMART.EMPLOYEE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CA_UUID_FK FOREIGN KEY (CA_UUID) 
	REFERENCES SMART.CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) 
	REFERENCES SMART.QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO manager;
GRANT SELECT ON SMART.SURVEY_OBSERVATION_QUERY TO data_entry;
GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO analsyt;
