/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.wcs.smart.event.filter.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_NOT = 8;
  /** RegularExpression Id. */
  int K_OR = 9;
  /** RegularExpression Id. */
  int K_EXACT = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LESS = 12;
  /** RegularExpression Id. */
  int LESSEQUAL = 13;
  /** RegularExpression Id. */
  int GREATER = 14;
  /** RegularExpression Id. */
  int GREATEREQUAL = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int NOTEQUAL = 17;
  /** RegularExpression Id. */
  int NOTEQUAL2 = 18;
  /** RegularExpression Id. */
  int OPENPAREN = 19;
  /** RegularExpression Id. */
  int CLOSEPAREN = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int CONTAINS = 24;
  /** RegularExpression Id. */
  int NOT_CONTAINS = 25;
  /** RegularExpression Id. */
  int STREQUALS = 26;
  /** RegularExpression Id. */
  int BETWEEN = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int FLOAT = 30;
  /** RegularExpression Id. */
  int INTEGER = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int S_CONST_LITERAL = 33;
  /** RegularExpression Id. */
  int CATEGORY_KEY = 34;
  /** RegularExpression Id. */
  int ATT_STR_KEY = 35;
  /** RegularExpression Id. */
  int ATT_VALUE_KEY = 36;
  /** RegularExpression Id. */
  int ATT_BOOL_KEY = 37;
  /** RegularExpression Id. */
  int ATT_LIST_KEY = 38;
  /** RegularExpression Id. */
  int ATT_MLIST_KEY = 39;
  /** RegularExpression Id. */
  int ATT_TREE_KEY = 40;
  /** RegularExpression Id. */
  int ATT_DATE_KEY = 41;
  /** RegularExpression Id. */
  int CAT_ATT_STR_KEY = 42;
  /** RegularExpression Id. */
  int CAT_ATT_VALUE_KEY = 43;
  /** RegularExpression Id. */
  int CAT_ATT_BOOL_KEY = 44;
  /** RegularExpression Id. */
  int CAT_ATT_LIST_KEY = 45;
  /** RegularExpression Id. */
  int CAT_ATT_MLIST_KEY = 46;
  /** RegularExpression Id. */
  int CAT_ATT_TREE_KEY = 47;
  /** RegularExpression Id. */
  int CAT_ATT_DATE_KEY = 48;
  /** RegularExpression Id. */
  int DATE_STRING = 49;
  /** RegularExpression Id. */
  int DM_KEY = 50;
  /** RegularExpression Id. */
  int LETTER = 51;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 52;
  /** RegularExpression Id. */
  int QUOTED_STRING = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"not\"",
    "\"or\"",
    "\"exact\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"contains\"",
    "\"notcontains\"",
    "\"equals\"",
    "\"between\"",
    "\":\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_CONST_LITERAL>",
    "<CATEGORY_KEY>",
    "<ATT_STR_KEY>",
    "<ATT_VALUE_KEY>",
    "<ATT_BOOL_KEY>",
    "<ATT_LIST_KEY>",
    "<ATT_MLIST_KEY>",
    "<ATT_TREE_KEY>",
    "<ATT_DATE_KEY>",
    "<CAT_ATT_STR_KEY>",
    "<CAT_ATT_VALUE_KEY>",
    "<CAT_ATT_BOOL_KEY>",
    "<CAT_ATT_LIST_KEY>",
    "<CAT_ATT_MLIST_KEY>",
    "<CAT_ATT_TREE_KEY>",
    "<CAT_ATT_DATE_KEY>",
    "<DATE_STRING>",
    "<DM_KEY>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<QUOTED_STRING>",
  };

}
