//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.17 at 05:06:27 PM MSK 
//


package org.wcs.smart.cybertracker.model.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Data.TimerTracks }
     * 
     */
    public Data.TimerTracks createDataTimerTracks() {
        return new Data.TimerTracks();
    }

    /**
     * Create an instance of {@link Data.TimerTracks.T }
     * 
     */
    public Data.TimerTracks.T createDataTimerTracksT() {
        return new Data.TimerTracks.T();
    }

    /**
     * Create an instance of {@link Data.Sightings }
     * 
     */
    public Data.Sightings createDataSightings() {
        return new Data.Sightings();
    }

    /**
     * Create an instance of {@link Data.Sightings.S }
     * 
     */
    public Data.Sightings.S createDataSightingsS() {
        return new Data.Sightings.S();
    }

    /**
     * Create an instance of {@link Data.Elements }
     * 
     */
    public Data.Elements createDataElements() {
        return new Data.Elements();
    }

    /**
     * Create an instance of {@link Data.TimerTracks.T.A }
     * 
     */
    public Data.TimerTracks.T.A createDataTimerTracksTA() {
        return new Data.TimerTracks.T.A();
    }

    /**
     * Create an instance of {@link Data.Sightings.S.A }
     * 
     */
    public Data.Sightings.S.A createDataSightingsSA() {
        return new Data.Sightings.S.A();
    }

    /**
     * Create an instance of {@link Data.Elements.E }
     * 
     */
    public Data.Elements.E createDataElementsE() {
        return new Data.Elements.E();
    }

}
