/*
 * Copyright (C) 2017 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.qa.patrol.routine;

import org.wcs.smart.observation.model.Waypoint;
import org.wcs.smart.qa.routine.ILocationRoutineData;

import com.vividsolutions.jts.geom.Coordinate;
import com.vividsolutions.jts.geom.Geometry;

/**
 * Results generated by the patrol waypoint data provider.  Extends ILocationRoutineData
 * to support the location validation routine.
 *  
 * @author Emily
 *
 */
public class WaypointLocationData implements ILocationRoutineData {

	private Waypoint wp;
	private Coordinate c = null;
	
	public WaypointLocationData(Waypoint wp) {
		this.wp = wp;
		c = new Coordinate(wp.getX(), wp.getY());
	}
	
	@Override
	public Geometry getGeometry() {
		return null;
	}

	@Override
	public Type getType() {
		return Type.POINT;
	}

	@Override
	public Coordinate getPoint() {
		return c;
	}

	public Waypoint getWaypoint(){
		return this.wp;
	}
}
