/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.wcs.smart.er.query.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_NOT = 8;
  /** RegularExpression Id. */
  int K_OR = 9;
  /** RegularExpression Id. */
  int K_EXACT = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LESS = 12;
  /** RegularExpression Id. */
  int LESSEQUAL = 13;
  /** RegularExpression Id. */
  int GREATER = 14;
  /** RegularExpression Id. */
  int GREATEREQUAL = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int NOTEQUAL = 17;
  /** RegularExpression Id. */
  int NOTEQUAL2 = 18;
  /** RegularExpression Id. */
  int OPENPAREN = 19;
  /** RegularExpression Id. */
  int CLOSEPAREN = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int CONTAINS = 24;
  /** RegularExpression Id. */
  int NOT_CONTAINS = 25;
  /** RegularExpression Id. */
  int STREQUALS = 26;
  /** RegularExpression Id. */
  int BETWEEN = 27;
  /** RegularExpression Id. */
  int QUERY_SPLITTER = 28;
  /** RegularExpression Id. */
  int AREA = 29;
  /** RegularExpression Id. */
  int PERIMETER = 30;
  /** RegularExpression Id. */
  int NUMBER = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int INTEGER = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int S_CONST_LITERAL = 35;
  /** RegularExpression Id. */
  int CATEGORY_KEY = 36;
  /** RegularExpression Id. */
  int ATT_STR_KEY = 37;
  /** RegularExpression Id. */
  int ATT_VALUE_KEY = 38;
  /** RegularExpression Id. */
  int ATT_BOOL_KEY = 39;
  /** RegularExpression Id. */
  int ATT_LIST_KEY = 40;
  /** RegularExpression Id. */
  int ATT_MLIST_KEY = 41;
  /** RegularExpression Id. */
  int ATT_TREE_KEY = 42;
  /** RegularExpression Id. */
  int ATT_DATE_KEY = 43;
  /** RegularExpression Id. */
  int ATT_GEOM_KEY = 44;
  /** RegularExpression Id. */
  int CAT_ATT_STR_KEY = 45;
  /** RegularExpression Id. */
  int CAT_ATT_VALUE_KEY = 46;
  /** RegularExpression Id. */
  int CAT_ATT_BOOL_KEY = 47;
  /** RegularExpression Id. */
  int CAT_ATT_LIST_KEY = 48;
  /** RegularExpression Id. */
  int CAT_ATT_MLIST_KEY = 49;
  /** RegularExpression Id. */
  int CM_CAT_ATT_LIST_KEY = 50;
  /** RegularExpression Id. */
  int CM_CAT_ATT_TREE_KEY = 51;
  /** RegularExpression Id. */
  int CAT_ATT_TREE_KEY = 52;
  /** RegularExpression Id. */
  int CAT_ATT_DATE_KEY = 53;
  /** RegularExpression Id. */
  int CAT_ATT_GEOM_KEY = 54;
  /** RegularExpression Id. */
  int DATE_STRING = 55;
  /** RegularExpression Id. */
  int DM_KEY = 56;
  /** RegularExpression Id. */
  int HEX_STRING = 57;
  /** RegularExpression Id. */
  int UUID = 58;
  /** RegularExpression Id. */
  int LETTER = 59;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 60;
  /** RegularExpression Id. */
  int SURVEY_ID_KEY = 61;
  /** RegularExpression Id. */
  int SURVEY_UUID_KEY = 62;
  /** RegularExpression Id. */
  int MISSION_ID_KEY = 63;
  /** RegularExpression Id. */
  int MISSION_UUID_KEY = 64;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_STR_KEY = 65;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_VALUE_KEY = 66;
  /** RegularExpression Id. */
  int MISSION_MEMBER = 67;
  /** RegularExpression Id. */
  int MISSION_LEADER = 68;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_LIST_KEY = 69;
  /** RegularExpression Id. */
  int MISSION_TRACK_TYPE = 70;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_SOURCE = 71;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_KEY = 72;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_ATTRIBUTE_STR_KEY = 73;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_ATTRIBUTE_VALUE_KEY = 74;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_ATTRIBUTE_LIST_KEY = 75;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_TRACK_KEY = 76;
  /** RegularExpression Id. */
  int AREA_TYPE_KEY = 77;
  /** RegularExpression Id. */
  int AREA_KEY = 78;
  /** RegularExpression Id. */
  int OBSERVATION_FILTER_TYPE_KEY = 79;
  /** RegularExpression Id. */
  int WAYPOINT_FILTER_TYPE_KEY = 80;
  /** RegularExpression Id. */
  int WAYPOINT_OBSERVER_KEY = 81;
  /** RegularExpression Id. */
  int SUM_CAT_VALUE_KEY = 82;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_KEY = 83;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_KEY = 84;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_GEOMETRY_KEY = 85;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_GEOMETRY_KEY = 86;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_LISTTREE_KEY = 87;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_LISTTREE_KEY = 88;
  /** RegularExpression Id. */
  int AGG = 89;
  /** RegularExpression Id. */
  int DATE_GROUPBY_ITEM = 90;
  /** RegularExpression Id. */
  int CATEGORY_GROUPBY_ITEM = 91;
  /** RegularExpression Id. */
  int AREA_GROUPBY_ITEM = 92;
  /** RegularExpression Id. */
  int ATTRIBUTE_GROUPBY_ITEM = 93;
  /** RegularExpression Id. */
  int CATEGORY_ATTRIBUTE_GROUPBY_ITEM = 94;
  /** RegularExpression Id. */
  int SURVEY_ID_GROUPBY_ITEM = 95;
  /** RegularExpression Id. */
  int MISSION_ID_GROUPBY_ITEM = 96;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_GROUPBY_ITEM = 97;
  /** RegularExpression Id. */
  int SAMPLINGUNIT_PROPERTY_GROUPBY_ITEM = 98;
  /** RegularExpression Id. */
  int SAMPLINGUNIT_GROUPBY_ITEM = 99;
  /** RegularExpression Id. */
  int WAYPOINT_OBSERVER_GROUPBY_ITEM = 100;
  /** RegularExpression Id. */
  int MISSION_TRACK_LENGTH = 101;
  /** RegularExpression Id. */
  int MISSION_TRACK_TOTAL_LENGTH = 102;
  /** RegularExpression Id. */
  int MISSION_COUNT = 103;
  /** RegularExpression Id. */
  int MISSION_TOTAL_COUNT = 104;
  /** RegularExpression Id. */
  int MISSION_DAY_COUNT = 105;
  /** RegularExpression Id. */
  int MISSION_HOUR_COUNT = 106;
  /** RegularExpression Id. */
  int MISSION_PERSONHOUR_COUNT = 107;
  /** RegularExpression Id. */
  int SURVEY_COUNT = 108;
  /** RegularExpression Id. */
  int SURVEY_TOTAL_COUNT = 109;
  /** RegularExpression Id. */
  int QUOTED_STRING = 110;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"not\"",
    "\"or\"",
    "\"exact\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"contains\"",
    "\"notcontains\"",
    "\"equals\"",
    "\"between\"",
    "\"|\"",
    "\"area\"",
    "\"perimeter\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_CONST_LITERAL>",
    "<CATEGORY_KEY>",
    "<ATT_STR_KEY>",
    "<ATT_VALUE_KEY>",
    "<ATT_BOOL_KEY>",
    "<ATT_LIST_KEY>",
    "<ATT_MLIST_KEY>",
    "<ATT_TREE_KEY>",
    "<ATT_DATE_KEY>",
    "<ATT_GEOM_KEY>",
    "<CAT_ATT_STR_KEY>",
    "<CAT_ATT_VALUE_KEY>",
    "<CAT_ATT_BOOL_KEY>",
    "<CAT_ATT_LIST_KEY>",
    "<CAT_ATT_MLIST_KEY>",
    "<CM_CAT_ATT_LIST_KEY>",
    "<CM_CAT_ATT_TREE_KEY>",
    "<CAT_ATT_TREE_KEY>",
    "<CAT_ATT_DATE_KEY>",
    "<CAT_ATT_GEOM_KEY>",
    "<DATE_STRING>",
    "<DM_KEY>",
    "<HEX_STRING>",
    "<UUID>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "\"s:survey:id\"",
    "<SURVEY_UUID_KEY>",
    "\"s:mission:id\"",
    "<MISSION_UUID_KEY>",
    "<MISSION_PROPERTY_STR_KEY>",
    "<MISSION_PROPERTY_VALUE_KEY>",
    "<MISSION_MEMBER>",
    "<MISSION_LEADER>",
    "<MISSION_PROPERTY_LIST_KEY>",
    "<MISSION_TRACK_TYPE>",
    "<SAMPLING_UNIT_SOURCE>",
    "<SAMPLING_UNIT_KEY>",
    "<SAMPLING_UNIT_ATTRIBUTE_STR_KEY>",
    "<SAMPLING_UNIT_ATTRIBUTE_VALUE_KEY>",
    "<SAMPLING_UNIT_ATTRIBUTE_LIST_KEY>",
    "<SAMPLING_UNIT_TRACK_KEY>",
    "<AREA_TYPE_KEY>",
    "<AREA_KEY>",
    "\"observation\"",
    "\"waypoint\"",
    "\"wpnobs:observer\"",
    "<SUM_CAT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_VALUE_KEY>",
    "<SUM_CAT_ATT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_GEOMETRY_KEY>",
    "<SUM_CAT_ATT_GEOMETRY_KEY>",
    "<SUM_ATTRIBUTE_VALUE_LISTTREE_KEY>",
    "<SUM_CAT_ATT_VALUE_LISTTREE_KEY>",
    "<AGG>",
    "<DATE_GROUPBY_ITEM>",
    "<CATEGORY_GROUPBY_ITEM>",
    "<AREA_GROUPBY_ITEM>",
    "<ATTRIBUTE_GROUPBY_ITEM>",
    "<CATEGORY_ATTRIBUTE_GROUPBY_ITEM>",
    "<SURVEY_ID_GROUPBY_ITEM>",
    "<MISSION_ID_GROUPBY_ITEM>",
    "<MISSION_PROPERTY_GROUPBY_ITEM>",
    "<SAMPLINGUNIT_PROPERTY_GROUPBY_ITEM>",
    "<SAMPLINGUNIT_GROUPBY_ITEM>",
    "<WAYPOINT_OBSERVER_GROUPBY_ITEM>",
    "\"s:missiontracklength\"",
    "\"s:totalmissiontracklength\"",
    "\"s:missioncount\"",
    "\"s:totalmissioncount\"",
    "\"s:missiondaycount\"",
    "\"s:missionhourcount\"",
    "\"s:missionpersonhourcount\"",
    "\"s:surveycount\"",
    "\"s:totalsurveycount\"",
    "<QUOTED_STRING>",
  };

}
