//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 02:52:49 PM PST 
//


package org.wcs.smart.entity.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataModelAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataModelAttribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggregations" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}AggregationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qa_minmax" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}MinMaxType" minOccurs="0"/>
 *         &lt;element name="qa_regex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="names" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}LabelType" maxOccurs="unbounded"/>
 *         &lt;element name="values" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}ListNode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tree" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}TreeNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isrequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NUMBERIC"/>
 *             &lt;enumeration value="TEXT"/>
 *             &lt;enumeration value="BOOLEAN"/>
 *             &lt;enumeration value="LIST"/>
 *             &lt;enumeration value="TREE"/>
 *             &lt;enumeration value="DATE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataModelAttribute", propOrder = {
    "aggregations",
    "qaMinmax",
    "qaRegex",
    "names",
    "values",
    "tree"
})
public class DataModelAttribute {

    protected List<AggregationType> aggregations;
    @XmlElement(name = "qa_minmax")
    protected MinMaxType qaMinmax;
    @XmlElement(name = "qa_regex")
    protected String qaRegex;
    @XmlElement(required = true)
    protected List<LabelType> names;
    protected List<ListNode> values;
    protected List<TreeNodeType> tree;
    @XmlAttribute
    protected String key;
    @XmlAttribute
    protected Boolean isrequired;
    @XmlAttribute
    protected String type;

    /**
     * Gets the value of the aggregations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AggregationType }
     * 
     * 
     */
    public List<AggregationType> getAggregations() {
        if (aggregations == null) {
            aggregations = new ArrayList<AggregationType>();
        }
        return this.aggregations;
    }

    /**
     * Gets the value of the qaMinmax property.
     * 
     * @return
     *     possible object is
     *     {@link MinMaxType }
     *     
     */
    public MinMaxType getQaMinmax() {
        return qaMinmax;
    }

    /**
     * Sets the value of the qaMinmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinMaxType }
     *     
     */
    public void setQaMinmax(MinMaxType value) {
        this.qaMinmax = value;
    }

    /**
     * Gets the value of the qaRegex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQaRegex() {
        return qaRegex;
    }

    /**
     * Sets the value of the qaRegex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQaRegex(String value) {
        this.qaRegex = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the names property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     * 
     * 
     */
    public List<LabelType> getNames() {
        if (names == null) {
            names = new ArrayList<LabelType>();
        }
        return this.names;
    }

    /**
     * Gets the value of the values property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the values property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListNode }
     * 
     * 
     */
    public List<ListNode> getValues() {
        if (values == null) {
            values = new ArrayList<ListNode>();
        }
        return this.values;
    }

    /**
     * Gets the value of the tree property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tree property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTree().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TreeNodeType }
     * 
     * 
     */
    public List<TreeNodeType> getTree() {
        if (tree == null) {
            tree = new ArrayList<TreeNodeType>();
        }
        return this.tree;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the isrequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsrequired() {
        return isrequired;
    }

    /**
     * Sets the value of the isrequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsrequired(Boolean value) {
        this.isrequired = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
