//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.18 at 08:30:37 AM MSK 
//


package org.wcs.smart.cybertracker.model.elements;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wcs.smart.cybertracker.model.elements package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wcs.smart.cybertracker.model.elements
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Elements }
     * 
     */
    public Elements createElements() {
        return new Elements();
    }

    /**
     * Create an instance of {@link Elements.List }
     * 
     */
    public Elements.List createElementsList() {
        return new Elements.List();
    }

    /**
     * Create an instance of {@link Elements.List.Items }
     * 
     */
    public Elements.List.Items createElementsListItems() {
        return new Elements.List.Items();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

    /**
     * Create an instance of {@link GpsSightingAccuracy }
     * 
     */
    public GpsSightingAccuracy createGpsSightingAccuracy() {
        return new GpsSightingAccuracy();
    }

    /**
     * Create an instance of {@link GpsWaypointAccuracy }
     * 
     */
    public GpsWaypointAccuracy createGpsWaypointAccuracy() {
        return new GpsWaypointAccuracy();
    }

    /**
     * Create an instance of {@link Elements.List.Items.Item }
     * 
     */
    public Elements.List.Items.Item createElementsListItemsItem() {
        return new Elements.List.Items.Item();
    }

}
