//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.26 at 01:13:22 PM PDT 
//


package org.wcs.smart.ct2smart.matcher.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ct2AttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Ct2AttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IGNORE"/>
 *     &lt;enumeration value="TEXT"/>
 *     &lt;enumeration value="NUMERIC"/>
 *     &lt;enumeration value="BOOL"/>
 *     &lt;enumeration value="REF"/>
 *     &lt;enumeration value="META"/>
 *     &lt;enumeration value="CATEGORY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Ct2AttributeType")
@XmlEnum
public enum Ct2AttributeType {

    IGNORE,
    TEXT,
    NUMERIC,
    BOOL,
    REF,
    META,
    CATEGORY;

    public String value() {
        return name();
    }

    public static Ct2AttributeType fromValue(String v) {
        return valueOf(v);
    }

}
