/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.upgrade;

import org.wcs.smart.changetracking.AbstractChangeTrackerInstaller;

/**
 * Change log tracker installer for the core smart plugins.  Creates all triggers 
 * to support change log tracking in core smart plugins.
 * 
 * @author Emily
 *
 */
public class SmartChangeLogTracker extends AbstractChangeTrackerInstaller {

	@SuppressWarnings("nls")
	private String[][] triggers = {
		{"trg_agency_insert", "CREATE TRIGGER trg_agency_insert AFTER INSERT ON smart.agency REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.agency', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_agency_update", "CREATE TRIGGER trg_agency_update AFTER UPDATE ON smart.agency REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.agency', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_agency_delete", "CREATE TRIGGER trg_agency_delete AFTER DELETE ON smart.agency REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.agency', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_area_geometries_insert", "CREATE TRIGGER trg_area_geometries_insert AFTER INSERT ON smart.area_geometries REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.area_geometries', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_area_geometries_update", "CREATE TRIGGER trg_area_geometries_update AFTER UPDATE ON smart.area_geometries REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.area_geometries', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_area_geometries_delete", "CREATE TRIGGER trg_area_geometries_delete AFTER DELETE ON smart.area_geometries REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.area_geometries', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_ca_projection_insert", "CREATE TRIGGER trg_ca_projection_insert AFTER INSERT ON smart.ca_projection REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.ca_projection', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_ca_projection_update", "CREATE TRIGGER trg_ca_projection_update AFTER UPDATE ON smart.ca_projection REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.ca_projection', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_ca_projection_delete", "CREATE TRIGGER trg_ca_projection_delete AFTER DELETE ON smart.ca_projection REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.ca_projection', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_conservation_area_insert", "CREATE TRIGGER trg_conservation_area_insert AFTER INSERT ON smart.conservation_area REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.conservation_area', 'uuid', new.uuid, new.uuid)"},
		{"trg_conservation_area_update", "CREATE TRIGGER trg_conservation_area_update AFTER UPDATE ON smart.conservation_area REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.conservation_area', 'uuid', new.uuid, new.uuid)"},
		{"trg_conservation_area_delete", "CREATE TRIGGER trg_conservation_area_delete AFTER DELETE ON smart.conservation_area REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.conservation_area', 'uuid', old.uuid, old.uuid)"},
		{"trg_dm_attribute_insert", "CREATE TRIGGER trg_dm_attribute_insert AFTER INSERT ON smart.dm_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.dm_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_dm_attribute_update", "CREATE TRIGGER trg_dm_attribute_update AFTER UPDATE ON smart.dm_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.dm_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_dm_attribute_delete", "CREATE TRIGGER trg_dm_attribute_delete AFTER DELETE ON smart.dm_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.dm_attribute', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_dm_attribute_list_insert", "CREATE TRIGGER trg_dm_attribute_list_insert AFTER INSERT ON smart.dm_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.dm_attribute_list', 'uuid', new.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = new.attribute_uuid"},
		{"trg_dm_attribute_list_update", "CREATE TRIGGER trg_dm_attribute_list_update AFTER UPDATE ON smart.dm_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.dm_attribute_list', 'uuid', new.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = new.attribute_uuid"},
		{"trg_dm_attribute_list_delete", "CREATE TRIGGER trg_dm_attribute_list_delete AFTER DELETE ON smart.dm_attribute_list REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.dm_attribute_list', 'uuid', old.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = old.attribute_uuid"},
		{"trg_dm_attribute_tree_insert", "CREATE TRIGGER trg_dm_attribute_tree_insert AFTER INSERT ON smart.dm_attribute_tree REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.dm_attribute_tree', 'uuid', new.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = new.attribute_uuid"},
		{"trg_dm_attribute_tree_update", "CREATE TRIGGER trg_dm_attribute_tree_update AFTER UPDATE ON smart.dm_attribute_tree REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.dm_attribute_tree', 'uuid', new.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = new.attribute_uuid"},
		{"trg_dm_attribute_tree_delete", "CREATE TRIGGER trg_dm_attribute_tree_delete AFTER DELETE ON smart.dm_attribute_tree REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.dm_attribute_tree', 'uuid', old.uuid, da.ca_uuid from smart.dm_attribute da where da.uuid = old.attribute_uuid"},
		{"trg_dm_category_insert", "CREATE TRIGGER trg_dm_category_insert AFTER INSERT ON smart.dm_category REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.dm_category', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_dm_category_update", "CREATE TRIGGER trg_dm_category_update AFTER UPDATE ON smart.dm_category REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.dm_category', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_dm_category_delete", "CREATE TRIGGER trg_dm_category_delete AFTER DELETE ON smart.dm_category REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.dm_category', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_dm_att_agg_map_insert", "CREATE TRIGGER trg_dm_att_agg_map_insert AFTER INSERT ON smart.dm_att_agg_map REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) select smart.uuid(), 'INSERT', 'smart.dm_att_agg_map', 'attribute_uuid', new.attribute_uuid, 'agg_name', new.agg_name, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_dm_att_agg_map_update", "CREATE TRIGGER trg_dm_att_agg_map_update AFTER UPDATE ON smart.dm_att_agg_map REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.dm_att_agg_map', 'attribute_uuid', new.attribute_uuid, 'agg_name', new.agg_name, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_dm_att_agg_map_delete", "CREATE TRIGGER trg_dm_att_agg_map_delete AFTER DELETE ON smart.dm_att_agg_map REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) select smart.uuid(), 'DELETE', 'smart.dm_att_agg_map', 'attribute_uuid', old.attribute_uuid, 'agg_name', old.agg_name, a.ca_uuid from smart.dm_attribute a where a.uuid = old.attribute_uuid"},
		{"trg_dm_cat_att_map_insert", "CREATE TRIGGER trg_dm_cat_att_map_insert AFTER INSERT ON smart.dm_cat_att_map REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.dm_cat_att_map', 'attribute_uuid', new.attribute_uuid, 'category_uuid', new.category_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_dm_cat_att_map_update", "CREATE TRIGGER trg_dm_cat_att_map_update AFTER UPDATE ON smart.dm_cat_att_map REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.dm_cat_att_map', 'attribute_uuid', new.attribute_uuid, 'category_uuid', new.category_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_dm_cat_att_map_delete", "CREATE TRIGGER trg_dm_cat_att_map_delete AFTER DELETE ON smart.dm_cat_att_map REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.dm_cat_att_map', 'attribute_uuid', old.attribute_uuid, 'category_uuid', old.category_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = old.attribute_uuid"},
		{"trg_employee_insert", "CREATE TRIGGER trg_employee_insert AFTER INSERT ON smart.employee REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.employee', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_employee_update", "CREATE TRIGGER trg_employee_update AFTER UPDATE ON smart.employee REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.employee', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_employee_delete", "CREATE TRIGGER trg_employee_delete AFTER DELETE ON smart.employee REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.employee', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_gridded_query_insert", "CREATE TRIGGER trg_gridded_query_insert AFTER INSERT ON smart.gridded_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.gridded_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_gridded_query_update", "CREATE TRIGGER trg_gridded_query_update AFTER UPDATE ON smart.gridded_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.gridded_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_gridded_query_delete", "CREATE TRIGGER trg_gridded_query_delete AFTER DELETE ON smart.gridded_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.gridded_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_i18n_label_insert", "CREATE TRIGGER trg_i18n_label_insert AFTER INSERT ON smart.i18n_label REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.i18n_label', 'element_uuid', new.element_uuid, 'language_uuid', new.language_uuid, l.ca_uuid from smart.language l where l.uuid = new.language_uuid"},
		{"trg_i18n_label_update", "CREATE TRIGGER trg_i18n_label_update AFTER UPDATE ON smart.i18n_label REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.i18n_label', 'element_uuid', new.element_uuid, 'language_uuid', new.language_uuid, l.ca_uuid from smart.language l where l.uuid = new.language_uuid"},
		{"trg_i18n_label_delete", "CREATE TRIGGER trg_i18n_label_delete AFTER DELETE ON smart.i18n_label REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.i18n_label', 'element_uuid', old.element_uuid, 'language_uuid', old.language_uuid, l.ca_uuid from smart.language l where l.uuid = old.language_uuid"},
		{"trg_language_insert", "CREATE TRIGGER trg_language_insert AFTER INSERT ON smart.language REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.language', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_language_update", "CREATE TRIGGER trg_language_update AFTER UPDATE ON smart.language REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.language', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_language_delete", "CREATE TRIGGER trg_language_delete AFTER DELETE ON smart.language REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.language', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_map_styles_insert", "CREATE TRIGGER trg_map_styles_insert AFTER INSERT ON smart.map_styles REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.map_styles', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_map_styles_update", "CREATE TRIGGER trg_map_styles_update AFTER UPDATE ON smart.map_styles REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.map_styles', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_map_styles_delete", "CREATE TRIGGER trg_map_styles_delete AFTER DELETE ON smart.map_styles REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.map_styles', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_observation_attachment_insert", "CREATE TRIGGER trg_observation_attachment_insert AFTER INSERT ON smart.observation_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.observation_attachment', 'uuid', new.uuid, wp.ca_uuid from smart.wp_observation ob, smart.waypoint wp where ob.wp_uuid = wp.uuid and ob.uuid = new.obs_uuid"},
		{"trg_observation_attachment_update", "CREATE TRIGGER trg_observation_attachment_update AFTER UPDATE ON smart.observation_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.observation_attachment', 'uuid', new.uuid, wp.ca_uuid from smart.wp_observation ob, smart.waypoint wp where ob.wp_uuid = wp.uuid and ob.uuid = new.obs_uuid"},
		{"trg_observation_attachment_delete", "CREATE TRIGGER trg_observation_attachment_delete AFTER DELETE ON smart.observation_attachment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.observation_attachment', 'uuid', old.uuid, wp.ca_uuid from smart.wp_observation ob, smart.waypoint wp where ob.wp_uuid = wp.uuid and ob.uuid = old.obs_uuid"},
		{"trg_observation_options_insert", "CREATE TRIGGER trg_observation_options_insert AFTER INSERT ON smart.observation_options REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.observation_options', 'ca_uuid', new.ca_uuid, new.ca_uuid)"},
		{"trg_observation_options_update", "CREATE TRIGGER trg_observation_options_update AFTER UPDATE ON smart.observation_options REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.observation_options', 'ca_uuid', new.ca_uuid, new.ca_uuid)"},
		{"trg_observation_options_delete", "CREATE TRIGGER trg_observation_options_delete AFTER DELETE ON smart.observation_options REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.observation_options', 'ca_uuid', old.ca_uuid, old.ca_uuid)"},
		{"trg_observation_query_insert", "CREATE TRIGGER trg_observation_query_insert AFTER INSERT ON smart.observation_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.observation_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_observation_query_update", "CREATE TRIGGER trg_observation_query_update AFTER UPDATE ON smart.observation_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.observation_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_observation_query_delete", "CREATE TRIGGER trg_observation_query_delete AFTER DELETE ON smart.observation_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.observation_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_obs_gridded_query_insert", "CREATE TRIGGER trg_obs_gridded_query_insert AFTER INSERT ON smart.obs_gridded_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.obs_gridded_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_gridded_query_update", "CREATE TRIGGER trg_obs_gridded_query_update AFTER UPDATE ON smart.obs_gridded_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.obs_gridded_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_gridded_query_delete", "CREATE TRIGGER trg_obs_gridded_query_delete AFTER DELETE ON smart.obs_gridded_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.obs_gridded_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_obs_observation_query_insert", "CREATE TRIGGER trg_obs_observation_query_insert AFTER INSERT ON smart.obs_observation_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.obs_observation_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_observation_query_update", "CREATE TRIGGER trg_obs_observation_query_update AFTER UPDATE ON smart.obs_observation_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.obs_observation_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_observation_query_delete", "CREATE TRIGGER trg_obs_observation_query_delete AFTER DELETE ON smart.obs_observation_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.obs_observation_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_obs_summary_query_insert", "CREATE TRIGGER trg_obs_summary_query_insert AFTER INSERT ON smart.obs_summary_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.obs_summary_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_summary_query_update", "CREATE TRIGGER trg_obs_summary_query_update AFTER UPDATE ON smart.obs_summary_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.obs_summary_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_summary_query_delete", "CREATE TRIGGER trg_obs_summary_query_delete AFTER DELETE ON smart.obs_summary_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.obs_summary_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_obs_waypoint_query_insert", "CREATE TRIGGER trg_obs_waypoint_query_insert AFTER INSERT ON smart.obs_waypoint_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.obs_waypoint_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_waypoint_query_update", "CREATE TRIGGER trg_obs_waypoint_query_update AFTER UPDATE ON smart.obs_waypoint_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.obs_waypoint_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_obs_waypoint_query_delete", "CREATE TRIGGER trg_obs_waypoint_query_delete AFTER DELETE ON smart.obs_waypoint_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.obs_waypoint_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_patrol_insert", "CREATE TRIGGER trg_patrol_insert AFTER INSERT ON smart.patrol REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.patrol', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_update", "CREATE TRIGGER trg_patrol_update AFTER UPDATE ON smart.patrol REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.patrol', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_delete", "CREATE TRIGGER trg_patrol_delete AFTER DELETE ON smart.patrol REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.patrol', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_patrol_leg_insert", "CREATE TRIGGER trg_patrol_leg_insert AFTER INSERT ON smart.patrol_leg REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.patrol_leg', 'uuid', new.uuid, p.ca_uuid from smart.patrol p where p.uuid = new.patrol_uuid"},
		{"trg_patrol_leg_update", "CREATE TRIGGER trg_patrol_leg_update AFTER UPDATE ON smart.patrol_leg REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.patrol_leg', 'uuid', new.uuid, p.ca_uuid from smart.patrol p where p.uuid = new.patrol_uuid"},
		{"trg_patrol_leg_delete", "CREATE TRIGGER trg_patrol_leg_delete AFTER DELETE ON smart.patrol_leg REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.patrol_leg', 'uuid', old.uuid, p.ca_uuid from smart.patrol p where p.uuid = old.patrol_uuid"},
		{"trg_patrol_leg_day_insert", "CREATE TRIGGER trg_patrol_leg_day_insert AFTER INSERT ON smart.patrol_leg_day REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.patrol_leg_day', 'uuid', new.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl where pl.patrol_uuid = p.uuid and pl.uuid = new.patrol_leg_uuid"},
		{"trg_patrol_leg_day_update", "CREATE TRIGGER trg_patrol_leg_day_update AFTER UPDATE ON smart.patrol_leg_day REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.patrol_leg_day', 'uuid', new.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl where pl.patrol_uuid = p.uuid and pl.uuid = new.patrol_leg_uuid"},
		{"trg_patrol_leg_day_delete", "CREATE TRIGGER trg_patrol_leg_day_delete AFTER DELETE ON smart.patrol_leg_day REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.patrol_leg_day', 'uuid', old.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl where pl.patrol_uuid = p.uuid and pl.uuid = old.patrol_leg_uuid"},
		{"trg_patrol_leg_members_insert", "CREATE TRIGGER trg_patrol_leg_members_insert AFTER INSERT ON smart.patrol_leg_members REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.patrol_leg_members', 'patrol_leg_uuid', new.patrol_leg_uuid, 'employee_uuid', new.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = new.employee_uuid"},
		{"trg_patrol_leg_members_update", "CREATE TRIGGER trg_patrol_leg_members_update AFTER UPDATE ON smart.patrol_leg_members REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.patrol_leg_members', 'patrol_leg_uuid', new.patrol_leg_uuid, 'employee_uuid', new.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = new.employee_uuid"},
		{"trg_patrol_leg_members_delete", "CREATE TRIGGER trg_patrol_leg_members_delete AFTER DELETE ON smart.patrol_leg_members REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.patrol_leg_members', 'patrol_leg_uuid', old.patrol_leg_uuid, 'employee_uuid', old.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = old.employee_uuid"},
		{"trg_patrol_mandate_insert", "CREATE TRIGGER trg_patrol_mandate_insert AFTER INSERT ON smart.patrol_mandate REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.patrol_mandate', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_mandate_update", "CREATE TRIGGER trg_patrol_mandate_update AFTER UPDATE ON smart.patrol_mandate REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.patrol_mandate', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_mandate_delete", "CREATE TRIGGER trg_patrol_mandate_delete AFTER DELETE ON smart.patrol_mandate REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.patrol_mandate', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_patrol_query_insert", "CREATE TRIGGER trg_patrol_query_insert AFTER INSERT ON smart.patrol_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.patrol_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_query_update", "CREATE TRIGGER trg_patrol_query_update AFTER UPDATE ON smart.patrol_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.patrol_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_query_delete", "CREATE TRIGGER trg_patrol_query_delete AFTER DELETE ON smart.patrol_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.patrol_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_patrol_transport_insert", "CREATE TRIGGER trg_patrol_transport_insert AFTER INSERT ON smart.patrol_transport REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.patrol_transport', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_transport_update", "CREATE TRIGGER trg_patrol_transport_update AFTER UPDATE ON smart.patrol_transport REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.patrol_transport', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_patrol_transport_delete", "CREATE TRIGGER trg_patrol_transport_delete AFTER DELETE ON smart.patrol_transport REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.patrol_transport', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_patrol_type_insert", "CREATE TRIGGER trg_patrol_type_insert AFTER INSERT ON smart.patrol_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.patrol_type', 'ca_uuid', new.ca_uuid, 'patrol_type', new.patrol_type, new.ca_uuid)"},
		{"trg_patrol_type_update", "CREATE TRIGGER trg_patrol_type_update AFTER UPDATE ON smart.patrol_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.patrol_type', 'ca_uuid', new.ca_uuid, 'patrol_type', new.patrol_type, new.ca_uuid)"},
		{"trg_patrol_type_delete", "CREATE TRIGGER trg_patrol_type_delete AFTER DELETE ON smart.patrol_type REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_str, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.patrol_type', 'ca_uuid', old.ca_uuid, 'patrol_type', old.patrol_type, old.ca_uuid)"},
		{"trg_patrol_waypoint_insert", "CREATE TRIGGER trg_patrol_waypoint_insert AFTER INSERT ON smart.patrol_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.patrol_waypoint', 'leg_day_uuid', new.leg_day_uuid, 'wp_uuid', new.wp_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_patrol_waypoint_update", "CREATE TRIGGER trg_patrol_waypoint_update AFTER UPDATE ON smart.patrol_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.patrol_waypoint', 'leg_day_uuid', new.leg_day_uuid, 'wp_uuid', new.wp_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_patrol_waypoint_delete", "CREATE TRIGGER trg_patrol_waypoint_delete AFTER DELETE ON smart.patrol_waypoint REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.patrol_waypoint', 'leg_day_uuid', old.leg_day_uuid, 'wp_uuid', old.wp_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = old.wp_uuid"},
		{"trg_query_folder_insert", "CREATE TRIGGER trg_query_folder_insert AFTER INSERT ON smart.query_folder REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.query_folder', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_query_folder_update", "CREATE TRIGGER trg_query_folder_update AFTER UPDATE ON smart.query_folder REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.query_folder', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_query_folder_delete", "CREATE TRIGGER trg_query_folder_delete AFTER DELETE ON smart.query_folder REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.query_folder', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_rank_insert", "CREATE TRIGGER trg_rank_insert AFTER INSERT ON smart.rank REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.rank', 'uuid', new.uuid, a.ca_uuid from smart.agency a where a.uuid = new.agency_uuid"},
		{"trg_rank_update", "CREATE TRIGGER trg_rank_update AFTER UPDATE ON smart.rank REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.rank', 'uuid', new.uuid, a.ca_uuid from smart.agency a where a.uuid = new.agency_uuid"},
		{"trg_rank_delete", "CREATE TRIGGER trg_rank_delete AFTER DELETE ON smart.rank REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.rank', 'uuid', old.uuid, a.ca_uuid from smart.agency a where a.uuid = old.agency_uuid"},
		{"trg_report_insert", "CREATE TRIGGER trg_report_insert AFTER INSERT ON smart.report REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.report', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_report_update", "CREATE TRIGGER trg_report_update AFTER UPDATE ON smart.report REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.report', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_report_delete", "CREATE TRIGGER trg_report_delete AFTER DELETE ON smart.report REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.report', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_report_folder_insert", "CREATE TRIGGER trg_report_folder_insert AFTER INSERT ON smart.report_folder REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.report_folder', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_report_folder_update", "CREATE TRIGGER trg_report_folder_update AFTER UPDATE ON smart.report_folder REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.report_folder', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_report_folder_delete", "CREATE TRIGGER trg_report_folder_delete AFTER DELETE ON smart.report_folder REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.report_folder', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_report_query_insert", "CREATE TRIGGER trg_report_query_insert AFTER INSERT ON smart.report_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.report_query', 'report_uuid', new.report_uuid, 'query_uuid', new.query_uuid, r.ca_uuid from smart.report r where r.uuid = new.report_uuid"},
		{"trg_report_query_update", "CREATE TRIGGER trg_report_query_update AFTER UPDATE ON smart.report_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.report_query', 'report_uuid', new.report_uuid, 'query_uuid', new.query_uuid, r.ca_uuid from smart.report r where r.uuid = new.report_uuid"},
		{"trg_report_query_delete", "CREATE TRIGGER trg_report_query_delete AFTER DELETE ON smart.report_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.report_query', 'report_uuid', old.report_uuid, 'query_uuid', old.query_uuid, r.ca_uuid from smart.report r where r.uuid = old.report_uuid"},
		{"trg_saved_maps_insert", "CREATE TRIGGER trg_saved_maps_insert AFTER INSERT ON smart.saved_maps REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.saved_maps', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_saved_maps_update", "CREATE TRIGGER trg_saved_maps_update AFTER UPDATE ON smart.saved_maps REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.saved_maps', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_saved_maps_delete", "CREATE TRIGGER trg_saved_maps_delete AFTER DELETE ON smart.saved_maps REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.saved_maps', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_station_insert", "CREATE TRIGGER trg_station_insert AFTER INSERT ON smart.station REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.station', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_station_update", "CREATE TRIGGER trg_station_update AFTER UPDATE ON smart.station REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.station', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_station_delete", "CREATE TRIGGER trg_station_delete AFTER DELETE ON smart.station REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.station', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_summary_query_insert", "CREATE TRIGGER trg_summary_query_insert AFTER INSERT ON smart.summary_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.summary_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_summary_query_update", "CREATE TRIGGER trg_summary_query_update AFTER UPDATE ON smart.summary_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.summary_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_summary_query_delete", "CREATE TRIGGER trg_summary_query_delete AFTER DELETE ON smart.summary_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.summary_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_team_insert", "CREATE TRIGGER trg_team_insert AFTER INSERT ON smart.team REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.team', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_team_update", "CREATE TRIGGER trg_team_update AFTER UPDATE ON smart.team REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.team', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_team_delete", "CREATE TRIGGER trg_team_delete AFTER DELETE ON smart.team REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.team', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_track_insert", "CREATE TRIGGER trg_track_insert AFTER INSERT ON smart.track REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.track', 'uuid', new.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl, smart.patrol_leg_day pld where p.uuid = pl.patrol_uuid and pl.uuid = pld.patrol_leg_uuid and pld.uuid = new.patrol_leg_day_uuid"},
		{"trg_track_update", "CREATE TRIGGER trg_track_update AFTER UPDATE ON smart.track REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.track', 'uuid', new.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl, smart.patrol_leg_day pld where p.uuid = pl.patrol_uuid and pl.uuid = pld.patrol_leg_uuid and pld.uuid = new.patrol_leg_day_uuid"},
		{"trg_track_delete", "CREATE TRIGGER trg_track_delete AFTER DELETE ON smart.track REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.track', 'uuid', old.uuid, p.ca_uuid from smart.patrol p, smart.patrol_leg pl, smart.patrol_leg_day pld where p.uuid = pl.patrol_uuid and pl.uuid = pld.patrol_leg_uuid and pld.uuid = old.patrol_leg_day_uuid"},
		{"trg_waypoint_insert", "CREATE TRIGGER trg_waypoint_insert AFTER INSERT ON smart.waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.waypoint', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_waypoint_update", "CREATE TRIGGER trg_waypoint_update AFTER UPDATE ON smart.waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.waypoint', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_waypoint_delete", "CREATE TRIGGER trg_waypoint_delete AFTER DELETE ON smart.waypoint REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.waypoint', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_waypoint_query_insert", "CREATE TRIGGER trg_waypoint_query_insert AFTER INSERT ON smart.waypoint_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.waypoint_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_waypoint_query_update", "CREATE TRIGGER trg_waypoint_query_update AFTER UPDATE ON smart.waypoint_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.waypoint_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_waypoint_query_delete", "CREATE TRIGGER trg_waypoint_query_delete AFTER DELETE ON smart.waypoint_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.waypoint_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_wp_attachments_insert", "CREATE TRIGGER trg_wp_attachments_insert AFTER INSERT ON smart.wp_attachments REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.wp_attachments', 'uuid', new.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_wp_attachments_update", "CREATE TRIGGER trg_wp_attachments_update AFTER UPDATE ON smart.wp_attachments REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.wp_attachments', 'uuid', new.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_wp_attachments_delete", "CREATE TRIGGER trg_wp_attachments_delete AFTER DELETE ON smart.wp_attachments REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.wp_attachments', 'uuid', old.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = old.wp_uuid"},
		{"trg_wp_observation_insert", "CREATE TRIGGER trg_wp_observation_insert AFTER INSERT ON smart.wp_observation REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.wp_observation', 'uuid', new.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_wp_observation_update", "CREATE TRIGGER trg_wp_observation_update AFTER UPDATE ON smart.wp_observation REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.wp_observation', 'uuid', new.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_wp_observation_delete", "CREATE TRIGGER trg_wp_observation_delete AFTER DELETE ON smart.wp_observation REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.wp_observation', 'uuid', old.uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = old.wp_uuid"},
		{"trg_wp_observation_attributes_insert", "CREATE TRIGGER trg_wp_observation_attributes_insert AFTER INSERT ON smart.wp_observation_attributes REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid,ca_uuid) select smart.uuid(), 'INSERT', 'smart.wp_observation_attributes', 'observation_uuid', new.observation_uuid, 'attribute_uuid', new.attribute_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_wp_observation_attributes_update", "CREATE TRIGGER trg_wp_observation_attributes_update AFTER UPDATE ON smart.wp_observation_attributes REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid,ca_uuid) select smart.uuid(), 'UPDATE', 'smart.wp_observation_attributes', 'observation_uuid', new.observation_uuid, 'attribute_uuid', new.attribute_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = new.attribute_uuid"},
		{"trg_wp_observation_attributes_delete", "CREATE TRIGGER trg_wp_observation_attributes_delete AFTER DELETE ON smart.wp_observation_attributes REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid,ca_uuid) select smart.uuid(), 'DELETE', 'smart.wp_observation_attributes', 'observation_uuid', old.observation_uuid, 'attribute_uuid', old.attribute_uuid, a.ca_uuid from smart.dm_attribute a where a.uuid = old.attribute_uuid"},
		{"trg_cm_attribute_insert", "CREATE TRIGGER trg_cm_attribute_insert AFTER INSERT ON smart.cm_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.cm_attribute', 'uuid', new.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = new.attribute_uuid"},
		{"trg_cm_attribute_update", "CREATE TRIGGER trg_cm_attribute_update AFTER UPDATE ON smart.cm_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.cm_attribute', 'uuid', new.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = new.attribute_uuid"},
		{"trg_cm_attribute_delete", "CREATE TRIGGER trg_cm_attribute_delete AFTER DELETE ON smart.cm_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.cm_attribute', 'uuid', old.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = old.attribute_uuid"},
		{"trg_cm_attribute_list_insert", "CREATE TRIGGER trg_cm_attribute_list_insert AFTER INSERT ON smart.cm_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.cm_attribute_list', 'uuid', new.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = new.dm_attribute_uuid"},
		{"trg_cm_attribute_list_update", "CREATE TRIGGER trg_cm_attribute_list_update AFTER UPDATE ON smart.cm_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.cm_attribute_list', 'uuid', new.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = new.dm_attribute_uuid"},
		{"trg_cm_attribute_list_delete", "CREATE TRIGGER trg_cm_attribute_list_delete AFTER DELETE ON smart.cm_attribute_list REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.cm_attribute_list', 'uuid', old.uuid, a.ca_uuid FROM smart.dm_attribute a WHERE a.uuid = old.dm_attribute_uuid"},
		{"trg_cm_attribute_option_insert", "CREATE TRIGGER trg_cm_attribute_option_insert AFTER INSERT ON smart.cm_attribute_option REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.cm_attribute_option', 'uuid', new.uuid, dm.ca_uuid FROM smart.cm_attribute cm, smart.dm_attribute dm where cm.attribute_uuid = dm.uuid and cm.uuid = new.cm_attribute_uuid"},
		{"trg_cm_attribute_option_update", "CREATE TRIGGER trg_cm_attribute_option_update AFTER UPDATE ON smart.cm_attribute_option REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.cm_attribute_option', 'uuid', new.uuid, dm.ca_uuid FROM smart.cm_attribute cm, smart.dm_attribute dm where cm.attribute_uuid = dm.uuid and cm.uuid = new.cm_attribute_uuid"},
		{"trg_cm_attribute_option_delete", "CREATE TRIGGER trg_cm_attribute_option_delete AFTER DELETE ON smart.cm_attribute_option REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.cm_attribute_option', 'uuid', old.uuid, dm.ca_uuid FROM smart.cm_attribute cm, smart.dm_attribute dm where cm.attribute_uuid = dm.uuid and cm.uuid = old.cm_attribute_uuid"},
		{"trg_cm_attribute_tree_node_insert", "CREATE TRIGGER trg_cm_attribute_tree_node_insert AFTER INSERT ON smart.cm_attribute_tree_node REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.cm_attribute_tree_node', 'uuid', new.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = new.cm_uuid"},
		{"trg_cm_attribute_tree_node_update", "CREATE TRIGGER trg_cm_attribute_tree_node_update AFTER UPDATE ON smart.cm_attribute_tree_node REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.cm_attribute_tree_node', 'uuid', new.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = new.cm_uuid"},
		{"trg_cm_attribute_tree_node_delete", "CREATE TRIGGER trg_cm_attribute_tree_node_delete AFTER DELETE ON smart.cm_attribute_tree_node REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.cm_attribute_tree_node', 'uuid', old.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = old.cm_uuid"},
		{"trg_cm_node_insert", "CREATE TRIGGER trg_cm_node_insert AFTER INSERT ON smart.cm_node REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.cm_node', 'uuid', new.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = new.cm_uuid"},
		{"trg_cm_node_update", "CREATE TRIGGER trg_cm_node_update AFTER UPDATE ON smart.cm_node REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.cm_node', 'uuid', new.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = new.cm_uuid"},
		{"trg_cm_node_delete", "CREATE TRIGGER trg_cm_node_delete AFTER DELETE ON smart.cm_node REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.cm_node', 'uuid', old.uuid, cm.ca_uuid FROM smart.configurable_model cm where cm.uuid = old.cm_uuid"},
		{"trg_configurable_model_insert", "CREATE TRIGGER trg_configurable_model_insert AFTER INSERT ON smart.configurable_model REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.configurable_model', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_configurable_model_update", "CREATE TRIGGER trg_configurable_model_update AFTER UPDATE ON smart.configurable_model REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.configurable_model', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_configurable_model_delete", "CREATE TRIGGER trg_configurable_model_delete AFTER DELETE ON smart.configurable_model REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.configurable_model', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_screen_option_insert", "CREATE TRIGGER trg_screen_option_insert AFTER INSERT ON smart.screen_option REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.screen_option', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_screen_option_update", "CREATE TRIGGER trg_screen_option_update AFTER UPDATE ON smart.screen_option REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.screen_option', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_screen_option_delete", "CREATE TRIGGER trg_screen_option_delete AFTER DELETE ON smart.screen_option REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.screen_option', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_screen_option_uuid_insert", "CREATE TRIGGER trg_screen_option_uuid_insert AFTER INSERT ON smart.screen_option_uuid REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.screen_option_uuid', 'uuid', new.uuid, op.ca_uuid from smart.screen_option op where op.uuid = new.option_uuid"},
		{"trg_screen_option_uuid_update", "CREATE TRIGGER trg_screen_option_uuid_update AFTER UPDATE ON smart.screen_option_uuid REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.screen_option_uuid', 'uuid', new.uuid, op.ca_uuid from smart.screen_option op where op.uuid = new.option_uuid"},
		{"trg_screen_option_uuid_delete", "CREATE TRIGGER trg_screen_option_uuid_delete AFTER DELETE ON smart.screen_option_uuid REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.screen_option_uuid', 'uuid', old.uuid, op.ca_uuid from smart.screen_option op where op.uuid = old.option_uuid"},
	};


	@Override
	public String[][] getTriggers() {
		return triggers;
	}

}
