//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.17 at 07:16:18 AM BRT 
//


package org.wcs.smart.conversion.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for CategoryMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryMap">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="ai" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="an" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryMap", propOrder = {
    "value"
})
public class CategoryMap {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ai")
    protected String ai;
    @XmlAttribute(name = "an")
    protected String an;
    @XmlAttribute(name = "vi")
    protected String vi;
    @XmlAttribute(name = "vn")
    protected String vn;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the ai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAi() {
        return ai;
    }

    /**
     * Sets the value of the ai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAi(String value) {
        this.ai = value;
    }

    /**
     * Gets the value of the an property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAn() {
        return an;
    }

    /**
     * Sets the value of the an property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAn(String value) {
        this.an = value;
    }

    /**
     * Gets the value of the vi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVi() {
        return vi;
    }

    /**
     * Sets the value of the vi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVi(String value) {
        this.vi = value;
    }

    /**
     * Gets the value of the vn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVn() {
        return vn;
    }

    /**
     * Sets the value of the vn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVn(String value) {
        this.vn = value;
    }

}
