source.. = shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               OSGI-INF/l10n/bundle.properties,\
               lib/commons-exec-1.1.jar
