/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.plugin;

import org.wcs.smart.changetracking.AbstractChangeTrackerInstaller;
import org.wcs.smart.i2.Intelligence2PlugIn;

/**
 * Installs triggers for change tracking the plan plugin.
 * 
 * @author Emily
 *
 */
public class ChangeTrackerInstaller extends AbstractChangeTrackerInstaller {
	
	@SuppressWarnings("nls")
	private String[][] triggers = new String[][]{
		{"smart.trg_i_attachment_insert", "CREATE TRIGGER smart.trg_i_attachment_insert AFTER INSERT ON smart.i_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_attachment', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_attachment_update", "CREATE TRIGGER smart.trg_i_attachment_update AFTER UPDATE ON smart.i_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_attachment', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_attachment_delete", "CREATE TRIGGER smart.trg_i_attachment_delete AFTER DELETE ON smart.i_attachment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_attachment', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_attribute_insert", "CREATE TRIGGER smart.trg_i_attribute_insert AFTER INSERT ON smart.i_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_attribute_update", "CREATE TRIGGER smart.trg_i_attribute_update AFTER UPDATE ON smart.i_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_attribute_delete", "CREATE TRIGGER smart.trg_i_attribute_delete AFTER DELETE ON smart.i_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_attribute', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_attribute_list_item_insert", "CREATE TRIGGER smart.trg_i_attribute_list_item_insert AFTER INSERT ON smart.i_attribute_list_item REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_attribute_list_item', 'uuid', new.uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_attribute_list_item_update", "CREATE TRIGGER smart.trg_i_attribute_list_item_update AFTER update ON smart.i_attribute_list_item REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_attribute_list_item', 'uuid', new.uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_attribute_list_item_delete", "CREATE TRIGGER smart.trg_i_attribute_list_item_delete AFTER delete ON smart.i_attribute_list_item REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_attribute_list_item', 'uuid', old.uuid, i.ca_uuid from smart.i_attribute i where i.uuid = old.attribute_uuid"},
		{"smart.trg_i_entity_insert", "CREATE TRIGGER smart.trg_i_entity_insert AFTER INSERT ON smart.i_entity REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_update", "CREATE TRIGGER smart.trg_i_entity_update AFTER UPDATE ON smart.i_entity REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_delete", "CREATE TRIGGER smart.trg_i_entity_delete AFTER DELETE ON smart.i_entity REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_entity_attachment_insert", "CREATE TRIGGER smart.trg_i_entity_attachment_insert AFTER INSERT ON smart.i_entity_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_attachment', 'entity_uuid', new.entity_uuid, 'attachment_uuid', new.attachment_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_attachment_update", "CREATE TRIGGER smart.trg_i_entity_attachment_update AFTER update ON smart.i_entity_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_attachment', 'entity_uuid', new.entity_uuid, 'attachment_uuid', new.attachment_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_attachment_delete", "CREATE TRIGGER smart.trg_i_entity_attachment_delete AFTER delete ON smart.i_entity_attachment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_attachment', 'entity_uuid', old.entity_uuid, 'attachment_uuid', old.attachment_uuid, i.ca_uuid from smart.i_entity i where i.uuid = old.entity_uuid"},	
		{"smart.trg_i_entity_attribute_value_insert", "CREATE TRIGGER smart.trg_i_entity_attribute_value_insert AFTER INSERT ON smart.i_entity_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_attribute_value', 'entity_uuid', new.entity_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_attribute_value_update", "CREATE TRIGGER smart.trg_i_entity_attribute_value_update AFTER UPDATE ON smart.i_entity_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_attribute_value', 'entity_uuid', new.entity_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_attribute_value_delete", "CREATE TRIGGER smart.trg_i_entity_attribute_value_delete AFTER DELETE ON smart.i_entity_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_attribute_value', 'entity_uuid', old.entity_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_entity i where i.uuid = old.entity_uuid"},   
		{"smart.trg_i_entity_location_insert", "CREATE TRIGGER smart.trg_i_entity_location_insert AFTER INSERT ON smart.i_entity_location REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_location', 'entity_uuid', new.entity_uuid, 'location_uuid', new.location_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_location_update", "CREATE TRIGGER smart.trg_i_entity_location_update AFTER update ON smart.i_entity_location REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_location', 'entity_uuid', new.entity_uuid, 'location_uuid', new.location_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_location_delete", "CREATE TRIGGER smart.trg_i_entity_location_delete AFTER delete ON smart.i_entity_location REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_location', 'entity_uuid', old.entity_uuid, 'location_uuid', old.location_uuid, i.ca_uuid from smart.i_entity i where i.uuid = old.entity_uuid"},
		{"smart.trg_i_entity_record_insert", "CREATE TRIGGER smart.trg_i_entity_record_insert AFTER INSERT ON smart.i_entity_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_record', 'entity_uuid', new.entity_uuid, 'record_uuid', new.record_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_record_update", "CREATE TRIGGER smart.trg_i_entity_record_update AFTER update ON smart.i_entity_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_record', 'entity_uuid', new.entity_uuid, 'record_uuid', new.record_uuid, i.ca_uuid from smart.i_entity i where i.uuid = new.entity_uuid"},
		{"smart.trg_i_entity_record_delete", "CREATE TRIGGER smart.trg_i_entity_record_delete AFTER delete ON smart.i_entity_record REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_record', 'entity_uuid', old.entity_uuid, 'record_uuid', old.record_uuid, i.ca_uuid from smart.i_entity i where i.uuid = old.entity_uuid"},
		{"smart.trg_i_entity_relationship_insert", "CREATE TRIGGER smart.trg_i_entity_relationship_insert AFTER INSERT ON smart.i_entity_relationship REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_relationship', 'uuid', new.uuid, i.ca_uuid from smart.i_relationship_type i where i.uuid = new.relationship_type_uuid"},
		{"smart.trg_i_entity_relationship_update", "CREATE TRIGGER smart.trg_i_entity_relationship_update AFTER update ON smart.i_entity_relationship REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_relationship', 'uuid', new.uuid, i.ca_uuid from smart.i_relationship_type i where i.uuid = new.relationship_type_uuid"},
		{"smart.trg_i_entity_relationship_delete", "CREATE TRIGGER smart.trg_i_entity_relationship_delete AFTER delete ON smart.i_entity_relationship REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_relationship', 'uuid', old.uuid, i.ca_uuid from smart.i_relationship_type i where i.uuid = old.relationship_type_uuid"},
		{"smart.trg_i_entity_relationship_attribute_value_insert", "CREATE TRIGGER smart.trg_i_entity_relationship_attribute_value_insert AFTER INSERT ON smart.i_entity_relationship_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_relationship_attribute_value', 'entity_relationship_uuid', new.entity_relationship_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_entity_relationship_attribute_value_update", "CREATE TRIGGER smart.trg_i_entity_relationship_attribute_value_update AFTER update ON smart.i_entity_relationship_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_relationship_attribute_value', 'entity_relationship_uuid', new.entity_relationship_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_entity_relationship_attribute_value_delete", "CREATE TRIGGER smart.trg_i_entity_relationship_attribute_value_delete AFTER delete ON smart.i_entity_relationship_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_relationship_attribute_value', 'entity_relationship_uuid', old.entity_relationship_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = old.attribute_uuid"},
		{"smart.trg_i_entity_search_insert", "CREATE TRIGGER smart.trg_i_entity_search_insert AFTER INSERT ON smart.i_entity_search REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_search', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_search_update", "CREATE TRIGGER smart.trg_i_entity_search_update AFTER UPDATE ON smart.i_entity_search REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_search', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_search_delete", "CREATE TRIGGER smart.trg_i_entity_search_delete AFTER DELETE ON smart.i_entity_search REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_search', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_entity_type_insert", "CREATE TRIGGER smart.trg_i_entity_type_insert AFTER INSERT ON smart.i_entity_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_type_update", "CREATE TRIGGER smart.trg_i_entity_type_update AFTER UPDATE ON smart.i_entity_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_entity_type_delete", "CREATE TRIGGER smart.trg_i_entity_type_delete AFTER DELETE ON smart.i_entity_type REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_type', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_entity_type_attribute_insert", "CREATE TRIGGER smart.trg_i_entity_type_attribute_insert AFTER INSERT ON smart.i_entity_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_type_attribute', 'entity_type_uuid', new.entity_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = new.entity_type_uuid"},
		{"smart.trg_i_entity_type_attribute_update", "CREATE TRIGGER smart.trg_i_entity_type_attribute_update AFTER update ON smart.i_entity_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_type_attribute', 'entity_type_uuid', new.entity_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = new.entity_type_uuid"},
		{"smart.trg_i_entity_type_attribute_delete", "CREATE TRIGGER smart.trg_i_entity_type_attribute_delete AFTER delete ON smart.i_entity_type_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_type_attribute', 'entity_type_uuid', old.entity_type_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = old.entity_type_uuid"},
		{"smart.trg_i_entity_type_attribute_group_insert", "CREATE TRIGGER smart.trg_i_entity_type_attribute_group_insert AFTER INSERT ON smart.i_entity_type_attribute_group REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_entity_type_attribute_group', 'uuid', new.uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = new.entity_type_uuid"},
		{"smart.trg_i_entity_type_attribute_group_update", "CREATE TRIGGER smart.trg_i_entity_type_attribute_group_update AFTER update ON smart.i_entity_type_attribute_group REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_entity_type_attribute_group', 'uuid', new.uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = new.entity_type_uuid"},
		{"smart.trg_i_entity_type_attribute_group_delete", "CREATE TRIGGER smart.trg_i_entity_type_attribute_group_delete AFTER delete ON smart.i_entity_type_attribute_group REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_entity_type_attribute_group', 'uuid', old.uuid, i.ca_uuid from smart.i_entity_type i where i.uuid = old.entity_type_uuid"},
		{"smart.trg_i_location_insert", "CREATE TRIGGER smart.trg_i_location_insert AFTER INSERT ON smart.i_location REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_location', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_location_update", "CREATE TRIGGER smart.trg_i_location_update AFTER UPDATE ON smart.i_location REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_location', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_location_delete", "CREATE TRIGGER smart.trg_i_location_delete AFTER DELETE ON smart.i_location REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_location', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_observation_insert", "CREATE TRIGGER smart.trg_i_observation_insert AFTER INSERT ON smart.i_observation REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_observation', 'uuid', new.uuid, i.ca_uuid from smart.i_location i where i.uuid = new.location_uuid"},
		{"smart.trg_i_observation_update", "CREATE TRIGGER smart.trg_i_observation_update AFTER update ON smart.i_observation REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_observation', 'uuid', new.uuid, i.ca_uuid from smart.i_location i where i.uuid = new.location_uuid"},
		{"smart.trg_i_observation_delete", "CREATE TRIGGER smart.trg_i_observation_delete AFTER delete ON smart.i_observation REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_observation', 'uuid', old.uuid, i.ca_uuid from smart.i_location i where i.uuid = old.location_uuid"},
		{"smart.trg_i_observation_attribute_insert", "CREATE TRIGGER smart.trg_i_observation_attribute_insert AFTER INSERT ON smart.i_observation_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_observation_attribute', 'observation_uuid', new.observation_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_observation_attribute_update", "CREATE TRIGGER smart.trg_i_observation_attribute_update AFTER update ON smart.i_observation_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_observation_attribute', 'observation_uuid', new.observation_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_observation_attribute_delete", "CREATE TRIGGER smart.trg_i_observation_attribute_delete AFTER delete ON smart.i_observation_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_observation_attribute', 'observation_uuid', old.observation_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = old.attribute_uuid"},
		{"smart.trg_i_record_insert", "CREATE TRIGGER smart.trg_i_record_insert AFTER INSERT ON smart.i_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_record', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_record_update", "CREATE TRIGGER smart.trg_i_record_update AFTER UPDATE ON smart.i_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_record', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_record_delete", "CREATE TRIGGER smart.trg_i_record_delete AFTER DELETE ON smart.i_record REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_record', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_record_attachment_insert", "CREATE TRIGGER smart.trg_i_record_attachment_insert AFTER INSERT ON smart.i_record_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_record_attachment', 'record_uuid', new.record_uuid, 'attachment_uuid', new.attachment_uuid, i.ca_uuid from smart.i_record i where i.uuid = new.record_uuid"},
		{"smart.trg_i_record_attachment_update", "CREATE TRIGGER smart.trg_i_record_attachment_update AFTER update ON smart.i_record_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_record_attachment', 'record_uuid', new.record_uuid, 'attachment_uuid', new.attachment_uuid, i.ca_uuid from smart.i_record i where i.uuid = new.record_uuid"},
		{"smart.trg_i_record_attachment_delete", "CREATE TRIGGER smart.trg_i_record_attachment_delete AFTER delete ON smart.i_record_attachment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_record_attachment', 'record_uuid', old.record_uuid, 'attachment_uuid', old.attachment_uuid, i.ca_uuid from smart.i_record i where i.uuid = old.record_uuid"},
		{"smart.trg_i_record_obs_query_insert", "CREATE TRIGGER smart.trg_i_record_obs_query_insert AFTER INSERT ON smart.i_record_obs_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_record_obs_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_record_obs_query_update", "CREATE TRIGGER smart.trg_i_record_obs_query_update AFTER UPDATE ON smart.i_record_obs_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_record_obs_query', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_record_obs_query_delete", "CREATE TRIGGER smart.trg_i_record_obs_query_delete AFTER DELETE ON smart.i_record_obs_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_record_obs_query', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_relationship_type_attribute_insert", "CREATE TRIGGER smart.trg_i_relationship_type_attribute_insert AFTER INSERT ON smart.i_relationship_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_relationship_type_attribute', 'relationship_type_uuid', new.relationship_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_relationship_type_attribute_update", "CREATE TRIGGER smart.trg_i_relationship_type_attribute_update AFTER update ON smart.i_relationship_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_relationship_type_attribute', 'relationship_type_uuid', new.relationship_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_i_relationship_type_attribute_delete", "CREATE TRIGGER smart.trg_i_relationship_type_attribute_delete AFTER delete ON smart.i_relationship_type_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_relationship_type_attribute', 'relationship_type_uuid', old.relationship_type_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_attribute i where i.uuid = old.attribute_uuid"},
		{"smart.trg_i_relationship_group_insert", "CREATE TRIGGER smart.trg_i_relationship_group_insert AFTER INSERT ON smart.i_relationship_group REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_relationship_group', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_relationship_group_update", "CREATE TRIGGER smart.trg_i_relationship_group_update AFTER UPDATE ON smart.i_relationship_group REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_relationship_group', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_relationship_group_delete", "CREATE TRIGGER smart.trg_i_relationship_group_delete AFTER DELETE ON smart.i_relationship_group REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_relationship_group', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_relationship_type_insert", "CREATE TRIGGER smart.trg_i_relationship_type_insert AFTER INSERT ON smart.i_relationship_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_relationship_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_relationship_type_update", "CREATE TRIGGER smart.trg_i_relationship_type_update AFTER UPDATE ON smart.i_relationship_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_relationship_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_relationship_type_delete", "CREATE TRIGGER smart.trg_i_relationship_type_delete AFTER DELETE ON smart.i_relationship_type REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_relationship_type', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_working_set_insert", "CREATE TRIGGER smart.trg_i_working_set_insert AFTER INSERT ON smart.i_working_set REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_working_set', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_working_set_update", "CREATE TRIGGER smart.trg_i_working_set_update AFTER UPDATE ON smart.i_working_set REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_working_set', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_working_set_delete", "CREATE TRIGGER smart.trg_i_working_set_delete AFTER DELETE ON smart.i_working_set REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_working_set', 'uuid', old.uuid, old.ca_uuid)"},
		{"smart.trg_i_working_set_entity_insert", "CREATE TRIGGER smart.trg_i_working_set_entity_insert AFTER INSERT ON smart.i_working_set_entity REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_working_set_entity', 'working_set_uuid', new.working_set_uuid, 'entity_uuid', new.entity_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_entity_update", "CREATE TRIGGER smart.trg_i_working_set_entity_update AFTER update ON smart.i_working_set_entity REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_working_set_entity', 'working_set_uuid', new.working_set_uuid, 'entity_uuid', new.entity_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_entity_delete", "CREATE TRIGGER smart.trg_i_working_set_entity_delete AFTER delete ON smart.i_working_set_entity REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_working_set_entity', 'working_set_uuid', old.working_set_uuid, 'entity_uuid', old.entity_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = old.working_set_uuid"},
		{"smart.trg_i_working_set_query_insert", "CREATE TRIGGER smart.trg_i_working_set_query_insert AFTER INSERT ON smart.i_working_set_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_working_set_query', 'working_set_uuid', new.working_set_uuid, 'query_uuid', new.query_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_query_update", "CREATE TRIGGER smart.trg_i_working_set_query_update AFTER update ON smart.i_working_set_query REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_working_set_query', 'working_set_uuid', new.working_set_uuid, 'query_uuid', new.query_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_query_delete", "CREATE TRIGGER smart.trg_i_working_set_query_delete AFTER delete ON smart.i_working_set_query REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_working_set_query', 'working_set_uuid', old.working_set_uuid, 'query_uuid', old.query_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = old.working_set_uuid"},
		{"smart.trg_i_working_set_record_insert", "CREATE TRIGGER smart.trg_i_working_set_record_insert AFTER INSERT ON smart.i_working_set_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_working_set_record', 'working_set_uuid', new.working_set_uuid, 'record_uuid', new.record_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_record_update", "CREATE TRIGGER smart.trg_i_working_set_record_update AFTER update ON smart.i_working_set_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_working_set_record', 'working_set_uuid', new.working_set_uuid, 'record_uuid', new.record_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = new.working_set_uuid"},
		{"smart.trg_i_working_set_record_delete", "CREATE TRIGGER smart.trg_i_working_set_record_delete AFTER delete ON smart.i_working_set_record REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_working_set_record', 'working_set_uuid', old.working_set_uuid, 'record_uuid', old.record_uuid, i.ca_uuid from smart.i_working_set i where i.uuid = old.working_set_uuid"},
		{"smart.trg_i_record_attribute_value_insert", "CREATE TRIGGER smart.trg_i_record_attribute_value_insert AFTER INSERT ON smart.i_record_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_record_attribute_value', 'record_uuid', new.record_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_record i where i.uuid = new.record_uuid"},
		{"smart.trg_i_record_attribute_value_update", "CREATE TRIGGER smart.trg_i_record_attribute_value_update AFTER update ON smart.i_record_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_record_attribute_value', 'record_uuid', new.record_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.i_record i where i.uuid = new.record_uuid"},
		{"smart.trg_i_record_attribute_value_delete", "CREATE TRIGGER smart.trg_i_record_attribute_value_delete AFTER delete ON smart.i_record_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_record_attribute_value', 'record_uuid', old.record_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.i_record i where i.uuid = old.record_uuid"},
		{"smart.trg_i_record_attribute_value_list_insert", "CREATE TRIGGER smart.trg_i_record_attribute_value_list_insert AFTER INSERT ON smart.i_record_attribute_value_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_record_attribute_value_list', 'value_uuid', new.value_uuid, 'element_uuid', new.element_uuid, i.ca_uuid from smart.i_record_attribute_value v, smart.i_record i where v.uuid = new.value_uuid and i.uuid = v.record_uuid"},
		{"smart.trg_i_record_attribute_value_list_update", "CREATE TRIGGER smart.trg_i_record_attribute_value_list_update AFTER update ON smart.i_record_attribute_value_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_record_attribute_value_list', 'value_uuid', new.value_uuid, 'element_uuid', new.element_uuid, i.ca_uuid from smart.i_record_attribute_value v, smart.i_record i where v.uuid = new.value_uuid and i.uuid = v.record_uuid"},
		{"smart.trg_i_record_attribute_value_list_delete", "CREATE TRIGGER smart.trg_i_record_attribute_value_list_delete AFTER delete ON smart.i_record_attribute_value_list REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_record_attribute_value_list', 'value_uuid', old.value_uuid, 'element_uuid', old.element_uuid, i.ca_uuid from smart.i_record_attribute_value v, smart.i_record i where v.uuid = old.value_uuid and i.uuid = v.record_uuid"},
		{"smart.trg_i_recordsource_attribute_insert", "CREATE TRIGGER smart.trg_i_recordsource_attribute_insert AFTER INSERT ON smart.i_recordsource_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_recordsource_attribute', 'uuid', new.uuid, i.ca_uuid from smart.i_recordsource i where i.uuid = new.source_uuid"},
		{"smart.trg_i_recordsource_attribute_update", "CREATE TRIGGER smart.trg_i_recordsource_attribute_update AFTER update ON smart.i_recordsource_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_recordsource_attribute', 'uuid', new.uuid, i.ca_uuid from smart.i_recordsource i where i.uuid = new.source_uuid"},
		{"smart.trg_i_recordsource_attribute_delete", "CREATE TRIGGER smart.trg_i_recordsource_attribute_delete AFTER delete ON smart.i_recordsource_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_recordsource_attribute', 'uuid', old.uuid, i.ca_uuid from smart.i_recordsource i where i.uuid = old.source_uuid"},
		{"smart.trg_i_recordsource_insert", "CREATE TRIGGER smart.trg_i_recordsource_insert AFTER INSERT ON smart.i_recordsource REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.i_recordsource', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_recordsource_update", "CREATE TRIGGER smart.trg_i_recordsource_update AFTER UPDATE ON smart.i_recordsource REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.i_recordsource', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_i_recordsource_delete", "CREATE TRIGGER smart.trg_i_recordsource_delete AFTER DELETE ON smart.i_recordsource REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.i_recordsource', 'uuid', old.uuid, old.ca_uuid)"},

	};
	
	@Override
	public String[][] getCurrentTriggers() {
		return triggers;
	}

	@Override
	public String[] getAllTriggersToDrop(){
		String[] t = new String[triggers.length];
		for (int i = 0; i < triggers.length; i ++){
			t[i] = triggers[i][0];
		}
		return t;
	}
	
	
	@Override
	public String getPluginId() {
		return Intelligence2PlugIn.PLUGIN_ID;
	}

	@Override
	public String getLastestVersion() {
		return Intelligence2PlugIn.DB_VERSION;
	}
}

