//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 03:47:19 PM PST 
//


package org.wcs.smart.patrol.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PatrolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatrolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mandate" type="{http://www.smartconservationsoftware.org/xml/1.0/patrol}LabelType"/>
 *         &lt;element name="objective" type="{http://www.smartconservationsoftware.org/xml/1.0/patrol}ObjectiveType" minOccurs="0"/>
 *         &lt;element name="team" type="{http://www.smartconservationsoftware.org/xml/1.0/patrol}LabelType" minOccurs="0"/>
 *         &lt;element name="station" type="{http://www.smartconservationsoftware.org/xml/1.0/patrol}LabelType" minOccurs="0"/>
 *         &lt;element name="legs" type="{http://www.smartconservationsoftware.org/xml/1.0/patrol}PatrolLegType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="patrolType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ground"/>
 *             &lt;enumeration value="air"/>
 *             &lt;enumeration value="marine"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="endDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="isArmed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatrolType", propOrder = {
    "mandate",
    "objective",
    "team",
    "station",
    "legs",
    "comment"
})
public class PatrolType {

    @XmlElement(required = true)
    protected LabelType mandate;
    protected ObjectiveType objective;
    protected LabelType team;
    protected LabelType station;
    @XmlElement(required = true)
    protected List<PatrolLegType> legs;
    @XmlAttribute(name = "patrolType")
    protected String patrolType;
    @XmlAttribute(name = "startDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(name = "endDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute(name = "isArmed")
    protected Boolean isArmed;
    protected String comment;
    @XmlAttribute(name = "id")
    protected String id;
    
    /**
     * Gets the value of the mandate property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getMandate() {
        return mandate;
    }

    /**
     * Sets the value of the mandate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setMandate(LabelType value) {
        this.mandate = value;
    }

    /**
     * Gets the value of the objective property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectiveType }
     *     
     */
    public ObjectiveType getObjective() {
        return objective;
    }

    /**
     * Sets the value of the objective property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectiveType }
     *     
     */
    public void setObjective(ObjectiveType value) {
        this.objective = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setTeam(LabelType value) {
        this.team = value;
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setStation(LabelType value) {
        this.station = value;
    }

    /**
     * Gets the value of the legs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatrolLegType }
     * 
     * 
     */
    public List<PatrolLegType> getLegs() {
        if (legs == null) {
            legs = new ArrayList<PatrolLegType>();
        }
        return this.legs;
    }

    /**
     * Gets the value of the patrolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatrolType() {
        return patrolType;
    }

    /**
     * Sets the value of the patrolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatrolType(String value) {
        this.patrolType = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the isArmed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsArmed() {
        return isArmed;
    }

    /**
     * Sets the value of the isArmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsArmed(Boolean value) {
        this.isArmed = value;
    }

    
    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String id) {
        this.id = id;
    }
}
