/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.updatesite;

import java.sql.Connection;
import java.sql.SQLException;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.jobs.Job;
import org.eclipse.swt.widgets.Display;
import org.eclipse.ui.application.DisplayAccess;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.wcs.smart.er.EcologicalRecordsPlugIn;
import org.wcs.smart.er.internal.Messages;
import org.wcs.smart.hibernate.HibernateManager;

/**
 * Job adds Ecological Records plug-in related tabled to the database
 * 
 * @author elitvin
 * @since 1.0.0
 */
public class AddERJob extends Job {

	public AddERJob() {
		super(Messages.AddERJob_Title);
	}

	@Override
	protected IStatus run(IProgressMonitor monitor) {
		//required if run during restore to ensure Display.syncexec calls don't block
		DisplayAccess.accessDisplayDuringStartup();
				
		String currentVersion = null;
		Session session = HibernateManager.openSession();
		try{
			currentVersion = HibernateManager.getPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, session);
			if (currentVersion != null && currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION)){
				//db version matches current version; we are ok
				return Status.OK_STATUS;
			}
		}finally{
			session.close();
		}

		session = HibernateManager.openSession();
		session.beginTransaction();
		try {
			if (currentVersion == null){
				createTables(session);
				HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION, session);
			}
			session.getTransaction().commit();
		} catch (final Exception ex) {
			Display.getDefault().syncExec(new Runnable(){
				@Override
				public void run() {
					EcologicalRecordsPlugIn.displayLog(Messages.AddERJob_InstallError, ex);
				}
			});
			return new Status(IStatus.ERROR, EcologicalRecordsPlugIn.PLUGIN_ID, 1, Messages.AddERJob_InstallError, ex); 
		} finally {
			if (session.getTransaction().isActive()) {
				session.getTransaction().rollback();
			}
			if (session.isOpen()) {
				session.close();
			}
		}

		return Status.OK_STATUS;
	}

	private void createTables(Session session){
		final String[] sql = new String[]{
				"CREATE TABLE SMART.MISSION(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_UUID CHAR(16) FOR BIT DATA NOT NULL,ID VARCHAR(128) NOT NULL,START_DATETIME TIMESTAMP NOT NULL,END_DATETIME TIMESTAMP NOT NULL,COMMENT LONG VARCHAR,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_ATTRIBUTE(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,ATT_TYPE VARCHAR(7) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_ATTRIBUTE_LIST(UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,LIST_ORDER SMALLINT NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_MEMBER(MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,EMPLOYEE_UUID CHAR(16) FOR BIT DATA NOT NULL,IS_LEADER BOOLEAN NOT NULL,PRIMARY KEY (MISSION_UUID, EMPLOYEE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_PROPERTY(SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,ATTRIBUTE_ORDER INTEGER NOT NULL,PRIMARY KEY (SURVEY_DESIGN_UUID, MISSION_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_PROPERTY_VALUE(MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,NUMBER_VALUE DOUBLE,STRING_VALUE VARCHAR(1024),LIST_ELEMENT_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (MISSION_UUID, MISSION_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_TRACK(UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA ,TRACK_TYPE VARCHAR(32) NOT NULL,TRACK_DATE DATE NOT NULL,GEOMETRY BLOB NOT NULL,ID VARCHAR(128),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA  NOT NULL,UNIT_TYPE VARCHAR(32) NOT NULL,ID VARCHAR(128) NOT NULL,STATE VARCHAR(8) NOT NULL,GEOMETRY BLOB NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,ID VARCHAR(128) NOT NULL,START_DATE DATE,END_DATE DATE,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,STATE VARCHAR(16) NOT NULL,START_DATE DATE,END_DATE DATE,DISTANCE_DIRECTION BOOLEAN DEFAULT FALSE NOT NULL,DESCRIPTION LONG VARCHAR,CONFIGURABLE_MODEL_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN_PROPERTY(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,NAME VARCHAR(256) NOT NULL,VALUE VARCHAR(8200),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_WAYPOINT(WP_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA,MISSION_TRACK_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (WP_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT(SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,PRIMARY KEY (SURVEY_DESIGN_UUID, SU_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE(SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,SU_UUID CHAR(16) FOR BIT DATA NOT NULL,STRING_VALUE VARCHAR(1024),NUMBER_VALUE DOUBLE,PRIMARY KEY (SU_ATTRIBUTE_UUID, SU_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128),ATT_TYPE VARCHAR(7),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,LIST_ORDER SMALLINT NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				
				"ALTER TABLE SMART.MISSION_MEMBER ADD CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_TRK_UUID FOREIGN KEY (MISSION_TRACK_UUID) REFERENCES SMART.MISSION_TRACK (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST ADD CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST ADD CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (SAMPLING_UNIT_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.MISSION_ATTRIBUTE_LIST (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION ADD CONSTRAINT MISSION_SURVEY_UUID FOREIGN KEY (SURVEY_UUID) REFERENCES SMART.SURVEY (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT ID_SD_UNQ UNIQUE (ID, SURVEY_DESIGN_UUID)", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY ADD CONSTRAINT SURVEY_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY ADD CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE ADD CONSTRAINT SU_ATTRIBUTE_CA_UUID FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SURVEY_DESIGN_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_UUID FOREIGN KEY (SU_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_LIST_ELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT CONFIGURABLE_MODEL_UUID_FK FOREIGN KEY (CONFIGURABLE_MODEL_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT;", //$NON-NLS-1$
				
				"GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO manager", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO data_entry", //$NON-NLS-1$
				"GRANT SELECT ON SMART.MISSION_PROPERTY_VALUE TO analyst", //$NON-NLS-1$

				"GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO manager", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO data_entry", //$NON-NLS-1$
				"GRANT SELECT ON SMART.MISSION_MEMBER TO analyst", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_TRACK TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_WAYPOINT TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_PROPERTY TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_PROPERTY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_PROPERTY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_PROPERTY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE_LIST TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_ATTRIBUTE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_ATTRIBUTE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO manager",		 //$NON-NLS-1$
				
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO manager" //$NON-NLS-1$
		};
		
		session.doWork(new Work() {
			
			@Override
			public void execute(Connection c) throws SQLException {
				for (int i = 0; i < sql.length; i ++){
					c.createStatement().execute(sql[i]);
				}
				
			}
		});
		
	}
	
}
