/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.updatesite;

import org.wcs.smart.changetracking.AbstractChangeTrackerInstaller;

/**
 * Installs triggers required for change log tracking for er plugin.
 * @author Emily
 *
 */
public class ChangeTrackerInstaller extends AbstractChangeTrackerInstaller {

	@SuppressWarnings("nls")
	private String triggers[][] = new String[][]{
		{"trg_mission_insert", "CREATE TRIGGER trg_mission_insert AFTER INSERT ON smart.mission REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission', 'uuid', new.uuid, sd.ca_uuid from smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = new.survey_uuid"},
		{"trg_mission_update", "CREATE TRIGGER trg_mission_update AFTER UPDATE ON smart.mission REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission', 'uuid', new.uuid, sd.ca_uuid from smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = new.survey_uuid"},
		{"trg_mission_delete", "CREATE TRIGGER trg_mission_delete AFTER DELETE ON smart.mission REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission', 'uuid', old.uuid, sd.ca_uuid from smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = old.survey_uuid"},
		{"trg_mission_attribute_insert", "CREATE TRIGGER trg_mission_attribute_insert AFTER INSERT ON smart.mission_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.mission_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_mission_attribute_update", "CREATE TRIGGER trg_mission_attribute_update AFTER UPDATE ON smart.mission_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.mission_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_mission_attribute_delete", "CREATE TRIGGER trg_mission_attribute_delete AFTER DELETE ON smart.mission_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.mission_attribute', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_mission_attribute_list_insert", "CREATE TRIGGER trg_mission_attribute_list_insert AFTER INSERT ON smart.mission_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_attribute_list', 'uuid', new.uuid, ma.ca_uuid FROM smart.mission_attribute ma WHERE ma.uuid = new.mission_attribute_uuid"},
		{"trg_mission_attribute_list_update", "CREATE TRIGGER trg_mission_attribute_list_update AFTER UPDATE ON smart.mission_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_attribute_list', 'uuid', new.uuid, ma.ca_uuid FROM smart.mission_attribute ma WHERE ma.uuid = new.mission_attribute_uuid"},
		{"trg_mission_attribute_list_delete", "CREATE TRIGGER trg_mission_attribute_list_delete AFTER DELETE ON smart.mission_attribute_list REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_attribute_list', 'uuid', old.uuid, ma.ca_uuid FROM smart.mission_attribute ma WHERE ma.uuid = old.mission_attribute_uuid"},
		{"trg_mission_day_insert", "CREATE TRIGGER trg_mission_day_insert AFTER INSERT ON smart.mission_day REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_day', 'uuid', new.uuid, sd.ca_uuid from smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = new.mission_uuid"},
		{"trg_mission_day_update", "CREATE TRIGGER trg_mission_day_update AFTER UPDATE ON smart.mission_day REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_day', 'uuid', new.uuid, sd.ca_uuid from smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = new.mission_uuid"},
		{"trg_mission_day_delete", "CREATE TRIGGER trg_mission_day_delete AFTER DELETE ON smart.mission_day REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_day', 'uuid', old.uuid, sd.ca_uuid from smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = old.mission_uuid"},
		{"trg_mission_member_insert", "CREATE TRIGGER trg_mission_member_insert AFTER INSERT ON smart.mission_member REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_member', 'mission_uuid', new.mission_uuid, 'employee_uuid', new.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = new.employee_uuid"},
		{"trg_mission_member_update", "CREATE TRIGGER trg_mission_member_update AFTER UPDATE ON smart.mission_member REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_member', 'mission_uuid', new.mission_uuid, 'employee_uuid', new.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = new.employee_uuid"},
		{"trg_mission_member_delete", "CREATE TRIGGER trg_mission_member_delete AFTER DELETE ON smart.mission_member REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_member', 'mission_uuid', old.mission_uuid, 'employee_uuid', old.employee_uuid, e.ca_uuid from smart.employee e where e.uuid = old.employee_uuid"},
		{"trg_mission_property_insert", "CREATE TRIGGER trg_mission_property_insert AFTER INSERT ON smart.mission_property REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_property', 'survey_design_uuid', new.survey_design_uuid, 'mission_attribute_uuid', new.mission_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_mission_property_update", "CREATE TRIGGER trg_mission_property_update AFTER UPDATE ON smart.mission_property REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_property', 'survey_design_uuid', new.survey_design_uuid, 'mission_attribute_uuid', new.mission_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_mission_property_delete", "CREATE TRIGGER trg_mission_property_delete AFTER DELETE ON smart.mission_property REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_property', 'survey_design_uuid', old.survey_design_uuid, 'mission_attribute_uuid', old.mission_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = old.survey_design_uuid"},
		{"trg_mission_property_value_insert", "CREATE TRIGGER trg_mission_property_value_insert AFTER INSERT ON smart.mission_property_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_property_value', 'mission_uuid', new.mission_uuid, 'mission_attribute_uuid', new.mission_attribute_uuid, ma.ca_uuid from smart.mission_attribute ma where ma.uuid = new.mission_attribute_uuid"},
		{"trg_mission_property_value_update", "CREATE TRIGGER trg_mission_property_value_update AFTER UPDATE ON smart.mission_property_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_property_value', 'mission_uuid', new.mission_uuid, 'mission_attribute_uuid', new.mission_attribute_uuid, ma.ca_uuid from smart.mission_attribute ma where ma.uuid = new.mission_attribute_uuid"},
		{"trg_mission_property_value_delete", "CREATE TRIGGER trg_mission_property_value_delete AFTER DELETE ON smart.mission_property_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_property_value', 'mission_uuid', old.mission_uuid, 'mission_attribute_uuid', old.mission_attribute_uuid, ma.ca_uuid from smart.mission_attribute ma where ma.uuid = old.mission_attribute_uuid"},
		{"trg_mission_track_insert", "CREATE TRIGGER trg_mission_track_insert AFTER INSERT ON smart.mission_track REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.mission_track', 'uuid', new.uuid, sd.ca_uuid from smart.mission_day md, smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = md.mission_uuid and md.uuid = new.mission_day_uuid"},
		{"trg_mission_track_update", "CREATE TRIGGER trg_mission_track_update AFTER UPDATE ON smart.mission_track REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.mission_track', 'uuid', new.uuid, sd.ca_uuid from smart.mission_day md, smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = md.mission_uuid and md.uuid = new.mission_day_uuid"},
		{"trg_mission_track_delete", "CREATE TRIGGER trg_mission_track_delete AFTER DELETE ON smart.mission_track REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.mission_track', 'uuid', old.uuid, sd.ca_uuid from smart.mission_day md, smart.mission m, smart.survey s, smart.survey_design sd where s.survey_design_uuid = sd.uuid and s.uuid = m.survey_uuid and m.uuid = md.mission_uuid and md.uuid = old.mission_day_uuid"},
		{"trg_sampling_unit_insert", "CREATE TRIGGER trg_sampling_unit_insert AFTER INSERT ON smart.sampling_unit REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.sampling_unit', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_sampling_unit_update", "CREATE TRIGGER trg_sampling_unit_update AFTER UPDATE ON smart.sampling_unit REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.sampling_unit', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_sampling_unit_delete", "CREATE TRIGGER trg_sampling_unit_delete AFTER DELETE ON smart.sampling_unit REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.sampling_unit', 'uuid', old.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = old.survey_design_uuid"},
		{"trg_sampling_unit_attribute_insert", "CREATE TRIGGER trg_sampling_unit_attribute_insert AFTER INSERT ON smart.sampling_unit_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.sampling_unit_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_sampling_unit_attribute_update", "CREATE TRIGGER trg_sampling_unit_attribute_update AFTER UPDATE ON smart.sampling_unit_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.sampling_unit_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_sampling_unit_attribute_delete", "CREATE TRIGGER trg_sampling_unit_attribute_delete AFTER DELETE ON smart.sampling_unit_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.sampling_unit_attribute', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_sampling_unit_attribute_list_insert", "CREATE TRIGGER trg_sampling_unit_attribute_list_insert AFTER INSERT ON smart.sampling_unit_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.sampling_unit_attribute_list', 'uuid', new.uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = new.sampling_unit_attribute_uuid"},
		{"trg_sampling_unit_attribute_list_update", "CREATE TRIGGER trg_sampling_unit_attribute_list_update AFTER UPDATE ON smart.sampling_unit_attribute_list REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.sampling_unit_attribute_list', 'uuid', new.uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = new.sampling_unit_attribute_uuid"},
		{"trg_sampling_unit_attribute_list_delete", "CREATE TRIGGER trg_sampling_unit_attribute_list_delete AFTER DELETE ON smart.sampling_unit_attribute_list REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.sampling_unit_attribute_list', 'uuid', old.uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = old.sampling_unit_attribute_uuid"},
		{"trg_sampling_unit_attribute_value_insert", "CREATE TRIGGER trg_sampling_unit_attribute_value_insert AFTER INSERT ON smart.sampling_unit_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.sampling_unit_attribute_value', 'su_attribute_uuid', new.su_attribute_uuid, 'su_uuid', new.su_uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = new.su_attribute_uuid"},
		{"trg_sampling_unit_attribute_value_update", "CREATE TRIGGER trg_sampling_unit_attribute_value_update AFTER UPDATE ON smart.sampling_unit_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.sampling_unit_attribute_value', 'su_attribute_uuid', new.su_attribute_uuid, 'su_uuid', new.su_uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = new.su_attribute_uuid"},
		{"trg_sampling_unit_attribute_value_delete", "CREATE TRIGGER trg_sampling_unit_attribute_value_delete AFTER DELETE ON smart.sampling_unit_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.sampling_unit_attribute_value', 'su_attribute_uuid', old.su_attribute_uuid, 'su_uuid', old.su_uuid, sa.ca_uuid from smart.sampling_unit_attribute sa where sa.uuid = old.su_attribute_uuid"},
		{"trg_survey_insert", "CREATE TRIGGER trg_survey_insert AFTER INSERT ON smart.survey REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.survey', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_update", "CREATE TRIGGER trg_survey_update AFTER UPDATE ON smart.survey REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.survey', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_delete", "CREATE TRIGGER trg_survey_delete AFTER DELETE ON smart.survey REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.survey', 'uuid', old.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = old.survey_design_uuid"},
		{"trg_survey_design_insert", "CREATE TRIGGER trg_survey_design_insert AFTER INSERT ON smart.survey_design REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'INSERT', 'smart.survey_design', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_survey_design_update", "CREATE TRIGGER trg_survey_design_update AFTER UPDATE ON smart.survey_design REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'UPDATE', 'smart.survey_design', 'uuid', new.uuid, new.ca_uuid)"},
		{"trg_survey_design_delete", "CREATE TRIGGER trg_survey_design_delete AFTER DELETE ON smart.survey_design REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.uuid(), 'DELETE', 'smart.survey_design', 'uuid', old.uuid, old.ca_uuid)"},
		{"trg_survey_design_property_insert", "CREATE TRIGGER trg_survey_design_property_insert AFTER INSERT ON smart.survey_design_property REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'INSERT', 'smart.survey_design_property', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_design_property_update", "CREATE TRIGGER trg_survey_design_property_update AFTER UPDATE ON smart.survey_design_property REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.survey_design_property', 'uuid', new.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_design_property_delete", "CREATE TRIGGER trg_survey_design_property_delete AFTER DELETE ON smart.survey_design_property REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.uuid(), 'DELETE', 'smart.survey_design_property', 'uuid', old.uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = old.survey_design_uuid"},
		{"trg_survey_design_sampling_unit_insert", "CREATE TRIGGER trg_survey_design_sampling_unit_insert AFTER INSERT ON smart.survey_design_sampling_unit REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.survey_design_sampling_unit', 'survey_design_uuid', new.survey_design_uuid, 'su_attribute_uuid', new.su_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_design_sampling_unit_update", "CREATE TRIGGER trg_survey_design_sampling_unit_update AFTER UPDATE ON smart.survey_design_sampling_unit REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.survey_design_sampling_unit', 'survey_design_uuid', new.survey_design_uuid, 'su_attribute_uuid', new.su_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = new.survey_design_uuid"},
		{"trg_survey_design_sampling_unit_delete", "CREATE TRIGGER trg_survey_design_sampling_unit_delete AFTER DELETE ON smart.survey_design_sampling_unit REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.survey_design_sampling_unit', 'survey_design_uuid', old.survey_design_uuid, 'su_attribute_uuid', old.su_attribute_uuid, sd.ca_uuid from smart.survey_design sd where sd.uuid = old.survey_design_uuid"},
		{"trg_survey_waypoint_insert", "CREATE TRIGGER trg_survey_waypoint_insert AFTER INSERT ON smart.survey_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'INSERT', 'smart.survey_waypoint', 'wp_uuid', new.wp_uuid, 'mission_day_uuid', new.mission_day_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_survey_waypoint_update", "CREATE TRIGGER trg_survey_waypoint_update AFTER UPDATE ON smart.survey_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'UPDATE', 'smart.survey_waypoint', 'wp_uuid', new.wp_uuid, 'mission_day_uuid', new.mission_day_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = new.wp_uuid"},
		{"trg_survey_waypoint_delete", "CREATE TRIGGER trg_survey_waypoint_delete AFTER DELETE ON smart.survey_waypoint REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.uuid(), 'DELETE', 'smart.survey_waypoint', 'wp_uuid', old.wp_uuid, 'mission_day_uuid', old.mission_day_uuid, wp.ca_uuid from smart.waypoint wp where wp.uuid = old.wp_uuid"},
	};

	@Override
	public String[][] getTriggers() {
		return triggers;
	}
}
