source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               fragment.e4xmi,\
               images/,\
               lib/java-string-similarity-0.19.jar,\
               lib/jcip-annotations-1.0.jar,\
               lib/commons-codec-1.6.jar,\
               src/org/wcs/smart/i2/search/words.txt,\
               OSGI-INF/l10n/bundle.properties
