
/* Drop Tables */
DROP TABLE SMART.MISSION_MEMBER;
DROP TABLE SMART.MISSION_PROPERTY_VALUE;
DROP TABLE SMART.SURVEY_WAYPOINT;
DROP TABLE SMART.MISSION_TRACK;
DROP TABLE SMART.MISSION;
DROP TABLE SMART.MISSION_ATTRIBUTE_LIST;
DROP TABLE SMART.MISSION_PROPERTY;
DROP TABLE SMART.MISSION_ATTRIBUTE;
DROP TABLE SMART.SAMPLING_UNIT;
DROP TABLE SMART.SURVEY;
DROP TABLE SMART.SURVEY_DESIGN_PROPERTY;
DROP TABLE SMART.SURVEY_DESIGN;

DROP TABLE SMART.SURVEY_DESING_SAMPLING_UNIT;
DROP TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE;
DROP TABLE SMART.SAMPLING_UNIT_ATTRIBUTE;





/* Create Tables */

-- A mission representing the act of performing the survey in the field.
CREATE TABLE SMART.MISSION
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	SURVEY_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ID VARCHAR(128) NOT NULL,
	START_DATETIME TIMESTAMP NOT NULL,
	END_DATETIME TIMESTAMP NOT NULL,
	COMMENT LONG VARCHAR,
	PRIMARY KEY (UUID)
);


-- A shared mission property.  These are shared across a Conservation Area and have keys for querying across conservation areas.
CREATE TABLE SMART.MISSION_ATTRIBUTE
(
	-- --for bit data
	-- 
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	ATT_TYPE VARCHAR(7) NOT NULL,
	PRIMARY KEY (UUID)
);


-- A mission attribute list element
CREATE TABLE SMART.MISSION_ATTRIBUTE_LIST
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	LIST_ORDER SMALLINT NOT NULL,
	PRIMARY KEY (UUID)
);


-- A mission member.
CREATE TABLE SMART.MISSION_MEMBER
(
	MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,
	EMPLOYEE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	PRIMARY KEY (MISSION_UUID, EMPLOYEE_UUID)
);


-- A link between a mission attribute and a mission property.  Allow for reuse of mission attributes between various survey designs.
CREATE TABLE SMART.MISSION_PROPERTY
(
	SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,
	MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ATTRIBUTE_ORDER INTEGER NOT NULL,
	PRIMARY KEY (SURVEY_DESIGN_UUID, MISSION_ATTRIBUTE_UUID)
);


-- A mission property value.
CREATE TABLE SMART.MISSION_PROPERTY_VALUE
(
	MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,
	MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	NUMBER_VALUE DOUBLE,
	STRING_VALUE VARCHAR(1024),
	LIST_ELEMENT_UUID CHAR(16) FOR BIT DATA,
	PRIMARY KEY (MISSION_UUID, MISSION_ATTRIBUTE_UUID)
);


-- A mission track.  There can be multiple tracks per mission.
CREATE TABLE SMART.MISSION_TRACK
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,
	SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA ,
	TRACK_TYPE VARCHAR(32) NOT NULL,
	TRACK_DATE DATE NOT NULL,
	GEOMETRY BLOB NOT NULL,
	ID VARCHAR(128),
	PRIMARY KEY (UUID)
);


-- A survey sampling unit and associated properties.
CREATE TABLE SMART.SAMPLING_UNIT
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA  NOT NULL,
	UNIT_TYPE VARCHAR(32) NOT NULL,
	ID VARCHAR(128),
	BUFFER DOUBLE,
	STATE VARCHAR(8) NOT NULL,
	GEOMETRY BLOB,
	PRIMARY KEY (UUID)
);


-- A survey object which contains a collection of missions.
CREATE TABLE SMART.SURVEY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ID VARCHAR(128) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	PRIMARY KEY (UUID)
);


-- The main survey design object table for recording surveys.
CREATE TABLE SMART.SURVEY_DESIGN
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	STATE VARCHAR(16) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	DISTANCE_DIRECTION BOOLEAN DEFAULT FALSE NOT NULL,
	DESCRIPTION LONG VARCHAR,
	CONFIGURABLE_MODEL_UUID CHAR(16) FOR BIT DATA,
	PRIMARY KEY (UUID)
);


-- A simple key value table for storing survey design properties.
CREATE TABLE SMART.SURVEY_DESIGN_PROPERTY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	VALUE VARCHAR(8200),
	PRIMARY KEY (UUID)
);


-- A link between a SMART waypoint and a survey waypoint providing additional information such as the sampling unit and mission of the associated waypoint.
CREATE TABLE SMART.SURVEY_WAYPOINT
(
	WP_UUID CHAR(16) FOR BIT DATA NOT NULL,
	MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,
	SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA,
	MISSION_TRACK_UUID CHAR(16) FOR BIT DATA,
	PRIMARY KEY (WP_UUID)
);

CREATE TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT
(
	SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,
	SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	PRIMARY KEY (SURVEY_DESIGN_UUID, SU_ATTRIBUTE_UUID)
);

CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE
(
	SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	SU_UUID CHAR(16) FOR BIT DATA NOT NULL,
	STRING_VALUE VARCHAR(1024),
	DOUBLE_VALUE DOUBLE,
	PRIMARY KEY (SU_ATTRIBUTE_UUID, SU_UUID)
);

CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	KEYID VARCHAR(128),
	ATT_TYPE VARCHAR(7),
	PRIMARY KEY (UUID)
);



/* Create Foreign Keys */

ALTER TABLE SMART.MISSION_MEMBER ADD CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) 
	REFERENCES SMART.MISSION (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID FOREIGN KEY (MISSION_UUID)
	REFERENCES SMART.MISSION (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK_MISSION_UUID FOREIGN KEY (MISSION_UUID)
	REFERENCES SMART.MISSION (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_UUID FOREIGN KEY (MISSION_UUID)
	REFERENCES SMART.MISSION (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_TRK_UUID FOREIGN KEY (MISSION_TRACK_UUID)
	REFERENCES SMART.MISSION_TRACK (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST ADD CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID)
	REFERENCES SMART.MISSION_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID)
	REFERENCES SMART.MISSION_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID FOREIGN KEY (MISSION_ATTRIBUTE_UUID)
	REFERENCES SMART.MISSION_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK FOREIGN KEY (SAMPLING_UNIT_UUID)
	REFERENCES SMART.SAMPLING_UNIT (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID FOREIGN KEY (SAMPLING_UNIT_UUID)
	REFERENCES SMART.SAMPLING_UNIT (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION ADD CONSTRAINT MISSION_SURVEY_UUID FOREIGN KEY (SURVEY_UUID)
	REFERENCES SMART.SURVEY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID)
	REFERENCES SMART.SURVEY_DESIGN (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID)
	REFERENCES SMART.SURVEY_DESIGN (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY ADD CONSTRAINT SURVEY_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID)
	REFERENCES SMART.SURVEY_DESIGN (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY ADD CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID)
	REFERENCES SMART.SURVEY_DESIGN (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE ADD CONSTRAINT SU_ATTRIBUTE_CA_UUID FOREIGN KEY (CA_UUID)
	REFERENCES SMART.CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SURVEY_DESIGN_UUID FOREIGN KEY (SURVEY_DESIGN_UUID)
	REFERENCES SMART.SURVEY_DESIGN(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID)
	REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID)
	REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_UUID FOREIGN KEY (SU_UUID)
	REFERENCES SMART.SAMPLING_UNIT(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO manager;
GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO data_entry;
GRANT SELECT ON SMART.MISSION_PROPERTY_VALUE TO analsyt;

GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO manager;
GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO data_entry;
GRANT SELECT ON SMART.MISSION_MEMBER TO analsyt;

GRANT SELECT ON smart.MISSION_TRACK TO analyst;
GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO data_entry;
GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO manager;

GRANT SELECT ON smart.SURVEY_WAYPOINT TO analyst;
GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO data_entry;
GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO manager;

GRANT SELECT ON smart.MISSION TO analyst;
GRANT ALL PRIVILEGES ON smart.MISSION TO data_entry;
GRANT ALL PRIVILEGES ON smart.MISSION TO manager;

GRANT SELECT ON smart.MISSION_PROPERTY TO analyst;
GRANT SELECT ON smart.MISSION_PROPERTY TO data_entry;
GRANT ALL PRIVILEGES ON smart.MISSION_PROPERTY TO manager;

GRANT SELECT ON smart.SAMPLING_UNIT TO analyst;
GRANT SELECT ON smart.SAMPLING_UNIT TO data_entry;
GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT TO manager;

GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO analyst;
GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO data_entry;
GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_PROPERTY TO manager;

GRANT SELECT ON smart.SURVEY TO analyst;
GRANT ALL PRIVILEGES ON smart.SURVEY TO data_entry;
GRANT ALL PRIVILEGES ON smart.SURVEY TO manager;

GRANT SELECT ON smart.SURVEY_DESIGN TO analyst;
GRANT SELECT ON smart.SURVEY_DESIGN TO data_entry;
GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN TO manager;

GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO analyst;
GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO data_entry;
GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE_LIST TO manager;

GRANT SELECT ON smart.MISSION_ATTRIBUTE TO analyst;
GRANT SELECT ON smart.MISSION_ATTRIBUTE TO data_entry;
GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE TO manager;

GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO analyst;
GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO data_entry;
GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE TO manager;

GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO analyst;
GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO data_entry;
GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO manager;

GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO analyst;
GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO data_entry;
GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO manager;