output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/icons/,\
               images/nl/,\
               plugin_customization.ini,\
               properties/smart.properties,\
               splash.bmp,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml,\
               lib/commons-compress-1.4.1.jar,\
               lib/opencsv-2.3.jar,\
               lib/gson-2.2.2.jar
source.. = src/
src.includes = properties/smart.properties,\
               splash.bmp,\
               images/icons/,\
               images/nl/,\
               lib/commons-collections-3.1.jar,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml,\
               lib/gson-2.2.2.jar,\
               lib/opencsv-2.3.jar
src.excludes = images/icons/elcl16/Thumbs.db,\
               images/icons/etool16/Thumbs.db,\
               images/icons/obj16/Thumbs.db
bin.excludes = images/icons/elcl16/Thumbs.db,\
               images/icons/etool16/Thumbs.db,\
               images/icons/obj16/Thumbs.db
