output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               splash.bmp,\
               properties/log4j.properties,\
               lib/commons-compress-1.4.1.jar,\
               lib/gson-2.2.2.jar,\
               plugin.properties,\
               about.mappings,\
               lib/opencsv-2.3.jar,\
               images/,\
               properties/datamodel.xml,\
               plugin_fr.properties,\
               configuration/config.ini,\
               smart_customization.ini
source.. = src/
src.includes = splash.bmp,\
               images/icons/,\
               images/nl/,\
               lib/commons-collections-3.1.jar,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml,\
               lib/gson-2.2.2.jar,\
               lib/opencsv-2.3.jar
