output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/icons/,\
               images/nl/,\
               plugin_customization.ini,\
               properties/smart.properties,\
               splash.bmp,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml,\
               lib/commons-compress-1.4.1.jar
source.. = src/
src.includes = properties/smart.properties,\
               splash.bmp,\
               images/icons/,\
               images/nl/,\
               lib/slf4j-api-1.6.1.jar,\
               lib/log4j-1.2.16.jar,\
               lib/slf4j-log4j12-1.6.4.jar,\
               lib/jta-1.1.jar,\
               lib/javassist-3.15.0-GA.jar,\
               lib/hibernate-jpa-2.0-api-1.0.1.Final.jar,\
               lib/hibernate-core-3.6.8.Final.jar,\
               lib/hibernate-commons-annotations-3.2.0.Final.jar,\
               lib/dom4j-1.6.1.jar,\
               lib/derby-10.8.2.2.jar,\
               lib/commons-collections-3.1.jar,\
               lib/antlr-2.7.6.jar,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml
