aboutText=Spatial Monitoring and Reporting Tool.\n \nVersion\: {0} \n \nCopyright (C) 2012 Wildlife Conservation Society\n\nSMART has been developed through the SMART Partnership.  At the time of release this \nincludes Frankfurt Zoological Society, North Carolina Zoological Park, Wildlife \nConservation Society, World Wildlife Fund, Zoological Society of London, and \nCITES-Monitoring Illegal Killing of Elephants (MIKE) program. \n\nSMART has been developed and released in accordance with the Conservation Commons\nprinciples of open access, mutual benefit, and rights and responsibilities. SMART is open source,\nnon-proprietary and free to obtain. For more information, visit\:\nhttp\://www.smartconservationsoftware.org\n 


mapview.name = SMART Map View
defaultperspective.name = SMART
file.menu.label = File
file.menu.mnemonic = F
exportca.command.label = Export Conservation Area ...
exportca.command.mnemonic = a
exportca.command.tooltip = Exports all data associated with the current conservation area
exportca.command.name = Export Conservation Area ...
backup.command.label = Backup System
backup.command.mnemonic = B
backup.command.tooltip = Backup the smart database and files.
backup.command.name = Backup System
configurebackup.command.label = Configure Automatic Backup...
configurebackup.command.mnemonic = Au
configurebackup.command.tooltip = Configure the automatic backup options.
configurebackup.command.name = Configure Automatic Backup
changeuserpass.command.label = Change Password ...
changeuserpass.command.mnemonic = P
changeuserpass.command.tooltip = Change your username or password
changeuserpass.command.name = Change Username or Password
exportmap.command.label = Export Map
exportmap.command.tooltip = exports the current map
exportmap.command.name = Export Map
logout.command.label = Logout
logoutcommand.mnemonic = L
logout.command.tooltip = logout of the application
logout.command.name = Logout
exit.command.label = Exit
exit.command.mnemonic = x
exit.command.tooltip = exit the application
exit.command.name = Exit
ca.menu.label = Conservation Area
ca.menu.mnemonic = C
caprop.command.label = Conservation Area Properties ...
caprop.command.mnemonic = C
caprop.command.name = Show Conservation Area Properties Page
agencyrank.command.label = Agency and Rank List ...
agencyrank.command.mnemonic = A
agencyrank.command.name = Show Agency and Rank Lists
employeelist.command.label = Employee List ...
employeelist.command.mnemonic = E
employeelist.command.name = Show Employee List
stationlist.command.label = Station List ...
stationlist.command.mnemonic = S
stationlist.command.name = Show Station List
manageprojections.command.label = Manage Projections ...
manageprojections.command.mnemonic = P
manageprojections.command.tooltip = Add, Remove, Modify projections available to users
manageprojections.command.name = Manage Projections ....
boundaries.command.label = Define Area Boundaries ...
boundaries.command.mnemonic = B
boundaries.command.name = Show Area Boundaries
basemaps.command.label = Manage Basemaps ...
basemaps.command.mnemonic = m
basemaps.command.name = Show Basemap List
datamodel.command.label = Data Model ...
datamodel.command.mnemonic = D
datamodel.command.name = Show Data Model
deleteca.command.label = Delete Conservation Area
deleteca.command.mnemonic = t
deleteca.command.tooltip = delete the conservation area from the database
deleteca.command.name = Delete Conservation Area
help.menu.label = Help
help.menu.mnemonic = H
about.command.label = About Smart
about.command.mnemonic = A
showmapperspective.command.label = Show Map Perspective
showmapperspective.command.name = Show Map Perspective
showmapperspective.command.tooltip = shows the default map perspective
resetwindows.command.label = Reset Windows
resetwindows.command.tooltip = reset the window layout to the default
resetwindows.command.name = Reset Perspective
selectbasemap.command.label = Set Basemap
selectbasemap.command.tooltip = Select the basemap to use on the map
selectbasemap.command.name = Set Basemap
pan.command.label = Pan
pan.command.name = Pan Map
pan.command.tooltip = pan the map
zoom.command.label = Zoom 
zoom.command.tooltip = zoom to various locations on map
zoom.command.name = Zoom Tool
zoomout.command.label = Zoom Out
zoomout.command.tooltip = zooms the map out
zoomout.command.name = Zoom Out
zoomin.command.label = Zoom In
zoomin.command.tooltip = zooms the map in
zoomin.command.name = Zoom In
zoomextents.command.label = Zoom to map extents
zoomextents.command.tooltip = Zoom to full extents of all layers
zoomextents.command.name = Zoom Extents Tool
addlayer.command.label = Add Layer 
addlayer.command.tooltip = Add a layer to the map
addlayer.command.name = Add Layer

maptools.category.name = Map Tools
savebasemap.command.name = Save as Basemap

addsmartlayer.wizardPage.description = Wizard for loading smart area datasets
addsmartlayer.wizardPage.name = Smart Area Connection Page
smartinfo.about.page.name = Smart Info
udig.service.name = Smart Service
systempref.command.label = System Preferences
systempref.command.mnemonic = P
systempref.command.tooltip = Opens system preferences page
systempref.command.name = System Preferences
gpsbabel.preferencepage.name = GPS Babel Configuration