//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.14 at 01:17:11 PM PDT 
//

@XmlSchema(namespace = "http://www.smartconservationsoftware.org/xml/1.0/plan", elementFormDefault = XmlNsForm.QUALIFIED)
package org.wcs.smart.plan.xml.model;

import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
