source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/
src.includes = images/,\
               plugin.xml,\
               META-INF/
src.excludes = META-INF/.svn/,\
               images/icons/.svn/,\
               images/icons/etool16/.svn/
bin.excludes = images/icons/.svn/,\
               images/icons/etool16/.svn/,\
               META-INF/.svn/
