/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.asset.plugin;

import org.wcs.smart.asset.AssetPlugIn;
import org.wcs.smart.changetracking.AbstractChangeTrackerInstaller;

/**
 * Installs triggers for change tracking the plan plugin.
 * 
 * @author Emily
 *
 */
public class ChangeTrackerInstaller extends AbstractChangeTrackerInstaller {
	
	@SuppressWarnings("nls")
	private String[][] triggers = new String[][]{
		{"smart.trg_asset_insert", "CREATE TRIGGER smart.trg_asset_insert AFTER INSERT ON smart.asset REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_update", "CREATE TRIGGER smart.trg_asset_update AFTER UPDATE ON smart.asset REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_delete", "CREATE TRIGGER smart.trg_asset_delete AFTER DELETE ON smart.asset REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset', 'uuid', old.uuid, old.ca_uuid)"},
		
		{"smart.trg_asset_attribute_insert", "CREATE TRIGGER smart.trg_asset_attribute_insert AFTER INSERT ON smart.asset_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_attribute_update", "CREATE TRIGGER smart.trg_asset_attribute_update AFTER UPDATE ON smart.asset_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_attribute', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_attribute_delete", "CREATE TRIGGER smart.trg_asset_attribute_delete AFTER DELETE ON smart.asset_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_attribute', 'uuid', old.uuid, old.ca_uuid)"},
		
		{"smart.trg_asset_attribute_list_item_insert", "CREATE TRIGGER smart.trg_asset_attribute_list_item_insert AFTER INSERT ON smart.asset_attribute_list_item REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_attribute_list_item', 'uuid', new.uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_attribute_list_item_update", "CREATE TRIGGER smart.trg_asset_attribute_list_item_update AFTER update ON smart.asset_attribute_list_item REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_attribute_list_item', 'uuid', new.uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_attribute_list_item_delete", "CREATE TRIGGER smart.trg_asset_attribute_list_item_delete AFTER delete ON smart.asset_attribute_list_item REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_attribute_list_item', 'uuid', old.uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_attribute_value_insert", "CREATE TRIGGER smart.trg_asset_attribute_value_insert AFTER INSERT ON smart.asset_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_attribute_value', 'asset_uuid', new.asset_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_attribute_value_update", "CREATE TRIGGER smart.trg_asset_attribute_value_update AFTER update ON smart.asset_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_attribute_value', 'asset_uuid', new.asset_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_attribute_value_delete", "CREATE TRIGGER smart.trg_asset_attribute_value_delete AFTER delete ON smart.asset_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_attribute_value', 'asset_uuid', old.asset_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_deployment_insert", "CREATE TRIGGER smart.trg_asset_deployment_insert AFTER INSERT ON smart.asset_deployment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_deployment', 'uuid', new.uuid, i.ca_uuid from smart.asset i where i.uuid = new.asset_uuid"},
		{"smart.trg_asset_deployment_update", "CREATE TRIGGER smart.trg_asset_deployment_update AFTER update ON smart.asset_deployment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_deployment', 'uuid', new.uuid, i.ca_uuid from smart.asset i where i.uuid = new.asset_uuid"},
		{"smart.trg_asset_deployment_delete", "CREATE TRIGGER smart.trg_asset_deployment_delete AFTER delete ON smart.asset_deployment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_deployment', 'uuid', old.uuid, i.ca_uuid from smart.asset i where i.uuid = old.asset_uuid"},

		{"smart.trg_asset_deployment_attribute_value_insert", "CREATE TRIGGER smart.trg_asset_deployment_attribute_value_insert AFTER INSERT ON smart.asset_deployment_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_deployment_attribute_value', 'asset_deployment_uuid', new.asset_deployment_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_deployment_attribute_value_update", "CREATE TRIGGER smart.trg_asset_deployment_attribute_value_update AFTER update ON smart.asset_deployment_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_deployment_attribute_value', 'asset_deployment_uuid', new.asset_deployment_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_deployment_attribute_value_delete", "CREATE TRIGGER smart.trg_asset_deployment_attribute_value_delete AFTER delete ON smart.asset_deployment_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_deployment_attribute_value', 'asset_deployment_uuid', old.asset_deployment_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},

		{"smart.trg_asset_history_insert", "CREATE TRIGGER smart.trg_asset_history_insert AFTER INSERT ON smart.asset_history_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_history_record', 'uuid', new.uuid, i.ca_uuid from smart.asset i where i.uuid = new.asset_uuid"},
		{"smart.trg_asset_history_update", "CREATE TRIGGER smart.trg_asset_history_update AFTER update ON smart.asset_history_record REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_history_record', 'uuid', new.uuid, i.ca_uuid from smart.asset i where i.uuid = new.asset_uuid"},
		{"smart.trg_asset_history_delete", "CREATE TRIGGER smart.trg_asset_history_delete AFTER delete ON smart.asset_history_record REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_history_record', 'uuid', old.uuid, i.ca_uuid from smart.asset i where i.uuid = old.asset_uuid"},

		{"smart.trg_asset_module_settings_insert", "CREATE TRIGGER smart.trg_asset_module_settings_insert AFTER INSERT ON smart.asset_module_settings REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_module_settings', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_module_settings_update", "CREATE TRIGGER smart.trg_asset_module_settings_update AFTER UPDATE ON smart.asset_module_settings REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_module_settings', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_module_settings_delete", "CREATE TRIGGER smart.trg_asset_module_settings_delete AFTER DELETE ON smart.asset_module_settings REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_module_settings', 'uuid', old.uuid, old.ca_uuid)"},
				
		{"smart.trg_asset_station_insert", "CREATE TRIGGER smart.trg_asset_station_insert AFTER INSERT ON smart.asset_station REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_station_update", "CREATE TRIGGER smart.trg_asset_station_update AFTER UPDATE ON smart.asset_station REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_station_delete", "CREATE TRIGGER smart.trg_asset_station_delete AFTER DELETE ON smart.asset_station REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station', 'uuid', old.uuid, old.ca_uuid)"},
		
		{"smart.trg_asset_station_attribute_insert", "CREATE TRIGGER smart.trg_asset_station_attribute_insert AFTER INSERT ON smart.asset_station_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_attribute', 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_attribute_update", "CREATE TRIGGER smart.trg_asset_station_attribute_update AFTER update ON smart.asset_station_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_attribute', 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_attribute_delete", "CREATE TRIGGER smart.trg_asset_station_attribute_delete AFTER delete ON smart.asset_station_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_attribute', 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_station_attribute_value_insert", "CREATE TRIGGER smart.trg_asset_station_attribute_value_insert AFTER INSERT ON smart.asset_station_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_attribute_value', 'station_uuid', new.station_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_attribute_value_update", "CREATE TRIGGER smart.trg_asset_station_attribute_value_update AFTER update ON smart.asset_station_attribute_value REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_attribute_value', 'station_uuid', new.station_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_attribute_value_delete", "CREATE TRIGGER smart.trg_asset_station_attribute_value_delete AFTER delete ON smart.asset_station_attribute_value REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_attribute_value', 'station_uuid', old.station_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"}, 
		
		{"smart.trg_asset_type_insert", "CREATE TRIGGER smart.trg_asset_type_insert AFTER INSERT ON smart.asset_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_type_update", "CREATE TRIGGER smart.trg_asset_type_update AFTER UPDATE ON smart.asset_type REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_type', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_type_delete", "CREATE TRIGGER smart.trg_asset_type_delete AFTER DELETE ON smart.asset_type REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_type', 'uuid', old.uuid, old.ca_uuid)"},
		
		{"smart.trg_asset_map_style_insert", "CREATE TRIGGER smart.trg_asset_map_style_insert AFTER INSERT ON smart.asset_map_style REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_map_style', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_map_style_update", "CREATE TRIGGER smart.trg_asset_map_style_update AFTER UPDATE ON smart.asset_map_style REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_map_style', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_map_style_delete", "CREATE TRIGGER smart.trg_asset_map_style_delete AFTER DELETE ON smart.asset_map_style REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_map_style', 'uuid', old.uuid, old.ca_uuid)"},
		
		{"smart.trg_asset_metadata_mapping_insert", "CREATE TRIGGER smart.trg_asset_metadata_mapping_insert AFTER INSERT ON smart.asset_metadata_mapping REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_metadata_mapping', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_metadata_mapping_update", "CREATE TRIGGER smart.trg_asset_metadata_mapping_update AFTER UPDATE ON smart.asset_metadata_mapping REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(new.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_metadata_mapping', 'uuid', new.uuid, new.ca_uuid)"},
		{"smart.trg_asset_metadata_mapping_delete", "CREATE TRIGGER smart.trg_asset_metadata_mapping_delete AFTER DELETE ON smart.asset_metadata_mapping REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) values (smart.next_revision_id(old.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_metadata_mapping', 'uuid', old.uuid, old.ca_uuid)"},

		{"smart.trg_asset_type_attribute_insert", "CREATE TRIGGER smart.trg_asset_type_attribute_insert AFTER INSERT ON smart.asset_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_type_attribute', 'asset_type_uuid', new.asset_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_type_attribute_update", "CREATE TRIGGER smart.trg_asset_type_attribute_update AFTER update ON smart.asset_type_attribute REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_type_attribute', 'asset_type_uuid', new.asset_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_type_attribute_delete", "CREATE TRIGGER smart.trg_asset_type_attribute_delete AFTER delete ON smart.asset_type_attribute REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_type_attribute', 'asset_type_uuid', old.asset_type_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_type_deployment_attribute_insert", "CREATE TRIGGER smart.trg_asset_type_deployment_attribute_insert AFTER INSERT ON smart.asset_type_deployment_attribute  REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_type_deployment_attribute', 'asset_type_uuid', new.asset_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_type_deployment_attribute_update", "CREATE TRIGGER smart.trg_asset_type_deployment_attribute_update AFTER update ON smart.asset_type_deployment_attribute  REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_type_deployment_attribute', 'asset_type_uuid', new.asset_type_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_type_deployment_attribute_delete", "CREATE TRIGGER smart.trg_asset_type_deployment_attribute_delete AFTER delete ON smart.asset_type_deployment_attribute  REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_type_deployment_attribute', 'asset_type_uuid', old.asset_type_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_station_location_attribute_insert", "CREATE TRIGGER smart.trg_asset_station_location_attribute_insert AFTER INSERT ON smart.asset_station_location_attribute   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_location_attribute', 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_location_attribute_update", "CREATE TRIGGER smart.trg_asset_station_location_attribute_update AFTER update ON smart.asset_station_location_attribute   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_location_attribute', 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_location_attribute_delete", "CREATE TRIGGER smart.trg_asset_station_location_attribute_delete AFTER delete ON smart.asset_station_location_attribute   REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_location_attribute', 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
		
		{"smart.trg_asset_station_location_attribute_value_insert", "CREATE TRIGGER smart.trg_asset_station_location_attribute_value_insert AFTER INSERT ON smart.asset_station_location_attribute_value   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_location_attribute_value', 'station_location_uuid', new.station_location_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_location_attribute_value_update", "CREATE TRIGGER smart.trg_asset_station_location_attribute_value_update AFTER update ON smart.asset_station_location_attribute_value   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_location_attribute_value', 'station_location_uuid', new.station_location_uuid, 'attribute_uuid', new.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = new.attribute_uuid"},
		{"smart.trg_asset_station_location_attribute_value_delete", "CREATE TRIGGER smart.trg_asset_station_location_attribute_value_delete AFTER delete ON smart.asset_station_location_attribute_value   REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_location_attribute_value', 'station_location_uuid', old.station_location_uuid, 'attribute_uuid', old.attribute_uuid, i.ca_uuid from smart.asset_attribute i where i.uuid = old.attribute_uuid"},
				
		{"smart.trg_asset_station_location_insert", "CREATE TRIGGER smart.trg_asset_station_location_insert AFTER INSERT ON smart.asset_station_location   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_location', 'uuid', new.uuid, i.ca_uuid from smart.asset_station i where i.uuid = new.station_uuid"},
		{"smart.trg_asset_station_location_update", "CREATE TRIGGER smart.trg_asset_station_location_update AFTER update ON smart.asset_station_location   REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_location', 'uuid', new.uuid, i.ca_uuid from smart.asset_station i where i.uuid = new.station_uuid"},
		{"smart.trg_asset_station_location_delete", "CREATE TRIGGER smart.trg_asset_station_location_delete AFTER delete ON smart.asset_station_location   REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_location', 'uuid', old.uuid, i.ca_uuid from smart.asset_station i where i.uuid = old.station_uuid"},
		
		{"smart.trg_asset_waypoint_insert", "CREATE TRIGGER smart.trg_asset_waypoint_insert AFTER INSERT ON smart.asset_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_waypoint', 'uuid', new.uuid, i.ca_uuid from smart.waypoint i where i.uuid = new.wp_uuid"},
		{"smart.trg_asset_waypoint_update", "CREATE TRIGGER smart.trg_asset_waypoint_update AFTER update ON smart.asset_waypoint REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_waypoint', 'uuid', new.uuid, i.ca_uuid from smart.waypoint i where i.uuid = new.wp_uuid"},
		{"smart.trg_asset_waypoint_delete", "CREATE TRIGGER smart.trg_asset_waypoint_delete AFTER delete ON smart.asset_waypoint REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(i.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_waypoint', 'uuid', old.uuid, i.ca_uuid from smart.waypoint i where i.uuid = old.wp_uuid"},

		{"smart.trg_asset_waypoint_attachment_insert", "CREATE TRIGGER smart.trg_asset_waypoint_attachment_insert AFTER INSERT ON smart.asset_waypoint_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_waypoint_attachment', 'wp_attachment_uuid', new.wp_attachment_uuid, 'asset_waypoint_uuid', new.asset_waypoint_uuid, w.ca_uuid from smart.asset_waypoint a, smart.waypoint w where a.wp_uuid = w.uuid and a.uuid = new.asset_waypoint_uuid"},
		{"smart.trg_asset_waypoint_attachment_update", "CREATE TRIGGER smart.trg_asset_waypoint_attachment_update AFTER update ON smart.asset_waypoint_attachment REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_waypoint_attachment', 'wp_attachment_uuid', new.wp_attachment_uuid, 'asset_waypoint_uuid', new.asset_waypoint_uuid, w.ca_uuid from smart.asset_waypoint a, smart.waypoint w where a.wp_uuid = w.uuid and a.uuid = new.asset_waypoint_uuid"},
		{"smart.trg_asset_waypoint_attachment_delete", "CREATE TRIGGER smart.trg_asset_waypoint_attachment_delete AFTER delete ON smart.asset_waypoint_attachment REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, key2_fieldname, key2_uuid, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_waypoint_attachment', 'wp_attachment_uuid', old.wp_attachment_uuid, 'asset_waypoint_uuid', old.asset_waypoint_uuid, w.ca_uuid from smart.asset_waypoint a, smart.waypoint w where a.wp_uuid = w.uuid and a.uuid = old.asset_waypoint_uuid"},
		
		{"smart.trg_asset_station_location_history_insert", "CREATE TRIGGER smart.trg_asset_station_location_history_insert AFTER INSERT ON smart.asset_station_location_history REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'INSERT', 'smart.asset_station_location_history', 'uuid', new.uuid, w.ca_uuid from smart.asset_station_location a, smart.asset_station w where a.station_uuid = w.uuid and a.uuid = new.station_location_uuid"},
		{"smart.trg_asset_station_location_history_update", "CREATE TRIGGER smart.trg_asset_station_location_history_update AFTER update ON smart.asset_station_location_history REFERENCING NEW AS new FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'UPDATE', 'smart.asset_station_location_history', 'uuid', new.uuid, w.ca_uuid from smart.asset_station_location a, smart.asset_station w where a.station_uuid = w.uuid and a.uuid = new.station_location_uuid"},
		{"smart.trg_asset_station_location_history_delete", "CREATE TRIGGER smart.trg_asset_station_location_history_delete AFTER delete ON smart.asset_station_location_history REFERENCING OLD AS old FOR EACH ROW WHEN (syscs_util.syscs_get_database_property( 'org.wcs.smart.isLogging' ) = true) INSERT INTO smart.connect_change_log (revision, uuid, action, tablename, key1_fieldname, key1, ca_uuid) select smart.next_revision_id(w.ca_uuid), smart.uuid(), 'DELETE', 'smart.asset_station_location_history', 'uuid', old.uuid, w.ca_uuid from smart.asset_station_location a, smart.asset_station w where a.station_uuid = w.uuid and a.uuid = old.station_location_uuid"},
		
	};
	
	@Override
	public String[][] getCurrentTriggers() {
		return triggers;
	}

	@Override
	public String[] getAllTriggersToDrop(){
		String[] t = new String[triggers.length];
		for (int i = 0; i < triggers.length; i ++){
			t[i] = triggers[i][0];
		}
		return t;
	}
	
	
	@Override
	public String getPluginId() {
		return AssetPlugIn.PLUGIN_ID;
	}

	@Override
	public String getLastestVersion() {
		return AssetPlugIn.DB_VERSION;
	}
}

