source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               OSGI-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/l10n/bundle.properties,\
               lib/azure-storage-blob-11.0.1.jar,\
               lib/client-runtime-2.1.1.jar,\
               lib/jackson-annotations-2.9.0.jar,\
               lib/jackson-core-2.9.6.jar,\
               lib/jackson-databind-2.9.6.jar,\
               lib/jackson-dataformat-xml-2.9.6.jar,\
               lib/jackson-datatype-jsr310-2.9.6.jar,\
               lib/jackson-module-jaxb-annotations-2.9.6.jar,\
               lib/netty-buffer-4.1.28.Final.jar,\
               lib/netty-codec-4.1.28.Final.jar,\
               lib/netty-codec-http-4.1.28.Final.jar,\
               lib/netty-codec-socks-4.1.28.Final.jar,\
               lib/netty-common-4.1.28.Final.jar,\
               lib/netty-handler-4.1.28.Final.jar,\
               lib/netty-handler-proxy-4.1.28.Final.jar,\
               lib/netty-resolver-4.1.28.Final.jar,\
               lib/netty-transport-4.1.28.Final.jar,\
               lib/reactive-streams-1.0.2.jar,\
               lib/rxjava-2.2.0.jar,\
               lib/slf4j-api-1.7.22.jar,\
               lib/stax2-api-3.1.4.jar,\
               lib/woodstox-core-5.0.3.jar
