source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               net.refractions.udig.project.ui.xslt,\
               transform.csv,\
               net.refractions.udig.catalog.ui.xslt,\
               eu.udig.style.advanced.xslt
