
#This represents the location of the
#embedded database file
#Used for backups etc.
db.dbname=./data/database/smartdb

backup.directory=./data/backup

filestore=./data/filestore/

gpsbabel=./GPSBabel/gpsbabel.exe