
DROP TABLE SMART.ENTITY_ATTRIBUTE_VALUE;
DROP TABLE SMART.ENTITY;
DROP TABLE SMART.ENTITY_ATTRIBUTE;
DROP TABLE SMART.ENTITY_TYPE;



/* Create Tables */
CREATE TABLE SMART.ENTITY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	ENTITY_TYPE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ID VARCHAR(32) NOT NULL,
	STATUS VARCHAR(16) NOT NULL,
	ATTRIBUTE_LIST_ITEM_UUID CHAR(16) FOR BIT DATA NOT NULL,
	X DOUBLE,
	Y DOUBLE,
	PRIMARY KEY (UUID)
);


CREATE TABLE SMART.ENTITY_ATTRIBUTE
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	ENTITY_TYPE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	DM_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	IS_REQUIRED BOOLEAN DEFAULT false NOT NULL,
	ATTRIBUTE_ORDER INTEGER NOT NULL,
	IS_PRIMARY BOOLEAN DEFAULT true NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE SMART.ENTITY_ATTRIBUTE_VALUE
(
	ENTITY_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ENTITY_UUID CHAR(16) FOR BIT DATA NOT NULL,
	NUMBER_VALUE DOUBLE,
	STRING_VALUE VARCHAR(1024),
	LIST_ELEMENT_UUID CHAR(16) FOR BIT DATA,
	TREE_NODE_UUID CHAR(16) FOR BIT DATA ,
	PRIMARY KEY (ENTITY_ATTRIBUTE_UUID, ENTITY_UUID)
);


CREATE TABLE SMART.ENTITY_TYPE
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	ID VARCHAR(32) NOT NULL,
	DATE_CREATED TIMESTAMP NOT NULL,
	CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,
	STATUS VARCHAR(16) NOT NULL,
	DM_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,
	ENTITY_TYPE VARCHAR(16),
	PRIMARY KEY (UUID)
);



/* Create Foreign Keys */

ALTER TABLE SMART.ENTITY_TYPE ADD CONSTRAINT entity_type_ca_uuid_fk FOREIGN KEY (CA_UUID)
	REFERENCES SMART.CONSERVATION_AREA(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE SMART.ENTITY_ATTRIBUTE ADD CONSTRAINT entity_attribute_dm_attribute_fk FOREIGN KEY (DM_ATTRIBUTE_UUID)
	REFERENCES SMART.DM_ATTRIBUTE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE SMART.ENTITY_TYPE ADD CONSTRAINT entity_type_dm_attribute_fk FOREIGN KEY (DM_ATTRIBUTE_UUID)
	REFERENCES SMART.DM_ATTRIBUTE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
	
ALTER TABLE SMART.ENTITY_ATTRIBUTE_VALUE ADD CONSTRAINT entity_attribute_value_entity_fk FOREIGN KEY (ENTITY_UUID)
	REFERENCES SMART.ENTITY(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;	

ALTER TABLE SMART.ENTITY_ATTRIBUTE_VALUE ADD CONSTRAINT entity_attribute_value_attribute_fk FOREIGN KEY (ENTITY_ATTRIBUTE_UUID)
	REFERENCES SMART.ENTITY_ATTRIBUTE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
	
ALTER TABLE SMART.ENTITY_ATTRIBUTE_VALUE ADD CONSTRAINT entity_attribute_value_listelement_fk FOREIGN KEY (LIST_ELEMENT_UUID)
	REFERENCES SMART.DM_ATTRIBUTE_LIST(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE SMART.ENTITY_ATTRIBUTE_VALUE ADD CONSTRAINT entity_attribute_value_treenode_fk FOREIGN KEY (TREE_NODE_UUID)
	REFERENCES SMART.DM_ATTRIBUTE_TREE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
	
ALTER TABLE SMART.ENTITY ADD CONSTRAINT entity_type_uuid_fk FOREIGN KEY (ENTITY_TYPE_UUID)
	REFERENCES SMART.ENTITY_TYPE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE SMART.ENTITY ADD CONSTRAINT entity_attribute_list_item_uuid_fk FOREIGN KEY (ATTRIBUTE_LIST_ITEM_UUID)
	REFERENCES SMART.DM_ATTRIBUTE_LIST(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE SMART.ENTITY_ATTRIBUTE ADD CONSTRAINT entity_attribute_type_uuid_fk FOREIGN KEY (ENTITY_TYPE_UUID)
	REFERENCES SMART.ENTITY_TYPE(UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
	
	
--manager
GRANT SELECT ON SMART.ENTITY_TYPE to manager;
GRANT SELECT ON SMART.ENTITY_ATTRIBUTE TO manager;
GRANT ALL PRIVILEGES ON SMART.ENTITY_ATTRIBUTE_VALUE to manager;
GRANT ALL PRIVILEGES ON SMART.ENTITY TO manager;

-- to modify entities we need to be able to modify the entity list
GRANT INSERT ON SMART.DM_ATTRIBUTE_LIST to manager;
GRANT DELETE ON SMART.DM_ATTRIBUTE_LIST to manager;
GRANT UPDATE ON SMART.DM_ATTRIBUTE_LIST to manager;
GRANT INSERT ON SMART.CM_ATTRIBUTE_LIST to manager;
GRANT DELETE ON SMART.CM_ATTRIBUTE_LIST to manager;

--analyst
GRANT SELECT ON SMART.ENTITY_TYPE to analyst;
GRANT SELECT ON SMART.ENTITY_ATTRIBUTE TO analyst;
GRANT SELECT ON SMART.ENTITY_ATTRIBUTE_VALUE to analyst;
GRANT SELECT ON SMART.ENTITY TO analyst;

--data entry
GRANT SELECT ON SMART.ENTITY_TYPE to data_entry;
GRANT SELECT ON SMART.ENTITY_ATTRIBUTE TO data_entry;
GRANT ALL PRIVILEGES ON SMART.ENTITY_ATTRIBUTE_VALUE to data_entry;
GRANT ALL PRIVILEGES ON SMART.ENTITY TO data_entry;

-- to modify entities we need to be able to modify the entity list
GRANT INSERT ON SMART.DM_ATTRIBUTE_LIST to data_entry;
GRANT DELETE ON SMART.DM_ATTRIBUTE_LIST to data_entry;
GRANT UPDATE ON SMART.DM_ATTRIBUTE_LIST to data_entry;
GRANT INSERT ON SMART.CM_ATTRIBUTE_LIST to data_entry;
GRANT DELETE ON SMART.CM_ATTRIBUTE_LIST to data_entry;