//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.15 at 10:16:12 AM PDT 
//


package org.wcs.smart.asset.data.inout.deployment.xml.v10;

import java.util.ArrayList;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for XmlAssetDeployment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlAssetDeployment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributes" type="{http://www.smartconservationsoftware.org/xml/1.0/assetdeployment}XmlAssetDeploymentAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="disruptions" type="{http://www.smartconservationsoftware.org/xml/1.0/assetdeployment}XmlAssetDeploymentDisruption" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="waypoints" type="{http://www.smartconservationsoftware.org/xml/1.0/assetdeployment}XmlWaypoint" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="assetKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="assetTypeKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="locationId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stationId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlAssetDeployment", propOrder = {
    "attributes",
    "disruptions",
    "waypoints"
})
public class XmlAssetDeployment {

    protected List<XmlAssetDeploymentAttribute> attributes;
    protected List<XmlAssetDeploymentDisruption> disruptions;
    protected List<XmlWaypoint> waypoints;
    @XmlAttribute(name = "assetKey")
    protected String assetKey;
    @XmlAttribute(name = "assetTypeKey")
    protected String assetTypeKey;
    @XmlAttribute(name = "startDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateTime;
    @XmlAttribute(name = "endDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateTime;
    @XmlAttribute(name = "locationId")
    protected String locationId;
    @XmlAttribute(name = "stationId")
    protected String stationId;

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlAssetDeploymentAttribute }
     * 
     * 
     */
    public List<XmlAssetDeploymentAttribute> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<XmlAssetDeploymentAttribute>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the disruptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disruptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisruptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlAssetDeploymentDisruption }
     * 
     * 
     */
    public List<XmlAssetDeploymentDisruption> getDisruptions() {
        if (disruptions == null) {
            disruptions = new ArrayList<XmlAssetDeploymentDisruption>();
        }
        return this.disruptions;
    }

    /**
     * Gets the value of the waypoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waypoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaypoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlWaypoint }
     * 
     * 
     */
    public List<XmlWaypoint> getWaypoints() {
        if (waypoints == null) {
            waypoints = new ArrayList<XmlWaypoint>();
        }
        return this.waypoints;
    }

    /**
     * Gets the value of the assetKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetKey() {
        return assetKey;
    }

    /**
     * Sets the value of the assetKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetKey(String value) {
        this.assetKey = value;
    }

    /**
     * Gets the value of the assetTypeKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetTypeKey() {
        return assetTypeKey;
    }

    /**
     * Sets the value of the assetTypeKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetTypeKey(String value) {
        this.assetTypeKey = value;
    }

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateTime(XMLGregorianCalendar value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateTime(XMLGregorianCalendar value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the locationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the stationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationId(String value) {
        this.stationId = value;
    }

}
