/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.upgrade;

import java.util.Map;

import org.eclipse.core.runtime.IProgressMonitor;
import org.hibernate.Session;
import org.wcs.smart.er.EcologicalRecordsPlugIn;
import org.wcs.smart.er.internal.Messages;
import org.wcs.smart.er.updatesite.AddERJob;
import org.wcs.smart.hibernate.HibernateManager;
import org.wcs.smart.upgrade.IDatabaseUpgrader;
import org.wcs.smart.upgrade.UpgradeEngine;

/**
 * Ecological Records upgrade operations while upgrade/restore backup.
 * 
 * @author elitvin
 * @since 1.0.0
 */
public class ERDatabaseUpgrader implements IDatabaseUpgrader {

	@Override
	public void upgrade(IProgressMonitor monitor) throws Exception {
		monitor.beginTask(Messages.ERDatabaseUpgrader_UpgradeTask, 1);
		Session session = HibernateManager.openSession();
		try{
			session.beginTransaction();
			Map<String, String> versions = UpgradeEngine.getVersions(session);
			if (versions == null) throw new IllegalStateException("Database versions not found."); //shouldn't happy //$NON-NLS-1$
			String currentPluginVersion = versions.get(EcologicalRecordsPlugIn.PLUGIN_ID);
			
			if (currentPluginVersion == null) {
				(new AddERJob()).installPlugin(session);
			}else{
				upgrade(currentPluginVersion, session);
			}
			session.getTransaction().commit();
		}catch (Exception ex){
			session.getTransaction().rollback();
			throw ex;
		}
		monitor.done();
	}
	
	/**
	 * Upgrades from the currentVersion to the most recent version.
	 * @param currentVersion
	 * @param session in active transaction
	 */
	public static final void upgrade(String currentVersion, Session session){
		if (currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION_1)){
			upgradeV1ToV2(session);
		}
	}
	
	private static void upgradeV1ToV2(Session session){
		@SuppressWarnings("nls")
		String[] sql = new String[]{
				"alter table smart.MISSION_ATTRIBUTE add constraint mission_attribute_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
				"alter table smart.MISSION_ATTRIBUTE_LIST add constraint mission_attribute_list_keyid_unq unique(mission_attribute_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
				"alter table smart.SAMPLING_UNIT_ATTRIBUTE add constraint su_attribute_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
				"alter table smart.SAMPLING_UNIT_ATTRIBUTE_LIST add constraint su_list_attribute_keyid_unq unique(sampling_unit_attribute_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
				"alter table smart.SURVEY_DESIGN add constraint survey_design_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
				
				"ALTER TABLE SMART.SURVEY_DESIGN DROP CONSTRAINT CONFIGURABLE_MODEL_UUID_FK",
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST DROP CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK",
				"ALTER TABLE SMART.MISSION_DAY DROP CONSTRAINT MISSION_DAY_MISSION_UUID_FK",
				"ALTER TABLE SMART.MISSION_MEMBER DROP CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK",
				"ALTER TABLE SMART.MISSION_PROPERTY DROP CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK",
				"ALTER TABLE SMART.MISSION_PROPERTY DROP CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID",
				"ALTER TABLE SMART.MISSION DROP CONSTRAINT MISSION_SURVEY_UUID",
				"ALTER TABLE SMART.MISSION_TRACK DROP CONSTRAINT MISSION_TRACK",
				"ALTER TABLE SMART.MISSION_TRACK DROP CONSTRAINT MISSION_TRACK_MISSIONDAY_UUID",
				"ALTER TABLE SMART.SAMPLING_UNIT DROP CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID",
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT DROP CONSTRAINT SD_SU_SURVEY_DESIGN_UUID",
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT DROP CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID",
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY DROP CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID",
				"ALTER TABLE SMART.SURVEY DROP CONSTRAINT SURVEY_SURVEY_DSG_UUID",
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_MISSIONDAY_UUID",
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_MISSION_TRK_UUID",
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE DROP CONSTRAINT SU_ATTRIBUTE_CA_UUID",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST DROP CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_ATTRIBUTE_UUID",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_LIST_ELEMENT_UUID",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_UUID",

				"ALTER TABLE SMART.MISSION ADD CONSTRAINT MISSION_SURVEY_UUID FOREIGN KEY (SURVEY_UUID) REFERENCES SMART.SURVEY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST ADD CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_DAY ADD CONSTRAINT MISSION_DAY_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_MEMBER ADD CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.MISSION_ATTRIBUTE_LIST(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE ADD CONSTRAINT SU_ATTRIBUTE_CA_UUID FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST ADD CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (SAMPLING_UNIT_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_UUID FOREIGN KEY (SU_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_LIST_ELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY ADD CONSTRAINT SURVEY_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT CONFIGURABLE_MODEL_UUID_FK FOREIGN KEY (CONFIGURABLE_MODEL_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY ADD CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SURVEY_DESIGN_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_TRK_UUID FOREIGN KEY (MISSION_TRACK_UUID) REFERENCES SMART.MISSION_TRACK(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				
				"ALTER TABLE SMART.MISSION_ATTRIBUTE ADD CONSTRAINT MISSION_ATT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID) ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT SD_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID) ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				
				"GRANT ALL PRIVILEGES ON smart.survey to analyst",
				"GRANT ALL PRIVILEGES ON smart.mission to analyst",
				"GRANT ALL PRIVILEGES ON smart.survey_waypoint to analyst",
				"GRANT ALL PRIVILEGES ON smart.mission_track to analyst",
				"GRANT ALL PRIVILEGES ON smart.mission_member to analyst",
				"GRANT ALL PRIVILEGES ON smart.mission_day to analyst",
				"GRANT ALL PRIVILEGES ON smart.mission_property_value to analyst",
		};
		
		for (String s : sql){
			session.createSQLQuery(s).executeUpdate();
		}
		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_2, session);
	}
}
