/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.ca.datamodel;

import java.text.Collator;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.eclipse.core.runtime.IProgressMonitor;
import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Language;
import org.wcs.smart.ca.NamedItem;
import org.wcs.smart.ca.datamodel.Attribute.AttributeType;
import org.wcs.smart.hibernate.SmartDB;
import org.wcs.smart.internal.Messages;

/**
 * Merges a source data model with a target data model updating
 * and adding values from the target data model that match the source
 * data model.  NOTHING is removed from the source data model.  If it
 * does not exist in the target data model, it remains in the source 
 * data model unchanged.
 * 
 * @author Emily
 *
 */
public class DataModelMergeAndUpdater {

	private DataModel sourceDm;
	private DataModel targetDm;
	
	private ConservationArea sourceConservationArea;
	
	private List<String> warnings;
	
	public DataModelMergeAndUpdater(DataModel source, DataModel target, ConservationArea sourceCa){
		this.sourceDm = source;
		this.targetDm = target;
		this.sourceConservationArea = sourceCa;
	}
	
	/**
	 * Merges the source and target datamodel updating the
	 * source data model as required.
	 * 
	 * @return list of warnings generated by the process
	 */
	public List<String> merge(IProgressMonitor monitor){
		warnings = new ArrayList<String>();
		monitor.beginTask(Messages.DataModelMergeAndUpdater_TaskName, targetDm.getAttributes().size() + targetDm.getCategories().size() +1);
		
		mergeAttributes(monitor);
	
		monitor.subTask(Messages.DataModelMergeAndUpdater_CategoriesTask);
		for (Category targetCategory : targetDm.getCategories()){
			boolean found = false;
			for (Category sourceCategory : sourceDm.getCategories()){
				if (sourceCategory.getKeyId().equals(targetCategory.getKeyId())){
					found = true;
					mergeCategory(sourceCategory, targetCategory);
					break;
				}
			}
			if (!found){
				//new category
				Category newSource = createNewCategory(targetCategory);
				sourceDm.getCategories().add(newSource);
				mergeCategory(newSource, targetCategory);
			}
			monitor.worked(1);
		}
		resortCategories(sourceDm.getCategories());
		monitor.done();
		return warnings;
	}
	
	
	private void mergeCategory(Category source, Category target){
		if (!source.getKeyId().equals(target.getKeyId())) return;
		if (!source.getHkey().equals(target.getHkey())) return;
		
		source.setIsActive(target.getIsActive());
		source.setIsMultiple(target.getIsMultiple());
		source.setCategoryOrder(target.getCategoryOrder());
		mergeNames(source, target);
		
		if (target.getAttributes() != null){
			for (CategoryAttribute targetAttribute : target.getAttributes()){
				boolean found = false;
				for (CategoryAttribute sourceAttribute : source.getAttributes()){
					if (targetAttribute.getAttribute().getKeyId().equals(sourceAttribute.getAttribute().getKeyId())){
						mergeCategoryAttribute(sourceAttribute, targetAttribute);
						found = true;
						break;
					}
				}
				if (!found){
					Attribute newSourceAttribute = findAttributeInSource(targetAttribute.getAttribute().getKeyId());
					if (newSourceAttribute == null){
						warnings.add(MessageFormat.format(Messages.DataModelMergeAndUpdater_AttributeNotFound, targetAttribute.getAttribute().getKeyId(),source.getName())); 
					}else{
						CategoryAttribute newSourceCa = new CategoryAttribute(source, newSourceAttribute);
						source.getAttributes().add(newSourceCa);
						mergeCategoryAttribute(newSourceCa, targetAttribute);
					}
				}
			}
			resortAttribute(source.getAttributes());
		}
		
		if (target.getChildren() != null){
			for (Category targetChild : target.getChildren()){
				boolean found = false;
				for (Category sourceChild : source.getChildren()){
					if (targetChild.getKeyId().equals(sourceChild.getKeyId())){
						found = true;
						mergeCategory(sourceChild, targetChild);
					}
				}
				if (!found){
					//create new category
					Category newSource = createNewCategory(targetChild);
					newSource.setParent(source);
					source.getChildren().add(newSource);
					mergeCategory(newSource, targetChild);
				}
			}
			resortCategories(source.getChildren());
		}
	}
	
	private Category createNewCategory(Category target){
		Category newSource = new Category();
		newSource.setKeyId(target.getKeyId());
		newSource.setHkey(target.getHkey());
		newSource.setConservationArea(sourceConservationArea);
		newSource.setCategoryOrder(target.getCategoryOrder());
		newSource.setChildren(new ArrayList<Category>());
		newSource.setAttributes(new ArrayList<CategoryAttribute>());
		return newSource;
	}
	
	private void mergeCategoryAttribute(CategoryAttribute source, CategoryAttribute target){
		source.setIsActive(target.getIsActive());
		source.setOrder(target.getOrder());
	}
	
	private Attribute findAttributeInSource(String keyId){
		for (Attribute a : sourceDm.getAttributes()){
			if (a.getKeyId().equals(keyId)){
				return a;
			}
		}
		return null;
	}
		
	private void mergeAttributes(IProgressMonitor monitor){
		monitor.subTask(Messages.DataModelMergeAndUpdater_AttributesTask);
		for(Attribute targetAttribute : targetDm.getAttributes()){
			boolean found = false;
			for(Attribute sourceAttribute : sourceDm.getAttributes()){
				if (targetAttribute.getKeyId().equals(sourceAttribute.getKeyId())){
					found = true;
					mergeAttribute(sourceAttribute, targetAttribute);
				}
			}
			if (!found){
				//create new attribute
				Attribute newSource = new Attribute();
				newSource.setKeyId(targetAttribute.getKeyId());
				newSource.setType(targetAttribute.getType());
				newSource.setConservationArea(sourceConservationArea);
				sourceDm.getAttributes().add(newSource);
				mergeAttribute(newSource, targetAttribute);
			}
			monitor.worked(1);
		}
	}
	
	
	
	private void mergeAttribute(Attribute source, Attribute target){
		if (!source.getKeyId().equals(target.getKeyId())) return;
		
		if (!source.getType().equals(target.getType())){
			warnings.add(MessageFormat.format(Messages.DataModelMergeAndUpdater_AttributeTypeError, source.getKeyId(), source.getType().name(), target.getType().name()));
			return;
		}
		mergeNames(source, target);
		source.setIsRequired(target.getIsRequired());
		
		if (source.getType() == AttributeType.NUMERIC){
			if (target.getMinValue() != null){
				source.setMinValue(target.getMinValue());
			}
			if (target.getMaxValue() != null){
				source.setMaxValue(target.getMaxValue());
			}
			if (source.getAggregations() == null){
				source.setAggregations(new ArrayList<Aggregation>());
			}
			for (Aggregation agg : target.getAggregations()){
				if (!source.getAggregations().contains(agg)){
					source.getAggregations().add(agg);
				}
			}
			
		}else if (source.getType() == AttributeType.TEXT){
			if (target.getRegex() != null && !target.getRegex().isEmpty()){
				source.setRegex(target.getRegex());
			}
			
		}else if (source.getType() == AttributeType.LIST){
			mergeListItems(source, target);
			
		}else if (source.getType() == AttributeType.TREE){
			mergeAttributeTreeNodes(source, target);
			syncEnabledTree(source);
		}
	}
	
	private void mergeAttributeTreeNodes(Attribute source, Attribute target){
		if (!source.getKeyId().equals(target.getKeyId())) return;
		if (target.getTree() == null) return;
		
		for(AttributeTreeNode targetNode : target.getTree()){
			boolean found = false;
			if (source.getTree() != null){
				for(AttributeTreeNode sourceNode : source.getTree()){
					if (sourceNode.getKeyId().equals(targetNode.getKeyId())){
						found = true;
						mergeTreeNodes(sourceNode, targetNode);
					}	
				}
			}else{
				source.setTree(new ArrayList<AttributeTreeNode>());
			}
			
			if (!found){
				//create new node
				AttributeTreeNode newSourceKid =createNewTreeNode(targetNode);
				newSourceKid.setAttribute(source);
				newSourceKid.setParent(null);				
				source.getTree().add(newSourceKid);
				
				mergeTreeNodes(newSourceKid, targetNode);	
			}
		}
		resortTreeNodes(source.getTree());
	}
	
	private void mergeTreeNodes(AttributeTreeNode source, AttributeTreeNode target){
		if (!source.getKeyId().equals(target.getKeyId())) return;
		if (!source.getAttribute().getKeyId().equals(target.getAttribute().getKeyId())) return;
		if ((source.getParent() == null && target.getParent() != null) ||
			(source.getParent() != null && target.getParent() == null) ||
			(source.getParent() != null && target.getParent() != null && 
			  !source.getParent().getKeyId().equals(target.getParent().getKeyId()))) return;
		
		mergeNames(source, target);
		source.setIsActive(target.getIsActive());
		source.setNodeOrder(target.getNodeOrder());
		
		//process kids
		if (target.getChildren() != null){
			for (AttributeTreeNode targetKid : target.getChildren()){
				boolean found = false;
				if (source.getChildren() == null){
					source.setChildren(new ArrayList<AttributeTreeNode>());
				}
				for (AttributeTreeNode sourceKid : source.getChildren()){
					if (targetKid.getKeyId().equals(sourceKid.getKeyId())){
						found = true;
						mergeTreeNodes(sourceKid, targetKid);
						break;
					}
				}
				if(!found){
					//create a new node and merge
					AttributeTreeNode newSourceKid = createNewTreeNode(targetKid);
					newSourceKid.setAttribute(source.getAttribute());
					newSourceKid.setParent(source);
					source.getChildren().add(newSourceKid);
					mergeTreeNodes(newSourceKid, targetKid);	
				}
			}
		}
			
		//re-order
		List<AttributeTreeNode> kids = source.getChildren();
		resortTreeNodes(kids);
	}
	
	private AttributeTreeNode createNewTreeNode(AttributeTreeNode targetNode){
		AttributeTreeNode newSourceKid = new AttributeTreeNode();
		newSourceKid.setKeyId(targetNode.getKeyId());
		newSourceKid.setHkey(targetNode.getHkey());
		newSourceKid.setChildren(new ArrayList<AttributeTreeNode>());
		newSourceKid.setNodeOrder(targetNode.getNodeOrder());
		return newSourceKid;
	}
	
	private void mergeListItems(Attribute source, Attribute target){
		if (target.getAttributeList() == null) return;
		for(AttributeListItem targetItem : target.getAttributeList()){
			boolean found = false;
			if (source.getAttributeList() == null){
				source.setAttributeList(new ArrayList<AttributeListItem>());
			}
			for (AttributeListItem sourceItem : source.getAttributeList()){
				if (sourceItem.getKeyId().equals(targetItem.getKeyId())){
					found = true;
					mergeListItem(sourceItem, targetItem);
					break;
				}
			}
			if (!found){
				//create new List Item
				AttributeListItem item = new AttributeListItem();
				item.setAttribute(source);
				item.setKeyId(targetItem.getKeyId());
				mergeListItem(item, targetItem);
				source.getAttributeList().add(item);
			}
		}
			
		//re-order
		resortListItems(source.getAttributeList());
	}
	
	private void mergeListItem(AttributeListItem source, AttributeListItem target){
		if (!source.getKeyId().equals(target.getKeyId())) return;
		if (!source.getAttribute().getKeyId().equals(target.getAttribute().getKeyId())) return;
		
		mergeNames(source, target);
		source.setListOrder(target.getListOrder());
		source.setIsActive(target.getIsActive());
	}
	
	private void mergeNames(NamedItem source, NamedItem target){
		for (Language l : sourceConservationArea.getLanguages()){
			String targetName = target.findNameNull(l);
			if (targetName != null){
				source.updateName(l, targetName);
			}
		}
		
		source.setName(source.findNameNull(SmartDB.getCurrentLanguage()));
		if (source.getName() == null){
			source.setName(source.findName(sourceConservationArea.getDefaultLanguage()));
		}
	}
	
	private int compareNames(NamedItem o1, NamedItem o2){
		return Collator.getInstance().compare(o1.findName(sourceConservationArea.getDefaultLanguage()), o2.findName(sourceConservationArea.getDefaultLanguage()));
	}
	private void resortCategories(List<Category> kids){
		Collections.sort(kids, new Comparator<Category>(){
			@Override
			public int compare(Category o1, Category o2) {
				int ret = ((Integer)o1.getCategoryOrder()).compareTo(o2.getCategoryOrder());
				if (ret != 0) return ret;
				return compareNames(o1, o2);
			}
		});
		int order = 0;
		for (Category i : kids){
			i.setCategoryOrder(order++);
		}
	}
	
	private void resortTreeNodes(List<AttributeTreeNode> kids){
		Collections.sort(kids, new Comparator<AttributeTreeNode>(){
			@Override
			public int compare(AttributeTreeNode o1, AttributeTreeNode o2) {
				int ret = ((Integer)o1.getNodeOrder()).compareTo(o2.getNodeOrder());
				if (ret != 0) return ret;
				return compareNames(o1, o2);
			}
		});
		int order = 0;
		for (AttributeTreeNode i : kids){
			i.setNodeOrder(order++);
		}
	}
	
	/**
	 * Syncs the enabled state of the tree.  It is possible that
	 * and update will disable a parent node without disabling a child
	 * node.  This will sync the state so that children of parent nodes
	 * that are disabled are disabled.
	 *  
	 * @param attribute
	 */
	private void syncEnabledTree(Attribute attribute){
		if (attribute.getTree() == null) return;
		
		List<AttributeTreeNode> toProcess = new ArrayList<AttributeTreeNode>();
		toProcess.addAll(attribute.getTree());
		while(!toProcess.isEmpty()){
			AttributeTreeNode node = toProcess.remove(0);
			if (node.getParent() != null 
					&& !node.getParent().getIsActive()
					&& node.getIsActive()){
				node.setIsActive(false);
			}
			if (node.getChildren() != null){
				toProcess.addAll(node.getChildren());
			}
		}
		
	}
	private void resortAttribute(List<CategoryAttribute> kids){
		Collections.sort(kids, new Comparator<CategoryAttribute>(){
			@Override
			public int compare(CategoryAttribute o1, CategoryAttribute o2) {
				int ret = ((Integer)o1.getOrder()).compareTo(o2.getOrder());
				if (ret != 0) return ret;
				return compareNames(o1.getAttribute(), o2.getAttribute());
			}
		});
		int order = 0;
		for (CategoryAttribute i : kids){
			i.setOrder(order++);
		}
	}
	
	private void resortListItems(List<AttributeListItem> kids){
		Collections.sort(kids, new Comparator<AttributeListItem>(){
			@Override
			public int compare(AttributeListItem o1, AttributeListItem o2) {
				int ret = ((Integer)o1.getListOrder()).compareTo(o2.getListOrder());
				if (ret != 0) return ret;
				return compareNames(o1, o2);
			}
		});
		int order = 0;
		for (AttributeListItem i : kids){
			i.setListOrder(order++);
		}
	}
}
