source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               OSGI-INF/,\
               images/,\
               src/org/wcs/smart/entity/query/model/type/grid.html,\
               src/org/wcs/smart/entity/query/model/type/grid.png,\
               src/org/wcs/smart/entity/query/model/type/incident.html,\
               src/org/wcs/smart/entity/query/model/type/incident.png,\
               src/org/wcs/smart/entity/query/model/type/observation.html,\
               src/org/wcs/smart/entity/query/model/type/observation.png,\
               src/org/wcs/smart/entity/query/model/type/summary.html,\
               src/org/wcs/smart/entity/query/model/type/summary.png
