/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Model class of i_relationship_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="i_relationship_type_attribute", schema="smart")
public class IntelRelationshipTypeAttribute{

	private IRelationshipTypeAttributePk id = new IRelationshipTypeAttributePk();	

	private int order;
	
	public IntelRelationshipTypeAttribute(){
	}
	
	@EmbeddedId
	public IRelationshipTypeAttributePk getId(){
		return this.id;
	}
	public void setId(IRelationshipTypeAttributePk id){
		this.id = id;
	}
	
	@Transient
	public IntelRelationshipType getRelationshipType() {
		return id.getRelationshipType();
	}

	public void setRelationshipType(IntelRelationshipType type) {
		id.setRelationshipType(type);
	}
	
	@Transient
	public IntelAttribute getAttribute() {
		return id.getAttribute();
	}

	public void setAttribute(IntelAttribute attribute) {
		id.setAttribute(attribute);
	}

	@Column(name="seq_order")
	public int getOrder(){
		return this.order;
	}
	public void setOrder(int order){
		this.order = order;
	}
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelRelationshipTypeAttribute){
			return this.id.equals(((IntelRelationshipTypeAttribute)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IRelationshipTypeAttributePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelRelationshipType type;
		private IntelAttribute attribute;

		public IRelationshipTypeAttributePk(){
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="relationship_type_uuid")
		public IntelRelationshipType getRelationshipType() {
			return type;
		}

		public void setRelationshipType(IntelRelationshipType entity) {
			this.type = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IRelationshipTypeAttributePk)){
				return false;
			}
			IRelationshipTypeAttributePk p = (IRelationshipTypeAttributePk)key;
			
			if (p.type == null || this.type == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.type == null && this.type == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.type.equals(this.type) &&
					p.attribute.equals(this.attribute);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (type != null) {code += type.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}

}