package org.wcs.smart.i2.model;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Employee;
import org.wcs.smart.ca.NamedItem;

/**
 * Model class of i_working_set.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_working_set")
public class IntelWorkingSet extends NamedItem{

	
	private ConservationArea ca;

	private Date dateCreated;
	private Date dateModified;

	private Employee createdBy;
	private Employee lastModifiedBy;

	private String entityDateFilter;

	private Set<IntelWorkingSetQuery> queries;
	private Set<IntelWorkingSetRecord> records;
	private Set<IntelWorkingSetEntity> entities;

	/**
	 * Constructor.
	 */
	public IntelWorkingSet() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param caConservationArea
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea caConservationArea) {
		this.ca = caConservationArea;
	}
	
	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	@Column(name="date_created")
	public Date getDateCreated() {
		return this.dateCreated;
	}
	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}


	/**
	 * Set the date_modified.
	 * 
	 * @param dateModified
	 *            date_modified
	 */
	@Column(name="date_modified")
	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	/**
	 * Get the date_modified.
	 * 
	 * @return date_modified
	 */
	public Date getDateModified() {
		return this.dateModified;
	}

	/**
	 * Get the created_by.
	 * 
	 * @return created_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="created_by", referencedColumnName="uuid")
	public Employee getCreatedBy() {
		return this.createdBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}
	
	/**
	 * Get the last modified by.
	 * 
	 * @return last_modified_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="last_modified_by", referencedColumnName="uuid")
	public Employee getLastModifiedBy() {
		return this.lastModifiedBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setLastModifiedBy(Employee lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}
	
	
	/**
	 * Set the entity_date_filter.
	 * 
	 * @param entityDateFilter
	 *            entity_date_filter
	 */
	public void setEntityDateFilter(String entityDateFilter) {
		this.entityDateFilter = entityDateFilter;
	}

	/**
	 * Get the entity_date_filter.
	 * 
	 * @return entity_date_filter
	 */
	public String getEntityDateFilter() {
		return this.entityDateFilter;
	}

	/**
	 * Get the set of the i_working_set_query.
	 * 
	 * @return The set of i_working_set_query
	 */
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="working_set_uuid", referencedColumnName="uuid")
	public Set<IntelWorkingSetQuery> getQueries() {
		return this.queries;
	}
	
	/**
	 * Set the set of the i_working_set_query.
	 * 
	 * @param iWorkingSetQuerySet
	 *            The set of i_working_set_query
	 */
	public void setQueries(Set<IntelWorkingSetQuery> queries) {
		this.queries = queries;
	}
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="working_set_uuid", referencedColumnName="uuid")
	public Set<IntelWorkingSetRecord> getRecords() {
		return this.records;
	}
	public void setRecords(Set<IntelWorkingSetRecord> records) {
		this.records = records;
	}
	
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="working_set_uuid", referencedColumnName="uuid")
	public Set<IntelWorkingSetEntity> getEntities() {
		return this.entities;
	}
	public void setEntities(Set<IntelWorkingSetEntity> entities) {
		this.entities = entities;
	}
}
