/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_entity_attribute_value.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_attribute_value")
public class IntelEntityAttributeValue extends IntelValueItem{

	private EntityAttributeValuePk id = new EntityAttributeValuePk();
	
	private String meta;

	/**
	 * Constructor.
	 */
	public IntelEntityAttributeValue() {
	}

	@EmbeddedId
	public EntityAttributeValuePk getId(){
		return this.id;
	}
	public void setId(EntityAttributeValuePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntity getEntity(){
		return id.getEntity();
	}
	public void setEntity(IntelEntity entity){
		id.setEntity(entity);
	}
	
	@Override
	@Transient
	public IntelAttribute getAttribute(){
		return id.getAttribute();
	}
	
	public void setAttribute(IntelAttribute attribute){
		id.setAttribute(attribute);
	}
	
	@Column(name="metaphone")
	public String getMetaphone(){
		return this.meta;
	}
	
	public void setMetaphone(String meta){
		this.meta = meta;
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityAttributeValue){
			return this.id.equals(((IntelEntityAttributeValue)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class EntityAttributeValuePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntity entity;
		private IntelAttribute attribute;
		

		public EntityAttributeValuePk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_uuid")
		public IntelEntity getEntity() {
			return entity;
		}

		public void setEntity(IntelEntity entity) {
			this.entity = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (this == key) return true;
			if (key == null) return false;
			if (!getClass().equals(key.getClass())) return false;
			
			EntityAttributeValuePk p = (EntityAttributeValuePk)key;
			return Objects.equals(entity, p.entity) && Objects.equals(attribute, p.attribute);
		}
		
		@Override
		public int hashCode() {
			return Objects.hash(entity, attribute);
		  }
	}
}
