package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_record_attachment.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_record_attachment")
public class IntelRecordAttachment {

	private IRecordAttachmentPk id = new IRecordAttachmentPk();	
	
	public IntelRecordAttachment(){
		
	}
	
	@EmbeddedId
	public IRecordAttachmentPk getId(){
		return this.id;
	}
	public void setId(IRecordAttachmentPk id){
		this.id = id;
	}
	
	@Transient
	public IntelRecord getRecord() {
		return id.getRecord();
	}

	public void setRecord(IntelRecord record) {
		id.setRecord(record);
	}
	
	@Transient
	public IntelAttachment getAttachment() {
		return id.getAttachment();
	}

	public void setAttachment(IntelAttachment attachment) {
		id.setAttachment(attachment);
	}
	

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelRecordAttachment){
			return this.id.equals(((IntelRecordAttachment)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IRecordAttachmentPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelRecord record;
		private IntelAttachment attachment;
		

		public IRecordAttachmentPk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="record_uuid")
		public IntelRecord getRecord() {
			return record;
		}

		public void setRecord(IntelRecord record) {
			this.record = record;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attachment_uuid")
		public IntelAttachment getAttachment() {
			return attachment;
		}

		public void setAttachment(IntelAttachment attachment) {
			this.attachment = attachment;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IRecordAttachmentPk)){
				return false;
			}
			IRecordAttachmentPk p = (IRecordAttachmentPk)key;
			
			if (p.record == null || this.record == null ||
				p.attachment == null || this.attachment == null ){
				
				if (p.record == null && this.record == null && 
					p.attachment == null && this.attachment == null){
						return true;
				}
				return false;
			}
			
			return p.record.equals(this.record) &&
					p.attachment.equals(this.attachment);
		}
		
		@Override
		public int hashCode() {
		    int code = 0;
		    if (record != null) {code += record.hashCode();}
		    code *= 31;
		    if (attachment != null) {code += attachment.hashCode(); }
		    return code;
		  }
	}
}