/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Employee;
import org.wcs.smart.ca.UuidItem;

/**
 * Model class of i_record.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_record")
public class IntelRecord extends UuidItem implements IIntelAuditItem{

	public static final int MAX_TITLE_LENGTH = 1024;
	
	public enum Status{
			NEW,
			PROCESSING,
			COMPLETE;
	};
	
	private ConservationArea ca;
	

	private Date dateCreated;
	private Date dateModified;
	private Date dateExported;

	private Employee createdBy;
	private Employee lastModifiedBy;

	private Status status;

	private String title;
	private String description;
	private String comment;

	private List<IntelEntityRecord> entities;
	private List<IntelLocation> locations;
	private List<IntelRecordAttachment> attachments;

	/**
	 * Constructor.
	 */
	public IntelRecord() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}
	
	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	@Column(name="date_created")
	public Date getDateCreated() {
		return this.dateCreated;
	}
	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}


	/**
	 * Set the date_modified.
	 * 
	 * @param dateModified
	 *            date_modified
	 */
	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	/**
	 * Get the date_modified.
	 * 
	 * @return date_modified
	 */
	@Column(name="last_modified_date")
	public Date getDateModified() {
		return this.dateModified;
	}

	/**
	 * Get the date_exported.
	 * 
	 * @return dateExported
	 */
	@Column(name="date_exported")
	public Date getDateExported() {
		return this.dateExported;
	}
	/**
	 * Set the date_exported.
	 * 
	 * @param dateExported
	 *            dateExported
	 */
	public void setDateExported(Date dateExported) {
		this.dateExported = dateExported;
	}
	
	/**
	 * Get the created_by.
	 * 
	 * @return created_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="created_by", referencedColumnName="uuid")
	public Employee getCreatedBy() {
		return this.createdBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}
	
	/**
	 * Get the last modified by.
	 * 
	 * @return last_modified_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="last_modified_by", referencedColumnName="uuid")
	public Employee getLastModifiedBy() {
		return this.lastModifiedBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setLastModifiedBy(Employee lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	
	/**
	 * Get the type.
	 * 
	 * @return type
	 */
	@Enumerated(EnumType.STRING)
	@Column(name="status")
	public Status getStatus() {
		return this.status;
	}
	
	/**
	 * Set the type.
	 * 
	 * @param type
	 *            type
	 */
	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name="title")
	public String getTitle(){
		return this.title;
	}
	public void setTitle(String title){
		this.title = title;
	}
	
	
	@Column(name="description")
	public String getDescription(){
		return this.description;
	}
	public void setDescription(String description){
		this.description = description;
	}
	
	@Column(name="comment")
	public String getComment(){
		return this.comment;
	}
	public void setComment(String comment){
		this.comment = comment;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.record", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityRecord> getEntities(){
		return this.entities;
	}
	public void setEntities(List<IntelEntityRecord> entities){
		this.entities = entities;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.record", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelRecordAttachment> getAttachments(){
		return this.attachments;
	}
	public void setAttachments(List<IntelRecordAttachment> attachments){
		this.attachments = attachments;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy="record", orphanRemoval=true, cascade={CascadeType.ALL})
	public List<IntelLocation> getLocations(){
		return this.locations;
	}
	public void setLocations(List<IntelLocation> locations){
		this.locations = locations;
	}
}
