package org.wcs.smart.i2.model;

import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.UuidItem;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.io.ParseException;
import com.vividsolutions.jts.io.WKBReader;
import com.vividsolutions.jts.io.WKBWriter;

/**
 * Model class of i_location.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_location")
public class IntelLocation extends UuidItem{

	public static final int COMMENT_MAX_LENGTH = 4096;
	
	private ConservationArea ca;
	private String id;
	private byte[] geom;
	private Date dateTime;
	private String comment;
	
	private List<IntelObservation> observations;
	private IntelRecord record;
	
	@Transient
	private Geometry geometry;
	
	public IntelLocation(){
		
	}
	
	
	@Column(name="geometry")
	@Lob
	@Basic(fetch = FetchType.LAZY)
	public byte[] getGeom() {
		return geom;
	}
	public void setGeom(byte[] geom) {
		this.geom = geom;
	}
	@Transient
	public Geometry getGeometry() throws ParseException{
		if (this.geometry == null && geom != null){
			WKBReader reader = new WKBReader();
			this.geometry = (Geometry)reader.read(geom);
		}
		return this.geometry;
	}
	/**
	 * Sets the geometry.  Geometry
	 * must be in EPSG:4326
	 * 
	 * @param geometry new geometry
	 */
	public void setLineString(Geometry geometry){
		if (geometry == null){
			this.geometry = null;
			this.geom = null;
			return;
		}
		
		WKBWriter writer = new WKBWriter(3);
		this.geom = writer.write(geometry);
		this.geometry = geometry;
	}
	
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return ca;
	}

	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}
	
	@Column(name="id")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Column(name="datetime")
	public Date getDateTime() {
		return dateTime;
	}

	/**
	 * @param time
	 */
	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}


	@Column(name="comment")
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="record_uiud", referencedColumnName="uuid")
	public IntelRecord getRecord(){
		return this.record;
	}
	public void setRecord(IntelRecord record){
		this.record = record;
	}
	
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name="location_uuid", referencedColumnName="uuid")
	public List<IntelObservation> getObservations(){
		return this.observations;
	}
	public void setObservations(List<IntelObservation> observations){
		this.observations = observations;
	}
	
	

}