/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.text.MessageFormat;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedItem;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Model class of i_entity_search.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="i_entity_search", schema="smart")
public class IntelEntitySearch extends NamedItem {

	private static final long serialVersionUID = 1L;

	public enum Type{
		BASIC("basic"), //$NON-NLS-1$
		ADVANCED("adv"), //$NON-NLS-1$
		RECORD("record"), //$NON-NLS-1$
		ALL("all"); //$NON-NLS-1$
		
		public String key;
		
		Type(String key){
			this.key = key;
		}
	}
	
	public static final String SEPARATOR = ";"; //$NON-NLS-1$
	
	/** conservation_area. */
	private ConservationArea ca;
	private String searchString;
	
	/**
	 * Constructor.
	 */
	public IntelEntitySearch() {
	}

	@Transient
	public Type getType() {
		String typePart = getSearchString().split(SEPARATOR)[0];
		for (Type t : Type.values()) {
			if (t.key.equals(typePart)) return t;
		}
		throw new IllegalStateException(MessageFormat.format("The search string type {0} is not supported", typePart));  //$NON-NLS-1$
	}
	
	/**
	 * Set the search_string.  The search string should
	 * be of the form <Type.key>;<String format> 
	 * 
	 * @param searchString
	 *            search_string
	 */
	public void setSearchString(String searchString) {
		String type = searchString.split(SEPARATOR)[0];
		boolean found = false;
		for (Type t : Type.values()) {
			if (t.key.equals(type)) {
				found = true; break;
			}
		}
		if (!found) throw new IllegalStateException(MessageFormat.format("The search string type {0} is not supported", type)); //$NON-NLS-1$
		this.searchString = searchString;
	}

	/**
	 * Get the search_string.
	 * 
	 * Get the search_string.  The search string should
	 * be of the form <Type.key>;<String format> 
	 * 
	 * @return search_string
	 */
	@Column(name="search_string")
	public String getSearchString() {
		return this.searchString;
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}
	
}
