package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_relationship_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_relationship_type_attribute")
public class IntelRelationshipTypeAttribute{


	private IRelationshipTypeAttributePk id = new IRelationshipTypeAttributePk();	
	
	public IntelRelationshipTypeAttribute(){
	}
	
	@EmbeddedId
	public IRelationshipTypeAttributePk getId(){
		return this.id;
	}
	public void setId(IRelationshipTypeAttributePk id){
		this.id = id;
	}
	
	@Transient
	public IntelRelationshipType getRelationshipType() {
		return id.getRelationshipType();
	}

	public void setRelationshipType(IntelRelationshipType type) {
		id.setRelationshipType(type);
	}
	
	@Transient
	public IntelAttribute getAttribute() {
		return id.getAttribute();
	}

	public void setAttribute(IntelAttribute attachment) {
		id.setAttribute(attachment);
	}

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelRelationshipTypeAttribute){
			return this.id.equals(((IntelRelationshipTypeAttribute)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IRelationshipTypeAttributePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelRelationshipType type;
		private IntelAttribute attribute;

		public IRelationshipTypeAttributePk(){
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="relationship_type_uuid")
		public IntelRelationshipType getRelationshipType() {
			return type;
		}

		public void setRelationshipType(IntelRelationshipType entity) {
			this.type = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IRelationshipTypeAttributePk)){
				return false;
			}
			IRelationshipTypeAttributePk p = (IRelationshipTypeAttributePk)key;
			
			if (p.type == null || this.type == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.type == null && this.type == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.type.equals(this.type) &&
					p.attribute.equals(this.attribute);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (type != null) {code += type.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}

}