/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;
import java.util.UUID;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Model class of i_working_set_query.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="i_working_set_query", schema="smart")
public class IntelWorkingSetQuery implements IWorkingSetMapLayer{
	
	private IWorkingSetQueryPk id = new IWorkingSetQueryPk();	
	
	private String mapStyle;
	private Boolean isVisible;
	private String queryType;
	
	public IntelWorkingSetQuery(){
		
	}
	
	@Override
	@Column(name="map_style")
	public String getMapStyle(){
		return this.mapStyle;
	}
	
	@Override
	public void setMapStyle(String style){
		this.mapStyle = style;
	}
	
	@Override
	@Column(name="is_visible")
	public boolean getIsVisible(){
		return this.isVisible;
	}
	@Override
	public void setIsVisible(boolean isVisible){
		this.isVisible = isVisible;
	}
	
	
	@Column(name="query_type")
	public String getQueryType() {
		return this.queryType;
	}

	public void setQueryType(String queryType){
		this.queryType = queryType;
	}
	
	@EmbeddedId
	public IWorkingSetQueryPk getId(){
		return this.id;
	}
	public void setId(IWorkingSetQueryPk id){
		this.id = id;
	}
	
	@Transient
	public UUID getQuery() {
		return id.getQuery();
	}

	public void setQuery(UUID entity) {
		id.setQuery(entity);
	}
	
	@Transient
	public IntelWorkingSet getWorkingSet() {
		return id.getWorkingSet();
	}

	public void setWorkingSet(IntelWorkingSet workingSet) {
		id.setWorkingSet(workingSet);
	}
	

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelWorkingSetQuery){
			return this.id.equals(((IntelWorkingSetQuery)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	public static class IWorkingSetQueryPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private UUID queryUuid;
		private IntelWorkingSet workingSet;
		

		public IWorkingSetQueryPk(){
			
		}
		
		@Column(name="query_uuid")
		public UUID getQuery() {
			return queryUuid;
		}

		public void setQuery(UUID queryUuid) {
			this.queryUuid = queryUuid;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="working_set_uuid")
		public IntelWorkingSet getWorkingSet() {
			return workingSet;
		}

		public void setWorkingSet(IntelWorkingSet workingSet) {
			this.workingSet = workingSet;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IWorkingSetQueryPk)){
				return false;
			}
			IWorkingSetQueryPk p = (IWorkingSetQueryPk)key;
			
			if (p.queryUuid == null || this.queryUuid == null ||
				p.workingSet == null || this.workingSet == null ){
				
				if (p.queryUuid == null && this.queryUuid == null && 
					p.workingSet == null && this.workingSet == null){
						return true;
				}
				return false;
			}
			
			return p.queryUuid.equals(this.queryUuid) &&
					p.workingSet.equals(this.workingSet);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (queryUuid != null) {code += queryUuid.hashCode();}
		    code *= 31;
		    if (workingSet != null) {code += workingSet.hashCode(); }
		    return code;
		  }
	}
}