/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.UuidItem;
import org.wcs.smart.ca.datamodel.Category;

/**
 * Model class of i_observation.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_observation")
public class IntelObservation extends UuidItem{

	private IntelLocation location;
	private Category category;
	private List<IntelObservationAttribute> attributes;

	/**
	 * Constructor.
	 */
	public IntelObservation() {
	}

	/**
	 * Get the i_location.
	 * 
	 * @return i_location
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="location_uuid", referencedColumnName="uuid")
	public IntelLocation getLocation() {
		return this.location;
	}
	/**
	 * Set the i_location.
	 * 
	 * @param locationILocation
	 *            i_location
	 */
	public void setLocation(IntelLocation location) {
		this.location = location;
	}


	/**
	 * Get the category_uuid.
	 * 
	 * @return category_uuid
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="category_uuid", referencedColumnName="uuid")
	public Category getCategory() {
		return this.category;
	}
	/**
	 * Set the category_uuid.
	 * 
	 * @param categoryUuid
	 *            category_uuid
	 */
	public void setCategory(Category category) {
		this.category = category;
	}


	/**
	 * Get the set of the i_observation_attribute.
	 * 
	 * @return The set of i_observation_attribute
	 */
	@OneToMany
	@JoinColumn(name="observation_uuid", referencedColumnName="uuid")
	public List<IntelObservationAttribute> getObservationAttributes() {
		return this.attributes;
	}
	/**
	 * Set the set of the i_observation_attribute.
	 * 
	 * @param iObservationAttributeSet
	 *            The set of i_observation_attribute
	 */
	public void setObservationAttributes(List<IntelObservationAttribute> attributes) {
		this.attributes = attributes;
	}


}
