package org.wcs.smart.i2.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.UuidItem;
import org.wcs.smart.ca.datamodel.Category;

/**
 * Model class of i_observation.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_observation")
public class IntelObservation extends UuidItem{

	private IntelLocation location;
	private Category category;
	private List<IntelObservationAttribute> attributes;

	/**
	 * Constructor.
	 */
	public IntelObservation() {
	}

	/**
	 * Get the i_location.
	 * 
	 * @return i_location
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="location_uuid", referencedColumnName="uuid")
	public IntelLocation getLocation() {
		return this.location;
	}
	/**
	 * Set the i_location.
	 * 
	 * @param locationILocation
	 *            i_location
	 */
	public void setLocation(IntelLocation location) {
		this.location = location;
	}


	/**
	 * Get the category_uuid.
	 * 
	 * @return category_uuid
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="category_uuid", referencedColumnName="uuid")
	public Category getCategory() {
		return this.category;
	}
	/**
	 * Set the category_uuid.
	 * 
	 * @param categoryUuid
	 *            category_uuid
	 */
	public void setCategory(Category category) {
		this.category = category;
	}


	/**
	 * Get the set of the i_observation_attribute.
	 * 
	 * @return The set of i_observation_attribute
	 */
	@OneToMany
	@JoinColumn(name="observation_uuid", referencedColumnName="uuid")
	public List<IntelObservationAttribute> getObservationAttributes() {
		return this.attributes;
	}
	/**
	 * Set the set of the i_observation_attribute.
	 * 
	 * @param iObservationAttributeSet
	 *            The set of i_observation_attribute
	 */
	public void setObservationAttributes(List<IntelObservationAttribute> attributes) {
		this.attributes = attributes;
	}


}
