package org.wcs.smart.i2.model;

import java.sql.Blob;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_relationship_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_relationship_type")
public class IntelRelationshipType extends NamedKeyItem {

	private ConservationArea ca;
	private Blob icon;
	private IntelRelationshipGroup group;

	private IntelEntityType srcType;
	private IntelEntityType targetType;
	
	private Set<IntelRelationshipTypeAttribute> attributes;

	
	/**
	 * Constructor.
	 */
	public IntelRelationshipType() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param caConservationArea
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea caConservationArea) {
		this.ca = caConservationArea;
	}

	/**
	 * Get the icon.
	 * 
	 * @return icon
	 */
	@Column(name="icon")
	public Blob getIcon() {
		return this.icon;
	}

	/**
	 * Set the icon.
	 * 
	 * @param icon
	 *            icon
	 */
	public void setIcon(Blob icon) {
		this.icon = icon;
	}

	/**
	 * Get the i_relationship_group.
	 * 
	 * @return i_relationship_group
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="relationship_group_uuid", referencedColumnName="uuid")
	public IntelRelationshipGroup getRelationshipGroup() {
		return this.group;
	}
	/**
	 * Set the i_relationship_group.
	 * 
	 * @param relationshipGroupIRelationshipGroup
	 *            i_relationship_group
	 */
	public void setRelationshipGroup(IntelRelationshipGroup group) {
		this.group = group;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="src_entity_type", referencedColumnName="uuid")
	public IntelEntityType getSourceEntityType(){
		return this.srcType;
	}
	
	public void setSourceEntityType(IntelEntityType srcType){
		this.srcType = srcType;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="target_entity_type", referencedColumnName="uuid")
	public IntelEntityType getTargetEntityType(){
		return this.targetType;
	}
	
	public void setTargetEntityType(IntelEntityType targetType){
		this.targetType = targetType;
	}

	
	/**
	 * Set the set of the i_relationship_attribute.
	 * 
	 * @param iRelationshipAttributeSet
	 *            The set of i_relationship_attribute
	 */
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name="relationship_type_uuid", referencedColumnName="uuid")
	public Set<IntelRelationshipTypeAttribute> getAttributes() {
		return this.attributes;
	}
	
	/**
	 * Set the set of the i_relationship_attribute.
	 * 
	 * @param iRelationshipAttributeSet
	 *            The set of i_relationship_attribute
	 */
	public void setAttributes(Set<IntelRelationshipTypeAttribute> attributes) {
		this.attributes = attributes;
	}


}
