/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.List;

import javax.imageio.ImageIO;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_entity_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_type")
public class IntelEntityType extends NamedKeyItem {

	private ConservationArea ca;
	private IntelAttribute idAttribute;
	private byte[] icon;
	private String birtTemplate;

	private List<IntelEntityTypeAttribute> attributes;

	/**
	 * Constructor.
	 */
	public IntelEntityType() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}


	/**
	 * Get the id_attribute_uuid.
	 * 
	 * @return id_attribute_uuid
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="id_attribute_uuid", referencedColumnName="uuid")
	public IntelAttribute getIdAttribute() {
		return this.idAttribute;
	}
	
	/**
	 * Set the id_attribute_uuid.
	 * 
	 * @param idAttributeUuid
	 *            id_attribute_uuid
	 */
	public void setIdAttribute(IntelAttribute idAttribute) {
		this.idAttribute = idAttribute;
	}

	
	/**
	 * Get the icon.
	 * 
	 * @return icon
	 */
	@Column(name="icon")
	@Lob
	public byte[] getIcon() {
		return this.icon;
	}
	/**
	 * Set the icon.
	 * 
	 * @param icon
	 *            icon
	 */
	public void setIcon(byte[] icon) {
		this.icon = icon;
	}


	/**
	 * Get the birt_template.
	 * 
	 * @return birt_template
	 */
	@Column(name="birt_template")
	public String getBirtTemplate() {
		return this.birtTemplate;
	}
	/**
	 * Set the birt_template.
	 * 
	 * @param birtTemplate
	 *            birt_template
	 */
	public void setBirtTemplate(String birtTemplate) {
		this.birtTemplate = birtTemplate;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="entity_type_uuid", referencedColumnName="uuid" )
	public List<IntelEntityTypeAttribute> getAttributes(){
		return this.attributes;
	}
	
	public void setAttributes(List<IntelEntityTypeAttribute> attributes){
		this.attributes = attributes;
	}
	
	@Transient
	public BufferedImage getIconAsImage() throws Exception{
		if (getIcon() == null) return null;
		try(ByteArrayInputStream in = new ByteArrayInputStream(getIcon())){
			return ImageIO.read(in);
		}
	}

}
