package org.wcs.smart.i2.model;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.UuidItem;
import org.wcs.smart.ca.datamodel.AttributeListItem;
import org.wcs.smart.ca.datamodel.AttributeTreeNode;
import org.wcs.smart.ca.datamodel.Category;

/**
 * Model class of i_datamodel_event.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_datamodel_event")
public class IntelDatamodelEvent extends UuidItem {

	private ConservationArea ca;
	private Category dmCategory;
	private AttributeListItem dmListItem;
	private AttributeTreeNode dmTreeNode;

	/**
	 * Constructor.
	 */
	public IntelDatamodelEvent() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="category_uuid", referencedColumnName="uuid")
	public Category getDmCategory() {
		return this.dmCategory;
	}

	public void setDmCategory(Category dmCategory) {
		this.dmCategory = dmCategory;
	}

	
	/**
	 * Get the attribute list item that should trigger event
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="list_item_uuid", referencedColumnName="uuid")
	public AttributeListItem getAttributeListItem() {
		return this.dmListItem;
	}
	

	public void setAttributeListItem(AttributeListItem dmListItem) {
		this.dmListItem = dmListItem;
	}

	/**
	 * Get the attribute tree node that should trigger event
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="tree_node_uuid", referencedColumnName="uuid")
	public AttributeTreeNode getAttributeTreeNode() {
		return this.dmTreeNode;
	}

	public void setAttributeTreeNode(AttributeTreeNode cmTreeNode) {
		this.dmTreeNode = cmTreeNode;
	}
}
