package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;


/**
 * Model class of i_entity_location.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_location")
public class IntelEntityLocation {

	private IEntityLocationPk id = new IEntityLocationPk();
	
	/**
	 * Constructor.
	 */
	public IntelEntityLocation() {
	}

	@EmbeddedId
	public IEntityLocationPk getId(){
		return this.id;
	}
	public void setId(IEntityLocationPk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntity getEntity() {
		return id.getEntity();
	}

	public void setEntity(IntelEntity entity) {
		id.setEntity(entity);
	}
	
	@Transient
	public IntelLocation getLocation() {
		return id.getLocation();
	}

	public void setLocation(IntelLocation location) {
		id.setLocation(location);
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityLocation){
			return this.id.equals(((IntelEntityLocation)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityLocationPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntity entity;
		private IntelLocation location;

		public IEntityLocationPk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_uuid")
		public IntelEntity getEntity() {
			return entity;
		}

		public void setEntity(IntelEntity entity) {
			this.entity = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="location_uuid")
		public IntelLocation getLocation() {
			return location;
		}

		public void setLocation(IntelLocation location) {
			this.location = location;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityLocationPk)){
				return false;
			}
			IEntityLocationPk p = (IEntityLocationPk)key;
			
			if (p.entity == null || this.entity == null ||
				p.location == null || this.location == null ){
				
				if (p.entity == null && this.entity == null && 
					p.location == null && this.location == null){
						return true;
				}
				return false;
			}
			
			return p.entity.equals(this.entity) &&
					p.location.equals(this.location);
		}
		
		@Override
		public int hashCode() {
		    int code = 0;
		    if (entity != null) {code += entity.hashCode();}
		    code *= 31;
		    if (location != null) {code += location.hashCode(); }
		    return code;
		  }
	}
}

