package org.wcs.smart.i2.model;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.UuidItem;

/**
 * Model class of i_entity_relationship.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_relationship")
public class IntelEntityRelationship extends UuidItem{

	private IntelEntity srcEntity;
	private IntelEntity targetEntity;
	
	private IntelRelationshipType relationshipType;

	private Set<IntelEntityRelationshipAttribute> attributes;

	/**
	 * Constructor.
	 */
	public IntelEntityRelationship() {
	}

	/**
	 * Get the source entity object.
	 * 
	 * @return source entity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="src_entity_uuid", referencedColumnName="uuid")
	public IntelEntity getSourceEntity() {
		return this.srcEntity;
	}
	
	/**
	 * Set the source entity object
	 * 
	 * @param srcEntity source entity
	 */
	public void setSourceEntity(IntelEntity srcEntity) {
		this.srcEntity = srcEntity;
	}
	
	/**
	 * Get the target entity object.
	 * 
	 * @return target entity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="target_entity_uuid", referencedColumnName="uuid")
	public IntelEntity getTargetEntity() {
		return this.targetEntity;
	}
	
	/**
	 * Set the garget entity object
	 * 
	 * @param targetEntity target entity
	 */
	public void setTargetEntity(IntelEntity targetEntity) {
		this.targetEntity = targetEntity;
	}
	

	/**
	 * Get the i_relationship_type.
	 * 
	 * @return i_relationship_type
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="relationship_type_uuid", referencedColumnName="uuid")
	public IntelRelationshipType getRelationshipType() {
		return this.relationshipType;
	}
	
	/**
	 * Set the i_relationship_type.
	 * 
	 * @param relationshipTypeIRelationshipType
	 *            i_relationship_type
	 */
	public void setRelationshipType(IntelRelationshipType type) {
		this.relationshipType = type;
	}


	/**
	 * Get the set of the i_entity_relationship_attribute.
	 * 
	 * @return The set of i_entity_relationship_attribute
	 */
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name="entity_relationship_uuid", referencedColumnName="uuid")
	public Set<IntelEntityRelationshipAttribute> getAttributes() {
		return this.attributes;
	}


	/**
	 * Set the set of the i_entity_relationship_attribute.
	 * 
	 * @param iEntityRelationshipAttributeSet
	 *            The set of i_entity_relationship_attribute
	 */
	public void setAttributes(Set<IntelEntityRelationshipAttribute> attributes) {
		this.attributes = attributes;
	}

}
