package org.wcs.smart.i2.model;

import java.sql.Blob;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_entity_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_type")
public class IntelEntityType extends NamedKeyItem {

	private ConservationArea ca;
	private IntelAttribute idAttribute;
	private Blob icon;
	private String birtTemplate;

	private List<IntelEntityTypeAttribute> attributes;

	/**
	 * Constructor.
	 */
	public IntelEntityType() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}


	/**
	 * Get the id_attribute_uuid.
	 * 
	 * @return id_attribute_uuid
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="id_attribute_uuid", referencedColumnName="uuid")
	public IntelAttribute getIdAttribute() {
		return this.idAttribute;
	}
	
	/**
	 * Set the id_attribute_uuid.
	 * 
	 * @param idAttributeUuid
	 *            id_attribute_uuid
	 */
	public void setIdAttribute(IntelAttribute idAttribute) {
		this.idAttribute = idAttribute;
	}

	
	/**
	 * Get the icon.
	 * 
	 * @return icon
	 */
	public Blob getIcon() {
		return this.icon;
	}
	/**
	 * Set the icon.
	 * 
	 * @param icon
	 *            icon
	 */
	public void setIcon(Blob icon) {
		this.icon = icon;
	}


	/**
	 * Get the birt_template.
	 * 
	 * @return birt_template
	 */
	@Column(name="birt_template")
	public String getBirtTemplate() {
		return this.birtTemplate;
	}
	/**
	 * Set the birt_template.
	 * 
	 * @param birtTemplate
	 *            birt_template
	 */
	public void setBirtTemplate(String birtTemplate) {
		this.birtTemplate = birtTemplate;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="entity_type_uuid", referencedColumnName="uuid")
	public List<IntelEntityTypeAttribute> getAttributes(){
		return this.attributes;
	}
	
	public void setAttributes(List<IntelEntityTypeAttribute> attributes){
		this.attributes = attributes;
	}

}
