/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import java.util.Locale;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.Session;
import org.wcs.smart.ICoreLabelProvider;
import org.wcs.smart.SmartContext;
import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Employee;
import org.wcs.smart.ca.NamedItem;
import org.wcs.smart.ca.NamedKeyItem;
import org.wcs.smart.ca.UuidItem;
import org.wcs.smart.ca.datamodel.Attribute;
import org.wcs.smart.ca.datamodel.AttributeListItem;
import org.wcs.smart.i2.IIntelligenceLabelProvider;
import org.wcs.smart.i2.model.IntelAttribute.AttributeType;
import org.wcs.smart.i2.query.Operator;
import org.wcs.smart.i2.query.observation.filter.IQueryFilter;
import org.wcs.smart.i2.search.AdvancedEntitySearch;
import org.wcs.smart.util.SharedUtils;

/**
 * Model class of i_entity.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity")
public class IntelEntity extends UuidItem implements IIntelAuditItem{

	private static final long serialVersionUID = 1L;

	public static final int SCRATCH_MAX_LENGTH = 32_700;
	
	private LocalDateTime dateCreated;
	private LocalDateTime dateModified;

	private IntelProfile profile;
	
	private Employee createdBy;
	private Employee lastModifiedBy;

	private IntelAttachment primaryAttachment;
	private IntelEntityType entityType;
	private ConservationArea conservationArea;
	
	private List<IntelEntityAttributeValue> entityAttributes;
	private List<IntelEntityAttachment> entityAttachments;
	private List<IntelEntityRecord> intelligenceRecords;
	private List<IntelEntityLocation> entityLocations;
	
	private String comment;
	
	private AttributeListItem listItem;

	/**
	 * Constructor.
	 */
	public IntelEntity() {
	}

	/**
	 * Get the conservation area
	 * @return
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea(){
		return this.conservationArea;
	}
	
	/**
	 * Sets the conservation area
	 * @param ca
	 */
	public void setConservationArea(ConservationArea ca){
		this.conservationArea = ca;
	}
	
	/**
	 * Get the profile associated with the entity
	 * @return
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="profile_uuid", referencedColumnName="uuid")
	public IntelProfile getProfile(){
		return this.profile;
	}
	
	/**
	 * Sets the profile associated with the entity 
	 * @param ca
	 */
	public void setProfile(IntelProfile profile){
		this.profile = profile;
	}

	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	@Column(name="date_created")
	public LocalDateTime getDateCreated() {
		return this.dateCreated;
	}
	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(LocalDateTime dateCreated) {
		this.dateCreated = dateCreated;
	}


	/**
	 * Set the date_modified.
	 * 
	 * @param dateModified
	 *            date_modified
	 */
	public void setDateModified(LocalDateTime dateModified) {
		this.dateModified = dateModified;
	}

	/**
	 * Get the date_modified.
	 * 
	 * @return date_modified
	 */
	@Column(name="date_modified")
	public LocalDateTime getDateModified() {
		return this.dateModified;
	}

	/**
	 * Get the created_by.
	 * 
	 * @return created_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="created_by", referencedColumnName="uuid")
	public Employee getCreatedBy() {
		return this.createdBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}
	
	/**
	 * Get the last modified by.
	 * 
	 * @return last_modified_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="last_modified_by", referencedColumnName="uuid")
	public Employee getLastModifiedBy() {
		return this.lastModifiedBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setLastModifiedBy(Employee lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	/**
	 * Get the primary_attachment_uuid.
	 * 
	 * @return primary_attachment_uuid
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="primary_attachment_uuid", referencedColumnName="uuid")
	public IntelAttachment getPrimaryAttachment() {
		return this.primaryAttachment;
	}
	
	/**
	 * Set the primary_attachment_uuid.
	 * 
	 * @param primaryAttachmentUuid
	 *            primary_attachment_uuid
	 */
	public void setPrimaryAttachment(IntelAttachment attachment) {
		this.primaryAttachment = attachment;
	}
	
	
	/**
	 * Get the i_entity_type.
	 * 
	 * @return i_entity_type
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="entity_type_uuid", referencedColumnName="uuid")
	public IntelEntityType getEntityType() {
		return this.entityType;
	}
	
	/**
	 * Set the i_entity_type.
	 * 
	 * @param entityTypeIEntityType
	 *            i_entity_type
	 */
	public void setEntityType(IntelEntityType entityType) {
		this.entityType = entityType;
	}


	/**
	 * Get the set of the i_entity_relationship.
	 * 
	 * @return The set of i_entity_relationship
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.entity", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityAttributeValue> getAttributes() {
		return this.entityAttributes;
	}
	
	/**
	 * Set the set of the i_entity_relationship.
	 * 
	 * @param iEntityRelationshipSet
	 *            The set of i_entity_relationship
	 */
	public void setAttributes(List<IntelEntityAttributeValue> entityAttributes) {
		this.entityAttributes = entityAttributes;
	}

	/**
	 * Get the set of the i_entity_attachment.
	 * 
	 * @return The set of i_entity_attachment
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.entity", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityAttachment> getEntityAttachments() {
		return this.entityAttachments;
	}

	/**
	 * Set the set of the i_entity_attachment.
	 * 
	 * @param iEntityAttachmentSet
	 *            The set of i_entity_attachment
	 */
	public void setEntityAttachments(List<IntelEntityAttachment> entityAttachments) {
		this.entityAttachments = entityAttachments;
	}


	/**
	 * Get the set of the i_entity_record.
	 * 
	 * @return The set of i_entity_record
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.entity", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityRecord> getIntelligenceRecords() {
		return this.intelligenceRecords;
	}
	
	/**
	 * Set the set of the i_entity_record.
	 * 
	 * @param iEntityRecordSet
	 *            The set of i_entity_record
	 */
	public void setIntelligenceRecords(List<IntelEntityRecord> records) {
		this.intelligenceRecords = records;
	}
	

	/**
	 * Get the set of the i_entity_location.
	 * 
	 * @return The set of i_entity_location
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.entity", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityLocation> getLocations() {
		return this.entityLocations;
	}
	
	/**
	 * Set the set of the i_entity_location.
	 * 
	 * @param iEntityLocationSet
	 *            The set of i_entity_location
	 */
	
	public void setLocations(List<IntelEntityLocation> entityLocations) {
		this.entityLocations = entityLocations;
	}
	
	/**
	 * Scratchpad associated with entity
	 * @return
	 */
	@Column(name="comment")
	public String getComment(){
		return this.comment;
	}
	
	/**
	 * scratchpad associated with eneity
	 * @param comment
	 */
	public void setComment(String comment){
		this.comment = comment;
	}
	
	 
	/**
	 * The object in the data model
	 * that represents this entity.
	 * 
	 * @return
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="dm_list_item_uuid", referencedColumnName="uuid")
	public AttributeListItem getDmAttributeListItem() {
		return listItem;
	}

	public void setDmAttributeListItem(AttributeListItem listItem) {
		this.listItem = listItem;
	}
	
	/**
	 * Gets the label for the default locale
	 * @param l
	 * @return
	 */
	@Transient
	public String getIdAttributeAsText(){
		return getIdAttributeAsText( null);
	}
	
	/**
	 * Gets the label for the given locale. If locale is null uses the default locale.
	 * @param l
	 * @return
	 */
	@Transient
	public String getIdAttributeAsText(Locale l){
		if (l == null) l = Locale.getDefault();
		for (IntelEntityAttributeValue v : getAttributes()){
			if (v.getAttribute().equals(getEntityType().getIdAttribute())){
				
				Object value = v.getAttributeValue();
				IntelAttribute attribute = v.getAttribute();
				if (value == null) return ""; //$NON-NLS-1$
				if (value instanceof String){
					return (String) value;
				}else if (value instanceof Number){
					if (attribute.getType() == AttributeType.BOOLEAN){
						if (((Number)value).doubleValue() >= 0.5){
							return SmartContext.INSTANCE.getClass(IIntelligenceLabelProvider.class).getLabel(Boolean.TRUE, l);
						}else{
							return SmartContext.INSTANCE.getClass(IIntelligenceLabelProvider.class).getLabel(Boolean.FALSE, l);
						}
					}
					return ((Number)value).toString();
				}else if (value instanceof LocalDate){
					return DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM).format((LocalDate)value);
				}else if (value instanceof NamedItem){
					return ((NamedItem) value).getName();
				}else if (value instanceof Employee) {
					return SmartContext.INSTANCE.getClass(ICoreLabelProvider.class).getEmployeeShortLabel((Employee)value, l);
				}else{
					return value.toString();
				}
			}
		}
		return ""; //$NON-NLS-1$
	}
	
	@Transient
	public IntelEntityAttributeValue findAttributeValue(IntelAttribute attribute){
		for (IntelEntityAttributeValue v : getAttributes()){
			if (v.getAttribute().equals(attribute)){
				return v;
			}
		}
		return null;
	}
	
	/**
	 * 
	 * @param session
	 * @return true if data model modified false otherwise
	 */
	@Transient
	public boolean createDataModelItem(Session session) {
		if (getEntityType().getDmAttribute() == null) return false;
		
		Attribute dmAttribute = session.get(Attribute.class, getEntityType().getDmAttribute().getUuid());
		//make a new list item
		AttributeListItem ali = new AttributeListItem();
		ali.setAttribute(dmAttribute);
		ali.setIsActive(true);
		ali.setKeyId(NamedKeyItem.generateKey(getIdAttributeAsText(), dmAttribute.getAttributeList()));
		ali.updateName(getConservationArea().getDefaultLanguage(), getIdAttributeAsText());
		dmAttribute.getAttributeList().add(ali);
		setDmAttributeListItem(ali);
		updateActiveValue();
		return true;
	}
	
	/**
	 * 
	 * @return true if value changed, false otherwise
	 */
	@Transient
	public boolean updateActiveValue()  {
		if (getDmAttributeListItem() == null) return false;
		
		boolean defaultActive = true;
		
		boolean current = getDmAttributeListItem().getIsActive();
		
		if (getEntityType().getActiveFilter() == null || getEntityType().getActiveFilter().isBlank()) {		
			getDmAttributeListItem().setIsActive(defaultActive);
			return current != defaultActive;
		}
		
		String[] parts = getEntityType().getActiveFilter().split("\\|"); //$NON-NLS-1$
		
		
		boolean result = true;
		boolean isnot = false;
		Operator lastOp = null;
		for (String x : parts) {
			if (x.equals(Operator.NOT.getKey())) {
				isnot = true;
			}else if (x.equals(Operator.AND.getKey())) {
				lastOp = Operator.AND;
			}else if (x.equals(Operator.OR.getKey())) {
				lastOp = Operator.OR;
			}else {
				String[] ex = x.split(" "); //$NON-NLS-1$
				String[] bits = ex[0].split(":"); //$NON-NLS-1$
				
				if (!bits[0].equals(AdvancedEntitySearch.ATTRIBUTE_KEY)) throw new RuntimeException("Cannot parse active filter"); //$NON-NLS-1$
				
				AttributeType type = AttributeType.parse(bits[1]);
				
				String akey = bits[2];
				IntelEntityAttributeValue value = null;
				for (IntelEntityAttributeValue av : getAttributes()) {
					if (av.getAttribute().getKeyId().equalsIgnoreCase(akey)) {
						value = av;
						break;
					}
				}
				
				if (value == null) {
					getDmAttributeListItem().setIsActive(defaultActive);
					return current != defaultActive;
				}
				
				boolean match = false;
				if (type == AttributeType.BOOLEAN) {
					match = value.getNumberValue() >= 0.5;
					
				}else if (type == AttributeType.DATE) {
					Operator op = Operator.parse(ex[1]);
					if (op != Operator.BETWEEN && op != Operator.NOT_BETWEEN) {
						getDmAttributeListItem().setIsActive(defaultActive);
						return current != defaultActive;
					}
					try {
						LocalDate d1 = LocalDate.parse(ex[2], DateTimeFormatter.ofPattern(IQueryFilter.DATE_FORMAT_STR));
						LocalDate d2 = LocalDate.parse(ex[4], DateTimeFormatter.ofPattern(IQueryFilter.DATE_FORMAT_STR));
						
						if (op == Operator.BETWEEN || op == Operator.NOT_BETWEEN) {
							match = (value.getDateValue().isEqual(d1) || value.getDateValue().isAfter(d1)) &&
									( value.getDateValue().isEqual(d2) || value.getDateValue().isBefore(d2));
						}
						if (op == Operator.NOT_BETWEEN) {
							match = !match;
						}
					}catch (Exception ex2) {
						ex2.printStackTrace();
						getDmAttributeListItem().setIsActive(defaultActive);
						return current != defaultActive;
					}
				}else if (type == AttributeType.LIST) {
					match = value.getAttributeListItem().getKeyId().equalsIgnoreCase(ex[2]);
					
				}else if (type == AttributeType.NUMERIC) {
					
					Operator op = Operator.parse(ex[1]);
					Double d = Double.parseDouble(ex[2]);
					
					if (op == Operator.EQUALS) {
						match = value.getNumberValue().doubleValue() == d; 
					}else if (op == Operator.LESSTHAN) {
						match = value.getNumberValue() < d;
					}else if (op == Operator.LESSTHANEQUALS) {
						match = value.getNumberValue() <= d;
					}else if (op == Operator.GREATERTHAN) {
						match = value.getNumberValue() > d;
					}else if (op == Operator.GREATERTHANEQUALS) {
						match = value.getNumberValue() >= d;
					}else if (op == Operator.NOTEQUALS) {
						match = value.getNumberValue().doubleValue() != d;
					}else {
						getDmAttributeListItem().setIsActive(defaultActive);
						return current != defaultActive;
					}
					
					
				}else if (type == AttributeType.TEXT) {
					Operator op = Operator.parse(ex[1]);
					String text = SharedUtils.stripQuotes(ex[2]);
					if (op == Operator.STR_EQUALS) {
						match = value.getStringValue().equalsIgnoreCase(text);
					}else if (op == Operator.STR_CONTAINS) {
						match = value.getStringValue().contains(text);
					}else if (op == Operator.STR_NOTCONTAINS) {
						match = !value.getStringValue().contains(text);
					}else {
						getDmAttributeListItem().setIsActive(defaultActive);
						return current != defaultActive;
					}					
				}
				if (isnot) match = !match;
				isnot = false;
				
				if (lastOp != null) {
					if (lastOp == Operator.AND) {
						result = result && match;
					}else if (lastOp == Operator.OR) {
						result = result || match;
					}else {
						getDmAttributeListItem().setIsActive(defaultActive);
						return current != defaultActive;
					}
				}else {
					result = match;
				}
				lastOp = null;	
			}	
		}
		getDmAttributeListItem().setIsActive(result);
		return current != result;
	}
	
	
	
}
