package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;


/**
 * Model class of i_entity_record.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_record")
public class IntelEntityRecord {

	private IEntityRecordPk id = new IEntityRecordPk();
	
	/**
	 * Constructor.
	 */
	public IntelEntityRecord() {
	}

	@EmbeddedId
	public IEntityRecordPk getId(){
		return this.id;
	}
	public void setId(IEntityRecordPk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntity getEntity() {
		return id.getEntity();
	}

	public void setEntity(IntelEntity entity) {
		id.setEntity(entity);
	}
	
	@Transient
	public IntelRecord getRecord() {
		return id.getRecord();
	}

	public void setRecord(IntelRecord record) {
		id.setRecord(record);
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityRecord){
			return this.id.equals(((IntelEntityRecord)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityRecordPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntity entity;
		private IntelRecord record;

		public IEntityRecordPk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_uuid")
		public IntelEntity getEntity() {
			return entity;
		}

		public void setEntity(IntelEntity entity) {
			this.entity = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="record_uuid")
		public IntelRecord getRecord() {
			return record;
		}

		public void setRecord(IntelRecord record) {
			this.record = record;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityRecordPk)){
				return false;
			}
			IEntityRecordPk p = (IEntityRecordPk)key;
			
			if (p.entity == null || this.entity == null ||
				p.record == null || this.record == null ){
				
				if (p.entity == null && this.entity == null && 
					p.record == null && this.record == null){
						return true;
				}
				return false;
			}
			
			return p.entity.equals(this.entity) &&
					p.record.equals(this.record);
		}
		
		@Override
		public int hashCode() {
		    int code = 0;
		    if (entity != null) {code += entity.hashCode();}
		    code *= 31;
		    if (record != null) {code += record.hashCode(); }
		    return code;
		}
	}
}
