package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_working_set_record.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_working_set_record")
public class IntelWorkingSetRecord {

	private IWorkingSetRecordPk id = new IWorkingSetRecordPk();	
	
	public IntelWorkingSetRecord(){
		
	}
	
	@EmbeddedId
	public IWorkingSetRecordPk getId(){
		return this.id;
	}
	public void setId(IWorkingSetRecordPk id){
		this.id = id;
	}
	
	@Transient
	public IntelRecord getRecord() {
		return id.getRecord();
	}

	public void setRecord(IntelRecord record) {
		id.setRecord(record);
	}
	
	@Transient
	public IntelWorkingSet getWorkingSet() {
		return id.getWorkingSet();
	}

	public void setWorkingSet(IntelWorkingSet workingSet) {
		id.setWorkingSet(workingSet);
	}
	

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelWorkingSetRecord){
			return this.id.equals(((IntelWorkingSetRecord)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IWorkingSetRecordPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelRecord record;
		private IntelWorkingSet workingSet;
		

		public IWorkingSetRecordPk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="record_uuid")
		public IntelRecord getRecord() {
			return record;
		}

		public void setRecord(IntelRecord record ) {
			this.record = record;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="working_set_uuid")
		public IntelWorkingSet getWorkingSet() {
			return workingSet;
		}

		public void setWorkingSet(IntelWorkingSet workingSet) {
			this.workingSet = workingSet;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IWorkingSetRecordPk)){
				return false;
			}
			IWorkingSetRecordPk p = (IWorkingSetRecordPk)key;
			
			if (p.record == null || this.record == null ||
				p.workingSet == null || this.workingSet == null ){
				
				if (p.record == null && this.record == null && 
					p.workingSet == null && this.workingSet == null){
						return true;
				}
				return false;
			}
			
			return p.record.equals(this.record) &&
					p.workingSet.equals(this.workingSet);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (record != null) {code += record.hashCode();}
		    code *= 31;
		    if (workingSet != null) {code += workingSet.hashCode(); }
		    return code;
		  }
	}
}