package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_entity_type_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_type_attribute")
public class IntelEntityTypeAttribute {

	private IEntityTypeAttributePk id = new IEntityTypeAttributePk();	
	
	public IntelEntityTypeAttribute(){		
	}
	
	@EmbeddedId
	public IEntityTypeAttributePk getId(){
		return this.id;
	}
	public void setId(IEntityTypeAttributePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntityType getEntityType() {
		return id.getEntityType();
	}

	public void setEntityType(IntelEntityType entity) {
		id.setEntityType(entity);
	}
	
	@Transient
	public IntelAttribute getAttribute() {
		return id.getAttribute();
	}

	public void setAttribute(IntelAttribute attachment) {
		id.setAttribute(attachment);
	}
	

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityTypeAttribute){
			return this.id.equals(((IntelEntityTypeAttribute)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityTypeAttributePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntityType entityType;
		private IntelAttribute attribute;
		

		public IEntityTypeAttributePk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_type_uuid")
		public IntelEntityType getEntityType() {
			return entityType;
		}

		public void setEntityType(IntelEntityType entityType) {
			this.entityType = entityType;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityTypeAttributePk)){
				return false;
			}
			IEntityTypeAttributePk p = (IEntityTypeAttributePk)key;
			
			if (p.entityType == null || this.entityType == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.entityType == null && this.entityType == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.entityType.equals(this.entityType) &&
					p.attribute.equals(this.attribute);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (entityType != null) {code += entityType.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}

}