/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.List;

import javax.imageio.ImageIO;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_relationship_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_relationship_type")
public class IntelRelationshipType extends NamedKeyItem {

	private ConservationArea ca;
	private byte[] icon;
	private IntelRelationshipGroup group;

	private IntelEntityType srcType;
	private IntelEntityType targetType;
	
	private List<IntelRelationshipTypeAttribute> attributes;

	
	/**
	 * Constructor.
	 */
	public IntelRelationshipType() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}

	/**
	 * Get the icon.
	 * 
	 * @return icon
	 */
	@Column(name="icon")
	@Lob
	public byte[] getIcon() {
		return this.icon;
	}

	/**
	 * Set the icon.
	 * 
	 * @param icon
	 *            icon
	 */
	public void setIcon(byte[] icon) {
		this.icon = icon;
	}

	@Transient
	public BufferedImage getIconAsImage() throws Exception{
		if (getIcon() == null) return null;
		try(ByteArrayInputStream in = new ByteArrayInputStream(getIcon())){
			return ImageIO.read(in);
		}
	}
	
	/**
	 * Get the i_relationship_group.
	 * 
	 * @return i_relationship_group
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="relationship_group_uuid", referencedColumnName="uuid")
	public IntelRelationshipGroup getRelationshipGroup() {
		return this.group;
	}
	/**
	 * Set the i_relationship_group.
	 * 
	 * @param relationshipGroupIRelationshipGroup
	 *            i_relationship_group
	 */
	public void setRelationshipGroup(IntelRelationshipGroup group) {
		this.group = group;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="src_entity_type", referencedColumnName="uuid")
	public IntelEntityType getSourceEntityType(){
		return this.srcType;
	}
	
	public void setSourceEntityType(IntelEntityType srcType){
		this.srcType = srcType;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="target_entity_type", referencedColumnName="uuid")
	public IntelEntityType getTargetEntityType(){
		return this.targetType;
	}
	
	public void setTargetEntityType(IntelEntityType targetType){
		this.targetType = targetType;
	}

	
	/**
	 * Set the set of the i_relationship_attribute.
	 * 
	 * @param iRelationshipAttributeSet
	 *            The set of i_relationship_attribute
	 */
	@OneToMany(fetch = FetchType.LAZY, cascade = {CascadeType.ALL},mappedBy="id.relationshipType", orphanRemoval = true)
	@OrderBy("seq_order asc")
	public List<IntelRelationshipTypeAttribute> getAttributes() {
		return this.attributes;
	}
	
	/**
	 * Set the set of the i_relationship_attribute.
	 * 
	 * @param iRelationshipAttributeSet
	 *            The set of i_relationship_attribute
	 */
	public void setAttributes(List<IntelRelationshipTypeAttribute> attributes) {
		this.attributes = attributes;
	}


}
