/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.util.List;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.ca.UuidItem;

/**
 * Model class of i_entity_relationship.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_relationship")
public class IntelEntityRelationship extends UuidItem{

	public enum Source{
		ENTITY,
		RECORD
	}
	private IntelEntity srcEntity;
	private IntelEntity targetEntity;
	
	private IntelRelationshipType relationshipType;

	private List<IntelEntityRelationshipAttributeValue> attributes;

	//source of relationship
	private Source source;
	private UUID sourceId;
	private Object sourceObject;	//transient and must be loaded by user if expect to use
	
	/**
	 * Constructor.
	 */
	public IntelEntityRelationship() {
	}

	/**
	 * Get the source entity object.
	 * 
	 * @return source entity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="src_entity_uuid", referencedColumnName="uuid")
	public IntelEntity getSourceEntity() {
		return this.srcEntity;
	}
	
	/**
	 * Set the source entity object
	 * 
	 * @param srcEntity source entity
	 */
	public void setSourceEntity(IntelEntity srcEntity) {
		this.srcEntity = srcEntity;
	}
	
	/**
	 * Get the target entity object.
	 * 
	 * @return target entity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="target_entity_uuid", referencedColumnName="uuid")
	public IntelEntity getTargetEntity() {
		return this.targetEntity;
	}
	
	/**
	 * Set the garget entity object
	 * 
	 * @param targetEntity target entity
	 */
	public void setTargetEntity(IntelEntity targetEntity) {
		this.targetEntity = targetEntity;
	}
	

	/**
	 * Get the i_relationship_type.
	 * 
	 * @return i_relationship_type
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="relationship_type_uuid", referencedColumnName="uuid")
	public IntelRelationshipType getRelationshipType() {
		return this.relationshipType;
	}
	
	/**
	 * Set the i_relationship_type.
	 * 
	 * @param relationshipTypeIRelationshipType
	 *            i_relationship_type
	 */
	public void setRelationshipType(IntelRelationshipType type) {
		this.relationshipType = type;
	}


	/**
	 * Get the set of the i_entity_relationship_attribute.
	 * 
	 * @return The set of i_entity_relationship_attribute
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy="id.relationship", orphanRemoval = true, cascade={CascadeType.ALL})
	public List<IntelEntityRelationshipAttributeValue> getAttributes() {
		return this.attributes;
	}


	/**
	 * Set the set of the i_entity_relationship_attribute.
	 * 
	 * @param iEntityRelationshipAttributeSet
	 *            The set of i_entity_relationship_attribute
	 */
	public void setAttributes(List<IntelEntityRelationshipAttributeValue> attributes) {
		this.attributes = attributes;
	}

	/**
	 * Get the relationship source
	 * @return
	 */
	@Column(name="source")
	@Enumerated(EnumType.STRING)
	public Source getSource(){
		return this.source;
	}
	
	/**
	 * Sets the relationship srouce
	 * @param source
	 */
	public void setSource(Source source){
		this.source = source;
	}
	
	/**
	 * Get the relationship source identifier; if applicable
	 * @return
	 */
	@Column(name="source_uuid")
	public UUID getSourceId(){
		return this.sourceId;
	}
	
	/**
	 * Sets the relationship srouce
	 * @param source
	 */
	public void setSourceId(UUID sourceId){
		this.sourceId = sourceId;
	}
	
	/**
	 * Source object; transient and must be set by user
	 * @param source
	 */
	@Transient
	public void setSourceObject(Object source){
		this.sourceObject = source;
	}
	@Transient
	public Object getSourceObject(){
		return this.sourceObject;
	}
	
	/**
	 * Find the relationship attribute value for the given attribute
	 * @param attribute
	 * @return
	 */
	@Transient
	public IntelEntityRelationshipAttributeValue findAttributeValue(IntelAttribute attribute){
		for (IntelEntityRelationshipAttributeValue v : getAttributes()){
			if (v.getAttribute().equals(attribute)){
				return v;
			}
		}
		return null;
	}
}
