/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_entity_type_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_type_attribute")
public class IntelEntityTypeAttribute {

	private IEntityTypeAttributePk id = new IEntityTypeAttributePk();	
	
	private int order;
	
	public IntelEntityTypeAttribute(){		
	}
	
	@EmbeddedId
	public IEntityTypeAttributePk getId(){
		return this.id;
	}
	public void setId(IEntityTypeAttributePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntityType getEntityType() {
		return id.getEntityType();
	}

	public void setEntityType(IntelEntityType entity) {
		id.setEntityType(entity);
	}
	
	@Transient
	public IntelAttribute getAttribute() {
		return id.getAttribute();
	}

	public void setAttribute(IntelAttribute attribute) {
		id.setAttribute(attribute);
	}
	

	@Column(name="seq_order")
	public int getOrder(){
		return this.order;
	}
	
	public void setOrder(int order){
		this.order = order;
	}
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityTypeAttribute){
			return this.id.equals(((IntelEntityTypeAttribute)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityTypeAttributePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntityType entityType;
		private IntelAttribute attribute;
		

		public IEntityTypeAttributePk(){
			
		}
		
		@ManyToOne
		@JoinColumn(name="entity_type_uuid")
		public IntelEntityType getEntityType() {
			return entityType;
		}

		public void setEntityType(IntelEntityType entityType) {
			this.entityType = entityType;
		}
		
		@ManyToOne
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityTypeAttributePk)){
				return false;
			}
			IEntityTypeAttributePk p = (IEntityTypeAttributePk)key;
			
			if (p.entityType == null || this.entityType == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.entityType == null && this.entityType == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.entityType.equals(this.entityType) &&
					p.attribute.equals(this.attribute);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (entityType != null) {code += entityType.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}

}