/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_entity_relationship_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_relationship_attribute_value")
public class IntelEntityRelationshipAttributeValue extends IntelValueItem{

	private IEntityRelationshipAttributeValuePk id = new IEntityRelationshipAttributeValuePk();
	

	/**
	 * Constructor.
	 */
	public IntelEntityRelationshipAttributeValue() {
	}

	@EmbeddedId
	public IEntityRelationshipAttributeValuePk getId(){
		return this.id;
	}
	public void setId(IEntityRelationshipAttributeValuePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntityRelationship getRelationship(){
		return id.getRelationship();
	}
	public void setRelationship(IntelEntityRelationship entity){
		id.setRelationship(entity);
	}
	
	@Override
	@Transient
	public IntelAttribute getAttribute(){
		return id.getAttribute();
	}
	
	public void setAttribute(IntelAttribute attribute){
		id.setAttribute(attribute);
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityRelationshipAttributeValue){
			return this.id.equals(((IntelEntityRelationshipAttributeValue)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityRelationshipAttributeValuePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntityRelationship relationship;
		private IntelAttribute attribute;
		
		public IEntityRelationshipAttributeValuePk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_relationship_uuid")
		public IntelEntityRelationship getRelationship() {
			return relationship;
		}

		public void setRelationship(IntelEntityRelationship relationship) {
			this.relationship = relationship;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (this == key) return true;
			if (key == null) return false;
			if (getClass() != key.getClass()) return false;
			IEntityRelationshipAttributeValuePk p = (IEntityRelationshipAttributeValuePk)key;
			return Objects.equals(relationship, p.relationship) && Objects.equals(attribute, p.attribute);
		}
		
		@Override
		public int hashCode() {
			return Objects.hash(relationship, attribute);
		  }
	}
}