package org.wcs.smart.i2.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_entity_search.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_search")
public class IntelEntitySearch extends NamedKeyItem {

	/** conservation_area. */
	private ConservationArea ca;
	private String searchString;
	
	/**
	 * Constructor.
	 */
	public IntelEntitySearch() {
	}

	/**
	 * Set the search_string.
	 * 
	 * @param searchString
	 *            search_string
	 */
	@Column(name="search_string")
	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}

	/**
	 * Get the search_string.
	 * 
	 * @return search_string
	 */
	public String getSearchString() {
		return this.searchString;
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.ca = ca;
	}
	
}
