package org.wcs.smart.i2.model;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Employee;
import org.wcs.smart.ca.UuidItem;

/**
 * Model class of i_record.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_record")
public class IntelRecord extends UuidItem {

	private enum Status{
			NEW,
			PROCESSING,
			COMPLETE
	};
	
	private ConservationArea ca;
	

	private Date dateCreated;
	private Date dateModified;

	private Employee createdBy;
	private Employee lastModifiedBy;

	private Status status;

	private String title;
	private String description;

	private Set<IntelEntityRecord> entities;
	private Set<IntelLocation> locations;
	private Set<IntelRecordAttachment> attachments;

	/**
	 * Constructor.
	 */
	public IntelRecord() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.ca;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param caConservationArea
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea caConservationArea) {
		this.ca = caConservationArea;
	}
	
	/**
	 * Get the date_created.
	 * 
	 * @return date_created
	 */
	@Column(name="date_created")
	public Date getDateCreated() {
		return this.dateCreated;
	}
	/**
	 * Set the date_created.
	 * 
	 * @param dateCreated
	 *            date_created
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}


	/**
	 * Set the date_modified.
	 * 
	 * @param dateModified
	 *            date_modified
	 */
	@Column(name="date_modified")
	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	/**
	 * Get the date_modified.
	 * 
	 * @return date_modified
	 */
	public Date getDateModified() {
		return this.dateModified;
	}

	/**
	 * Get the created_by.
	 * 
	 * @return created_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="created_by", referencedColumnName="uuid")
	public Employee getCreatedBy() {
		return this.createdBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}
	
	/**
	 * Get the last modified by.
	 * 
	 * @return last_modified_by
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="last_modified_by", referencedColumnName="uuid")
	public Employee getLastModifiedBy() {
		return this.lastModifiedBy;
	}
	
	/**
	 * Set the created_by.
	 * 
	 * @param createdBy
	 *            created_by
	 */
	public void setLastModifiedBy(Employee lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	
	/**
	 * Get the type.
	 * 
	 * @return type
	 */
	@Enumerated(EnumType.STRING)
	@Column(name="status")
	public Status getStatus() {
		return this.status;
	}
	
	/**
	 * Set the type.
	 * 
	 * @param type
	 *            type
	 */
	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name="title")
	public String getTitle(){
		return this.title;
	}
	public void setTitle(String title){
		this.title = title;
	}
	
	
	@Column(name="description")
	public String getDescription(){
		return this.description;
	}
	public void setDescription(String description){
		this.description = description;
	}
	
	@OneToMany
	@JoinColumn(name="record_uuid", referencedColumnName="uuid")
	public Set<IntelEntityRecord> getEntities(){
		return this.entities;
	}
	public void setEntities(Set<IntelEntityRecord> entities){
		this.entities = entities;
	}
	
	@OneToMany
	@JoinColumn(name="record_uuid", referencedColumnName="uuid")
	public Set<IntelRecordAttachment> getAttachments(){
		return this.attachments;
	}
	public void setAttachments(Set<IntelRecordAttachment> attachments){
		this.attachments = attachments;
	}
	
	
	@OneToMany
	@JoinColumn(name="location_uuid", referencedColumnName="uuid")
	public Set<IntelLocation> getLocations(){
		return this.locations;
	}
	public void setLocations(Set<IntelLocation> locations){
		this.locations = locations;
	}
}
