/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.i2.model.IntelAttribute.IAttributeType;

/**
 * Model class of i_entity_relationship_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_relationship_attribute_value")
public class IntelEntityRelationshipAttributeValue {

	private IEntityRelationshipAttributeValuePk id = new IEntityRelationshipAttributeValuePk();
	
	private String stringValue;
	private Double doubleValue;
	private IntelAttributeListItem listItem;

	/**
	 * Constructor.
	 */
	public IntelEntityRelationshipAttributeValue() {
	}

	@EmbeddedId
	public IEntityRelationshipAttributeValuePk getId(){
		return this.id;
	}
	public void setId(IEntityRelationshipAttributeValuePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntityRelationship getRelationship(){
		return id.getRelationship();
	}
	public void setRelationship(IntelEntityRelationship entity){
		id.setRelationship(entity);
	}
	
	@Transient
	public IntelAttribute getAttribute(){
		return id.getAttribute();
	}
	
	public void setAttribute(IntelAttribute attribute){
		id.setAttribute(attribute);
	}
	
	@ManyToOne(fetch =FetchType.LAZY)
	@JoinColumn(name="list_item_uuid", referencedColumnName="uuid")
	public IntelAttributeListItem getAttributeListItem(){
		return this.listItem;
	}
	public void setAttributeListItem(IntelAttributeListItem listItem){
		this.listItem = listItem;
	}
		
	@Column(name="string_value")
	public String getStringValue(){
		return this.stringValue;
	}
	public void setStringValue(String stringValue){
		this.stringValue = stringValue;
	}
	
	@Column(name="double_value")
	public Double getNumberValue(){
		return this.doubleValue;
	}
	public void setNumberValue(Double doubleValue){
		this.doubleValue = doubleValue;
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityRelationshipAttributeValue){
			return this.id.equals(((IntelEntityRelationshipAttributeValue)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	
	/**
	 * 
	 * @return the value of the observation based
	 * on the attribute type.
	 */
	@Transient
	public Object getAttributeValue(){
		IAttributeType type = getAttribute().getType();
		if (type == IAttributeType.BOOLEAN ||
				type == IAttributeType.NUMERIC){
			return getNumberValue();
		}else if (type == IAttributeType.TEXT){
			return getStringValue();
		}else if (type == IAttributeType.LIST){
			return getAttributeListItem();
		}else if (type == IAttributeType.DATE){
			return getDateValue();
		}
		throw new IllegalStateException("Invalid attribute type"); //$NON-NLS-1$
	}
	
	/**
	 * Date attribute types are stored
	 * as in the string field in the ISO8601 format
	 * of yyyy-mm-dd.  This is a transient
	 * function which converts the string value to 
	 * a date.
	 * 
	 * @return
	 */
	@Transient
	public Date getDateValue(){
		if (getStringValue() == null){
			return null;
		}
		return java.sql.Date.valueOf(getStringValue());
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityRelationshipAttributeValuePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntityRelationship relationship;
		private IntelAttribute attribute;
		
		public IEntityRelationshipAttributeValuePk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="entity_relationship_uuid")
		public IntelEntityRelationship getRelationship() {
			return relationship;
		}

		public void setRelationship(IntelEntityRelationship relationship) {
			this.relationship = relationship;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityRelationshipAttributeValuePk)){
				return false;
			}
			IEntityRelationshipAttributeValuePk p = (IEntityRelationshipAttributeValuePk)key;
			
			if (p.relationship == null || this.relationship == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.relationship == null && this.relationship == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.relationship.equals(this.relationship) &&
					p.attribute.equals(this.attribute);
		}
		
		@Override
		public int hashCode() {
		    int code = 0;
		    if (relationship != null) {code += relationship.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}
}