/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_working_set_query.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_working_set_query")
public class IntelWorkingSetQuery {
	
	private IWorkingSetQueryPk id = new IWorkingSetQueryPk();	
	
	public IntelWorkingSetQuery(){
		
	}
	
	@EmbeddedId
	public IWorkingSetQueryPk getId(){
		return this.id;
	}
	public void setId(IWorkingSetQueryPk id){
		this.id = id;
	}
	
	@Transient
	public IntelRecordQuery getQuery() {
		return id.getQuery();
	}

	public void setQuery(IntelRecordQuery entity) {
		id.setQuery(entity);
	}
	
	@Transient
	public IntelWorkingSet getWorkingSet() {
		return id.getWorkingSet();
	}

	public void setWorkingSet(IntelWorkingSet workingSet) {
		id.setWorkingSet(workingSet);
	}
	

	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelWorkingSetQuery){
			return this.id.equals(((IntelWorkingSetQuery)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IWorkingSetQueryPk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelRecordQuery query;
		private IntelWorkingSet workingSet;
		

		public IWorkingSetQueryPk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="query_uuid")
		public IntelRecordQuery getQuery() {
			return query;
		}

		public void setQuery(IntelRecordQuery query) {
			this.query = query;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="working_set_uuid")
		public IntelWorkingSet getWorkingSet() {
			return workingSet;
		}

		public void setWorkingSet(IntelWorkingSet workingSet) {
			this.workingSet = workingSet;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IWorkingSetQueryPk)){
				return false;
			}
			IWorkingSetQueryPk p = (IWorkingSetQueryPk)key;
			
			if (p.query == null || this.query == null ||
				p.workingSet == null || this.workingSet == null ){
				
				if (p.query == null && this.query == null && 
					p.workingSet == null && this.workingSet == null){
						return true;
				}
				return false;
			}
			
			return p.query.equals(this.query) &&
					p.workingSet.equals(this.workingSet);
		}
		@Override
		public int hashCode() {
		    int code = 0;
		    if (query != null) {code += query.hashCode();}
		    code *= 31;
		    if (workingSet != null) {code += workingSet.hashCode(); }
		    return code;
		  }
	}
}