/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.i2.model;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.i2.query.observation.filter.IQueryFilter.FilterType;
import org.wcs.smart.i2.query.observation.filter.ParsedObservationQuery;
import org.wcs.smart.i2.query.observation.parser.ParseException;
import org.wcs.smart.i2.query.observation.parser.Parser;

/**
 * Model class of i_record_query.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_record_obs_query")
public class IntelRecordObservationQuery extends AbstractIntelQuery {

	public static final String KEY = "I2_OBS_QUERY"; //$NON-NLS-1$
	
	private String style;
	private String columnFilter;

	/**
	 * Constructor.
	 */
	public IntelRecordObservationQuery() {
	}

	@Override
	@Transient
	public String getKeyId() {
		return KEY;
	}
	
	@Override
	@Column(name="style")
	public String getStyle(){
		return this.style;
	}
	public void setStyle(String style){
		this.style = style;
	}

	
	@Column(name="column_filter")
	public String getColumnFilter(){
		return this.columnFilter;
	}
	public void setColumnFilter(String columnFilter){
		this.columnFilter = columnFilter;
	}
	
	
	@Transient
	public static ParsedObservationQuery parseQuery(String queryString) throws ParseException, IOException{
		if (queryString.isEmpty()) return new ParsedObservationQuery(FilterType.OBSERVATION, null);
			
		try(InputStream is = new ByteArrayInputStream(queryString.getBytes())){
			Parser parser = new Parser(is);
			return parser.ParseQuery();
		}
	}
}
