package org.wcs.smart.i2.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Model class of i_entity_relationship_attribute.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_entity_relationship_attribute")
public class IntelEntityRelationshipAttribute {

	private IEntityRelationshipAttributePk id = new IEntityRelationshipAttributePk();
	
	private String stringValue;
	private Double doubleValue;
	private IntelAttributeListItem listItem;

	/**
	 * Constructor.
	 */
	public IntelEntityRelationshipAttribute() {
	}

	@EmbeddedId
	public IEntityRelationshipAttributePk getId(){
		return this.id;
	}
	public void setId(IEntityRelationshipAttributePk id){
		this.id = id;
	}
	
	@Transient
	public IntelEntity getEntity(){
		return id.getEntity();
	}
	public void setEntity(IntelEntity entity){
		id.setEntity(entity);
	}
	
	@Transient
	public IntelAttribute getAttribute(){
		return id.getAttribute();
	}
	
	public void setAttribute(IntelAttribute attribute){
		id.setAttribute(attribute);
	}
	
	@ManyToOne(fetch =FetchType.LAZY)
	@JoinColumn(name="list_item_uuid", referencedColumnName="uuid")
	public IntelAttributeListItem getAttributeListItem(){
		return this.listItem;
	}
	public void setAttributeListItem(IntelAttributeListItem listItem){
		this.listItem = listItem;
	}
		
	@Column(name="string_value")
	public String getStringValue(){
		return this.stringValue;
	}
	public void setStringValue(String stringValue){
		this.stringValue = stringValue;
	}
	
	@Column(name="double_value")
	public Double getNumberValue(){
		return this.doubleValue;
	}
	public void setNumberValue(Double doubleValue){
		this.doubleValue = doubleValue;
	}
	
	/**
	 * @param o
	 * @return
	 */
	@Override
	public boolean equals(Object o){
		if (o instanceof IntelEntityRelationshipAttribute){
			return this.id.equals(((IntelEntityRelationshipAttribute)o).id);
		}
		return false;
	}
	
	/**
	 * @return
	 */
	@Override
	public int hashCode(){
		return id.hashCode();
	}
	
	/**
	 * Primary key object for category attribute association 
	 * 
	 */
	@Embeddable
	private static class IEntityRelationshipAttributePk implements Serializable {
		private static final long serialVersionUID = 1L;
		
		private IntelEntity entity;
		private IntelAttribute attribute;
		
		public IEntityRelationshipAttributePk(){
			
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="category_uuid")
		public IntelEntity getEntity() {
			return entity;
		}

		public void setEntity(IntelEntity entity) {
			this.entity = entity;
		}
		
		@ManyToOne(cascade = {CascadeType.ALL})
		@JoinColumn(name="attribute_uuid")
		public IntelAttribute getAttribute() {
			return attribute;
		}

		public void setAttribute(IntelAttribute attribute) {
			this.attribute = attribute;
		}
		
		@Override
		public boolean equals(Object key) {
			if (! (key instanceof IEntityRelationshipAttributePk)){
				return false;
			}
			IEntityRelationshipAttributePk p = (IEntityRelationshipAttributePk)key;
			
			if (p.entity == null || this.entity == null ||
				p.attribute == null || this.attribute == null ){
				
				if (p.entity == null && this.entity == null && 
					p.attribute == null && this.attribute == null){
						return true;
				}
				return false;
			}
			
			return p.entity.equals(this.entity) &&
					p.attribute.equals(this.attribute);
		}
		
		@Override
		public int hashCode() {
		    int code = 0;
		    if (entity != null) {code += entity.hashCode();}
		    code *= 31;
		    if (attribute != null) {code += attribute.hashCode(); }
		    return code;
		  }
	}
}