package org.wcs.smart.i2.model;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.wcs.smart.ca.NamedKeyItem;

/**
 * Model class of i_relationship_group.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.i_relationship_group")
public class IntelRelationshipGroup extends NamedKeyItem{

	private Set<IntelRelationshipType> types;

	/**
	 * Constructor.
	 */
	public IntelRelationshipGroup() {
	}

	/**
	 * Get the set of the i_relationship_type.
	 * 
	 * @return The set of i_relationship_type
	 */
	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="relationship_group_uuid", referencedColumnName="uuid")
	public Set<IntelRelationshipType> getRelationshipTypes() {
		return this.types;
	}
	
	/**
	 * Set the set of the i_relationship_type.
	 * 
	 * @param iRelationshipTypeSet
	 *            The set of i_relationship_type
	 */
	public void setRelationshipTypes(Set<IntelRelationshipType> types) {
		this.types = types;
	}



}
