source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               OSGI-INF/l10n/bundle.properties,\
               lib/jboss-logging-3.3.2.Final.jar,\
               lib/btf-1.3.jar,\
               lib/jakarta.activation-1.2.1.jar,\
               lib/jakarta.activation-api-1.2.1.jar,\
               lib/jakarta.validation-api-2.0.2.jar,\
               lib/jaxb-runtime-2.3.3-b02.jar,\
               lib/jboss-annotations-api_1.3_spec-2.0.1.Final.jar,\
               lib/microprofile-config-api-1.4.jar,\
               lib/asyncutil-0.1.0.jar,\
               lib/jackson-jaxrs-base-2.11.1.jar,\
               lib/jackson-jaxrs-json-provider-2.11.1.jar,\
               lib/jackson-module-jaxb-annotations-2.11.1.jar,\
               lib/jboss-jaxb-api_2.3_spec-1.0.1.Final.jar,\
               lib/jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar,\
               lib/json-patch-1.13.jar,\
               lib/msg-simple-1.2.jar,\
               lib/reactive-streams-1.0.3.jar,\
               lib/resteasy-client-4.5.8.Final.jar,\
               lib/resteasy-client-api-4.5.8.Final.jar,\
               lib/resteasy-core-4.5.8.Final.jar,\
               lib/resteasy-core-spi-4.5.8.Final.jar,\
               lib/resteasy-jackson2-provider-4.5.8.Final.jar,\
               lib/resteasy-jaxb-provider-4.5.8.Final.jar,\
               lib/smallrye-config-1.6.1.jar,\
               lib/smallrye-config-common-1.6.1.jar,\
               lib/txw2-2.3.3-b02.jar
