source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               OSGI-INF/l10n/bundle.properties,\
               lib/jackson-annotations-2.8.9.jar,\
               lib/jackson-core-2.8.9.jar,\
               lib/jackson-databind-2.8.9.jar,\
               lib/jackson-jaxrs-base-2.8.9.jar,\
               lib/jackson-jaxrs-json-provider-2.8.9.jar,\
               lib/jackson-module-jaxb-annotations-2.8.9.jar,\
               lib/jboss-jaxrs-api_2.0_spec-1.0.1.Beta1.jar,\
               lib/jboss-logging-3.3.0.Final.jar,\
               lib/resteasy-client-3.1.4.Final.jar,\
               lib/resteasy-jackson2-provider-3.1.4.Final.jar,\
               lib/resteasy-jaxrs-3.1.4.Final.jar
