/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.upgrade.v400;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

import org.eclipse.core.runtime.IProgressMonitor;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.hibernate.jdbc.Work;
import org.wcs.smart.SmartPlugIn;
import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.Employee;
import org.wcs.smart.ca.Employee.SmartUserLevel;
import org.wcs.smart.hibernate.DerbyHibernateExtensions;
import org.wcs.smart.hibernate.HibernateManager;
import org.wcs.smart.hibernate.SmartDB.DbUser;
import org.wcs.smart.internal.Messages;
import org.wcs.smart.upgrade.IDatabaseUpgrader;
import org.wcs.smart.util.UuidUtils;

/**
 * Upgrades from database version 330 to 400.
 *
 * @author Emily
 * @author elitvin
 * @since 3.2.0
 */
public class Upgrader330To400 implements IDatabaseUpgrader {
	
	private String dbUrl = null;
	private Exception thrownException = null;
	
	@Override
	public void upgrade(final IProgressMonitor monitor) throws Exception{
		monitor.beginTask(Messages.Upgrader330To400_ProcessMessage,1);
		thrownException = null;
		final Session s = HibernateManager.openSession();
		try{
			s.doWork(new Work() {
				@Override
				public void execute(Connection c) throws SQLException {
					try {
						dbUrl = c.getMetaData().getURL();
						c.setAutoCommit(false);
						upgrade(c, s, monitor);
						c.setAutoCommit(true);
					} catch (final Exception e) {
						thrownException = new Exception(Messages.Upgrader330To400_Error,e);
					}
				}
			});
			
		}finally{
			s.close();
		}
		if (thrownException != null) throw thrownException;
		
		/* do a hard derby upgrade to version 10.12.1.1 */ 
		try{
			//disconnect 
			HibernateManager.endSessionFactory(true);
			//perform hard upgrade
			DriverManager.getConnection(dbUrl + ";create=false;upgrade=true;user=" + DbUser.ADMIN.getUserName() + ";password=" + DbUser.ADMIN.getPassword()); //$NON-NLS-1$ //$NON-NLS-2$ 
			DerbyHibernateExtensions.shutDown(true);
		}catch(Exception ex){
			throw new Exception("Could not perform hard derby upgrade.", ex); //$NON-NLS-1$
		}
		monitor.done();
	}

	private void upgrade(Connection c, Session session, IProgressMonitor monitor) throws Exception {
		@SuppressWarnings("nls")
		String[] sql = new String[]{
			/* aggregations */
			"alter table smart.dm_aggregation_i18n drop constraint dm_aggregation_i18n_fk",
			"alter table smart.DM_ATT_AGG_MAP drop constraint dm_att_agg_map_agg_name_fk",

			"alter table smart.dm_aggregation alter column name set data type varchar(16)",
			"alter table smart.DM_AGGREGATION_I18N alter column name set data type varchar(16)",
			"alter table smart.DM_ATT_AGG_MAP alter column agg_name set data type varchar(16)",
			"ALTER TABLE SMART.DM_AGGREGATION_I18N ADD CONSTRAINT DM_AGGREGATION_I18N_FK FOREIGN KEY (NAME) REFERENCES SMART.DM_AGGREGATION(NAME)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
			"ALTER TABLE SMART.DM_ATT_AGG_MAP ADD CONSTRAINT DM_ATT_AGG_MAP_AGG_NAME_FK FOREIGN KEY (AGG_NAME) REFERENCES SMART.DM_AGGREGATION(NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE",
				
			"insert into smart.dm_aggregation values ('stddev_samp')",
			"insert into smart.dm_aggregation values ('var_samp')",
			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'en', 'standard deviation (samp.)')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'en', 'variance (samp.)')",
				
			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'es', 'Desviación estándar')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'es', 'Varianza')",
				
			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'fr', 'Ecart type')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'fr', 'Variance')",

			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'vi', 'Độ lệch chuẩn')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'vi', 'Phương sai')",

			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'th', 'ส่วนเบี่ยงเบนมาตรฐาน')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'th', 'ค่าความแปรปรวน')",

			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'zh', '标准差')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'zh', '方差')",

			"insert into smart.dm_aggregation_i18n values ('stddev_samp', 'in', 'Standar Deviasi')",
			"insert into smart.dm_aggregation_i18n values ('var_samp', 'in', 'Varians')",		

			/* core db changes */
			"alter table smart.area_geometries drop column pid",
			
			/* unique constraints for connect error checking */
			"alter table smart.PATROL_MANDATE add constraint patrol_mandate_keyid_unq UNIQUE(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.PATROL_TRANSPORT add constraint patrol_transport_keyid_unq UNIQUE(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.TEAM add constraint team_keyid_unq UNIQUE(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.DM_ATTRIBUTE add constraint dm_attribute_keyid_unq UNIQUE(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.DM_ATTRIBUTE_LIST add constraint dm_attribute_list_keyid_unq UNIQUE(attribute_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.DM_CATEGORY add constraint dm_category_keyid_unq UNIQUE(ca_uuid, hkey) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.DM_ATTRIBUTE_TREE add constraint dm_attribute_tree_keyid_unq UNIQUE(attribute_uuid, hkey) DEFERRABLE INITIALLY IMMEDIATE",
			"alter table smart.AREA_GEOMETRIES add constraint area_geom_key_ca_type_unq UNIQUE(keyid, ca_uuid, area_type) DEFERRABLE INITIALLY IMMEDIATE",
			
			/* drop all constraints and make deferrable for SMART connect */
			"ALTER TABLE SMART.AGENCY DROP CONSTRAINT AGENCY_CA_UUID_FK",
			"ALTER TABLE SMART.AREA_GEOMETRIES DROP CONSTRAINT AREA_GEOMETRIES_CA_UUID_FK",
			"ALTER TABLE SMART.CA_PROJECTION DROP CONSTRAINT CA_PROJECTION_CA_UUID_FK",
			"ALTER TABLE SMART.DM_AGGREGATION_I18N DROP CONSTRAINT DM_AGGREGATION_I18N_FK",
			"ALTER TABLE SMART.DM_ATTRIBUTE DROP CONSTRAINT DM_ATTRIBUTE_CA_UUID_FK",
			"ALTER TABLE SMART.DM_ATTRIBUTE_LIST DROP CONSTRAINT DM_ATTRIBUTE_LIST_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.DM_ATTRIBUTE_TREE DROP CONSTRAINT DM_ATTRIBUT_TREE_PARENT_UUID_FK",
			"ALTER TABLE SMART.DM_ATTRIBUTE_TREE DROP CONSTRAINT DM_ATTRIBUT_UUID_FK",
			"ALTER TABLE SMART.DM_ATT_AGG_MAP DROP CONSTRAINT DM_ATT_AGG_MAP_AGG_NAME_FK",
			"ALTER TABLE SMART.DM_ATT_AGG_MAP DROP CONSTRAINT DM_ATT_AGG_MAP_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.DM_CATEGORY DROP CONSTRAINT DM_CATEGORY_CA_UUID_FK",
			"ALTER TABLE SMART.DM_CATEGORY DROP CONSTRAINT DM_CATEGORY_PARENT_CATEGORY_UUID_FK",
			"ALTER TABLE SMART.DM_CAT_ATT_MAP DROP CONSTRAINT DM_CAT_ATT_MAP_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.DM_CAT_ATT_MAP DROP CONSTRAINT DM_CAT_ATT_MAP_CATEGORY_UUID_FK",
			"ALTER TABLE SMART.EMPLOYEE DROP CONSTRAINT EMPLOYEE_AGENCY_UUID_FK",
			"ALTER TABLE SMART.EMPLOYEE DROP CONSTRAINT EMPLOYEE_CA_UUID_FK",
			"ALTER TABLE SMART.EMPLOYEE DROP CONSTRAINT EMPLOYEE_RANK_UUID_FK",
			"ALTER TABLE SMART.I18N_LABEL DROP CONSTRAINT LANGUAGES_CA_UUID_FK",
			"ALTER TABLE SMART.LANGUAGE DROP CONSTRAINT LANGUAGE_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_LEG_MEMBERS DROP CONSTRAINT LEG_MEMBERS_EMPLOYEE_UUID_FK",
			"ALTER TABLE SMART.PATROL_LEG_MEMBERS DROP CONSTRAINT LEG_MEMBERS_PATROL_LEG_UUID_FK",
			"ALTER TABLE SMART.MAP_STYLES DROP CONSTRAINT MAPSTYLE_CA_UUID_FK",
			"ALTER TABLE SMART.OBSERVATION_ATTACHMENT DROP CONSTRAINT OBSERVATION_ATTACHMENT_OBS_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES DROP CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_LIST_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES DROP CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_TREE_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES DROP CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION DROP CONSTRAINT OBSERVATION_CATEGORY_UUID_FK",
			"ALTER TABLE SMART.OBSERVATION_QUERY DROP CONSTRAINT OBSERVATION_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.OBSERVATION_QUERY DROP CONSTRAINT OBSERVATION_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.OBSERVATION_QUERY DROP CONSTRAINT OBSERVATION_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION DROP CONSTRAINT OBSERVATION_WP_UUID_FK",
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY DROP CONSTRAINT OBSOBSERVATION_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY DROP CONSTRAINT OBSWAYPOINT_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES DROP CONSTRAINT OBS_ATTRIBUTE_OBS_UUID_FK",
			"ALTER TABLE SMART.WP_OBSERVATION DROP CONSTRAINT OBS_EMPLOYEE_UUID_FK",
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY DROP CONSTRAINT OBS_GRIDDED_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY DROP CONSTRAINT OBS_GRIDDED_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY DROP CONSTRAINT OBS_GRIDDED_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY DROP CONSTRAINT OBS_OBSERVATION_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY DROP CONSTRAINT OBS_OBSERVATION_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY DROP CONSTRAINT OBS_SUMMARY_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY DROP CONSTRAINT OBS_SUMMARY_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY DROP CONSTRAINT OBS_SUMMARY_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY DROP CONSTRAINT OBS_WAYPOINT_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY DROP CONSTRAINT OBS_WAYPOINT_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.PATROL DROP CONSTRAINT PATROL_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_LEG_DAY DROP CONSTRAINT PATROL_LEG_DAY_LEG_UUID_FK",
			"ALTER TABLE SMART.PATROL_LEG DROP CONSTRAINT PATROL_LEG_PATROL_UUID_FK",
			"ALTER TABLE SMART.PATROL_LEG DROP CONSTRAINT PATROL_LEG_TRANSPORT_UUID_FK",
			"ALTER TABLE SMART.PATROL_MANDATE DROP CONSTRAINT PATROL_MANDATE_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL DROP CONSTRAINT PATROL_MANDATE_UUID_FK",
			"ALTER TABLE SMART.OBSERVATION_OPTIONS DROP CONSTRAINT PATROL_OPTIONS_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_QUERY DROP CONSTRAINT PATROL_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_QUERY DROP CONSTRAINT PATROL_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.PATROL_QUERY DROP CONSTRAINT PATROL_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.PATROL DROP CONSTRAINT PATROL_STATION_UUID_FK",
			"ALTER TABLE SMART.PATROL DROP CONSTRAINT PATROL_TEAM_UUID_FK",
			"ALTER TABLE SMART.PATROL_TRANSPORT DROP CONSTRAINT PATROL_TRANSPORT_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_TYPE DROP CONSTRAINT PATROL_TYPE_CA_UUID_FK",
			"ALTER TABLE SMART.PATROL_WAYPOINT DROP CONSTRAINT PATROL_WAYPOINT_LEG_DAY_UUID_FK",
			"ALTER TABLE SMART.PATROL_WAYPOINT DROP CONSTRAINT PATROL_WAYPOINT_WP_UUID_FK",
			"ALTER TABLE SMART.QUERY_FOLDER DROP CONSTRAINT QUERY_FOLDER_CA_UUID_FK",
			"ALTER TABLE SMART.QUERY_FOLDER DROP CONSTRAINT QUERY_FOLDER_EMPLOYEE_UUID_FK",
			"ALTER TABLE SMART.QUERY_FOLDER DROP CONSTRAINT QUERY_FOLDER_PARENT_UUID_FK",
			"ALTER TABLE SMART.RANK DROP CONSTRAINT RANK_AGENCY_UUID_FK",
			"ALTER TABLE SMART.REPORT DROP CONSTRAINT REPORT_CA_UUID_FK",
			"ALTER TABLE SMART.REPORT DROP CONSTRAINT REPORT_CREATOR_UUID_FK",
			"ALTER TABLE SMART.REPORT_FOLDER DROP CONSTRAINT REPORT_EMPLOYEE_UUID_FK",
			"ALTER TABLE SMART.REPORT_FOLDER DROP CONSTRAINT REPORT_FOLDER_CA_UUID_FK",
			"ALTER TABLE SMART.REPORT_FOLDER DROP CONSTRAINT REPORT_FOLDER_PARENT_UUID_FK",
			"ALTER TABLE SMART.REPORT DROP CONSTRAINT REPORT_FOLDER_UUID_FK",
			"ALTER TABLE SMART.REPORT_QUERY DROP CONSTRAINT REPORT_QUERY_REPORT_UUID_FK",
			"ALTER TABLE SMART.SAVED_MAPS DROP CONSTRAINT SAVED_MAPS_CA_UUID_FK",
			"ALTER TABLE SMART.STATION DROP CONSTRAINT STATION_CA_UUID_FK",
			"ALTER TABLE SMART.SUMMARY_QUERY DROP CONSTRAINT SUMMARY_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.SUMMARY_QUERY DROP CONSTRAINT SUMMARY_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.SUMMARY_QUERY DROP CONSTRAINT SUMMARY_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.TEAM DROP CONSTRAINT TEAM_CA_UUID_FK",
			"ALTER TABLE SMART.TEAM DROP CONSTRAINT TEAM_PATROL_MANDATE_UUID_FK",
			"ALTER TABLE SMART.TRACK DROP CONSTRAINT TRACK_LEG_DAY_UUID_FK",
			"ALTER TABLE SMART.WAYPOINT DROP CONSTRAINT WAYPOINT_CA_UUID_FK",
			"ALTER TABLE SMART.WAYPOINT_QUERY DROP CONSTRAINT WAYPOINT_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.WAYPOINT_QUERY DROP CONSTRAINT WAYPOINT_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.WAYPOINT_QUERY DROP CONSTRAINT WAYPOINT_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.WP_ATTACHMENTS DROP CONSTRAINT WP_ATTACHMENTS_WP_UUID_FK",
			"ALTER TABLE SMART.GRIDDED_QUERY DROP CONSTRAINT GRIDDED_QUERY_CA_UUID_FK",
			"ALTER TABLE SMART.GRIDDED_QUERY DROP CONSTRAINT GRIDDED_QUERY_CREATOR_UUID_FK",
			"ALTER TABLE SMART.GRIDDED_QUERY DROP CONSTRAINT GRIDDED_QUERY_FOLDER_UUID_FK",
			"ALTER TABLE SMART.SCREEN_OPTION DROP CONSTRAINT SCREEN_OPTION_CA_UUID_FK",
			"ALTER TABLE SMART.SCREEN_OPTION_UUID DROP CONSTRAINT SCREEN_OPTION_UUID_OPTION_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE DROP CONSTRAINT CM_ATTRIBUTE_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST DROP CONSTRAINT CM_ATTRIBUTE_LIST_CM_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST DROP CONSTRAINT CM_ATTRIBUTE_LIST_CM_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST DROP CONSTRAINT CM_ATTRIBUTE_LIST_DM_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST DROP CONSTRAINT CM_ATTRIBUTE_LIST_LIST_ELEMENT_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE DROP CONSTRAINT CM_ATTRIBUTE_NODE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_OPTION DROP CONSTRAINT CM_ATTRIBUTE_OPTION_CM_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE DROP CONSTRAINT CM_ATTRIBUTE_TREE_NODE_CM_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE DROP CONSTRAINT CM_ATTRIBUTE_TREE_NODE_CM_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE DROP CONSTRAINT CM_ATTRIBUTE_TREE_NODE_DM_ATTRIBUTE_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE DROP CONSTRAINT CM_ATTRIBUTE_TREE_NODE_PARENT_UUID_FK",
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE DROP CONSTRAINT CM_ATTRIBUTE_TREE_NODE_TREE_NODE_UUID_FK",
			"ALTER TABLE SMART.CM_NODE DROP CONSTRAINT CM_NODE_CATEGORY_UUID_FK",
			"ALTER TABLE SMART.CM_NODE DROP CONSTRAINT CM_NODE_CM_UUID_FK",
			"ALTER TABLE SMART.CONFIGURABLE_MODEL DROP CONSTRAINT CONFIGURABLE_MODEL_CA_UUID_FK",
			
			"ALTER TABLE SMART.AGENCY ADD CONSTRAINT AGENCY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.AREA_GEOMETRIES ADD CONSTRAINT AREA_GEOMETRIES_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CA_PROJECTION ADD CONSTRAINT CA_PROJECTION_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_AGGREGATION_I18N ADD CONSTRAINT DM_AGGREGATION_I18N_FK FOREIGN KEY (NAME) REFERENCES SMART.DM_AGGREGATION(NAME)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATTRIBUTE ADD CONSTRAINT DM_ATTRIBUTE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATTRIBUTE_LIST ADD CONSTRAINT DM_ATTRIBUTE_LIST_ATTRIBUTE_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATTRIBUTE_TREE ADD CONSTRAINT DM_ATTRIBUT_TREE_PARENT_UUID_FK FOREIGN KEY (PARENT_UUID) REFERENCES SMART.DM_ATTRIBUTE_TREE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATTRIBUTE_TREE ADD CONSTRAINT DM_ATTRIBUT_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATT_AGG_MAP ADD CONSTRAINT DM_ATT_AGG_MAP_AGG_NAME_FK FOREIGN KEY (AGG_NAME) REFERENCES SMART.DM_AGGREGATION(NAME)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_ATT_AGG_MAP ADD CONSTRAINT DM_ATT_AGG_MAP_ATTRIBUTE_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_CATEGORY ADD CONSTRAINT DM_CATEGORY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_CATEGORY ADD CONSTRAINT DM_CATEGORY_PARENT_CATEGORY_UUID_FK FOREIGN KEY (PARENT_CATEGORY_UUID) REFERENCES SMART.DM_CATEGORY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_CAT_ATT_MAP ADD CONSTRAINT DM_CAT_ATT_MAP_ATTRIBUTE_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.DM_CAT_ATT_MAP ADD CONSTRAINT DM_CAT_ATT_MAP_CATEGORY_UUID_FK FOREIGN KEY (CATEGORY_UUID) REFERENCES SMART.DM_CATEGORY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.EMPLOYEE ADD CONSTRAINT EMPLOYEE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.EMPLOYEE ADD CONSTRAINT EMPLOYEE_AGENCY_UUID_FK FOREIGN KEY (AGENCY_UUID) REFERENCES SMART.AGENCY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.EMPLOYEE ADD CONSTRAINT EMPLOYEE_RANK_UUID_FK FOREIGN KEY (RANK_UUID) REFERENCES SMART.RANK(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.GRIDDED_QUERY ADD CONSTRAINT GRIDDED_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.GRIDDED_QUERY ADD CONSTRAINT GRIDDED_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.GRIDDED_QUERY ADD CONSTRAINT GRIDDED_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.I18N_LABEL ADD CONSTRAINT LANGUAGES_CA_UUID_FK FOREIGN KEY (LANGUAGE_UUID) REFERENCES SMART.LANGUAGE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.LANGUAGE ADD CONSTRAINT LANGUAGE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.MAP_STYLES ADD CONSTRAINT MAPSTYLE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBSERVATION_ATTACHMENT ADD CONSTRAINT OBSERVATION_ATTACHMENT_OBS_UUID_FK FOREIGN KEY (OBS_UUID) REFERENCES SMART.WP_OBSERVATION(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBSERVATION_OPTIONS ADD CONSTRAINT PATROL_OPTIONS_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBSERVATION_QUERY ADD CONSTRAINT OBSERVATION_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBSERVATION_QUERY ADD CONSTRAINT OBSERVATION_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBSERVATION_QUERY ADD CONSTRAINT OBSERVATION_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY ADD CONSTRAINT OBS_GRIDDED_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY ADD CONSTRAINT OBS_GRIDDED_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_GRIDDED_QUERY ADD CONSTRAINT OBS_GRIDDED_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY ADD CONSTRAINT OBSOBSERVATION_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY ADD CONSTRAINT OBS_OBSERVATION_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_OBSERVATION_QUERY ADD CONSTRAINT OBS_OBSERVATION_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY ADD CONSTRAINT OBS_SUMMARY_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY ADD CONSTRAINT OBS_SUMMARY_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_SUMMARY_QUERY ADD CONSTRAINT OBS_SUMMARY_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY ADD CONSTRAINT OBSWAYPOINT_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY ADD CONSTRAINT OBS_WAYPOINT_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.OBS_WAYPOINT_QUERY ADD CONSTRAINT OBS_WAYPOINT_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL ADD CONSTRAINT PATROL_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL ADD CONSTRAINT PATROL_STATION_UUID_FK FOREIGN KEY (STATION_UUID) REFERENCES SMART.STATION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL ADD CONSTRAINT PATROL_TEAM_UUID_FK FOREIGN KEY (TEAM_UUID) REFERENCES SMART.TEAM(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL ADD CONSTRAINT PATROL_MANDATE_UUID_FK FOREIGN KEY (MANDATE_UUID) REFERENCES SMART.PATROL_MANDATE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_LEG ADD CONSTRAINT PATROL_LEG_PATROL_UUID_FK FOREIGN KEY (PATROL_UUID) REFERENCES SMART.PATROL(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_LEG ADD CONSTRAINT PATROL_LEG_TRANSPORT_UUID_FK FOREIGN KEY (TRANSPORT_UUID) REFERENCES SMART.PATROL_TRANSPORT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_LEG_DAY ADD CONSTRAINT PATROL_LEG_DAY_LEG_UUID_FK FOREIGN KEY (PATROL_LEG_UUID) REFERENCES SMART.PATROL_LEG(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_LEG_MEMBERS ADD CONSTRAINT LEG_MEMBERS_PATROL_LEG_UUID_FK FOREIGN KEY (PATROL_LEG_UUID) REFERENCES SMART.PATROL_LEG(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_LEG_MEMBERS ADD CONSTRAINT LEG_MEMBERS_EMPLOYEE_UUID_FK FOREIGN KEY (EMPLOYEE_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_MANDATE ADD CONSTRAINT PATROL_MANDATE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_QUERY ADD CONSTRAINT PATROL_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_QUERY ADD CONSTRAINT PATROL_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_QUERY ADD CONSTRAINT PATROL_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_TRANSPORT ADD CONSTRAINT PATROL_TRANSPORT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_TYPE ADD CONSTRAINT PATROL_TYPE_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_WAYPOINT ADD CONSTRAINT PATROL_WAYPOINT_LEG_DAY_UUID_FK FOREIGN KEY (LEG_DAY_UUID) REFERENCES SMART.PATROL_LEG_DAY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.PATROL_WAYPOINT ADD CONSTRAINT PATROL_WAYPOINT_WP_UUID_FK FOREIGN KEY (WP_UUID) REFERENCES SMART.WAYPOINT(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.QUERY_FOLDER ADD CONSTRAINT QUERY_FOLDER_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.QUERY_FOLDER ADD CONSTRAINT QUERY_FOLDER_EMPLOYEE_UUID_FK FOREIGN KEY (EMPLOYEE_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.QUERY_FOLDER ADD CONSTRAINT QUERY_FOLDER_PARENT_UUID_FK FOREIGN KEY (PARENT_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.RANK ADD CONSTRAINT RANK_AGENCY_UUID_FK FOREIGN KEY (AGENCY_UUID) REFERENCES SMART.AGENCY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT ADD CONSTRAINT REPORT_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.REPORT_FOLDER(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT ADD CONSTRAINT REPORT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT ADD CONSTRAINT REPORT_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT_FOLDER ADD CONSTRAINT REPORT_FOLDER_PARENT_UUID_FK FOREIGN KEY (PARENT_UUID) REFERENCES SMART.REPORT_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT_FOLDER ADD CONSTRAINT REPORT_FOLDER_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT_FOLDER ADD CONSTRAINT REPORT_EMPLOYEE_UUID_FK FOREIGN KEY (EMPLOYEE_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.REPORT_QUERY ADD CONSTRAINT REPORT_QUERY_REPORT_UUID_FK FOREIGN KEY (REPORT_UUID) REFERENCES SMART.REPORT(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SAVED_MAPS ADD CONSTRAINT SAVED_MAPS_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SCREEN_OPTION ADD CONSTRAINT SCREEN_OPTION_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SCREEN_OPTION_UUID ADD CONSTRAINT SCREEN_OPTION_UUID_OPTION_UUID_FK FOREIGN KEY (OPTION_UUID) REFERENCES SMART.SCREEN_OPTION(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.STATION ADD CONSTRAINT STATION_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SUMMARY_QUERY ADD CONSTRAINT SUMMARY_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SUMMARY_QUERY ADD CONSTRAINT SUMMARY_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.SUMMARY_QUERY ADD CONSTRAINT SUMMARY_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.TEAM ADD CONSTRAINT TEAM_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.TEAM ADD CONSTRAINT TEAM_PATROL_MANDATE_UUID_FK FOREIGN KEY (PATROL_MANDATE_UUID) REFERENCES SMART.PATROL_MANDATE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.TRACK ADD CONSTRAINT TRACK_LEG_DAY_UUID_FK FOREIGN KEY (PATROL_LEG_DAY_UUID) REFERENCES SMART.PATROL_LEG_DAY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WAYPOINT_QUERY ADD CONSTRAINT WAYPOINT_QUERY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WAYPOINT_QUERY ADD CONSTRAINT WAYPOINT_QUERY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WAYPOINT_QUERY ADD CONSTRAINT WAYPOINT_QUERY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_ATTACHMENTS ADD CONSTRAINT WP_ATTACHMENTS_WP_UUID_FK FOREIGN KEY (WP_UUID) REFERENCES SMART.WAYPOINT(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION ADD CONSTRAINT OBSERVATION_WP_UUID_FK FOREIGN KEY (WP_UUID) REFERENCES SMART.WAYPOINT(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION ADD CONSTRAINT OBS_EMPLOYEE_UUID_FK FOREIGN KEY (EMPLOYEE_UUID) REFERENCES SMART.EMPLOYEE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION ADD CONSTRAINT OBSERVATION_CATEGORY_UUID_FK FOREIGN KEY (CATEGORY_UUID) REFERENCES SMART.DM_CATEGORY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES ADD CONSTRAINT OBS_ATTRIBUTE_OBS_UUID_FK FOREIGN KEY (OBSERVATION_UUID) REFERENCES SMART.WP_OBSERVATION(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES ADD CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES ADD CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_LIST_UUID_FK FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.DM_ATTRIBUTE_LIST(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WP_OBSERVATION_ATTRIBUTES ADD CONSTRAINT OBSERVATION_ATTRIBUTE_ATT_TREE_UUID_FK FOREIGN KEY (TREE_NODE_UUID) REFERENCES SMART.DM_ATTRIBUTE_TREE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE ADD CONSTRAINT CM_ATTRIBUTE_NODE_UUID_FK FOREIGN KEY (NODE_UUID) REFERENCES SMART.CM_NODE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE ADD CONSTRAINT CM_ATTRIBUTE_ATTRIBUTE_UUID_FK FOREIGN KEY (ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST ADD CONSTRAINT CM_ATTRIBUTE_LIST_CM_UUID_FK FOREIGN KEY (CM_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST ADD CONSTRAINT CM_ATTRIBUTE_LIST_LIST_ELEMENT_UUID_FK FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.DM_ATTRIBUTE_LIST(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST ADD CONSTRAINT CM_ATTRIBUTE_LIST_CM_ATTRIBUTE_UUID_FK FOREIGN KEY (CM_ATTRIBUTE_UUID) REFERENCES SMART.CM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_LIST ADD CONSTRAINT CM_ATTRIBUTE_LIST_DM_ATTRIBUTE_UUID_FK FOREIGN KEY (DM_ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_OPTION ADD CONSTRAINT CM_ATTRIBUTE_OPTION_CM_ATTRIBUTE_UUID_FK FOREIGN KEY (CM_ATTRIBUTE_UUID) REFERENCES SMART.CM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE ADD CONSTRAINT CM_ATTRIBUTE_TREE_NODE_TREE_NODE_UUID_FK FOREIGN KEY (DM_TREE_NODE_UUID) REFERENCES SMART.DM_ATTRIBUTE_TREE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE ADD CONSTRAINT CM_ATTRIBUTE_TREE_NODE_CM_UUID_FK FOREIGN KEY (CM_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE ADD CONSTRAINT CM_ATTRIBUTE_TREE_NODE_PARENT_UUID_FK FOREIGN KEY (PARENT_UUID) REFERENCES SMART.CM_ATTRIBUTE_TREE_NODE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE ADD CONSTRAINT CM_ATTRIBUTE_TREE_NODE_CM_ATTRIBUTE_UUID_FK FOREIGN KEY (CM_ATTRIBUTE_UUID) REFERENCES SMART.CM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_ATTRIBUTE_TREE_NODE ADD CONSTRAINT CM_ATTRIBUTE_TREE_NODE_DM_ATTRIBUTE_UUID_FK FOREIGN KEY (DM_ATTRIBUTE_UUID) REFERENCES SMART.DM_ATTRIBUTE(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_NODE ADD CONSTRAINT CM_NODE_CM_UUID_FK FOREIGN KEY (CM_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CM_NODE ADD CONSTRAINT CM_NODE_CATEGORY_UUID_FK FOREIGN KEY (CATEGORY_UUID) REFERENCES SMART.DM_CATEGORY(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.CONFIGURABLE_MODEL ADD CONSTRAINT CONFIGURABLE_MODEL_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
			"ALTER TABLE SMART.WAYPOINT ADD CONSTRAINT WAYPOINT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", 
		
			"alter table smart.employee alter column smartpassword set data type varchar(256)",
			
			//max speed changes
			"alter table smart.PATROL_TYPE ADD COLUMN max_speed INTEGER",
			"update smart.PATROL_TYPE set max_speed = 120 WHERE PATROL_TYPE = 'GROUND'",
			"update smart.PATROL_TYPE set max_speed = 70 WHERE PATROL_TYPE = 'MARINE'",
			"update smart.PATROL_TYPE set max_speed = 500 WHERE PATROL_TYPE = 'AIR'",
			
			// permission changes for analyst users
			"GRANT ALL PRIVILEGES ON  smart.track TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.wp_attachments TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.WP_OBSERVATION_ATTRIBUTES TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.WP_OBSERVATION TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.WAYPOINT TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.PATROL_LEG_DAY TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.PATROL_LEG_MEMBERS TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.PATROL_LEG TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.PATROL TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.TRACK TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.OBSERVATION_ATTACHMENT TO analyst",
			"GRANT ALL PRIVILEGES ON  smart.PATROL_WAYPOINT TO analyst",
			"GRANT SELECT ON SMART.CM_NODE to analyst",
			"GRANT SELECT ON SMART.CM_ATTRIBUTE_LIST to analyst",
			"GRANT SELECT ON SMART.CM_ATTRIBUTE_TREE_NODE to analyst",
			"GRANT SELECT ON SMART.CM_ATTRIBUTE_OPTION to analyst",
			
			"GRANT SELECT ON SMART.AGENCY to analyst",
			"GRANT SELECT ON SMART.RANK to analyst",
			"GRANT SELECT ON SMART.AGENCY to dataentry",
			"GRANT SELECT ON SMART.RANK to dataentry",
			"GRANT SELECT ON SMART.AGENCY to manager",
			"GRANT SELECT ON SMART.RANK to manager",
			
			"GRANT INSERT ON  SMART.STATION TO analyst",
			"GRANT INSERT ON  SMART.STATION TO dataentry",
			"GRANT INSERT ON  SMART.STATION TO manager",
			"GRANT UPDATE ON  SMART.STATION TO analyst",
			"GRANT UPDATE ON  SMART.STATION TO dataentry",
			"GRANT UPDATE ON  SMART.STATION TO manager",
			
			"GRANT USAGE ON SEQUENCE smart.smart_user_id_seq TO analyst",
			"GRANT USAGE ON SEQUENCE smart.smart_user_id_seq TO dataentry",
			"GRANT USAGE ON SEQUENCE smart.smart_user_id_seq TO manager",
			
			"GRANT INSERT ON  SMART.EMPLOYEE TO analyst",
			"GRANT INSERT ON  SMART.EMPLOYEE TO dataentry",
			"GRANT INSERT ON  SMART.EMPLOYEE TO manager",
			"GRANT UPDATE ON  SMART.EMPLOYEE TO analyst",
			"GRANT UPDATE ON  SMART.EMPLOYEE TO dataentry",
			"GRANT UPDATE ON  SMART.EMPLOYEE TO manager",
		};
		
		for (String s : sql){
			SmartPlugIn.logInfo(s);
			c.createStatement().execute(s);
		}
		/* UPDATE PASSWORDS */
		String querysql = "select uuid, smartpassword from smart.employee where smartpassword is not null"; //$NON-NLS-1$
		String upsql = "UPDATE smart.employee set smartpassword = ? where uuid = ?"; //$NON-NLS-1$
		
		try(ResultSet rs = c.createStatement().executeQuery(querysql);
				PreparedStatement ps = c.prepareStatement(upsql);){
			while(rs.next()){
				byte[] uuid = rs.getBytes(1);
				String pass = rs.getString(2);
				
				ps.setString(1, HibernateManager.generatePassword(pass));
				ps.setBytes(2, uuid);

				ps.executeUpdate();
			}
		}
		upgradeCcaaQueriesAndReports(session, c);
		/* VERSION UDATE */ 
		String ssql = "update smart.db_version set version = '4.0.0' where plugin_id = 'org.wcs.smart'"; //$NON-NLS-1$
		c.createStatement().execute(ssql);
		
		c.commit();
	}
	
	@SuppressWarnings("unchecked")
	private static void upgradeCcaaQueriesAndReports(Session s, Connection c)
			throws SQLException {
		HashMap<String, Employee> ccaaUsers = new HashMap<String, Employee>();

		ConservationArea ccaa = (ConservationArea) s.get(
				ConservationArea.class, ConservationArea.MULTIPLE_CA);

		List<Employee> existingUsers = (List<Employee>) s
				.createCriteria(Employee.class)
				.add(Restrictions.eq("conservationArea", ccaa)) //$NON-NLS-1$
				.add(Restrictions.ne("uuid", Employee.SHARED_UUID)) //$NON-NLS-1$
				.list();
		for (Employee e : existingUsers) {
			if (e.getSmartUserId() != null) {
				ccaaUsers.put(e.getSmartUserId(), e);
			}
		}
		upgradeCCAAQueryUser("smart.report", //$NON-NLS-1$
				"creator_uuid", s, c, ccaaUsers, ccaa); //$NON-NLS-1$
		upgradeCCAAQueryUser("smart.report_folder", //$NON-NLS-1$
				"employee_uuid", s, c, ccaaUsers, ccaa); //$NON-NLS-1$
		upgradeCCAAQueryUser("smart.query_folder", //$NON-NLS-1$
				"employee_uuid", s, c, ccaaUsers, ccaa); //$NON-NLS-1$
		
		// --- Queries ---
		// we only worry about the query tables we know about; plugins are
		// responsible for their query tables
		String[] queryTables = new String[] { 
				"smart.OBS_OBSERVATION_QUERY", //$NON-NLS-1$
				"smart.OBS_SUMMARY_QUERY", //$NON-NLS-1$
				"smart.OBS_WAYPOINT_QUERY", //$NON-NLS-1$
				"smart.OBS_GRIDDED_QUERY", //$NON-NLS-1$
				"smart.OBSERVATION_QUERY", //$NON-NLS-1$
				"smart.WAYPOINT_QUERY", //$NON-NLS-1$
				"smart.SUMMARY_QUERY", //$NON-NLS-1$
				"smart.GRIDDED_QUERY", //$NON-NLS-1$
				"smart.PATROL_QUERY" //$NON-NLS-1$
		};
		for (String table : queryTables) {
			upgradeCCAAQueryUser(table,
					"creator_uuid", s, c, ccaaUsers, ccaa); //$NON-NLS-1$
		}
	}
	
	/**
	 * Upgrades the owner of ccaa queries in the provided query tables.  Assumes each
	 * query table has a "creator_uuid" column that identifies the creator.  This will change
	 * the creator from referencing a CA user to referencing a CCAA user (a new CCAA user will be
	 * created if necessary).
	 * 
	 * @param s
	 * @param c
	 * @param tableNames
	 * @throws SQLException
	 */
	@SuppressWarnings("unchecked")
	public static void updateCCAAQueryTables(Session s, Connection c, String[] tableNames) throws SQLException{
		ConservationArea ccaa = (ConservationArea) s.get(
				ConservationArea.class, ConservationArea.MULTIPLE_CA);
		HashMap<String, Employee> ccaaUsers = new HashMap<String, Employee>();

		List<Employee> existingUsers = (List<Employee>) s
				.createCriteria(Employee.class)
				.add(Restrictions.eq("conservationArea", ccaa)) //$NON-NLS-1$
				.add(Restrictions.ne("uuid", Employee.SHARED_UUID)) //$NON-NLS-1$
				.list();
		for (Employee e : existingUsers) {
			if (e.getSmartUserId() != null) {
				ccaaUsers.put(e.getSmartUserId(), e);
			}
		}
		for (String table : tableNames) {
			upgradeCCAAQueryUser(table,
					"creator_uuid", s, c, ccaaUsers, ccaa); //$NON-NLS-1$
		}
	}
	
	private static void upgradeCCAAQueryUser(String tableName, String employeeName, Session session, Connection c,HashMap<String, Employee> ccaaUsers, ConservationArea ccaa) throws SQLException{
		String sql = "SELECT uuid, " + employeeName + " FROM " + tableName + " WHERE ca_uuid = ? AND " + employeeName + " != ?"; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
		PreparedStatement ps = c.prepareStatement(sql);
		ps.setBytes(1, UuidUtils.uuidToByte(ConservationArea.MULTIPLE_CA));
		ps.setBytes(2, UuidUtils.uuidToByte(Employee.SHARED_UUID));
		
		sql = "UPDATE " + tableName + " SET " + employeeName + " = ?  WHERE uuid = ? ";  //$NON-NLS-1$//$NON-NLS-2$ //$NON-NLS-3$
		PreparedStatement updateps = c.prepareStatement(sql);
		
		try(ResultSet rs = ps.executeQuery()){
			while(rs.next()){
				byte[] uuid = rs.getBytes(1);
				UUID employee = UuidUtils.byteToUUID(rs.getBytes(2));
				
				Employee e = (Employee)session.get(Employee.class, employee);
				if (e.getConservationArea().getIsCcaa()) continue;
				
				Employee newe = ccaaUsers.get(e.getSmartUserId());
				if (newe == null){
					newe = new Employee();
					newe = new Employee();
					newe.setGender(Employee.DB_MALE);
					newe.setSmartUserId(e.getSmartUserId());
					newe.setGivenName(newe.getSmartUserId());
					newe.setFamilyName(""); //$NON-NLS-1$
					newe.setStartEmploymentDate(new Date());
					newe.setId(newe.getSmartUserId());
					newe.setConservationArea(ccaa);
					newe.setSmartUserLevel(SmartUserLevel.ADMIN);
					session.save(newe);
					session.flush();
					ccaaUsers.put(newe.getSmartUserId(), newe);
				}
				updateps.setBytes(1, UuidUtils.uuidToByte(newe.getUuid()));
				updateps.setBytes(2, uuid);
				updateps.executeUpdate();
			}
		}
	}
}
