
/* Drop Tables */

DROP TABLE PATROL_LEG_MEMBERS;
DROP TABLE EMPLOYEE;
DROP TABLE RANK;
DROP TABLE AGENCY;
DROP TABLE AREA_GEOMETRIES;
DROP TABLE WP_OBSERVATION_ATTRIBUTES;
DROP TABLE DM_ATTRIBUTE_LIST;
DROP TABLE DM_ATT_AGG_MAP;
DROP TABLE DM_ATT_TREE_NODES;
DROP TABLE DM_CAT_ATT_MAP;
DROP TABLE DM_ATTRIBUTE;
DROP TABLE WP_OBSERVATION;
DROP TABLE DM_CATEGORY;
DROP TABLE I18N_LABEL;
DROP TABLE LANGUAGES;
DROP TABLE TRACK;
DROP TABLE WP_ATTACHMENTS;
DROP TABLE WAYPOINT;
DROP TABLE PATROL_LEG_DAY;
DROP TABLE PATROL_LEG;
DROP TABLE PATROL;
DROP TABLE TEAM_LIST;
DROP TABLE PATROL_MANDATE_LIST;
DROP TABLE PATROL_TRANSPORT_LIST;
DROP TABLE PATROL_TYPE_LIST;
DROP TABLE STATION;
DROP TABLE CONSERVATION_AREA;
DROP TABLE DM_AGGREGATION;
DROP TABLE DM_ATTRIBUTE_TREE;
DROP TABLE PATROL_OPTIONS;




/* Create Tables */

CREATE TABLE AGENCY
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	CA_UUID CHAR(16),
	PRIMARY KEY (UUID)
);


CREATE TABLE AREA_GEOMETRIES
(
	-- not null
	PID INTEGER NOT NULL,
	-- --for bit data
	UUID CHAR(16) NOT NULL UNIQUE,
	-- --for bit data
	CA_UUID CHAR(16) NOT NULL,
	AREA_TYPE VARCHAR(5) NOT NULL,
	ID VARCHAR(256),
	GEOM BLOB NOT NULL,
	PRIMARY KEY (PID)
);


-- Tracks all conservation areas loaded in the current database.
CREATE TABLE CONSERVATION_AREA
(
	-- char(16) for bit data
	UUID CHAR(16) NOT NULL,
	ID VARCHAR(8) NOT NULL UNIQUE,
	NAME VARCHAR(256),
	DESCRIPTION TEXT,
	WP_DIRECTION BOOLEAN NOT NULL,
	PLAN_POINT_BUFFER FLOAT NOT NULL,
	DEFAULT_SRS VARCHAR(16) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE DM_AGGREGATION
(
	NAME VARCHAR(10) NOT NULL,
	GUI_NAME VARCHAR(48) NOT NULL,
	PRIMARY KEY (NAME)
);


CREATE TABLE DM_ATTRIBUTE
(
	-- --for bit data
	-- 
	UUID CHAR(16) NOT NULL,
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	IS_REQUIRED BOOLEAN NOT NULL,
	ATT_TYPE VARCHAR(7) NOT NULL,
	MIN_VALUE DOUBLE,
	MAX_VALUE DOUBLE,
	REGEX VARBINARY(1024),
	PRIMARY KEY (UUID)
);


CREATE TABLE DM_ATTRIBUTE_LIST
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	ATTRIBUTE_UUID CHAR(16) NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	LIST_ORDER SMALLINT NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE DM_ATTRIBUTE_TREE
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	NODE_ORDER SMALLINT NOT NULL,
	PARENT_UUID CHAR(16),
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE DM_ATT_AGG_MAP
(
	-- for bit data
	ATTRIBUTE_UUID CHAR(16) NOT NULL,
	AGG_NAME VARCHAR(10) NOT NULL,
	PRIMARY KEY (ATTRIBUTE_UUID, AGG_NAME)
);


CREATE TABLE DM_ATT_TREE_NODES
(
	-- --for bit data
	-- 
	ATTRIBUTE_UUID CHAR(16) NOT NULL,
	-- for bit data
	NODE_UUID CHAR(16) NOT NULL,
	PRIMARY KEY (ATTRIBUTE_UUID, NODE_UUID)
);


CREATE TABLE DM_CATEGORY
(
	-- --for bit data
	UUID CHAR(16) NOT NULL,
	-- --for bit data
	CA_UUID CHAR(16) NOT NULL,
	KEYID VARCHAR(128) NOT NULL,
	-- for bit data
	PARENT_CATEGORY_UUID CHAR(16),
	IS_MULTIPLE BOOLEAN,
	CAT_ORDER SMALLINT NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE DM_CAT_ATT_MAP
(
	-- for bit data
	CATEGORY_UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	ATTRIBUTE_UUID CHAR(16) NOT NULL,
	ATT_ORDER SMALLINT NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (CATEGORY_UUID, ATTRIBUTE_UUID)
);


CREATE TABLE EMPLOYEE
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	ID VARCHAR(32) NOT NULL,
	GIVENNAME VARCHAR(64) NOT NULL,
	FAMILYNAME VARCHAR(64) NOT NULL,
	STARTEMPLOYMENTDATE DATE NOT NULL,
	ENDEMPLOYMENTDATE DATE,
	DATECREATED DATE NOT NULL,
	BIRTHDATE DATE,
	GENDER CHAR(1) NOT NULL,
	SMARTUSERID VARCHAR(16),
	SMARTPASSWORD VARCHAR(16),
	SMARTUSERLEVEL TINYINT,
	-- for bit data
	AGENCY_UUID CHAR(16),
	-- for bit data
	RANK_UUID CHAR(16),
	PRIMARY KEY (UUID)
);


CREATE TABLE I18N_LABEL
(
	LANGUAGE_UUID CHAR(16) NOT NULL,
	ELEMENT_UUID CHAR(16) NOT NULL,
	VALUE VARCHAR(1024) NOT NULL,
	PRIMARY KEY (LANGUAGE_UUID, ELEMENT_UUID)
);


CREATE TABLE LANGUAGES
(
	UUID CHAR(16) NOT NULL,
	-- char(16) for bit data
	CA_UUID CHAR(16) NOT NULL,
	CODE CHAR(5) NOT NULL,
	NAME VARCHAR(64),
	ISDEFAULT BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL
(
	-- for bit data
	-- 
	UUID CHAR(16) NOT NULL,
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	STATION_UUID CHAR(16),
	-- for bit data
	-- 
	TEAM_UUID CHAR(16),
	OBJECTIVE_RATING TINYINT,
	OBJECTIVE VARCHAR(8192),
	-- for bit data
	MANDATE_UUID CHAR(16),
	-- for bit data
	PATROL_TYPE_UUI CHAR(16) NOT NULL,
	IS_ARMED BOOLEAN NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL_LEG
(
	UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	PATROL_UUID CHAR(16) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	TRANSPORT_UUID CHAR(16) NOT NULL,
	ID INTEGER NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL_LEG_DAY
(
	UUID CHAR(16) NOT NULL,
	-- for bit data
	PATROL_LEG_UUID CHAR(16) NOT NULL,
	PATROL_DAY DATE NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL_LEG_MEMBERS
(
	PATROL_LEG_UUID CHAR(16) NOT NULL,
	-- for bit data
	EMPLOYEE_UUID CHAR(16) NOT NULL,
	IS_LEADER BOOLEAN NOT NULL,
	IS_PILOT BOOLEAN NOT NULL,
	PRIMARY KEY (PATROL_LEG_UUID, EMPLOYEE_UUID)
);


CREATE TABLE PATROL_MANDATE_LIST
(
	-- --for bit data
	UUID CHAR(16) NOT NULL,
	-- char(16) for bit data
	CA_UUID CHAR(16) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL_OPTIONS
(
	-- --for bit data
	CA_UUID CHAR(16) NOT NULL,
	DISTANCE_DIRECTION BOOLEAN NOT NULL,
	EDIT_TIME SMALLINT,
	PRIMARY KEY (CA_UUID)
);


CREATE TABLE PATROL_TRANSPORT_LIST
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	CA_UUID CHAR(16) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PATROL_TYPE VARCHAR(6) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE PATROL_TYPE_LIST
(
	-- for bit data
	-- 
	CA_UUID CHAR(16) NOT NULL,
	PATROL_TYPE VARCHAR(6) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL
);


CREATE TABLE RANK
(
	UUID CHAR(16) NOT NULL,
	-- for bit data
	AGENCY_UUID CHAR(16) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE STATION
(
	UUID CHAR(16) NOT NULL,
	-- char(16) for bit data
	CA_UUID CHAR(16) NOT NULL,
	DESC_UUID CHAR(16),
	PRIMARY KEY (UUID)
);


CREATE TABLE TEAM_LIST
(
	-- for bit data
	-- 
	UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	CA_UUID CHAR(16) NOT NULL,
	IS_ACTIVE BOOLEAN DEFAULT 'true' NOT NULL,
	-- for bit data
	DESC_UUID CHAR(16) UNIQUE,
	-- for bit data
	-- 
	PATROL_MANDATE_UUID CHAR(16),
	PRIMARY KEY (UUID)
);


CREATE TABLE TRACK
(
	-- for bit data
	TRACK_UUID CHAR(16) NOT NULL,
	-- for bit data
	PATROL_LEG_DAY_UUID CHAR(16) NOT NULL,
	GEOMETRY BLOB NOT NULL,
	DISTANCE REAL NOT NULL,
	PRIMARY KEY (TRACK_UUID, PATROL_LEG_DAY_UUID)
);


CREATE TABLE WAYPOINT
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	LEG_DAY_UUID CHAR(16) NOT NULL,
	ID INTEGER NOT NULL,
	X DOUBLE NOT NULL,
	Y DOUBLE NOT NULL,
	DATETIME DATETIME NOT NULL,
	DIRECTION REAL,
	DISTANCE REAL,
	WP_COMMENT VARCHAR(4096),
	PRIMARY KEY (UUID)
);


CREATE TABLE WP_ATTACHMENTS
(
	UUID CHAR(16) NOT NULL,
	-- for bit data
	WP_UUID CHAR(16) NOT NULL,
	FILENAME VARCHAR(1024) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE WP_OBSERVATION
(
	UUID CHAR(16) NOT NULL,
	-- for bit data
	WP_UUID CHAR(16) NOT NULL,
	-- --for bit data
	CATEGORY_UUID CHAR(16) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE WP_OBSERVATION_ATTRIBUTES
(
	OBSERVATION_UUID CHAR(16) NOT NULL,
	-- --for bit data
	-- 
	ATTRIBUTE_UUID CHAR(16) NOT NULL,
	-- for bit data
	LIST_ELEMENT_UUID CHAR(16),
	-- for bit data
	TREE_NODE_UUID CHAR(16),
	NUMBER_VALUE DOUBLE,
	STRING_VALUE VARCHAR(1024),
	PRIMARY KEY (OBSERVATION_UUID, ATTRIBUTE_UUID)
);



/* Create Foreign Keys */

ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (AGENCY_UUID)
	REFERENCES AGENCY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RANK
	ADD FOREIGN KEY (AGENCY_UUID)
	REFERENCES AGENCY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENCY
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AREA_GEOMETRIES
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATTRIBUTE
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_CATEGORY
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLOYEE
	ADD CONSTRAINT EMPLOYEE_CA_UUID_FK FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LANGUAGES
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_MANDATE_LIST
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_TRANSPORT_LIST
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_TYPE_LIST
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE STATION
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TEAM_LIST
	ADD FOREIGN KEY (CA_UUID)
	REFERENCES CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATT_AGG_MAP
	ADD FOREIGN KEY (AGG_NAME)
	REFERENCES DM_AGGREGATION (NAME)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATTRIBUTE_LIST
	ADD FOREIGN KEY (ATTRIBUTE_UUID)
	REFERENCES DM_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATT_AGG_MAP
	ADD FOREIGN KEY (ATTRIBUTE_UUID)
	REFERENCES DM_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATT_TREE_NODES
	ADD FOREIGN KEY (ATTRIBUTE_UUID)
	REFERENCES DM_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_CAT_ATT_MAP
	ADD FOREIGN KEY (ATTRIBUTE_UUID)
	REFERENCES DM_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION_ATTRIBUTES
	ADD FOREIGN KEY (ATTRIBUTE_UUID)
	REFERENCES DM_ATTRIBUTE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION_ATTRIBUTES
	ADD FOREIGN KEY (LIST_ELEMENT_UUID)
	REFERENCES DM_ATTRIBUTE_LIST (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_ATT_TREE_NODES
	ADD FOREIGN KEY (NODE_UUID)
	REFERENCES DM_ATTRIBUTE_TREE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION_ATTRIBUTES
	ADD FOREIGN KEY (TREE_NODE_UUID)
	REFERENCES DM_ATTRIBUTE_TREE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DM_CAT_ATT_MAP
	ADD FOREIGN KEY (CATEGORY_UUID)
	REFERENCES DM_CATEGORY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION
	ADD FOREIGN KEY (CATEGORY_UUID)
	REFERENCES DM_CATEGORY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_LEG_MEMBERS
	ADD FOREIGN KEY (EMPLOYEE_UUID)
	REFERENCES EMPLOYEE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE I18N_LABEL
	ADD FOREIGN KEY (LANGUAGE_UUID)
	REFERENCES LANGUAGES (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_LEG
	ADD FOREIGN KEY (PATROL_UUID)
	REFERENCES PATROL (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_LEG_DAY
	ADD FOREIGN KEY (PATROL_LEG_UUID)
	REFERENCES PATROL_LEG (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROL_LEG_MEMBERS
	ADD FOREIGN KEY (PATROL_LEG_UUID)
	REFERENCES PATROL_LEG (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRACK
	ADD FOREIGN KEY (PATROL_LEG_DAY_UUID)
	REFERENCES PATROL_LEG_DAY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WAYPOINT
	ADD FOREIGN KEY (LEG_DAY_UUID)
	REFERENCES PATROL_LEG_DAY (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TEAM_LIST
	ADD FOREIGN KEY (PATROL_MANDATE_UUID)
	REFERENCES PATROL_MANDATE_LIST (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONSERVATION_AREA
	ADD FOREIGN KEY (UUID)
	REFERENCES PATROL_OPTIONS (CA_UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLOYEE
	ADD FOREIGN KEY (RANK_UUID)
	REFERENCES RANK (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_ATTACHMENTS
	ADD FOREIGN KEY (WP_UUID)
	REFERENCES WAYPOINT (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION
	ADD FOREIGN KEY (WP_UUID)
	REFERENCES WAYPOINT (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WP_OBSERVATION_ATTRIBUTES
	ADD FOREIGN KEY (OBSERVATION_UUID)
	REFERENCES WP_OBSERVATION (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



