package org.wcs.smart.er.xml;

import java.io.File;
import java.nio.file.Path;
import java.util.List;

import org.hibernate.Session;
import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.er.model.Mission;

public interface IXmlToMissionConverter {

	/**
	 * Convert the file to a mission
	 * @param xml
	 * @param keepIDs
	 * @param session
	 * @param ca
	 * @param attachmentLocation
	 * @throws Exception
	 */
	public void fromXml(Path xml, boolean keepIDs, Session session, ConservationArea ca, File attachmentLocation) throws Exception;
		
	/**
	 * Add a validation error
	 * @param error
	 */
	public void addValidationError(String error);
	
	/**
	 * Errors generated by the validation process
	 * @return
	 */
	public List<String> getValidationErrors();
	
	/**
	 * @return any warnings generated during the import process
	 */
	public List<String> getWarnings();
	
	/**
	 * @return the imported mission
	 */
	public Mission getImportedMission();
	
}
