
/* Drop Tables */

DROP TABLE SMART.SURVEY_OBSERVATION_QUERY;
DROP TABLE SMART.SURVEY_GRIDDED_QUERY;
DROP TABLE SMART.SURVEY_SUMMARY_QUERY;


/* Create Tables */

CREATE TABLE SMART.SURVEY_OBSERVATION_QUERY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,
	QUERY_FILTER VARCHAR(32672),
	CA_FILTER VARCHAR(32672),
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	FOLDER_UUID CHAR(16) FOR BIT DATA ,
	COLUMN_FILTER VARCHAR(32672),
	SURVEYDESIGN_KEY VARCHAR(128),
	SHARED BOOLEAN NOT NULL,
	ID VARCHAR(6) NOT NULL,
	PRIMARY KEY (UUID)
);

CREATE TABLE SMART.SURVEY_GRIDDED_QUERY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,
	QUERY_FILTER VARCHAR(32672),
	CA_FILTER VARCHAR(32672),
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	FOLDER_UUID CHAR(16) FOR BIT DATA ,
	QUERY_DEF VARCHAR(32672),
	SHARED BOOLEAN NOT NULL,
	ID VARCHAR(6) NOT NULL,
	CRS_DEFINITION VARCHAR(32672),
	SURVEYDESIGN_KEY VARCHAR(128),
	PRIMARY KEY (UUID)
);

CREATE TABLE SMART.SURVEY_SUMMARY_QUERY
(
	UUID CHAR(16) FOR BIT DATA NOT NULL,
	CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,
	QUERY_DEF VARCHAR(32672),
	CA_FILTER VARCHAR(32672),
	CA_UUID CHAR(16) FOR BIT DATA NOT NULL,
	FOLDER_UUID CHAR(16) FOR BIT DATA ,
	SHARED BOOLEAN NOT NULL,
	ID VARCHAR(6) NOT NULL,
	SURVEYDESIGN_KEY VARCHAR(128),
	PRIMARY KEY (UUID)
);
/* Create Foreign Keys */

ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) 
	REFERENCES SMART.EMPLOYEE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CA_UUID_FK FOREIGN KEY (CA_UUID) 
	REFERENCES SMART.CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) 
	REFERENCES SMART.QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) 
	REFERENCES SMART.EMPLOYEE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_CA_UUID_FK FOREIGN KEY (CA_UUID) 
	REFERENCES SMART.CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) 
	REFERENCES SMART.QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) 
	REFERENCES SMART.EMPLOYEE (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_CA_UUID_FK FOREIGN KEY (CA_UUID) 
	REFERENCES SMART.CONSERVATION_AREA (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) 
	REFERENCES SMART.QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO manager;
GRANT SELECT ON SMART.SURVEY_OBSERVATION_QUERY TO data_entry;
GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO analsyt;

GRANT ALL PRIVILEGES ON SMART.SURVEY_GRIDDED_QUERY TO manager;
GRANT SELECT ON SMART.SURVEY_GRIDDED_QUERY TO data_entry;
GRANT ALL PRIVILEGES ON SMART.SURVEY_GRIDDED_QUERY TO analsyt;

GRANT ALL PRIVILEGES ON SMART.SURVEY_SUMMARY_QUERY TO manager;
GRANT SELECT ON SMART.SURVEY_SUMMARY_QUERY TO data_entry;
GRANT ALL PRIVILEGES ON SMART.SURVEY_SUMMARY_QUERY TO analsyt;