/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.asset.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.wcs.smart.asset.model.mapping.ExifMetadataField;
import org.wcs.smart.asset.model.mapping.IMetadataField;
import org.wcs.smart.asset.model.mapping.XmpMetadataField;
import org.wcs.smart.ca.ConservationArea;
import org.wcs.smart.ca.UuidItem;
import org.wcs.smart.ca.datamodel.Attribute;
import org.wcs.smart.ca.datamodel.AttributeListItem;
import org.wcs.smart.ca.datamodel.AttributeTreeNode;
import org.wcs.smart.ca.datamodel.Category;

/**
 * Model class of exif_metadata_mapping.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="smart.asset_metadata_mapping")
public class AssetMetadataMapping extends UuidItem {

	private static final long serialVersionUID = 1L;
	
	public enum AssetProperty{
		ASSET_ID,
		STATION_ID,
		LOCATION_ID,
		WAYPOINT_COMMENT
	}
	
	public enum MetadataType{
		EXIF,
		XMP
	}
	
	private ConservationArea conservationArea;
	
	private String mappingstring;
	private MetadataType type;
	private Integer order;
	
	private AssetProperty mappedAssetProperty;
	
	private Category mappedCategory;
	private Attribute mappedAttribute;
	private AttributeListItem mappedListItem;
	private AttributeTreeNode mappedTreeNode;
	
	//parsed metadata mapping
	@Transient
	private IMetadataField mField = null;
	
	/**
	 * Constructor.
	 */
	public AssetMetadataMapping() {
	}

	/**
	 * Get the conservation_area.
	 * 
	 * @return conservation_area
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="ca_uuid", referencedColumnName="uuid")
	public ConservationArea getConservationArea() {
		return this.conservationArea;
	}
	
	/**
	 * Set the conservation_area.
	 * 
	 * @param ca
	 *            conservation_area
	 */
	public void setConservationArea(ConservationArea ca) {
		this.conservationArea = ca;
	}


	/**
	 * Get the metadata type
	 * 
	 * @return tag
	 */
	@Column(name="metadata_type")
	@Enumerated(EnumType.STRING)
	public MetadataType getMetadataType() {
		return this.type;
	}

	/**
	 * Set the metadata type
	 * 
	 * @param tag
	 */
	public void setMetadataType(MetadataType type) {
		this.type = type;
	}

	/**
	 * Set the metadata mapping key.
	 * 
	 */
	@Column(name="metadata_key")
	public String getMetadataKey() {
		return this.mappingstring;
	}

	/**
	 * 
	 */
	public void setMetadataKey(String mappingstring) {
		this.mappingstring = mappingstring;
	}
	
	@Transient
	public void setMetadataKey(IMetadataField field) {
		this.mappingstring = field.asString();
		this.mField = field;
	}
	
	/**
	 * The order the matedata mapping swill be searched
	 * 
	 */
	@Column(name="search_order")
	public Integer getSearchOrder() {
		return this.order;
	}

	/**
	 * 
	 */
	public void setSearchOrder(Integer order) {
		this.order = order;
	}
	

	/**
	 * Get the asset_field this tag is mapped to
	 * 
	 * @return asset_field
	 */
	@Enumerated(value=EnumType.STRING)
	@Column(name="asset_field")
	public AssetProperty getMappedAssetProperty() {
		return this.mappedAssetProperty;
	}
	
	/**
	 * Set the asset_field.
	 * 
	 * @param assetProperty
	 *            asset_field
	 */
	public void setMappedAssetProperty(AssetProperty assetProperty) {
		this.mappedAssetProperty = assetProperty;
	}


	/**
	 * Get the data model category this tag is mapped to
	 * 
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="category_uuid", referencedColumnName="uuid")
	public Category getMappedCategory() {
		return this.mappedCategory;
	}
	
	/**
	 * Set the category_uuid.
	 * 
	 * @param category
	 */
	public void setMappedCategory(Category category) {
		this.mappedCategory = category;
	}

	

	/**
	 * Get the data model attribute this tag is mapped to.
	 * 
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="attribute_uuid", referencedColumnName="uuid")
	public Attribute getMappedAttribute() {
		return this.mappedAttribute;
	}
	
	/**
	 * Set the mapped attribute.
	 * 
	 * @param attribute
	 */
	public void setMappedAttribute(Attribute attribute) {
		this.mappedAttribute = attribute;
	}

	
	/**
	 * Get the data model attribute list item this tag/value is mapped to
	 * 
	 * @return category_uuid
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="attribute_list_item_uuid", referencedColumnName="uuid")
	public AttributeListItem getMappedListItem() {
		return this.mappedListItem;
	}
	
	/**
	 * Set the mapped list item
	 * 
	 * @param listItem
	 */
	public void setMappedListItem(AttributeListItem listItem) {
		this.mappedListItem = listItem;
	}
	
	/**
	 * Get the data model attribute tree node this tag/value is mapped to
	 */
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="attribute_tree_node_uuid", referencedColumnName="uuid")
	public AttributeTreeNode getMappedTreeNode() {
		return this.mappedTreeNode;
	}
	
	/**
	 * Set the mapped tree node.
	 * 
	 * @param treeNode
	 */
	public void setMappedTreeNode(AttributeTreeNode treeNode) {
		this.mappedTreeNode = treeNode;
	}
	
	
	@Transient
	public IMetadataField getMetadataField() {
		if (mField != null) return mField; 
		switch (getMetadataType()){
		case EXIF:
			return ExifMetadataField.parseMapping(getMetadataKey());
		case XMP:
			return XmpMetadataField.parseMapping(getMetadataKey());
		}
		return null;
	}
}
