//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.09 at 11:00:45 AM PDT 
//


package org.wcs.smart.er.xml.model.surveyDesign;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for surveyDesign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="surveyDesign">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MissionProperty" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}missionProperty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SurveyDesignProperty" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}surveyDesignProperty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SurveyDesignSamplingUnitAttribute" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}surveyDesignSamplingUnitAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SamplingUnit" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}samplingUnit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}Names" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="endDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="trackDistanceDirection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="configurableModelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "surveyDesign", propOrder = {
    "missionProperty",
    "surveyDesignProperty",
    "surveyDesignSamplingUnitAttribute",
    "samplingUnit",
    "names"
})
public class SurveyDesign {

    @XmlElement(name = "MissionProperty")
    protected List<MissionProperty> missionProperty;
    @XmlElement(name = "SurveyDesignProperty")
    protected List<SurveyDesignProperty> surveyDesignProperty;
    @XmlElement(name = "SurveyDesignSamplingUnitAttribute")
    protected List<SurveyDesignSamplingUnitAttribute> surveyDesignSamplingUnitAttribute;
    @XmlElement(name = "SamplingUnit")
    protected List<SamplingUnit> samplingUnit;
    @XmlElement(name = "Names")
    protected List<NamesType> names;
    @XmlAttribute
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute
    protected Boolean trackDistanceDirection;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected String state;
    @XmlAttribute
    protected String configurableModelName;
    @XmlAttribute
    protected String keyid;

    /**
     * Gets the value of the missionProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missionProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissionProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MissionProperty }
     * 
     * 
     */
    public List<MissionProperty> getMissionProperty() {
        if (missionProperty == null) {
            missionProperty = new ArrayList<MissionProperty>();
        }
        return this.missionProperty;
    }

    /**
     * Gets the value of the surveyDesignProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the surveyDesignProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSurveyDesignProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SurveyDesignProperty }
     * 
     * 
     */
    public List<SurveyDesignProperty> getSurveyDesignProperty() {
        if (surveyDesignProperty == null) {
            surveyDesignProperty = new ArrayList<SurveyDesignProperty>();
        }
        return this.surveyDesignProperty;
    }

    /**
     * Gets the value of the surveyDesignSamplingUnitAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the surveyDesignSamplingUnitAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSurveyDesignSamplingUnitAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SurveyDesignSamplingUnitAttribute }
     * 
     * 
     */
    public List<SurveyDesignSamplingUnitAttribute> getSurveyDesignSamplingUnitAttribute() {
        if (surveyDesignSamplingUnitAttribute == null) {
            surveyDesignSamplingUnitAttribute = new ArrayList<SurveyDesignSamplingUnitAttribute>();
        }
        return this.surveyDesignSamplingUnitAttribute;
    }

    /**
     * Gets the value of the samplingUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samplingUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamplingUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SamplingUnit }
     * 
     * 
     */
    public List<SamplingUnit> getSamplingUnit() {
        if (samplingUnit == null) {
            samplingUnit = new ArrayList<SamplingUnit>();
        }
        return this.samplingUnit;
    }

    /**
     * Gets the value of the names property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the names property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamesType }
     * 
     * 
     */
    public List<NamesType> getNames() {
        if (names == null) {
            names = new ArrayList<NamesType>();
        }
        return this.names;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the trackDistanceDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrackDistanceDirection() {
        return trackDistanceDirection;
    }

    /**
     * Sets the value of the trackDistanceDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrackDistanceDirection(Boolean value) {
        this.trackDistanceDirection = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the configurableModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurableModelName() {
        return configurableModelName;
    }

    /**
     * Sets the value of the configurableModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurableModelName(String value) {
        this.configurableModelName = value;
    }

    /**
     * Gets the value of the keyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * Sets the value of the keyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyid(String value) {
        this.keyid = value;
    }

}
