//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.07 at 11:26:30 AM PDT 
//


package org.wcs.smart.internal.ca.datamodel.xml.generate.v11;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="names" type="{http://www.smartconservationsoftware.org/xml/1.1/datamodel}NameType" maxOccurs="unbounded"/>
 *         &lt;element name="attributes" type="{http://www.smartconservationsoftware.org/xml/1.1/datamodel}CategoryAttributeLink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.smartconservationsoftware.org/xml/1.1/datamodel}CategoryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ismultiple" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isactive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="iconkey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryType", propOrder = {
    "names",
    "attributes",
    "category"
})
public class CategoryType {

    @XmlElement(required = true)
    protected List<NameType> names;
    protected List<CategoryAttributeLink> attributes;
    protected List<CategoryType> category;
    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "ismultiple")
    protected Boolean ismultiple;
    @XmlAttribute(name = "isactive")
    protected Boolean isactive;
    @XmlAttribute(name = "iconkey")
    protected String iconkey;

    /**
     * Gets the value of the names property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the names property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getNames() {
        if (names == null) {
            names = new ArrayList<NameType>();
        }
        return this.names;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryAttributeLink }
     * 
     * 
     */
    public List<CategoryAttributeLink> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<CategoryAttributeLink>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryType }
     * 
     * 
     */
    public List<CategoryType> getCategory() {
        if (category == null) {
            category = new ArrayList<CategoryType>();
        }
        return this.category;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the ismultiple property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsmultiple() {
        return ismultiple;
    }

    /**
     * Sets the value of the ismultiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsmultiple(Boolean value) {
        this.ismultiple = value;
    }

    /**
     * Gets the value of the isactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsactive() {
        return isactive;
    }

    /**
     * Sets the value of the isactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsactive(Boolean value) {
        this.isactive = value;
    }

    /**
     * Gets the value of the iconkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconkey() {
        return iconkey;
    }

    /**
     * Sets the value of the iconkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconkey(String value) {
        this.iconkey = value;
    }

}
