/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.updatesite;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;

import org.eclipse.core.runtime.IProgressMonitor;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.wcs.smart.er.EcologicalRecordsPlugIn;
import org.wcs.smart.er.internal.Messages;
import org.wcs.smart.hibernate.HibernateManager;
import org.wcs.smart.upgrade.IDatabaseUpgrader;
import org.wcs.smart.upgrade.UpgradeEngine;

/**
 * Ecological Records upgrade operations while upgrade/restore backup.
 * 
 * @author elitvin
 * @since 1.0.0
 */
public class ERDatabaseUpgrader implements IDatabaseUpgrader {

	@Override
	public String getPluginId() {
		return EcologicalRecordsPlugIn.PLUGIN_ID;
	}

	@Override
	public String getPluginName() {
		return getName(EcologicalRecordsPlugIn.getDefault().getBundle());
	}
	
	
	@Override
	public boolean isUpdateToDate(Map<String, String> currentVersions) {
		if (!currentVersions.containsKey(EcologicalRecordsPlugIn.PLUGIN_ID)) return false;
		return currentVersions.get(EcologicalRecordsPlugIn.PLUGIN_ID).equals(EcologicalRecordsPlugIn.DB_VERSION);
	}
	
	@Override
	public void upgrade(IProgressMonitor monitor) throws Exception {
		monitor.subTask(Messages.ERDatabaseUpgrader_UpgradeTask);
		try(Session session = HibernateManager.openSession()){
			session.beginTransaction();
			try{
				Map<String, String> versions = UpgradeEngine.getVersions(session);
				upgrade(versions.get(EcologicalRecordsPlugIn.PLUGIN_ID), session);
				session.getTransaction().commit();
			}catch (Exception ex){
				session.getTransaction().rollback();
				throw ex;
			}
		}
		monitor.done();
	}

	
	/**
	 * Upgrades from the currentVersion to the most recent version.
	 * @param currentVersion
	 * @param session in active transaction
	 */
	private void upgrade(String currentVersion, Session session){
		if (currentVersion == null) {
			createTables(session);
			upgradeV1ToV2(session);
			upgradeV2ToV3(session);
			upgradeV3ToV4(session);
			upgradeV4ToV5(session);
		}else if (currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION_1)){
			upgradeV1ToV2(session);
			upgradeV2ToV3(session);
			upgradeV3ToV4(session);
			upgradeV4ToV5(session);
		}else if (currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION_2)){
			upgradeV2ToV3(session);
			upgradeV3ToV4(session);
			upgradeV4ToV5(session);
		}else if (currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION_3)){
			upgradeV3ToV4(session);
			upgradeV4ToV5(session);
		}else if (currentVersion.equals(EcologicalRecordsPlugIn.DB_VERSION_4)){
			upgradeV4ToV5(session);
		}
	}
	
	private void upgradeV1ToV2(Session session){
		String[] sql = new String[]{
				"alter table smart.MISSION_ATTRIBUTE add constraint mission_attribute_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"alter table smart.MISSION_ATTRIBUTE_LIST add constraint mission_attribute_list_keyid_unq unique(mission_attribute_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"alter table smart.SAMPLING_UNIT_ATTRIBUTE add constraint su_attribute_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"alter table smart.SAMPLING_UNIT_ATTRIBUTE_LIST add constraint su_list_attribute_keyid_unq unique(sampling_unit_attribute_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"alter table smart.SURVEY_DESIGN add constraint survey_design_keyid_unq unique(ca_uuid, keyid) DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				
				"ALTER TABLE SMART.SURVEY_DESIGN DROP CONSTRAINT CONFIGURABLE_MODEL_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST DROP CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_DAY DROP CONSTRAINT MISSION_DAY_MISSION_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_MEMBER DROP CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY DROP CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY DROP CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE DROP CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION DROP CONSTRAINT MISSION_SURVEY_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK DROP CONSTRAINT MISSION_TRACK", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK DROP CONSTRAINT MISSION_TRACK_MISSIONDAY_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT DROP CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT DROP CONSTRAINT SD_SU_SURVEY_DESIGN_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT DROP CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY DROP CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY DROP CONSTRAINT SURVEY_SURVEY_DSG_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_MISSIONDAY_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_MISSION_TRK_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT DROP CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE DROP CONSTRAINT SU_ATTRIBUTE_CA_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST DROP CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_ATTRIBUTE_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_LIST_ELEMENT_UUID", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE DROP CONSTRAINT SU_SU_UUID", //$NON-NLS-1$

				"ALTER TABLE SMART.MISSION ADD CONSTRAINT MISSION_SURVEY_UUID FOREIGN KEY (SURVEY_UUID) REFERENCES SMART.SURVEY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST ADD CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_DAY ADD CONSTRAINT MISSION_DAY_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_MEMBER ADD CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.MISSION_ATTRIBUTE_LIST(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE ADD CONSTRAINT SU_ATTRIBUTE_CA_UUID FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST ADD CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (SAMPLING_UNIT_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_UUID FOREIGN KEY (SU_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_LIST_ELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY ADD CONSTRAINT SURVEY_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT CONFIGURABLE_MODEL_UUID_FK FOREIGN KEY (CONFIGURABLE_MODEL_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY ADD CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SURVEY_DESIGN_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_TRK_UUID FOREIGN KEY (MISSION_TRACK_UUID) REFERENCES SMART.MISSION_TRACK(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID)  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				
				"ALTER TABLE SMART.MISSION_ATTRIBUTE ADD CONSTRAINT MISSION_ATT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID) ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT SD_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA(UUID) ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				
				"GRANT ALL PRIVILEGES ON smart.survey to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.mission to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.survey_waypoint to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.mission_track to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.mission_member to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.mission_day to analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.mission_property_value to analyst", //$NON-NLS-1$
		};
		
		for (String s : sql){
			session.createNativeQuery(s).executeUpdate();
		}
		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_2, session);
	}
	
	private void upgradeV2ToV3(Session session){
		String[] sql = new String[]{
				"alter table smart.mission add column start_date date",  //$NON-NLS-1$
				"alter table smart.mission add column end_date date", //$NON-NLS-1$
				"update smart.mission set start_date = cast(Start_datetime as date), end_date = cast(end_datetime as date)", //$NON-NLS-1$
				"alter table smart.mission drop column start_datetime", //$NON-NLS-1$
				"alter table smart.mission drop column end_datetime", //$NON-NLS-1$
				
				"alter table smart.survey drop column start_date", //$NON-NLS-1$
				"alter table smart.survey drop column end_date", //$NON-NLS-1$
				"alter table smart.survey_design drop column start_date", //$NON-NLS-1$
				"alter table smart.survey_design drop column end_date", //$NON-NLS-1$
				
				"ALTER TABLE smart.MISSION_PROPERTY_VALUE alter column string_value set data type varchar(8200)", //$NON-NLS-1$
				"ALTER TABLE smart.SAMPLING_UNIT_ATTRIBUTE_VALUE alter column string_value set data type varchar(8200)" //$NON-NLS-1$
		};
		
		for (String s : sql){
			session.createNativeQuery(s).executeUpdate();
		}
		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_3, session);
	}

	private void upgradeV3ToV4(Session session){
		//this is version update is required to fix the issue with the survey_waypoint trigger
		//see #3271
		
			//we need this code specifically when upgrade is performed during login
			//as that upgrade process doesn't uninstall change logging but we do need to
			//make sure this trigger gets updated
			for (String[] triggers : (new ChangeTrackerInstaller()).getCurrentTriggers()) {
				String name = triggers[0];
				if (name.equals("smart.trg_survey_waypoint_insert")|| //$NON-NLS-1$
						name.equals("smart.trg_survey_waypoint_update") || //$NON-NLS-1$
						name.equals("smart.trg_survey_waypoint_delete")) { //$NON-NLS-1$
			
					String[] bits = name.split("\\."); //$NON-NLS-1$
					
					Number cnt = (Number)session.createNativeQuery("select count(*) from sys.systriggers a, sys.sysschemas b WHERE a.schemaid = b.schemaid  AND  a.triggername = '" + bits[1].toUpperCase() + "' and b.schemaname ='" + bits[0].toUpperCase() + "'") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
							.uniqueResult();
					if (cnt.intValue() > 0) {
						session.createNativeQuery("DROP trigger " + name).executeUpdate(); //$NON-NLS-1$
						session.createNativeQuery(triggers[1]).executeUpdate();
					}
				}
			}

		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_4, session);
	}
	
	private void createTables(Session session){
		final String[] sql = new String[]{
				"CREATE TABLE SMART.MISSION(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_UUID CHAR(16) FOR BIT DATA NOT NULL,ID VARCHAR(128) NOT NULL,START_DATETIME TIMESTAMP NOT NULL,END_DATETIME TIMESTAMP NOT NULL,COMMENT LONG VARCHAR,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_ATTRIBUTE(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,ATT_TYPE VARCHAR(7) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_ATTRIBUTE_LIST(UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,LIST_ORDER SMALLINT NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_MEMBER(MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,EMPLOYEE_UUID CHAR(16) FOR BIT DATA NOT NULL,IS_LEADER BOOLEAN NOT NULL,PRIMARY KEY (MISSION_UUID, EMPLOYEE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_PROPERTY(SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,ATTRIBUTE_ORDER INTEGER NOT NULL,PRIMARY KEY (SURVEY_DESIGN_UUID, MISSION_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_PROPERTY_VALUE(MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,NUMBER_VALUE DOUBLE,STRING_VALUE VARCHAR(1024),LIST_ELEMENT_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (MISSION_UUID, MISSION_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_TRACK(UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_DAY_UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA ,TRACK_TYPE VARCHAR(32) NOT NULL,GEOMETRY BLOB NOT NULL,ID VARCHAR(128),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA  NOT NULL,UNIT_TYPE VARCHAR(32) NOT NULL,ID VARCHAR(128) NOT NULL,STATE VARCHAR(8) NOT NULL,GEOMETRY BLOB NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,ID VARCHAR(128) NOT NULL,START_DATE DATE,END_DATE DATE,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,STATE VARCHAR(16) NOT NULL,START_DATE DATE,END_DATE DATE,OBSERVER BOOLEAN DEFAULT FALSE NOT NULL,DISTANCE_DIRECTION BOOLEAN DEFAULT FALSE NOT NULL,DESCRIPTION LONG VARCHAR,CONFIGURABLE_MODEL_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN_PROPERTY(UUID CHAR(16) FOR BIT DATA NOT NULL,SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,NAME VARCHAR(256) NOT NULL,VALUE VARCHAR(8200),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_WAYPOINT(WP_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_DAY_UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_UUID CHAR(16) FOR BIT DATA,MISSION_TRACK_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (WP_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT(SURVEY_DESIGN_UUID CHAR(16) FOR BIT DATA NOT NULL,SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,PRIMARY KEY (SURVEY_DESIGN_UUID, SU_ATTRIBUTE_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE(SU_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,SU_UUID CHAR(16) FOR BIT DATA NOT NULL,STRING_VALUE VARCHAR(1024),NUMBER_VALUE DOUBLE,LIST_ELEMENT_UUID CHAR(16) FOR BIT DATA,PRIMARY KEY (SU_ATTRIBUTE_UUID, SU_UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE(UUID CHAR(16) FOR BIT DATA NOT NULL,CA_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128),ATT_TYPE VARCHAR(7),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID CHAR(16) FOR BIT DATA NOT NULL,SAMPLING_UNIT_ATTRIBUTE_UUID CHAR(16) FOR BIT DATA NOT NULL,KEYID VARCHAR(128) NOT NULL,LIST_ORDER SMALLINT NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.MISSION_DAY (UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_UUID CHAR(16) FOR BIT DATA NOT NULL,MISSION_DAY DATE NOT NULL,START_TIME TIME NOT NULL,END_TIME TIME NOT NULL,REST_MINUTES INTEGER,PRIMARY KEY (UUID))", //$NON-NLS-1$
				 
				"ALTER TABLE SMART.MISSION_MEMBER ADD CONSTRAINT MISSION_MEMBER_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_UUID FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSIONDAY_UUID FOREIGN KEY (MISSION_DAY_UUID) REFERENCES SMART.MISSION_DAY (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_MISSION_TRK_UUID FOREIGN KEY (MISSION_TRACK_UUID) REFERENCES SMART.MISSION_TRACK (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_ATTRIBUTE_LIST ADD CONSTRAINT MISSION_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_LIST ADD CONSTRAINT SU_ATT_LIST_MISSION_ATT_UUID_FK FOREIGN KEY (SAMPLING_UNIT_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_MISSION_ATT_UUID_FK FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_MISSION_ATT_UUID FOREIGN KEY (MISSION_ATTRIBUTE_UUID) REFERENCES SMART.MISSION_ATTRIBUTE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY_VALUE ADD CONSTRAINT MISSION_PROP_VALUE_LISTELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.MISSION_ATTRIBUTE_LIST (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_TRACK ADD CONSTRAINT MISSION_TRACK FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT ADD CONSTRAINT SURVEY_WP_SAMPLING_UNIT_UUID FOREIGN KEY (SAMPLING_UNIT_UUID) REFERENCES SMART.SAMPLING_UNIT (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION ADD CONSTRAINT MISSION_SURVEY_UUID FOREIGN KEY (SURVEY_UUID) REFERENCES SMART.SURVEY (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_PROPERTY ADD CONSTRAINT MISSION_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT SAMPLING_UNIT_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT ADD CONSTRAINT ID_SD_UNQ UNIQUE (ID, SURVEY_DESIGN_UUID)", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY ADD CONSTRAINT SURVEY_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_PROPERTY ADD CONSTRAINT SURVEY_DSG_PROP_SURVEY_DSG_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE ADD CONSTRAINT SU_ATTRIBUTE_CA_UUID FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SURVEY_DESIGN_UUID FOREIGN KEY (SURVEY_DESIGN_UUID) REFERENCES SMART.SURVEY_DESIGN(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN_SAMPLING_UNIT ADD CONSTRAINT SD_SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_ATTRIBUTE_UUID FOREIGN KEY (SU_ATTRIBUTE_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_UUID FOREIGN KEY (SU_UUID) REFERENCES SMART.SAMPLING_UNIT(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SAMPLING_UNIT_ATTRIBUTE_VALUE ADD CONSTRAINT SU_SU_LIST_ELEMENT_UUID FOREIGN KEY (LIST_ELEMENT_UUID) REFERENCES SMART.SAMPLING_UNIT_ATTRIBUTE_LIST(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.MISSION_DAY ADD CONSTRAINT MISSION_DAY_MISSION_UUID_FK FOREIGN KEY (MISSION_UUID) REFERENCES SMART.MISSION (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_DESIGN ADD CONSTRAINT CONFIGURABLE_MODEL_UUID_FK FOREIGN KEY (CONFIGURABLE_MODEL_UUID) REFERENCES SMART.CONFIGURABLE_MODEL(UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$

				"GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO manager", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.MISSION_PROPERTY_VALUE TO data_entry", //$NON-NLS-1$
				"GRANT SELECT ON SMART.MISSION_PROPERTY_VALUE TO analyst", //$NON-NLS-1$

				"GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO manager", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.MISSION_MEMBER TO data_entry", //$NON-NLS-1$
				"GRANT SELECT ON SMART.MISSION_MEMBER TO analyst", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_TRACK TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_TRACK TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_WAYPOINT TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_WAYPOINT TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_PROPERTY TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_PROPERTY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_PROPERTY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN_PROPERTY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_PROPERTY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_ATTRIBUTE_LIST TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE_LIST TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_ATTRIBUTE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.MISSION_ATTRIBUTE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_ATTRIBUTE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE_VALUE TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SURVEY_DESIGN_SAMPLING_UNIT TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO analyst", //$NON-NLS-1$
				"GRANT SELECT ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.SAMPLING_UNIT_ATTRIBUTE_LIST TO manager", //$NON-NLS-1$

				"GRANT SELECT ON smart.MISSION_DAY TO analyst", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_DAY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON smart.MISSION_DAY TO manager" //$NON-NLS-1$
		};
		
		session.doWork(new Work() {
			@Override
			public void execute(Connection c) throws SQLException {
				for (int i = 0; i < sql.length; i ++){
					c.createStatement().execute(sql[i]);
				}				
			}
		});
		
		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_1, session);

	}
	
	
	private void upgradeV4ToV5(Session session){
		String[] sql = new String[]{
				"ALTER TABLE smart.mission_attribute ADD COLUMN icon_uuid char(16) for bit data", //$NON-NLS-1$
				"ALTER table smart.mission_attribute ADD CONSTRAINT mission_attribute_icon_uuid_fk FOREIGN KEY (icon_uuid) REFERENCES smart.icon (uuid) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE smart.mission_attribute_list ADD COLUMN icon_uuid char(16) for bit data", //$NON-NLS-1$
				"ALTER table smart.mission_attribute_list ADD CONSTRAINT mission_attribute_list_icon_uuid_fk FOREIGN KEY (icon_uuid) REFERENCES smart.icon (uuid) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE smart.sampling_unit_attribute ADD COLUMN icon_uuid char(16) for bit data", //$NON-NLS-1$
				"ALTER table smart.sampling_unit_attribute ADD CONSTRAINT su_attribute_icon_uuid_fk FOREIGN KEY (icon_uuid) REFERENCES smart.icon (uuid) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$
				"ALTER TABLE smart.sampling_unit_attribute_list ADD COLUMN icon_uuid char(16) for bit data", //$NON-NLS-1$
				"ALTER table smart.sampling_unit_attribute_list ADD CONSTRAINT su_attribute_list_icon_uuid_fk FOREIGN KEY (icon_uuid) REFERENCES smart.icon (uuid) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE", //$NON-NLS-1$				
		};
		
		for (String s : sql){
			session.createNativeQuery(s).executeUpdate();
		}
		HibernateManager.setPlugInVersion(EcologicalRecordsPlugIn.PLUGIN_ID, EcologicalRecordsPlugIn.DB_VERSION_5, session);
	}
}
