/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.wcs.smart.er.query.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_NOT = 8;
  /** RegularExpression Id. */
  int K_OR = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int LESS = 11;
  /** RegularExpression Id. */
  int LESSEQUAL = 12;
  /** RegularExpression Id. */
  int GREATER = 13;
  /** RegularExpression Id. */
  int GREATEREQUAL = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int NOTEQUAL = 16;
  /** RegularExpression Id. */
  int NOTEQUAL2 = 17;
  /** RegularExpression Id. */
  int OPENPAREN = 18;
  /** RegularExpression Id. */
  int CLOSEPAREN = 19;
  /** RegularExpression Id. */
  int SLASH = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int CONTAINS = 23;
  /** RegularExpression Id. */
  int NOT_CONTAINS = 24;
  /** RegularExpression Id. */
  int STREQUALS = 25;
  /** RegularExpression Id. */
  int BETWEEN = 26;
  /** RegularExpression Id. */
  int QUERY_SPLITTER = 27;
  /** RegularExpression Id. */
  int NUMBER = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int INTEGER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int S_CONST_LITERAL = 32;
  /** RegularExpression Id. */
  int CATEGORY_KEY = 33;
  /** RegularExpression Id. */
  int ATT_STR_KEY = 34;
  /** RegularExpression Id. */
  int ATT_VALUE_KEY = 35;
  /** RegularExpression Id. */
  int ATT_BOOL_KEY = 36;
  /** RegularExpression Id. */
  int ATT_LIST_KEY = 37;
  /** RegularExpression Id. */
  int ATT_TREE_KEY = 38;
  /** RegularExpression Id. */
  int ATT_DATE_KEY = 39;
  /** RegularExpression Id. */
  int CAT_ATT_STR_KEY = 40;
  /** RegularExpression Id. */
  int CAT_ATT_VALUE_KEY = 41;
  /** RegularExpression Id. */
  int CAT_ATT_BOOL_KEY = 42;
  /** RegularExpression Id. */
  int CAT_ATT_LIST_KEY = 43;
  /** RegularExpression Id. */
  int CAT_ATT_TREE_KEY = 44;
  /** RegularExpression Id. */
  int CAT_ATT_DATE_KEY = 45;
  /** RegularExpression Id. */
  int DATE_STRING = 46;
  /** RegularExpression Id. */
  int DM_KEY = 47;
  /** RegularExpression Id. */
  int UUID = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 50;
  /** RegularExpression Id. */
  int SURVEY_ID_KEY = 51;
  /** RegularExpression Id. */
  int SURVEY_UUID_KEY = 52;
  /** RegularExpression Id. */
  int MISSION_ID_KEY = 53;
  /** RegularExpression Id. */
  int MISSION_UUID_KEY = 54;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_STR_KEY = 55;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_VALUE_KEY = 56;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_LIST_KEY = 57;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_KEY = 58;
  /** RegularExpression Id. */
  int SAMPLING_UNIT_TRACK_KEY = 59;
  /** RegularExpression Id. */
  int AREA_TYPE_KEY = 60;
  /** RegularExpression Id. */
  int AREA_KEY = 61;
  /** RegularExpression Id. */
  int OBSERVATION_FILTER_TYPE_KEY = 62;
  /** RegularExpression Id. */
  int WAYPOINT_FILTER_TYPE_KEY = 63;
  /** RegularExpression Id. */
  int SUM_CAT_VALUE_KEY = 64;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_KEY = 65;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_KEY = 66;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_LISTTREE_KEY = 67;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_LISTTREE_KEY = 68;
  /** RegularExpression Id. */
  int AGG = 69;
  /** RegularExpression Id. */
  int DATE_GROUPBY_ITEM = 70;
  /** RegularExpression Id. */
  int CATEGORY_GROUPBY_ITEM = 71;
  /** RegularExpression Id. */
  int AREA_GROUPBY_ITEM = 72;
  /** RegularExpression Id. */
  int ATTRIBUTE_GROUPBY_ITEM = 73;
  /** RegularExpression Id. */
  int CATEGORY_ATTRIBUTE_GROUPBY_ITEM = 74;
  /** RegularExpression Id. */
  int SURVEY_ID_GROUPBY_ITEM = 75;
  /** RegularExpression Id. */
  int MISSION_ID_GROUPBY_ITEM = 76;
  /** RegularExpression Id. */
  int MISSION_PROPERTY_GROUPBY_ITEM = 77;
  /** RegularExpression Id. */
  int SAMPLINGUNIT_GROUPBY_ITEM = 78;
  /** RegularExpression Id. */
  int QUOTED_STRING = 79;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"not\"",
    "\"or\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"contains\"",
    "\"notcontains\"",
    "\"equals\"",
    "\"between\"",
    "\"|\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_CONST_LITERAL>",
    "<CATEGORY_KEY>",
    "<ATT_STR_KEY>",
    "<ATT_VALUE_KEY>",
    "<ATT_BOOL_KEY>",
    "<ATT_LIST_KEY>",
    "<ATT_TREE_KEY>",
    "<ATT_DATE_KEY>",
    "<CAT_ATT_STR_KEY>",
    "<CAT_ATT_VALUE_KEY>",
    "<CAT_ATT_BOOL_KEY>",
    "<CAT_ATT_LIST_KEY>",
    "<CAT_ATT_TREE_KEY>",
    "<CAT_ATT_DATE_KEY>",
    "<DATE_STRING>",
    "<DM_KEY>",
    "<UUID>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "\"s:survey:id\"",
    "<SURVEY_UUID_KEY>",
    "\"s:mission:id\"",
    "<MISSION_UUID_KEY>",
    "<MISSION_PROPERTY_STR_KEY>",
    "<MISSION_PROPERTY_VALUE_KEY>",
    "<MISSION_PROPERTY_LIST_KEY>",
    "<SAMPLING_UNIT_KEY>",
    "<SAMPLING_UNIT_TRACK_KEY>",
    "<AREA_TYPE_KEY>",
    "<AREA_KEY>",
    "\"observation\"",
    "\"waypoint\"",
    "<SUM_CAT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_VALUE_KEY>",
    "<SUM_CAT_ATT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_VALUE_LISTTREE_KEY>",
    "<SUM_CAT_ATT_VALUE_LISTTREE_KEY>",
    "<AGG>",
    "<DATE_GROUPBY_ITEM>",
    "<CATEGORY_GROUPBY_ITEM>",
    "<AREA_GROUPBY_ITEM>",
    "<ATTRIBUTE_GROUPBY_ITEM>",
    "<CATEGORY_ATTRIBUTE_GROUPBY_ITEM>",
    "<SURVEY_ID_GROUPBY_ITEM>",
    "<MISSION_ID_GROUPBY_ITEM>",
    "<MISSION_PROPERTY_GROUPBY_ITEM>",
    "<SAMPLINGUNIT_GROUPBY_ITEM>",
    "<QUOTED_STRING>",
  };

}
