//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:18:05 PM MSK 
//


package org.wcs.smart.cybertracker.model.elements;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="List">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Items">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag0" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tag7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Alias0" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Alias1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Alias2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="GpsAccuracyEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="GpsSightingAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsSightingAccuracy" minOccurs="0"/>
 *                                       &lt;element name="GpsWaypointAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsWaypointAccuracy" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "list"
})
@XmlRootElement(name = "Elements")
public class Elements {

    @XmlElement(name = "List", required = true)
    protected Elements.List list;

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link Elements.List }
     *     
     */
    public Elements.List getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link Elements.List }
     *     
     */
    public void setList(Elements.List value) {
        this.list = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Items">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag0" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag6" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Tag7" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Alias0" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Alias1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Alias2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="GpsAccuracyEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="GpsSightingAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsSightingAccuracy" minOccurs="0"/>
     *                             &lt;element name="GpsWaypointAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsWaypointAccuracy" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "items"
    })
    public static class List {

        @XmlElement(name = "Items", required = true)
        protected Elements.List.Items items;

        /**
         * Gets the value of the items property.
         * 
         * @return
         *     possible object is
         *     {@link Elements.List.Items }
         *     
         */
        public Elements.List.Items getItems() {
            return items;
        }

        /**
         * Sets the value of the items property.
         * 
         * @param value
         *     allowed object is
         *     {@link Elements.List.Items }
         *     
         */
        public void setItems(Elements.List.Items value) {
            this.items = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag0" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag4" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag5" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag6" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Tag7" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Alias0" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Alias1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Alias2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="GpsAccuracyEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="GpsSightingAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsSightingAccuracy" minOccurs="0"/>
         *                   &lt;element name="GpsWaypointAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsWaypointAccuracy" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Items {

            @XmlElement(name = "Item")
            protected java.util.List<Elements.List.Items.Item> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Elements.List.Items.Item }
             * 
             * 
             */
            public java.util.List<Elements.List.Items.Item> getItem() {
                if (item == null) {
                    item = new ArrayList<Elements.List.Items.Item>();
                }
                return this.item;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag0" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag3" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag4" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag5" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag6" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Tag7" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Alias0" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Alias1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Alias2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="GpsAccuracyEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="GpsSightingAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsSightingAccuracy" minOccurs="0"/>
             *         &lt;element name="GpsWaypointAccuracy" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}GpsWaypointAccuracy" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "name",
                "description",
                "keywords",
                "tag0",
                "tag1",
                "tag2",
                "tag3",
                "tag4",
                "tag5",
                "tag6",
                "tag7",
                "alias0",
                "alias1",
                "alias2",
                "gpsAccuracyEnabled",
                "gpsSightingAccuracy",
                "gpsWaypointAccuracy"
            })
            public static class Item {

                @XmlElement(name = "Id", required = true)
                protected String id;
                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Description", required = true)
                protected String description;
                @XmlElement(name = "Keywords", required = true)
                protected String keywords;
                @XmlElement(name = "Tag0", required = true)
                protected String tag0;
                @XmlElement(name = "Tag1", required = true)
                protected String tag1;
                @XmlElement(name = "Tag2", required = true)
                protected String tag2;
                @XmlElement(name = "Tag3", required = true)
                protected String tag3;
                @XmlElement(name = "Tag4", required = true)
                protected String tag4;
                @XmlElement(name = "Tag5", required = true)
                protected String tag5;
                @XmlElement(name = "Tag6", required = true)
                protected String tag6;
                @XmlElement(name = "Tag7", required = true)
                protected String tag7;
                @XmlElement(name = "Alias0", required = true)
                protected String alias0;
                @XmlElement(name = "Alias1", required = true)
                protected String alias1;
                @XmlElement(name = "Alias2", required = true)
                protected String alias2;
                @XmlElement(name = "GpsAccuracyEnabled", required = true)
                protected String gpsAccuracyEnabled;
                @XmlElement(name = "GpsSightingAccuracy")
                protected GpsSightingAccuracy gpsSightingAccuracy;
                @XmlElement(name = "GpsWaypointAccuracy")
                protected GpsWaypointAccuracy gpsWaypointAccuracy;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the keywords property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKeywords() {
                    return keywords;
                }

                /**
                 * Sets the value of the keywords property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKeywords(String value) {
                    this.keywords = value;
                }

                /**
                 * Gets the value of the tag0 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag0() {
                    return tag0;
                }

                /**
                 * Sets the value of the tag0 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag0(String value) {
                    this.tag0 = value;
                }

                /**
                 * Gets the value of the tag1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag1() {
                    return tag1;
                }

                /**
                 * Sets the value of the tag1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag1(String value) {
                    this.tag1 = value;
                }

                /**
                 * Gets the value of the tag2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag2() {
                    return tag2;
                }

                /**
                 * Sets the value of the tag2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag2(String value) {
                    this.tag2 = value;
                }

                /**
                 * Gets the value of the tag3 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag3() {
                    return tag3;
                }

                /**
                 * Sets the value of the tag3 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag3(String value) {
                    this.tag3 = value;
                }

                /**
                 * Gets the value of the tag4 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag4() {
                    return tag4;
                }

                /**
                 * Sets the value of the tag4 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag4(String value) {
                    this.tag4 = value;
                }

                /**
                 * Gets the value of the tag5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag5() {
                    return tag5;
                }

                /**
                 * Sets the value of the tag5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag5(String value) {
                    this.tag5 = value;
                }

                /**
                 * Gets the value of the tag6 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag6() {
                    return tag6;
                }

                /**
                 * Sets the value of the tag6 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag6(String value) {
                    this.tag6 = value;
                }

                /**
                 * Gets the value of the tag7 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag7() {
                    return tag7;
                }

                /**
                 * Sets the value of the tag7 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag7(String value) {
                    this.tag7 = value;
                }

                /**
                 * Gets the value of the alias0 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlias0() {
                    return alias0;
                }

                /**
                 * Sets the value of the alias0 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlias0(String value) {
                    this.alias0 = value;
                }

                /**
                 * Gets the value of the alias1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlias1() {
                    return alias1;
                }

                /**
                 * Sets the value of the alias1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlias1(String value) {
                    this.alias1 = value;
                }

                /**
                 * Gets the value of the alias2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlias2() {
                    return alias2;
                }

                /**
                 * Sets the value of the alias2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlias2(String value) {
                    this.alias2 = value;
                }

                /**
                 * Gets the value of the gpsAccuracyEnabled property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGpsAccuracyEnabled() {
                    return gpsAccuracyEnabled;
                }

                /**
                 * Sets the value of the gpsAccuracyEnabled property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGpsAccuracyEnabled(String value) {
                    this.gpsAccuracyEnabled = value;
                }

                /**
                 * Gets the value of the gpsSightingAccuracy property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GpsSightingAccuracy }
                 *     
                 */
                public GpsSightingAccuracy getGpsSightingAccuracy() {
                    return gpsSightingAccuracy;
                }

                /**
                 * Sets the value of the gpsSightingAccuracy property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GpsSightingAccuracy }
                 *     
                 */
                public void setGpsSightingAccuracy(GpsSightingAccuracy value) {
                    this.gpsSightingAccuracy = value;
                }

                /**
                 * Gets the value of the gpsWaypointAccuracy property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GpsWaypointAccuracy }
                 *     
                 */
                public GpsWaypointAccuracy getGpsWaypointAccuracy() {
                    return gpsWaypointAccuracy;
                }

                /**
                 * Sets the value of the gpsWaypointAccuracy property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GpsWaypointAccuracy }
                 *     
                 */
                public void setGpsWaypointAccuracy(GpsWaypointAccuracy value) {
                    this.gpsWaypointAccuracy = value;
                }

            }

        }

    }

}
