
/* Drop Tables */

DROP TABLE SUMMARY_QUERY;
DROP TABLE WAYPOINT_QUERY;
DROP TABLE QUERY_FOLDER;




/* Create Tables */

CREATE TABLE QUERY_FOLDER
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	EMPLOYEE_UUID CHAR(16),
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	-- for bit data
	PARENT_UUID CHAR(16),
	PRIMARY KEY (UUID)
);


CREATE TABLE SUMMARY_QUERY
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	CREATOR_UUID CHAR(16) NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	CA_FILTER VARCHAR(32672),
	QUERY_DEF VARBINARY(32672),
	-- for bit data
	FOLDER_UUID CHAR(16),
	SHARED BOOLEAN NOT NULL,
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	PRIMARY KEY (UUID)
);


CREATE TABLE WAYPOINT_QUERY
(
	-- for bit data
	UUID CHAR(16) NOT NULL,
	-- for bit data
	CREATOR_UUID CHAR(16) NOT NULL,
	NAME VARCHAR(1024) NOT NULL,
	QUERY_FILTER VARCHAR(32672),
	CA_FILTER VARCHAR(32672),
	-- for bit data
	CA_UUID CHAR(16) NOT NULL,
	-- for bit data
	-- 
	FOLDER_UUID CHAR(16),
	SHARED BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (UUID)
);



/* Create Foreign Keys */

ALTER TABLE QUERY_FOLDER
	ADD FOREIGN KEY (PARENT_UUID)
	REFERENCES QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SUMMARY_QUERY
	ADD FOREIGN KEY (FOLDER_UUID)
	REFERENCES QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WAYPOINT_QUERY
	ADD FOREIGN KEY (FOLDER_UUID)
	REFERENCES QUERY_FOLDER (UUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



