/*
 * Copyright (C) 2017 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.qa.model;

import org.wcs.smart.ca.UuidItem;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Model class of qa_routine_parameter.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="qa_routine_parameter", schema="smart")
public class QaRoutineParameter extends UuidItem{

	private static final long serialVersionUID = 1L;
	
	private QaRoutine routine;
	private String parameterId;
	
	private String stringValue;
	private byte[] byteValue;

	/**
	 * Constructor.
	 */
	public QaRoutineParameter() {
	}


	/**
	 * Get the parameter identifier
	 * 
	 * @return id
	 */
	@Column(name="id")
	public String getParameterId() {
		return this.parameterId;
	}

	/**
	 * Set the parameter identifier
	 * 
	 * @param id
	 */
	public void setParameterId(String id) {
		this.parameterId = id;
	}


	/**
	 * Get the string parameter value.
	 * 
	 * @return value
	 */
	@Column(name="str_value")
	public String getStringValue() {
		return this.stringValue;
	}
	
	/**
	 * Set the string parameter value
	 * 
	 * @param value
	 */
	public void setStringValue(String value) {
		this.stringValue = value;
	}
	
	/**
	 * Get the byte parameter value.
	 * 
	 * @return value
	 */
	@Column(name="byte_value")
	@Lob
	public byte[] getByteValue() {
		return this.byteValue;
	}
	
	/**
	 * Set the byte parameter value
	 * 
	 * @param value
	 */
	public void setByteValue(byte[] value) {
		this.byteValue = value;
	}
	
	/**
	 * Get the value.
	 * 
	 * @return value
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="qa_routine_uuid", referencedColumnName="uuid")
	public QaRoutine getQaRoutine() {
		return this.routine;
	}
	
	/**
	 * Set the parameter value
	 * 
	 * @param value
	 */
	public void setQaRoutine(QaRoutine routine) {
		this.routine = routine;
	}

}
