source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               html/,\
               toc.xml,\
               OSGI-INF/l10n/bundle.properties
