//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.19 at 01:48:48 PM PDT 
//


package org.wcs.smart.datagenerator.er.model.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for BoundingBoxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BoundingBoxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="x_min" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y_min" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="x_max" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y_max" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="area_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundingBoxType")
public class BoundingBoxType {

    @XmlAttribute(name = "x_min")
    protected Double xMin;
    @XmlAttribute(name = "y_min")
    protected Double yMin;
    @XmlAttribute(name = "x_max")
    protected Double xMax;
    @XmlAttribute(name = "y_max")
    protected Double yMax;
    @XmlAttribute(name = "area_type")
    protected String areaType;

    /**
     * Gets the value of the xMin property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXMin() {
        return xMin;
    }

    /**
     * Sets the value of the xMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXMin(Double value) {
        this.xMin = value;
    }

    /**
     * Gets the value of the yMin property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYMin() {
        return yMin;
    }

    /**
     * Sets the value of the yMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYMin(Double value) {
        this.yMin = value;
    }

    /**
     * Gets the value of the xMax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getXMax() {
        return xMax;
    }

    /**
     * Sets the value of the xMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setXMax(Double value) {
        this.xMax = value;
    }

    /**
     * Gets the value of the yMax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getYMax() {
        return yMax;
    }

    /**
     * Sets the value of the yMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setYMax(Double value) {
        this.yMax = value;
    }

    /**
     * Gets the value of the areaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * Sets the value of the areaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaType(String value) {
        this.areaType = value;
    }

}
