//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.19 at 01:48:48 PM PDT 
//


package org.wcs.smart.datagenerator.er.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wcs.smart.datagenerator.er.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SurveyGeneratorConfiguration_QNAME = new QName("http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration", "SurveyGeneratorConfiguration"); //$NON-NLS-1$ //$NON-NLS-2$

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wcs.smart.datagenerator.er.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SurveyGeneratorConfiguration }
     * 
     */
    public SurveyGeneratorConfiguration createSurveyGeneratorConfiguration() {
        return new SurveyGeneratorConfiguration();
    }

    /**
     * Create an instance of {@link BoundingBoxType }
     * 
     */
    public BoundingBoxType createBoundingBoxType() {
        return new BoundingBoxType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ObservationMappingType }
     * 
     */
    public ObservationMappingType createObservationMappingType() {
        return new ObservationMappingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurveyGeneratorConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration", name = "SurveyGeneratorConfiguration")
    public JAXBElement<SurveyGeneratorConfiguration> createSurveyGeneratorConfiguration(SurveyGeneratorConfiguration value) {
        return new JAXBElement<SurveyGeneratorConfiguration>(_SurveyGeneratorConfiguration_QNAME, SurveyGeneratorConfiguration.class, null, value);
    }

}
