/*
 * Copyright (C) 2016 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.cybertracker.importer.json;

import java.io.Reader;
import java.lang.reflect.InvocationTargetException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.apache.commons.io.IOUtils;
import org.eclipse.core.runtime.IConfigurationElement;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.Platform;
import org.eclipse.core.runtime.SubMonitor;
import org.eclipse.jface.dialogs.IDialogConstants;
import org.eclipse.jface.dialogs.ProgressMonitorDialog;
import org.eclipse.jface.operation.IRunnableWithProgress;
import org.eclipse.swt.widgets.Display;
import org.hibernate.Session;
import org.json.simple.JSONObject;
import org.wcs.smart.common.attachment.AttachmentInterceptor;
import org.wcs.smart.common.control.WarningDialog;
import org.wcs.smart.cybertracker.CyberTrackerPlugIn;
import org.wcs.smart.cybertracker.internal.Messages;
import org.wcs.smart.cybertracker.json.CtJsonUtil;
import org.wcs.smart.cybertracker.json.IJsonPostProcessor;
import org.wcs.smart.cybertracker.json.UserCancelledException;
import org.wcs.smart.hibernate.HibernateManager;

/**
 * Cybertracker JSON File Processor.   
 * 
 * @author Emily
 *
 */
public class JsonFileProcessor {
	
	private static volatile List<IDesktopJsonProcessor> jsonProcessors;
	private static volatile List<IJsonPostProcessor> jsonPostProcessors;
	
	/**
	 * Status of the file processed
	 * 
	 */
	public enum FileStatus{
		OK, 
		CANCELLED,
		NO_DATA,
		ERROR
	}

	/**
	 * Tracks a file and associated processing state including any messages and errors
	 * generated by processing
	 */
	public class FileState{
		Path file;
		FileStatus status;
		String message;
		Throwable ex;
		
		public FileState(Path file, FileStatus status, String message, Exception ex) {
			this.file = file;
			this.status = status;
			this.message = message;
			this.ex = ex;
		}
		public FileState(Path file, FileStatus status, String message) {
			this(file, status, message, null);
		}
		
		public FileState(Path file, FileStatus status) {
			this(file, status, ""); //$NON-NLS-1$
		}
		public FileState(Path file) {
			this(file, null, ""); //$NON-NLS-1$
		}
		
		public FileStatus getStatus() {
			return this.status;
		}
		public String getMessage() {
			return this.message;
		}
		public Throwable getException() {
			return this.ex;
		}
	}
	
	/**
	 * Creates a new processor
	 */
	public JsonFileProcessor() {
	}

	/**
	 * Processes a list of json files
	 * 
	 * @param files
	 * @return
	 */
	public HashMap<Path, FileState> process(List<Path> files) {
		final HashMap<Path, FileState> results = new HashMap<>();
		
		ProgressMonitorDialog dialog = new ProgressMonitorDialog(Display.getDefault().getActiveShell());
		try {
			dialog.run(true, true, new IRunnableWithProgress() {

				@Override
				public void run(IProgressMonitor monitor) throws InvocationTargetException, InterruptedException {
				
					SubMonitor progress = SubMonitor.convert(monitor, files.size());
					progress.setTaskName(Messages.JsonFileProcessor_TaskName);
					
					try(Session session = HibernateManager.openSession(new AttachmentInterceptor())){
						for (Path p : files) {
							try {
								FileState returnValue = process(p, session, progress.split(1));
								if (returnValue.ex != null) {
									CyberTrackerPlugIn.log(returnValue.ex.getMessage(), returnValue.ex);
								}
								results.put(p, returnValue);
							}catch(UserCancelledException cancelled) {
								throw cancelled;
							}
						}
					}catch (UserCancelledException ex) {
						for (Path p : files) {
							if (!results.containsKey(p)) {
								results.put(p, new FileState(p, FileStatus.CANCELLED));
							}
						}
					}
					postProcess();
				}
				
			});
		} catch (Exception e) {
			CyberTrackerPlugIn.displayError(Messages.JsonFileProcessor_ErrorTitle, e.getMessage(), e);
		}
		
		//summarize results with option to reprocess individual files
		return results;
	}
	
	private FileState process(Path file, Session session, IProgressMonitor monitor) throws UserCancelledException {
		String json = null;
		try(Reader in = Files.newBufferedReader(file, StandardCharsets.UTF_8)){
			json = IOUtils.toString(in);
		}catch (Exception ex) {
			return new FileState(file, FileStatus.ERROR, MessageFormat.format(Messages.JsonFileProcessor_InvalidJsonFile, ex.getMessage()), ex);
		}
		
		FileState returnValue = new FileState(file);
		
		final List<JSONObject> features = new ArrayList<>();;
		try {
			features.addAll(CtJsonUtil.parseFeaturesFromJsonString(json));
		}catch (Throwable ex) {
			returnValue.ex = ex;
			returnValue.status = FileStatus.ERROR;
			returnValue.message = MessageFormat.format(Messages.JsonFileProcessor_ParseError, ex.getMessage());
			return returnValue;
		}
		
		
		session.beginTransaction();
		try {
			List<JSONObject> notProc = new ArrayList<JSONObject>();
			notProc.addAll(features);
			
			
			List<IDesktopJsonProcessor> processors = getProcessors();
			
			StringBuilder statusMsg = new StringBuilder();
			for (IDesktopJsonProcessor p : processors){
				List<JSONObject> processed = p.processJson(features, session);
				notProc.removeAll(processed);
				String msg = p.getStatusMessage();
				if (msg != null){
					statusMsg.append(msg);
				}
			}
	
			returnValue.message = statusMsg.toString();
				
			if (notProc.size() == features.size()){
				//nothing has been processed perhaps we re-queue this item
				//for later as maybe something else needs to be processed first
				session.getTransaction().rollback();
				returnValue.message = Messages.JsonFileProcessor_NoDataProcessed;
				returnValue.status = FileStatus.NO_DATA;
				return returnValue;
			}
				
			final boolean[] cont = new boolean[]{true};			
			if (!notProc.isEmpty()){
				//not all items have been processed
				final List<String> warnings = new ArrayList<String>();
				for (JSONObject o : notProc){
					warnings.add(o.toJSONString());
				}	
				Display.getDefault().syncExec(new Runnable(){
					@Override
					public void run() {
						String message = MessageFormat.format(Messages.JsonFileProcessor_FeaturesProcessed, features.size() - notProc.size(), features.size(), notProc.size() );
						WarningDialog wd = new WarningDialog(Display.getDefault().getActiveShell(),Messages.JsonFileProcessor_WarningTitle, message,
								warnings, new String[]{IDialogConstants.YES_LABEL, IDialogConstants.NO_LABEL}, 1);
						if (wd.open() == 0){
							cont[0] = true;
						}else{
							cont[0] = false;
						}
					}
					
				});
				}
			
			if (!cont[0]){
				returnValue.message = Messages.JsonFileProcessor_DataMissing;
				returnValue.status = FileStatus.CANCELLED;
				return returnValue;
			}
			session.getTransaction().commit();

			for (IDesktopJsonProcessor p : processors){
				try{
					p.afterSave();
				}catch (Throwable t){
					returnValue.message = Messages.JsonFileProcessor_DataSavedRefreshError + returnValue.message;
					returnValue.ex = t;
					returnValue.status = FileStatus.ERROR;
					return returnValue;
				}
			}
			//done ok file loaded
			returnValue.status = FileStatus.OK;
			return returnValue;
		}catch (UserCancelledException ex){
			session.getTransaction().rollback();
			throw ex;
	
		}catch (Throwable ex){
			if (session.getTransaction().isActive()) session.getTransaction().rollback();
			returnValue.message = Messages.JsonFileProcessor_ErrorMessage + ex.getMessage();
			returnValue.ex = ex;
			returnValue.status = FileStatus.ERROR;
			return returnValue;
		}
	
	}
	
	private void postProcess() {
		try (Session session = HibernateManager.openSession()){
			for (IJsonPostProcessor p : getPostProcessors()) {
				try {
					p.postProcess(session);
				}catch (Exception ex) {
					CyberTrackerPlugIn.log(ex.getMessage(), ex);
				}
			}
		}catch (Exception ex) {
			CyberTrackerPlugIn.log(ex.getMessage(), ex);
		}
	}

	private static List<IDesktopJsonProcessor> getProcessors() throws Exception{
		if (jsonProcessors == null){
			synchronized (JsonFileProcessor.class) {
				if (jsonProcessors == null){
					ArrayList<IDesktopJsonProcessor> temp = new ArrayList<IDesktopJsonProcessor>();
					IConfigurationElement[] config = Platform.getExtensionRegistry()
							.getConfigurationElementsFor(IDesktopJsonProcessor.EXTENSION_ID);
					
					for (IConfigurationElement e : config) {
						if (e.getName().equalsIgnoreCase("JsonProcessor")){ //$NON-NLS-1$
							IDesktopJsonProcessor proc = (IDesktopJsonProcessor) e.createExecutableExtension("class"); //$NON-NLS-1$
							temp.add(proc);
						}
					}
					jsonProcessors = temp;
				}
			}
			
		}
		List<IDesktopJsonProcessor> copy = new ArrayList<IDesktopJsonProcessor>(jsonProcessors.size());
		for (IDesktopJsonProcessor p : jsonProcessors){
			copy.add(p.getClass().getConstructor().newInstance());
		}
		return copy;
	}
	
	private static List<IJsonPostProcessor> getPostProcessors() throws Exception{
		if (jsonPostProcessors == null){
			synchronized (JsonFileProcessor.class) {
				if (jsonPostProcessors == null){
					ArrayList<IJsonPostProcessor> temp2 = new ArrayList<IJsonPostProcessor>();					
					IConfigurationElement[] config = Platform.getExtensionRegistry()
							.getConfigurationElementsFor(IDesktopJsonProcessor.EXTENSION_ID);
					
					for (IConfigurationElement e : config) {
						if (e.getName().equalsIgnoreCase("JsonPostProcessor")){ //$NON-NLS-1$
							IJsonPostProcessor proc = (IJsonPostProcessor) e.createExecutableExtension("class"); //$NON-NLS-1$
							temp2.add(proc);
						}
					}
					jsonPostProcessors = temp2;
				}
			}
			
		}
		List<IJsonPostProcessor> copy = new ArrayList<IJsonPostProcessor>(jsonPostProcessors.size());
		for (IJsonPostProcessor p : jsonPostProcessors){
			copy.add(p.getClass().getConstructor().newInstance());
		}
		return copy;
	}
}
