/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.wcs.smart.patrol.query.parser.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_NOT = 8;
  /** RegularExpression Id. */
  int K_OR = 9;
  /** RegularExpression Id. */
  int K_EXACT = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LESS = 12;
  /** RegularExpression Id. */
  int LESSEQUAL = 13;
  /** RegularExpression Id. */
  int GREATER = 14;
  /** RegularExpression Id. */
  int GREATEREQUAL = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int NOTEQUAL = 17;
  /** RegularExpression Id. */
  int NOTEQUAL2 = 18;
  /** RegularExpression Id. */
  int OPENPAREN = 19;
  /** RegularExpression Id. */
  int CLOSEPAREN = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int CONTAINS = 24;
  /** RegularExpression Id. */
  int NOT_CONTAINS = 25;
  /** RegularExpression Id. */
  int STREQUALS = 26;
  /** RegularExpression Id. */
  int BETWEEN = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int AREA = 29;
  /** RegularExpression Id. */
  int PERIMETER = 30;
  /** RegularExpression Id. */
  int NUMBER = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int INTEGER = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int S_CONST_LITERAL = 35;
  /** RegularExpression Id. */
  int CATEGORY_KEY = 36;
  /** RegularExpression Id. */
  int ATT_STR_KEY = 37;
  /** RegularExpression Id. */
  int ATT_VALUE_KEY = 38;
  /** RegularExpression Id. */
  int ATT_BOOL_KEY = 39;
  /** RegularExpression Id. */
  int ATT_LIST_KEY = 40;
  /** RegularExpression Id. */
  int ATT_MLIST_KEY = 41;
  /** RegularExpression Id. */
  int ATT_TREE_KEY = 42;
  /** RegularExpression Id. */
  int ATT_DATE_KEY = 43;
  /** RegularExpression Id. */
  int ATT_TIME_KEY = 44;
  /** RegularExpression Id. */
  int ATT_GEOM_KEY = 45;
  /** RegularExpression Id. */
  int CAT_ATT_STR_KEY = 46;
  /** RegularExpression Id. */
  int CAT_ATT_VALUE_KEY = 47;
  /** RegularExpression Id. */
  int CAT_ATT_BOOL_KEY = 48;
  /** RegularExpression Id. */
  int CAT_ATT_LIST_KEY = 49;
  /** RegularExpression Id. */
  int CAT_ATT_MLIST_KEY = 50;
  /** RegularExpression Id. */
  int CAT_ATT_TREE_KEY = 51;
  /** RegularExpression Id. */
  int CAT_ATT_DATE_KEY = 52;
  /** RegularExpression Id. */
  int CAT_ATT_TIME_KEY = 53;
  /** RegularExpression Id. */
  int CAT_ATT_GEOM_KEY = 54;
  /** RegularExpression Id. */
  int DATE_STRING = 55;
  /** RegularExpression Id. */
  int TIME_STRING = 56;
  /** RegularExpression Id. */
  int DM_KEY = 57;
  /** RegularExpression Id. */
  int HEX_STRING = 58;
  /** RegularExpression Id. */
  int LETTER = 59;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 60;
  /** RegularExpression Id. */
  int PATROL_ARMED_KEY = 61;
  /** RegularExpression Id. */
  int PATROL_ID_KEY = 62;
  /** RegularExpression Id. */
  int PATROL_UUID_KEY = 63;
  /** RegularExpression Id. */
  int PATROL_STATION_KEY = 64;
  /** RegularExpression Id. */
  int PATROL_TEAM_KEY = 65;
  /** RegularExpression Id. */
  int PATROL_TEAM_KEY_KEY = 66;
  /** RegularExpression Id. */
  int PATROL_MANDATE_KEY = 67;
  /** RegularExpression Id. */
  int PATROL_MANDATE_KEY_KEY = 68;
  /** RegularExpression Id. */
  int PATROL_TYPE_KEY = 69;
  /** RegularExpression Id. */
  int PATROL_CA_KEY = 70;
  /** RegularExpression Id. */
  int PATROLLEG_TRANSPORT_KEY = 71;
  /** RegularExpression Id. */
  int PATROLLEG_TRANSPORT_KEY_KEY = 72;
  /** RegularExpression Id. */
  int PATROLLEG_TRANSPORT_GROUP_KEY_KEY = 73;
  /** RegularExpression Id. */
  int PATROL_TRANSPORT_GROUP_KEY_KEY = 74;
  /** RegularExpression Id. */
  int PATROLLEG_LEADER_KEY = 75;
  /** RegularExpression Id. */
  int PATROLLEG_PILOT_KEY = 76;
  /** RegularExpression Id. */
  int PATROLLEG_MEMBER_KEY = 77;
  /** RegularExpression Id. */
  int PATROLLEG_AGENCY_KEY = 78;
  /** RegularExpression Id. */
  int PATROLLEG_AGENCY_KEY_KEY = 79;
  /** RegularExpression Id. */
  int PATROLLEG_RANK_KEY = 80;
  /** RegularExpression Id. */
  int WAYPOINT_CM_KEY = 81;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_BOOLEAN_KEY = 82;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_STRING_KEY = 83;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_LIST_KEY = 84;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_TREE_KEY = 85;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_NUMBER_KEY = 86;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_DATE_KEY = 87;
  /** RegularExpression Id. */
  int PATROL_CONTRIBUTION = 88;
  /** RegularExpression Id. */
  int PATROL_CONTRIBUTION_BOOL_KEY = 89;
  /** RegularExpression Id. */
  int PATROL_CONTRIBUTION_STRING_KEY = 90;
  /** RegularExpression Id. */
  int AREA_TYPE_KEY = 91;
  /** RegularExpression Id. */
  int AREA_KEY = 92;
  /** RegularExpression Id. */
  int OBSERVATION_FILTER_TYPE_KEY = 93;
  /** RegularExpression Id. */
  int WAYPOINT_FILTER_TYPE_KEY = 94;
  /** RegularExpression Id. */
  int PATROL_VALUE_ITEM = 95;
  /** RegularExpression Id. */
  int PATROL_VALUE_KEY = 96;
  /** RegularExpression Id. */
  int PATROL_VALUE_ENCOUNTERRATE_KEY = 97;
  /** RegularExpression Id. */
  int SUM_CAT_VALUE_KEY = 98;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_KEY = 99;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_KEY = 100;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_GEOMETRY_KEY = 101;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_GEOMETRY_KEY = 102;
  /** RegularExpression Id. */
  int SUM_ATTRIBUTE_VALUE_LISTTREE_KEY = 103;
  /** RegularExpression Id. */
  int SUM_CAT_ATT_VALUE_LISTTREE_KEY = 104;
  /** RegularExpression Id. */
  int AGG = 105;
  /** RegularExpression Id. */
  int DATE_GROUPBY_ITEM = 106;
  /** RegularExpression Id. */
  int QUERY_SPLITTER = 107;
  /** RegularExpression Id. */
  int PATROL_UUID_GROUPBY_OPTION = 108;
  /** RegularExpression Id. */
  int PATROL_CONTRIBUTION_GROUPBY_OPTION = 109;
  /** RegularExpression Id. */
  int PATROL_STRING_GROUPBY_OPTION = 110;
  /** RegularExpression Id. */
  int CATEGORY_GROUPBY_ITEM = 111;
  /** RegularExpression Id. */
  int AREA_GROUPBY_ITEM = 112;
  /** RegularExpression Id. */
  int ATTRIBUTE_GROUPBY_ITEM = 113;
  /** RegularExpression Id. */
  int CATEGORY_ATTRIBUTE_GROUPBY_ITEM = 114;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_LIST_GROUPBYITEM = 115;
  /** RegularExpression Id. */
  int PATROL_ATTRIBUTE_TREE_GROUPBYITEM = 116;
  /** RegularExpression Id. */
  int QUOTED_STRING = 117;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"not\"",
    "\"or\"",
    "\"exact\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"contains\"",
    "\"notcontains\"",
    "\"equals\"",
    "\"between\"",
    "\":\"",
    "\"area\"",
    "\"perimeter\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_CONST_LITERAL>",
    "<CATEGORY_KEY>",
    "<ATT_STR_KEY>",
    "<ATT_VALUE_KEY>",
    "<ATT_BOOL_KEY>",
    "<ATT_LIST_KEY>",
    "<ATT_MLIST_KEY>",
    "<ATT_TREE_KEY>",
    "<ATT_DATE_KEY>",
    "<ATT_TIME_KEY>",
    "<ATT_GEOM_KEY>",
    "<CAT_ATT_STR_KEY>",
    "<CAT_ATT_VALUE_KEY>",
    "<CAT_ATT_BOOL_KEY>",
    "<CAT_ATT_LIST_KEY>",
    "<CAT_ATT_MLIST_KEY>",
    "<CAT_ATT_TREE_KEY>",
    "<CAT_ATT_DATE_KEY>",
    "<CAT_ATT_TIME_KEY>",
    "<CAT_ATT_GEOM_KEY>",
    "<DATE_STRING>",
    "<TIME_STRING>",
    "<DM_KEY>",
    "<HEX_STRING>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "\"patrol:armed\"",
    "\"patrol:id\"",
    "\"patrol:uuid\"",
    "\"patrol:station\"",
    "\"patrol:team\"",
    "\"patrol:teamkey\"",
    "\"patrol:mandate\"",
    "\"patrol:mandatekey\"",
    "\"patrol:patroltype\"",
    "\"patrol:ca\"",
    "\"patrol:transport\"",
    "\"patrol:transportkey\"",
    "\"patrol:transgroupkey\"",
    "\"patrol:patroltransgroupkey\"",
    "\"patrol:leader\"",
    "\"patrol:pilot\"",
    "\"patrol:member\"",
    "\"patrol:agency\"",
    "\"patrol:agencykey\"",
    "\"patrol:rank\"",
    "\"waypoint:cm\"",
    "<PATROL_ATTRIBUTE_BOOLEAN_KEY>",
    "<PATROL_ATTRIBUTE_STRING_KEY>",
    "<PATROL_ATTRIBUTE_LIST_KEY>",
    "<PATROL_ATTRIBUTE_TREE_KEY>",
    "<PATROL_ATTRIBUTE_NUMBER_KEY>",
    "<PATROL_ATTRIBUTE_DATE_KEY>",
    "\"patrol:contribution\"",
    "<PATROL_CONTRIBUTION_BOOL_KEY>",
    "<PATROL_CONTRIBUTION_STRING_KEY>",
    "<AREA_TYPE_KEY>",
    "<AREA_KEY>",
    "\"observation\"",
    "\"waypoint\"",
    "<PATROL_VALUE_ITEM>",
    "<PATROL_VALUE_KEY>",
    "<PATROL_VALUE_ENCOUNTERRATE_KEY>",
    "<SUM_CAT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_VALUE_KEY>",
    "<SUM_CAT_ATT_VALUE_KEY>",
    "<SUM_ATTRIBUTE_GEOMETRY_KEY>",
    "<SUM_CAT_ATT_GEOMETRY_KEY>",
    "<SUM_ATTRIBUTE_VALUE_LISTTREE_KEY>",
    "<SUM_CAT_ATT_VALUE_LISTTREE_KEY>",
    "<AGG>",
    "<DATE_GROUPBY_ITEM>",
    "\"|\"",
    "<PATROL_UUID_GROUPBY_OPTION>",
    "<PATROL_CONTRIBUTION_GROUPBY_OPTION>",
    "<PATROL_STRING_GROUPBY_OPTION>",
    "<CATEGORY_GROUPBY_ITEM>",
    "<AREA_GROUPBY_ITEM>",
    "<ATTRIBUTE_GROUPBY_ITEM>",
    "<CATEGORY_ATTRIBUTE_GROUPBY_ITEM>",
    "<PATROL_ATTRIBUTE_LIST_GROUPBYITEM>",
    "<PATROL_ATTRIBUTE_TREE_GROUPBYITEM>",
    "<QUOTED_STRING>",
  };

}
