//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 10:12:51 AM PDT 
//


package org.wcs.smart.cybertracker.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Elements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="E" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Static" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Tag_0" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sightings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="S" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="A" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="V" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elements",
    "sightings"
})
@XmlRootElement(name = "Data")
public class Data {

    @XmlElement(name = "Elements", required = true)
    protected Data.Elements elements;
    @XmlElement(name = "Sightings", required = true)
    protected Data.Sightings sightings;

    /**
     * Gets the value of the elements property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Elements }
     *     
     */
    public Data.Elements getElements() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Elements }
     *     
     */
    public void setElements(Data.Elements value) {
        this.elements = value;
    }

    /**
     * Gets the value of the sightings property.
     * 
     * @return
     *     possible object is
     *     {@link Data.Sightings }
     *     
     */
    public Data.Sightings getSightings() {
        return sightings;
    }

    /**
     * Sets the value of the sightings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data.Sightings }
     *     
     */
    public void setSightings(Data.Sightings value) {
        this.sightings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="E" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Static" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Tag_0" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "e"
    })
    public static class Elements {

        @XmlElement(name = "E")
        protected List<Data.Elements.E> e;

        /**
         * Gets the value of the e property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the e property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Elements.E }
         * 
         * 
         */
        public List<Data.Elements.E> getE() {
            if (e == null) {
                e = new ArrayList<Data.Elements.E>();
            }
            return this.e;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Static" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Tag_0" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class E {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "I")
            protected String i;
            @XmlAttribute(name = "N")
            protected String n;
            @XmlAttribute(name = "Static")
            protected Integer _static;
            @XmlAttribute(name = "Tag_0")
            protected String tag0;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the i property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getI() {
                return i;
            }

            /**
             * Sets the value of the i property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setI(String value) {
                this.i = value;
            }

            /**
             * Gets the value of the n property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getN() {
                return n;
            }

            /**
             * Sets the value of the n property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setN(String value) {
                this.n = value;
            }

            /**
             * Gets the value of the static property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStatic() {
                return _static;
            }

            /**
             * Sets the value of the static property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStatic(Integer value) {
                this._static = value;
            }

            /**
             * Gets the value of the tag0 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTag0() {
                return tag0;
            }

            /**
             * Sets the value of the tag0 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTag0(String value) {
                this.tag0 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="S" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="A" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="V" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s"
    })
    public static class Sightings {

        @XmlElement(name = "S")
        protected List<Data.Sightings.S> s;

        /**
         * Gets the value of the s property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Data.Sightings.S }
         * 
         * 
         */
        public List<Data.Sightings.S> getS() {
            if (s == null) {
                s = new ArrayList<Data.Sightings.S>();
            }
            return this.s;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="A" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="V" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "a"
        })
        public static class S {

            @XmlElement(name = "A")
            protected List<Data.Sightings.S.A> a;

            /**
             * Gets the value of the a property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the a property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getA().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Data.Sightings.S.A }
             * 
             * 
             */
            public List<Data.Sightings.S.A> getA() {
                if (a == null) {
                    a = new ArrayList<Data.Sightings.S.A>();
                }
                return this.a;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="I" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="V" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class A {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "I")
                protected String i;
                @XmlAttribute(name = "N")
                protected String n;
                @XmlAttribute(name = "V")
                protected String v;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the i property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getI() {
                    return i;
                }

                /**
                 * Sets the value of the i property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setI(String value) {
                    this.i = value;
                }

                /**
                 * Gets the value of the n property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getN() {
                    return n;
                }

                /**
                 * Sets the value of the n property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setN(String value) {
                    this.n = value;
                }

                /**
                 * Gets the value of the v property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getV() {
                    return v;
                }

                /**
                 * Sets the value of the v property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setV(String value) {
                    this.v = value;
                }

            }

        }

    }

}
