//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 10:44:02 AM PDT 
//


package org.wcs.smart.cybertracker.model.filter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Categories.Items.Item }
     * 
     */
    public Categories.Items.Item createCategoriesItemsItem() {
        return new Categories.Items.Item();
    }

    /**
     * Create an instance of {@link ElementFilters.Items.Item }
     * 
     */
    public ElementFilters.Items.Item createElementFiltersItemsItem() {
        return new ElementFilters.Items.Item();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ElementFilters.Items.Item.CheckedElements }
     * 
     */
    public ElementFilters.Items.Item.CheckedElements createElementFiltersItemsItemCheckedElements() {
        return new ElementFilters.Items.Item.CheckedElements();
    }

    /**
     * Create an instance of {@link ElementFilters.Items }
     * 
     */
    public ElementFilters.Items createElementFiltersItems() {
        return new ElementFilters.Items();
    }

    /**
     * Create an instance of {@link Categories.Items }
     * 
     */
    public Categories.Items createCategoriesItems() {
        return new Categories.Items();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link ElementFilters }
     * 
     */
    public ElementFilters createElementFilters() {
        return new ElementFilters();
    }

}
