//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 11:48:12 AM PDT 
//


package org.wcs.smart.ct2smart.matcher.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ct2Attribute" type="{}Ct2Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CtCategory" type="{}CtCategory" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ct2Attribute",
    "ctCategory"
})
@XmlRootElement(name = "Ct2Smart")
public class Ct2Smart {

    @XmlElement(name = "Ct2Attribute")
    protected List<Ct2Attribute> ct2Attribute;
    @XmlElement(name = "CtCategory")
    protected List<CtCategory> ctCategory;

    /**
     * Gets the value of the ct2Attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ct2Attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCt2Attribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ct2Attribute }
     * 
     * 
     */
    public List<Ct2Attribute> getCt2Attribute() {
        if (ct2Attribute == null) {
            ct2Attribute = new ArrayList<Ct2Attribute>();
        }
        return this.ct2Attribute;
    }

    /**
     * Gets the value of the ctCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ctCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCtCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtCategory }
     * 
     * 
     */
    public List<CtCategory> getCtCategory() {
        if (ctCategory == null) {
            ctCategory = new ArrayList<CtCategory>();
        }
        return this.ctCategory;
    }

}
