//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 01:42:59 PM PDT 
//


package org.wcs.smart.er.xml.model.missions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wcs.smart.er.xml.model.missions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mission_QNAME = new QName("http://www.example.org/Mission/", "Mission");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wcs.smart.er.xml.model.missions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MissionType }
     * 
     */
    public MissionType createMissionType() {
        return new MissionType();
    }

    /**
     * Create an instance of {@link TracksType }
     * 
     */
    public TracksType createTracksType() {
        return new TracksType();
    }

    /**
     * Create an instance of {@link SurveyWaypointsType }
     * 
     */
    public SurveyWaypointsType createSurveyWaypointsType() {
        return new SurveyWaypointsType();
    }

    /**
     * Create an instance of {@link WaypointObservationType }
     * 
     */
    public WaypointObservationType createWaypointObservationType() {
        return new WaypointObservationType();
    }

    /**
     * Create an instance of {@link MissionPropertyValuesType }
     * 
     */
    public MissionPropertyValuesType createMissionPropertyValuesType() {
        return new MissionPropertyValuesType();
    }

    /**
     * Create an instance of {@link SurveyType }
     * 
     */
    public SurveyType createSurveyType() {
        return new SurveyType();
    }

    /**
     * Create an instance of {@link WaypointType }
     * 
     */
    public WaypointType createWaypointType() {
        return new WaypointType();
    }

    /**
     * Create an instance of {@link MembersType }
     * 
     */
    public MembersType createMembersType() {
        return new MembersType();
    }

    /**
     * Create an instance of {@link MissionDayType }
     * 
     */
    public MissionDayType createMissionDayType() {
        return new MissionDayType();
    }

    /**
     * Create an instance of {@link WaypointObservationAttributeType }
     * 
     */
    public WaypointObservationAttributeType createWaypointObservationAttributeType() {
        return new WaypointObservationAttributeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Mission/", name = "Mission")
    public JAXBElement<MissionType> createMission(MissionType value) {
        return new JAXBElement<MissionType>(_Mission_QNAME, MissionType.class, null, value);
    }

}
