source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/,\
               lib/antlr-2.7.7.jar,\
               lib/c3p0-0.9.5.2.jar,\
               lib/dom4j-1.6.1.jar,\
               lib/derby-10.13.1.1.jar,\
               lib/derbytools-10.13.1.1.jar,\
               lib/ehcache-2.10.3.jar,\
               lib/hibernate-jpa-2.1-api-1.0.0.Final.jar,\
               lib/javassist-3.20.0-GA.jar,\
               lib/jboss-logging-3.3.0.Final.jar,\
               lib/jboss-transaction-api_1.2_spec-1.0.1.Final.jar,\
               lib/mchange-commons-java-0.2.11.jar,\
               lib/classmate-1.3.0.jar,\
               lib/hibernate-c3p0-5.2.10.Final.jar,\
               lib/hibernate-commons-annotations-5.0.1.Final.jar,\
               lib/hibernate-core-5.2.10.Final.jar,\
               lib/hibernate-ehcache-5.2.10.Final.jar,\
               lib/jandex-2.0.3.Final.jar
src.includes = schema/,\
               pom.xml
