source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/,\
               schema/,\
               lib/antlr4-runtime-4.13.0.jar,\
               lib/byte-buddy-1.14.11.jar,\
               lib/c3p0-0.10.0.jar,\
               lib/cache-api-1.0.0.jar,\
               lib/classmate-1.5.1.jar,\
               lib/derby-10.17.1.0.jar,\
               lib/derbyshared-10.17.1.0.jar,\
               lib/derbytools-10.17.1.0.jar,\
               lib/ehcache-3.10.8-jakarta.jar,\
               lib/hibernate-c3p0-6.4.4.Final.jar,\
               lib/hibernate-commons-annotations-6.0.6.Final.jar,\
               lib/hibernate-core-6.4.4.Final.jar,\
               lib/hibernate-jcache-6.4.4.Final.jar,\
               lib/istack-commons-runtime-4.1.1.jar,\
               lib/jakarta.inject-api-2.0.1.jar,\
               lib/jakarta.persistence-api-3.1.0.jar,\
               lib/jakarta.xml.bind-api-4.0.0.jar,\
               lib/jaxb-core-4.0.2.jar,\
               lib/jaxb-runtime-4.0.2.jar,\
               lib/jboss-logging-3.5.0.Final.jar,\
               lib/mchange-commons-java-0.3.0.jar,\
               lib/slf4j-api-1.7.36.jar,\
               lib/txw2-4.0.2.jar,\
               lib/jakarta.activation-api-2.1.0.jar,\
               lib/slf4j-log4j12-1.6.4.jar
src.includes = schema/,\
               pom.xml
