source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/,\
               lib/antlr-2.7.7.jar,\
               lib/c3p0-0.9.5.2.jar,\
               lib/derby-10.12.1.1.jar,\
               lib/derbytools-10.12.1.1.jar,\
               lib/dom4j-1.6.1.jar,\
               lib/ehcache-core-2.4.3.jar,\
               lib/hibernate-c3p0-4.2.18.Final.jar,\
               lib/hibernate-commons-annotations-4.0.2.Final.jar,\
               lib/hibernate-core-4.2.18.Final.jar,\
               lib/hibernate-ehcache-4.2.18.Final.jar,\
               lib/hibernate-jpa-2.0-api-1.0.1.Final.jar,\
               lib/javassist-3.18.1-GA.jar,\
               lib/jboss-logging-3.1.0.GA.jar,\
               lib/jboss-transaction-api_1.1_spec-1.0.1.Final.jar,\
               lib/mchange-commons-java-0.2.11.jar
src.includes = schema/,\
               pom.xml
