#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Smart Data Source ODA Runtime Driver
oda.data.source.id=org.wcs.smart.data.oda.smart
data.source.name=Smart Data Source
data.set.name=Smart Queries Data Set
connection.profile.name=Smart Data Source Connection Profile
