###############################################################################
# Copyright (c) 2012 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.wcs.smart.data.oda.smart
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Smart Data Source ODA Runtime Driver
data.source.name=Smart Data Source
data.set.name=Smart Queries Data Set
connection.profile.name=Smart Data Source Connection Profile
