source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               src/org/wcs/smart/asset/query/model/types/assetincident.html,\
               src/org/wcs/smart/asset/query/model/types/assetobservation.html,\
               src/org/wcs/smart/asset/query/model/types/assetsummary.html,\
               src/org/wcs/smart/asset/query/model/types/assetobservation.png,\
               OSGI-INF/l10n/bundle.properties,\
               src/org/wcs/smart/asset/query/model/types/assetincident.png,\
               src/org/wcs/smart/asset/query/model/types/assetsummary.png
src.includes = images/
