//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 11:28:26 PM MSK 
//


package org.wcs.smart.cybertracker.model.screens;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.smartconservationsoftware.xml._1_0.cybertracker package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.smartconservationsoftware.xml._1_0.cybertracker
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Screens }
     * 
     */
    public Screens createScreens() {
        return new Screens();
    }

    /**
     * Create an instance of {@link Controls }
     * 
     */
    public Controls createControls() {
        return new Controls();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link MovingMaps }
     * 
     */
    public MovingMaps createMovingMaps() {
        return new MovingMaps();
    }

    /**
     * Create an instance of {@link MovingMaps.Items }
     * 
     */
    public MovingMaps.Items createMovingMapsItems() {
        return new MovingMaps.Items();
    }

    /**
     * Create an instance of {@link Screens.Root }
     * 
     */
    public Screens.Root createScreensRoot() {
        return new Screens.Root();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Controls.Control }
     * 
     */
    public Controls.Control createControlsControl() {
        return new Controls.Control();
    }

    /**
     * Create an instance of {@link Node.Items }
     * 
     */
    public Node.Items createNodeItems() {
        return new Node.Items();
    }

    /**
     * Create an instance of {@link Node.Data }
     * 
     */
    public Node.Data createNodeData() {
        return new Node.Data();
    }

    /**
     * Create an instance of {@link MovingMaps.Items.Item }
     * 
     */
    public MovingMaps.Items.Item createMovingMapsItemsItem() {
        return new MovingMaps.Items.Item();
    }

}
