/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.wcs.smart.asset.map.engine.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_OR = 8;
  /** RegularExpression Id. */
  int LESS = 9;
  /** RegularExpression Id. */
  int LESSEQUAL = 10;
  /** RegularExpression Id. */
  int GREATER = 11;
  /** RegularExpression Id. */
  int GREATEREQUAL = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int NOTEQUAL = 14;
  /** RegularExpression Id. */
  int OPENPAREN = 15;
  /** RegularExpression Id. */
  int CLOSEPAREN = 16;
  /** RegularExpression Id. */
  int SLASH = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int CONTAINS = 20;
  /** RegularExpression Id. */
  int STREQUALS = 21;
  /** RegularExpression Id. */
  int BEFORE = 22;
  /** RegularExpression Id. */
  int AFTER = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int LETTER = 28;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 29;
  /** RegularExpression Id. */
  int S_CONST_LITERAL = 30;
  /** RegularExpression Id. */
  int FILTER_OPEN = 31;
  /** RegularExpression Id. */
  int FILTER_CLOSE = 32;
  /** RegularExpression Id. */
  int DM_KEY = 33;
  /** RegularExpression Id. */
  int DATE_STRING = 34;
  /** RegularExpression Id. */
  int QUOTED_STRING = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"contains\"",
    "\"equals\"",
    "\"before\"",
    "\"after\"",
    "<NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CONST_LITERAL>",
    "\"[\"",
    "\"]\"",
    "<DM_KEY>",
    "<DATE_STRING>",
    "<QUOTED_STRING>",
  };

}
