/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.query.updatesite;

import java.sql.Connection;
import java.sql.SQLException;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.jobs.Job;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.swt.widgets.Display;
import org.eclipse.ui.application.DisplayAccess;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.wcs.smart.er.query.ERQueryPlugIn;
import org.wcs.smart.er.query.internal.Messages;
import org.wcs.smart.er.query.upgrade.ERQueryDatabaseUpgrader;
import org.wcs.smart.hibernate.HibernateManager;

/**
 * Job adds Ecological Records plug-in related tabled to the database
 * 
 * @author elitvin
 * @since 1.0.0
 */
public class AddERQueryJob extends Job {

	public AddERQueryJob() {
		super(Messages.AddERQueryJob_JobName);
	}

	@Override
	protected IStatus run(IProgressMonitor monitor) {
		//required if run during restore to ensure Display.syncexec calls don't block
		DisplayAccess.accessDisplayDuringStartup();
				
		Session session = HibernateManager.openSession();
		try{
			session.beginTransaction();
			String currentVersion = HibernateManager.getPlugInVersion(ERQueryPlugIn.PLUGIN_ID, session);
			
			if (currentVersion == null){
				createTables(session);
				HibernateManager.setPlugInVersion(ERQueryPlugIn.PLUGIN_ID, ERQueryPlugIn.DB_VERSION_1, session);
				currentVersion = ERQueryPlugIn.DB_VERSION_1;
			}
			ERQueryDatabaseUpgrader.upgrade(currentVersion, session);
			session.getTransaction().commit();
		}catch(Exception ex){
			if (session.getTransaction().isActive()) session.getTransaction().rollback();
			Display.getDefault().syncExec(new Runnable(){
				@Override
				public void run() {
					MessageDialog.openError(Display.getDefault().getActiveShell(),
							Messages.AddERQueryJob_Errortitle,
							Messages.AddERQueryJob_ErrorMsg);
				}
				
			});
			return new Status(Status.ERROR,ERQueryPlugIn.PLUGIN_ID, "Error installing plugin tables.", ex); //$NON-NLS-1$
		}finally{
			session.close();
		}
		monitor.done();
		return Status.OK_STATUS;
	}

	private void createTables(Session session){
		final String[] sql = new String[]{
				"CREATE TABLE SMART.SURVEY_OBSERVATION_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_FILTER VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA ,COLUMN_FILTER VARCHAR(32672),SURVEYDESIGN_KEY VARCHAR(128),SHARED BOOLEAN NOT NULL,ID VARCHAR(6) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_WAYPOINT_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_FILTER VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA ,COLUMN_FILTER VARCHAR(32672),SURVEYDESIGN_KEY VARCHAR(128),SHARED BOOLEAN NOT NULL,ID VARCHAR(6) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_MISSION_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_FILTER VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA ,COLUMN_FILTER VARCHAR(32672),SURVEYDESIGN_KEY VARCHAR(128),SHARED BOOLEAN NOT NULL,ID VARCHAR(6) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_MISSION_TRACK_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_FILTER VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA ,COLUMN_FILTER VARCHAR(32672),SURVEYDESIGN_KEY VARCHAR(128),SHARED BOOLEAN NOT NULL,ID VARCHAR(6) NOT NULL,PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_GRIDDED_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_FILTER VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA ,QUERY_DEF VARCHAR(32672),SHARED BOOLEAN NOT NULL,ID VARCHAR(6) NOT NULL,CRS_DEFINITION VARCHAR(32672),SURVEYDESIGN_KEY VARCHAR(128),PRIMARY KEY (UUID))", //$NON-NLS-1$
				"CREATE TABLE SMART.SURVEY_SUMMARY_QUERY(UUID CHAR(16) FOR BIT DATA NOT NULL,CREATOR_UUID CHAR(16) FOR BIT DATA NOT NULL,QUERY_DEF VARCHAR(32672),CA_FILTER VARCHAR(32672),CA_UUID CHAR(16) FOR BIT DATA NOT NULL,FOLDER_UUID CHAR(16) FOR BIT DATA , SHARED BOOLEAN NOT NULL, ID VARCHAR(6) NOT NULL, SURVEYDESIGN_KEY VARCHAR(128),PRIMARY KEY (UUID))", //$NON-NLS-1$

				"ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_OBSERVATION_QUERY ADD CONSTRAINT SVY_OBSERVATION_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT_QUERY ADD CONSTRAINT SVY_WAYPOINT_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT_QUERY ADD CONSTRAINT SVY_WAYPOINT_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_WAYPOINT_QUERY ADD CONSTRAINT SVY_WAYPOINT_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID)  REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_GRIDDED_QUERY ADD CONSTRAINT SVY_GRIDDED_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_SUMMARY_QUERY ADD CONSTRAINT SVY_SUMMARY_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_TRACK_QUERY ADD CONSTRAINT SVY_MISSION_TRACK_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_TRACK_QUERY ADD CONSTRAINT SVY_MISSION_TRACK_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_TRACK_QUERY ADD CONSTRAINT SVY_MISSION_TRACK_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_QUERY ADD CONSTRAINT SVY_MISSION_CREATOR_UUID_FK FOREIGN KEY (CREATOR_UUID) REFERENCES SMART.EMPLOYEE (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_QUERY ADD CONSTRAINT SVY_MISSION_CA_UUID_FK FOREIGN KEY (CA_UUID) REFERENCES SMART.CONSERVATION_AREA (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$
				"ALTER TABLE SMART.SURVEY_MISSION_QUERY ADD CONSTRAINT SVY_MISSION_FOLDER_UUID_FK FOREIGN KEY (FOLDER_UUID) REFERENCES SMART.QUERY_FOLDER (UUID) ON UPDATE RESTRICT ON DELETE RESTRICT", //$NON-NLS-1$

				"GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_OBSERVATION_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_OBSERVATION_QUERY TO ANALYST", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_WAYPOINT_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_WAYPOINT_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_WAYPOINT_QUERY TO ANALYST", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_GRIDDED_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_GRIDDED_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_GRIDDED_QUERY TO ANALYST", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_SUMMARY_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_SUMMARY_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_SUMMARY_QUERY TO ANALYST", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_MISSION_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_MISSION_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_MISSION_QUERY TO ANALYST", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_MISSION_TRACK_QUERY TO manager", //$NON-NLS-1$
				"GRANT SELECT ON SMART.SURVEY_MISSION_TRACK_QUERY TO data_entry", //$NON-NLS-1$
				"GRANT ALL PRIVILEGES ON SMART.SURVEY_MISSION_TRACK_QUERY TO ANALYST" //$NON-NLS-1$

		};
		
		session.doWork(new Work() {
			@Override
			public void execute(Connection c) throws SQLException {
				for (int i = 0; i < sql.length; i ++){
					c.createStatement().execute(sql[i]);
				}	
			}
		});
	}
}
