source.. = src/,\
           shared/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               images/,\
               OSGI-INF/,\
               src/org/wcs/smart/patrol/query/model/types/patrol.html,\
               src/org/wcs/smart/patrol/query/model/types/patrolgrid.html,\
               src/org/wcs/smart/patrol/query/model/types/patrolincident.html,\
               src/org/wcs/smart/patrol/query/model/types/patrolobservation.html,\
               src/org/wcs/smart/patrol/query/model/types/patrolsummary.html,\
               src/org/wcs/smart/patrol/query/model/types/patrolobservation.png,\
               OSGI-INF/l10n/bundle.properties,\
               src/org/wcs/smart/patrol/query/model/types/patrolgrid.png,\
               src/org/wcs/smart/patrol/query/model/types/patrolincident.png,\
               src/org/wcs/smart/patrol/query/model/types/patrolquery.png,\
               src/org/wcs/smart/patrol/query/model/types/patrolsummary.png
src.includes = images/
