//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 10:13:14 AM PST 
//


package org.wcs.smart.datagenerator.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataGeneratorConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataGeneratorConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bounding_box" type="{http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration}BoundingBoxType"/>
 *         &lt;element name="mappings" type="{http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration}ObservationMappingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="number_of_patrols" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="days_per_patrol_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="days_per_patrol_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="employees_per_patrol_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="employees_per_patrol_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="waypoints_per_day_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="waypoints_per_day_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="observations_per_waypoint_min" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="observations_per_waypoint_max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataGeneratorConfiguration", propOrder = {
    "boundingBox",
    "mappings"
})
public class DataGeneratorConfiguration {

    @XmlElement(name = "bounding_box", required = true)
    protected BoundingBoxType boundingBox;
    protected List<ObservationMappingType> mappings;
    @XmlAttribute(name = "number_of_patrols")
    protected Integer numberOfPatrols;
    @XmlAttribute(name = "start_date")
    protected String startDate;
    @XmlAttribute(name = "end_date")
    protected String endDate;
    @XmlAttribute(name = "days_per_patrol_min")
    protected Integer daysPerPatrolMin;
    @XmlAttribute(name = "days_per_patrol_max")
    protected Integer daysPerPatrolMax;
    @XmlAttribute(name = "employees_per_patrol_min")
    protected Integer employeesPerPatrolMin;
    @XmlAttribute(name = "employees_per_patrol_max")
    protected Integer employeesPerPatrolMax;
    @XmlAttribute(name = "waypoints_per_day_min")
    protected Integer waypointsPerDayMin;
    @XmlAttribute(name = "waypoints_per_day_max")
    protected Integer waypointsPerDayMax;
    @XmlAttribute(name = "observations_per_waypoint_min")
    protected Integer observationsPerWaypointMin;
    @XmlAttribute(name = "observations_per_waypoint_max")
    protected Integer observationsPerWaypointMax;

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link BoundingBoxType }
     *     
     */
    public BoundingBoxType getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoundingBoxType }
     *     
     */
    public void setBoundingBox(BoundingBoxType value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservationMappingType }
     * 
     * 
     */
    public List<ObservationMappingType> getMappings() {
        if (mappings == null) {
            mappings = new ArrayList<ObservationMappingType>();
        }
        return this.mappings;
    }

    /**
     * Gets the value of the numberOfPatrols property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfPatrols() {
        return numberOfPatrols;
    }

    /**
     * Sets the value of the numberOfPatrols property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfPatrols(Integer value) {
        this.numberOfPatrols = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the daysPerPatrolMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysPerPatrolMin() {
        return daysPerPatrolMin;
    }

    /**
     * Sets the value of the daysPerPatrolMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysPerPatrolMin(Integer value) {
        this.daysPerPatrolMin = value;
    }

    /**
     * Gets the value of the daysPerPatrolMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysPerPatrolMax() {
        return daysPerPatrolMax;
    }

    /**
     * Sets the value of the daysPerPatrolMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysPerPatrolMax(Integer value) {
        this.daysPerPatrolMax = value;
    }

    /**
     * Gets the value of the employeesPerPatrolMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEmployeesPerPatrolMin() {
        return employeesPerPatrolMin;
    }

    /**
     * Sets the value of the employeesPerPatrolMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEmployeesPerPatrolMin(Integer value) {
        this.employeesPerPatrolMin = value;
    }

    /**
     * Gets the value of the employeesPerPatrolMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEmployeesPerPatrolMax() {
        return employeesPerPatrolMax;
    }

    /**
     * Sets the value of the employeesPerPatrolMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEmployeesPerPatrolMax(Integer value) {
        this.employeesPerPatrolMax = value;
    }

    /**
     * Gets the value of the waypointsPerDayMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWaypointsPerDayMin() {
        return waypointsPerDayMin;
    }

    /**
     * Sets the value of the waypointsPerDayMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWaypointsPerDayMin(Integer value) {
        this.waypointsPerDayMin = value;
    }

    /**
     * Gets the value of the waypointsPerDayMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWaypointsPerDayMax() {
        return waypointsPerDayMax;
    }

    /**
     * Sets the value of the waypointsPerDayMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWaypointsPerDayMax(Integer value) {
        this.waypointsPerDayMax = value;
    }

    /**
     * Gets the value of the observationsPerWaypointMin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObservationsPerWaypointMin() {
        return observationsPerWaypointMin;
    }

    /**
     * Sets the value of the observationsPerWaypointMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObservationsPerWaypointMin(Integer value) {
        this.observationsPerWaypointMin = value;
    }

    /**
     * Gets the value of the observationsPerWaypointMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getObservationsPerWaypointMax() {
        return observationsPerWaypointMax;
    }

    /**
     * Sets the value of the observationsPerWaypointMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setObservationsPerWaypointMax(Integer value) {
        this.observationsPerWaypointMax = value;
    }

}
