//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 10:13:14 AM PST 
//


package org.wcs.smart.datagenerator.model.xml;

import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wcs.smart.datagenerator.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataGeneratorConfiguration_QNAME = new QName("http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration", "DataGeneratorConfiguration"); //$NON-NLS-1$ //$NON-NLS-2$

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wcs.smart.datagenerator.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataGeneratorConfiguration }
     * 
     */
    public DataGeneratorConfiguration createDataGeneratorConfiguration() {
        return new DataGeneratorConfiguration();
    }

    /**
     * Create an instance of {@link BoundingBoxType }
     * 
     */
    public BoundingBoxType createBoundingBoxType() {
        return new BoundingBoxType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ObservationMappingType }
     * 
     */
    public ObservationMappingType createObservationMappingType() {
        return new ObservationMappingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataGeneratorConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smartconservationsoftware.org/xml/1.0/datageneratorconfiguration", name = "DataGeneratorConfiguration")
    public JAXBElement<DataGeneratorConfiguration> createDataGeneratorConfiguration(DataGeneratorConfiguration value) {
        return new JAXBElement<DataGeneratorConfiguration>(_DataGeneratorConfiguration_QNAME, DataGeneratorConfiguration.class, null, value);
    }

}
