//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 11:00:59 AM PDT 
//


package org.wcs.smart.cybertracker.model.screens;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Node">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Items" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SightingAccuracy" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="SightingFixCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="WaypointTimer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="TestTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GpsTimeZone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="GpsSkipTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="KioskMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BigTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BigScroller" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NextId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="TemplateId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Controls" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}Controls" minOccurs="0"/>
 *                   &lt;element name="DownloadTargetKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Node" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}Node" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Node", propOrder = {
    "items",
    "id",
    "name",
    "dataClass",
    "data",
    "node"
})
public class Node {

    @XmlElement(name = "Items")
    protected Node.Items items;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "DataClass", required = true)
    protected String dataClass;
    @XmlElement(name = "Data", required = true)
    protected Node.Data data;
    @XmlElement(name = "Node")
    protected List<Node> node;

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Node.Items }
     *     
     */
    public Node.Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Node.Items }
     *     
     */
    public void setItems(Node.Items value) {
        this.items = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dataClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataClass() {
        return dataClass;
    }

    /**
     * Sets the value of the dataClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataClass(String value) {
        this.dataClass = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Node.Data }
     *     
     */
    public Node.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Node.Data }
     *     
     */
    public void setData(Node.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Node }
     * 
     * 
     */
    public List<Node> getNode() {
        if (node == null) {
            node = new ArrayList<Node>();
        }
        return this.node;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SightingAccuracy" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *         &lt;element name="SightingFixCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="WaypointTimer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="TestTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GpsTimeZone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="GpsSkipTimeout" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="KioskMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BigTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BigScroller" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NextId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="TemplateId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Controls" type="{http://www.smartconservationsoftware.org/xml/1.0/cybertracker}Controls" minOccurs="0"/>
     *         &lt;element name="DownloadTargetKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "sightingAccuracy",
        "sightingFixCount",
        "waypointTimer",
        "testTime",
        "gpsTimeZone",
        "gpsSkipTimeout",
        "kioskMode",
        "bigTitle",
        "bigScroller",
        "nextId",
        "templateId",
        "controls",
        "downloadTargetKey"
    })
    public static class Data {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "SightingAccuracy")
        protected Double sightingAccuracy;
        @XmlElement(name = "SightingFixCount")
        protected Integer sightingFixCount;
        @XmlElement(name = "WaypointTimer")
        protected Integer waypointTimer;
        @XmlElement(name = "TestTime", required = true)
        protected String testTime;
        @XmlElement(name = "GpsTimeZone")
        protected Integer gpsTimeZone;
        @XmlElement(name = "GpsSkipTimeout")
        protected Integer gpsSkipTimeout;
        @XmlElement(name = "KioskMode", required = true)
        protected String kioskMode;
        @XmlElement(name = "BigTitle", required = true)
        protected String bigTitle;
        @XmlElement(name = "BigScroller", required = true)
        protected String bigScroller;
        @XmlElement(name = "NextId")
        protected Integer nextId;
        @XmlElement(name = "TemplateId", required = true)
        protected String templateId;
        @XmlElement(name = "Controls")
        protected Controls controls;
        @XmlElement(name = "DownloadTargetKey", required = true)
        protected String downloadTargetKey;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the sightingAccuracy property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSightingAccuracy() {
            return sightingAccuracy;
        }

        /**
         * Sets the value of the sightingAccuracy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSightingAccuracy(Double value) {
            this.sightingAccuracy = value;
        }

        /**
         * Gets the value of the sightingFixCount property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSightingFixCount() {
            return sightingFixCount;
        }

        /**
         * Sets the value of the sightingFixCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSightingFixCount(Integer value) {
            this.sightingFixCount = value;
        }

        /**
         * Gets the value of the waypointTimer property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getWaypointTimer() {
            return waypointTimer;
        }

        /**
         * Sets the value of the waypointTimer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setWaypointTimer(Integer value) {
            this.waypointTimer = value;
        }

        /**
         * Gets the value of the testTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestTime() {
            return testTime;
        }

        /**
         * Sets the value of the testTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestTime(String value) {
            this.testTime = value;
        }

        /**
         * Gets the value of the gpsTimeZone property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getGpsTimeZone() {
            return gpsTimeZone;
        }

        /**
         * Sets the value of the gpsTimeZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGpsTimeZone(Integer value) {
            this.gpsTimeZone = value;
        }

        /**
         * Gets the value of the gpsSkipTimeout property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getGpsSkipTimeout() {
            return gpsSkipTimeout;
        }

        /**
         * Sets the value of the gpsSkipTimeout property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGpsSkipTimeout(Integer value) {
            this.gpsSkipTimeout = value;
        }

        /**
         * Gets the value of the kioskMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKioskMode() {
            return kioskMode;
        }

        /**
         * Sets the value of the kioskMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKioskMode(String value) {
            this.kioskMode = value;
        }

        /**
         * Gets the value of the bigTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBigTitle() {
            return bigTitle;
        }

        /**
         * Sets the value of the bigTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBigTitle(String value) {
            this.bigTitle = value;
        }

        /**
         * Gets the value of the bigScroller property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBigScroller() {
            return bigScroller;
        }

        /**
         * Sets the value of the bigScroller property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBigScroller(String value) {
            this.bigScroller = value;
        }

        /**
         * Gets the value of the nextId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNextId() {
            return nextId;
        }

        /**
         * Sets the value of the nextId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNextId(Integer value) {
            this.nextId = value;
        }

        /**
         * Gets the value of the templateId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTemplateId() {
            return templateId;
        }

        /**
         * Sets the value of the templateId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTemplateId(String value) {
            this.templateId = value;
        }

        /**
         * Gets the value of the controls property.
         * 
         * @return
         *     possible object is
         *     {@link Controls }
         *     
         */
        public Controls getControls() {
            return controls;
        }

        /**
         * Sets the value of the controls property.
         * 
         * @param value
         *     allowed object is
         *     {@link Controls }
         *     
         */
        public void setControls(Controls value) {
            this.controls = value;
        }

        /**
         * Gets the value of the downloadTargetKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDownloadTargetKey() {
            return downloadTargetKey;
        }

        /**
         * Sets the value of the downloadTargetKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDownloadTargetKey(String value) {
            this.downloadTargetKey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Items {

        @XmlElement(name = "Value")
        protected List<String> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getValue() {
            if (value == null) {
                value = new ArrayList<String>();
            }
            return this.value;
        }

    }

}
