bin.includes = feature.xml,\
		build.properties
#root.macosx.cocoa.x86_64.folder.SMART.app/Contents=file:Info2.plist
#copy the license file into the root folder on build
root=file:smart_license.txt

#we can't do below because it causes these to be included in the plugin and 
#duplicates all the items so they can be rolledback if necessary
#this is not what we want; so instead we do this using maven copy-resources plugin
#see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=385456
#root.win32.win32.x86_64=file:win64_includes/items/**
