//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 03:07:08 PM PDT 
//


package org.wcs.smart.i2.xml.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wcs.smart.i2.xml.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Data_QNAME = new QName("http://www.smartconservationsoftware.org/xml/2.0/org.wcs.smart.i2.entity", "IntelEntity"); //$NON-NLS-1$ //$NON-NLS-2$
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wcs.smart.i2.xml.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstanceData }
     * 
     */
    public InstanceData createInstanceData() {
        return new InstanceData();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link AttributeValue }
     * 
     */
    public AttributeValue createAttributeValue() {
        return new AttributeValue();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link NamedItem }
     * 
     */
    public NamedItem createNamedItem() {
        return new NamedItem();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstanceData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smartconservationsoftware.org/xml/2.0/org.wcs.smart.i2.entity", name="IntelEntity")
    public JAXBElement<InstanceData> createData(InstanceData value) {
        return new JAXBElement<InstanceData>(_Data_QNAME, InstanceData.class, null, value);
    }

}
