//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.26 at 02:26:27 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.smartconservationsoftware.org/xml/1.3/patrol", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.wcs.smart.patrol.xml.model.v13;
