/*
 * Copyright (C) 2012 Wildlife Conservation Society
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.wcs.smart.er.ui.samplingunit.load;

import java.io.File;
import java.text.MessageFormat;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.swt.widgets.Display;
import org.wcs.smart.ca.Label;
import org.wcs.smart.common.control.WarningDialog;
import org.wcs.smart.er.internal.Messages;
import org.wcs.smart.er.model.SamplingUnit;
import org.wcs.smart.er.model.SamplingUnitAttribute;
import org.wcs.smart.er.model.SamplingUnitAttributeListItem;

/**
 * Sampling unit importer interface.
 * 
 * @author Emily
 *
 */
public abstract class ISamplingUnitImporter {

	public static final String TYPE_KEY = "SU_TYPE"; //$NON-NLS-1$
	public static final String ID_FIELD_KEY = "ID_FIELD"; //$NON-NLS-1$
	public static final String X1_FIELD_KEY = "X1_FIELD"; //$NON-NLS-1$
	public static final String Y1_FIELD_KEY = "Y1_FIELD"; //$NON-NLS-1$
	public static final String X2_FIELD_KEY = "X2_FIELD"; //$NON-NLS-1$
	public static final String Y2_FIELD_KEY = "Y2_FIELD"; //$NON-NLS-1$
	public static final String PROJECTION_KEY = "PROJECTION"; //$NON-NLS-1$
	public static final String EXISTING_IDS_KEY = "SUIDS"; //$NON-NLS-1$
	public static final String AUTO_GENERATE_KEY_PREFIX = Messages.ISamplingUnitImporter_AutoGeneratedUnitPrefix;
	
	/**
	 * Gets the field names from the file.  
	 * 
	 * @param f the file 
	 * @param options a map of options for reading the file
	 * @return list of field names
	 * @throws Exception
	 */
	public abstract String[] getFieldNames(File f, Map<String, Object> options) throws Exception;
	
	/**
	 * Imports all sampling units from the file.
	 * 
	 * @param f the file
	 * @param options set of import options
	 * @param monitor process monitor
	 * @return
	 * @throws Exception
	 */
	public abstract List<SamplingUnit> importFile(File f, HashMap<Object, Object> options, IProgressMonitor monitor) throws Exception;

	
	/**
	 * Generates a valid sampling unit id
	 * @param idField request id
	 * @param cnt sampling unit count
	 * @param existingIds list of existing ids ; this list will be updated with the generated id
	 * @param warnings list of warnings; this list will be updated with any new warnings
	 * @return
	 */
	public static String generateId(String idField, int cnt, 
			HashSet<String> existingIds, List<String> warnings){
		String id = idField;
		
		if (idField == null || idField.length() == 0){
			id = AUTO_GENERATE_KEY_PREFIX + " " + cnt;  //$NON-NLS-1$
		}else if (existingIds.contains(idField)){
			warnings.add(MessageFormat.format(Messages.ISamplingUnitImporter_IdNotUnique, new Object[]{idField}));
			id = AUTO_GENERATE_KEY_PREFIX + " " + cnt; //$NON-NLS-1$
		}else{
			String warn = SamplingUnit.validateId(id);
			if (warn != null){
				warnings.add(MessageFormat.format(Messages.ISamplingUnitImporter_IdInvalid, new Object[]{id, warn} ));
				id = AUTO_GENERATE_KEY_PREFIX + " " + cnt; //$NON-NLS-1$
			}
		}
		
		while(existingIds.contains(id)){
			cnt++;
			id = AUTO_GENERATE_KEY_PREFIX + " " + cnt;  //$NON-NLS-1$
		}
		System.out.println(id);
		existingIds.add(id);
		return id;
	}
	
	/**
	 * If warnings is populated shows warning dialog to users.
	 * @param warnings
	 */
	public static  void showWarnings(final List<String> warnings){
		if (warnings.size() > 0){
			Display.getDefault().syncExec(new Runnable() {
				@Override
				public void run() {
					final WarningDialog wd = new WarningDialog(Display.getDefault().getActiveShell(), Messages.ISamplingUnitImporter_WarningsDialog, Messages.ISamplingUnitImporter_WarningMessage, warnings);
					wd.open();
				}
			});
		}
	}
	
	/**
	 * Validates string attribute value. 
	 * @param value
	 * @return error message or null
	 */
	public static String validateStringAttributeValue(String value, SamplingUnitAttribute att){
		if (value.length() > SamplingUnitAttribute.MAX_STRING_LENGTH){
			return MessageFormat.format(Messages.ISamplingUnitImporter_StringToLong, new Object[]{att.getName(), SamplingUnitAttribute.MAX_STRING_LENGTH});
		}
		return null;
	}
	
	public static String getSamplingUnitListItemNotFoundError(String value, SamplingUnitAttribute att){
		return MessageFormat.format(Messages.ISamplingUnitImporter_ListNotFound,
				new Object[]{(String)value, att.getName()});
	}
	/**
	 * Finds sampling unit attribute list item match
	 * 
	 * @param su
	 * @param value
	 * @return sampling unit list item or null if none found
	 */
	public static SamplingUnitAttributeListItem findMatch(SamplingUnitAttribute su, String value){
		if (value == null) return null;
		value = value.trim();
	
		//search keys; likely won't match
		for (SamplingUnitAttributeListItem item : su.getAttributeList()){
			if (item.getKeyId().equals(value)){
				return item;
			}
		}
		//search current language name
		for (SamplingUnitAttributeListItem item : su.getAttributeList()){
			if (item.getName().equals(value)){
				return item;
			}
		}
			
		//search all names; case insensitive
		for (SamplingUnitAttributeListItem item : su.getAttributeList()){
			for (Label l : item.getNames()){
				if (l.getValue().toUpperCase().equals(value.toUpperCase())){
					return item;
				}
			}
		}
		return null;
	}
}
