//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.09 at 09:16:11 AM PST 
//


package org.wcs.smart.i2.xml.record;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record_attribute" type="{http://www.smartconservationsoftware.org/xml/2.0/org.wcs.smart.i2.record}LabelUuid" minOccurs="0"/>
 *         &lt;element name="string_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="number_value_1" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="number_value_2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="list_value" type="{http://www.smartconservationsoftware.org/xml/2.0/org.wcs.smart.i2.record}LabelUuid" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.smartconservationsoftware.org/xml/2.0/org.wcs.smart.i2.record}AttributeType" />
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordAttributeType", propOrder = {
    "recordAttribute",
    "stringValue",
    "numberValue1",
    "numberValue2",
    "listValue"
})
public class RecordAttributeType {

    @XmlElement(name = "record_attribute")
    protected LabelUuid recordAttribute;
    @XmlElement(name = "string_value")
    protected String stringValue;
    @XmlElement(name = "number_value_1")
    protected Double numberValue1;
    @XmlElement(name = "number_value_2")
    protected Double numberValue2;
    @XmlElement(name = "list_value")
    protected List<LabelUuid> listValue;
    @XmlAttribute(name = "type")
    protected AttributeType type;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the recordAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link LabelUuid }
     *     
     */
    public LabelUuid getRecordAttribute() {
        return recordAttribute;
    }

    /**
     * Sets the value of the recordAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelUuid }
     *     
     */
    public void setRecordAttribute(LabelUuid value) {
        this.recordAttribute = value;
    }

    /**
     * Gets the value of the stringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringValue() {
        return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringValue(String value) {
        this.stringValue = value;
    }

    /**
     * Gets the value of the numberValue1 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNumberValue1() {
        return numberValue1;
    }

    /**
     * Sets the value of the numberValue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNumberValue1(Double value) {
        this.numberValue1 = value;
    }

    /**
     * Gets the value of the numberValue2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNumberValue2() {
        return numberValue2;
    }

    /**
     * Sets the value of the numberValue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNumberValue2(Double value) {
        this.numberValue2 = value;
    }

    /**
     * Gets the value of the listValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelUuid }
     * 
     * 
     */
    public List<LabelUuid> getListValue() {
        if (listValue == null) {
            listValue = new ArrayList<LabelUuid>();
        }
        return this.listValue;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeType }
     *     
     */
    public AttributeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeType }
     *     
     */
    public void setType(AttributeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}
