output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               splash.bmp,\
               properties/log4j.properties,\
               plugin.properties,\
               about.mappings,\
               images/,\
               properties/datamodel.xml,\
               smart_customization.ini,\
               properties/species.xml,\
               properties/smart.properties,\
               properties/locales.properties,\
               css/,\
               lib/commons-exec-1.3.jar,\
               lib/jBCrypt-0.4.1.jar,\
               lib/opencsv-2.3.jar,\
               lib/xmpcore-5.1.3.jar,\
               lib/commons-compress-1.16.1.jar,\
               lib/metadata-extractor-2.11.0.jar,\
               lib/gson-2.8.5.jar
src.includes = splash.bmp,\
               images/icons/,\
               images/nl/,\
               properties/log4j.properties,\
               properties/IUCN_Threats.xml,\
               lib/gson-2.8.2.jar,\
               lib/opencsv-2.3.jar,\
               lib/commons-compress-1.16.1.jar
source.. = src/,\
           shared/
javacDefaultEncoding.. = UTF-8
