# Root Logger
rootLogger=INFO, STDOUT

# Direct log messages to stdout
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss,SSS} %-5p [%c] - %m%n

logger.hibernate.name=org.hibernate
logger.hibernate.level=warn