//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 02:52:49 PM PST 
//


package org.wcs.smart.entity.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="names" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}LabelType" maxOccurs="unbounded"/>
 *         &lt;element name="attributes" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}EntityAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dmAttribute" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}DataModelAttribute"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityType", propOrder = {
    "names",
    "attributes",
    "dmAttribute"
})
public class EntityType {

    @XmlElement(required = true)
    protected List<LabelType> names;
    protected List<EntityAttribute> attributes;
    @XmlElement(required = true)
    protected DataModelAttribute dmAttribute;
    @XmlAttribute
    protected String keyid;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String status;
    @XmlAttribute
    protected String type;

    /**
     * Gets the value of the names property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the names property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     * 
     * 
     */
    public List<LabelType> getNames() {
        if (names == null) {
            names = new ArrayList<LabelType>();
        }
        return this.names;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityAttribute }
     * 
     * 
     */
    public List<EntityAttribute> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<EntityAttribute>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the dmAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link DataModelAttribute }
     *     
     */
    public DataModelAttribute getDmAttribute() {
        return dmAttribute;
    }

    /**
     * Sets the value of the dmAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataModelAttribute }
     *     
     */
    public void setDmAttribute(DataModelAttribute value) {
        this.dmAttribute = value;
    }

    /**
     * Gets the value of the keyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * Sets the value of the keyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyid(String value) {
        this.keyid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
