//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.15 at 02:52:49 PM PST 
//


package org.wcs.smart.entity.xml.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityAttribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aliases" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}LabelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dmAttribute" type="{http://www.smartconservationsoftware.org/xml/1.0/entitytype}DataModelAttribute"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isPrimary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityAttribute", propOrder = {
    "aliases",
    "dmAttribute"
})
public class EntityAttribute {

    protected List<LabelType> aliases;
    @XmlElement(required = true)
    protected DataModelAttribute dmAttribute;
    @XmlAttribute
    protected String keyid;
    @XmlAttribute
    protected Boolean isRequired;
    @XmlAttribute
    protected Boolean isPrimary;

    /**
     * Gets the value of the aliases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aliases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAliases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     * 
     * 
     */
    public List<LabelType> getAliases() {
        if (aliases == null) {
            aliases = new ArrayList<LabelType>();
        }
        return this.aliases;
    }

    /**
     * Gets the value of the dmAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link DataModelAttribute }
     *     
     */
    public DataModelAttribute getDmAttribute() {
        return dmAttribute;
    }

    /**
     * Sets the value of the dmAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataModelAttribute }
     *     
     */
    public void setDmAttribute(DataModelAttribute value) {
        this.dmAttribute = value;
    }

    /**
     * Gets the value of the keyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * Sets the value of the keyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyid(String value) {
        this.keyid = value;
    }

    /**
     * Gets the value of the isRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRequired() {
        return isRequired;
    }

    /**
     * Sets the value of the isRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRequired(Boolean value) {
        this.isRequired = value;
    }

    /**
     * Gets the value of the isPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimary() {
        return isPrimary;
    }

    /**
     * Sets the value of the isPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimary(Boolean value) {
        this.isPrimary = value;
    }

}
